/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.defeasible;

global java.util.List list;

declare A
    id  : int   @key
end

declare X
    id  : int   @key
end

declare entry-point "neg" end

rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
end

rule "Defeater Rule"
@Defeater
when
    A( 1; )
then
    insertLogical( new X( -1 ), "neg" );
end

rule "Never"
when
    $x : X()
then
    System.out.println( "This should not happen" );
    list.add( $x );
end
