/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.defeasible;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare C
    id  : int   @key
end

declare D
    id  : int   @key
end

rule "Init"
when
    $s : String( this == "go" )
then
    insertLogical( new A( 3 ) );
end

rule "Init 2"
when

then
    insert( new B( 2 ) );
end

rule "Defeasible Rule"
@Defeasible
when
    B( 2; )
then
    insertLogical( new C( 99 ) );
end

rule "Strict Rule 2"
when
    A( 3; )
then
    insertLogical( new C( 99 ) );
end


