package org.drools.defeasible;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare C
    id  : int   @key
end

declare D
    id  : int   @key
end

rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
    insert( new A( 3 ) );   // A(1) is a Fact
    insert( new B( 2 ) );   // same for B(2)
end

rule "Strict Rule"
when
    A( 1; )
    B( 2; )
then
    System.out.println( "Strict rule inserts C99" );
    insertLogical( new C( 99 ) );
end

rule "Strict Rule 2"
when
    A( 3; )
then
    System.out.println( "Another Strict rule 2 inserts C99" );
    insertLogical( new C( 99 ) );
end

rule "Strict Rule 3"
when
    C( 99; )
then
    System.out.println( "Strict rule 3 chains and inserts D5" );
    insertLogical( new D( -5 ) );
end

