/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

<?xml version="1.0" encoding="UTF-8"?>

<rule-set 
    name="JavaRules.org Test Agent Drools Port"
    description="Some rules for the JavaOne demo"
    xmlns="http://drools.org/rules"
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
        xs:schemaLocation="http://drools.org/rules rules.xsd
                           http://drools.org/semantics/java java.xsd">

<!-- Rules -->
  <rule name="Say hello if Mozilla User">
    <parameter identifier="s">
      <class>java.lang.String</class>
    </parameter>
    <java:condition> s.startsWith("Gecko") </java:condition>
    <java:consequence> assertObject("Hello Mozilla user!"); </java:consequence>
  </rule>
    
  <rule name="Say hello if IE user">
    <parameter identifier="s">
        <class>java.lang.String</class>
    </parameter>
    <java:condition> s.startsWith("MSIE") </java:condition>
    <java:consequence> assertObject("Hello IE user!"); </java:consequence>
  </rule>

</rule-set>

