package org.drools.common;

/*
 * Copyright 2005 JBoss Inc
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.Externalizable;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectInput;
import java.io.ObjectOutput;
import java.io.ObjectOutputStream;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.WeakHashMap;

import org.drools.FactException;
import org.drools.PackageIntegrationException;
import org.drools.RuleBase;
import org.drools.RuleBaseConfiguration;
import org.drools.RuleIntegrationException;
import org.drools.WorkingMemory;
import org.drools.rule.CompositePackageClassLoader;
import org.drools.rule.InvalidPatternException;
import org.drools.rule.Package;
import org.drools.rule.PackageCompilationData;
import org.drools.rule.Rule;
import org.drools.spi.FactHandleFactory;

/**
 * Implementation of <code>RuleBase</code>.
 * 
 * @author <a href="mailto:bob@werken.com">bob mcwhirter</a>
 * @author <a href="mailto:mark.proctor@jboss.com">Mark Proctor</a> 
 * 
 * @version $Id: RuleBaseImpl.java,v 1.5 2005/08/14 22:44:12 mproctor Exp $
 */
abstract public class AbstractRuleBase
    implements
    InternalRuleBase,
    Externalizable {
    // ------------------------------------------------------------
    // Instance members
    // ------------------------------------------------------------
    protected String                                id;

    protected int                                   workingMemoryCounter;

    protected RuleBaseConfiguration                 config;

    protected Map                                   pkgs;

    protected transient CompositePackageClassLoader packageClassLoader;

    /** The fact handle factory. */
    protected FactHandleFactory                     factHandleFactory;

    protected Map                                   globals;

    /**
     * WeakHashMap to keep references of WorkingMemories but allow them to be
     * garbage collected
     */
    protected transient Map                         workingMemories;

    /** Special value when adding to the underlying map. */
    protected static final Object                   PRESENT = new Object();

    /**
     * Default constructor - for Externalizable. This should never be used by a user, as it 
     * will result in an invalid state for the instance.
     */
    public AbstractRuleBase() {

    }

    /**
     * Construct.
     * 
     * @param rete
     *            The rete network.
     */
    public AbstractRuleBase(final String id,
                            final RuleBaseConfiguration config,
                            final FactHandleFactory factHandleFactory) {
        if ( id != null ) {
            this.id = id;
        } else {
            this.id = "default";
        }
        this.config = (config != null) ? config : new RuleBaseConfiguration();
        this.config.makeImmutable();
        this.factHandleFactory = factHandleFactory;

        this.packageClassLoader = new CompositePackageClassLoader( Thread.currentThread().getContextClassLoader() );
        this.pkgs = new HashMap();
        this.globals = new HashMap();
        this.workingMemories = new WeakHashMap();
    }

    // ------------------------------------------------------------
    // Instance methods
    // ------------------------------------------------------------

    /**
     * Handles the write serialization of the Package. Patterns in Rules may reference generated data which cannot be serialized by default methods.
     * The Package uses PackageCompilationData to hold a reference to the generated bytecode. The generated bytecode must be restored before any Rules.
     * 
     */
    public void doWriteExternal(final ObjectOutput stream,
                                final Object[] objects) throws IOException {
        stream.writeObject( this.pkgs );

        // Rules must be restored by an ObjectInputStream that can resolve using a given ClassLoader to handle seaprately by storing as
        // a byte[]
        final ByteArrayOutputStream bos = new ByteArrayOutputStream();
        final ObjectOutput out = new ObjectOutputStream( bos );
        out.writeObject( this.id );
        out.writeObject( this.factHandleFactory );
        out.writeObject( this.globals );
        out.writeObject( this.config );

        for ( int i = 0, length = objects.length; i < length; i++ ) {
            out.writeObject( objects[i] );
        }

        stream.writeObject( bos.toByteArray() );
    }

    /**
     * Handles the read serialization of the Package. Patterns in Rules may reference generated data which cannot be serialized by default methods.
     * The Package uses PackageCompilationData to hold a reference to the generated bytecode; which must be restored before any Rules.
     * A custom ObjectInputStream, able to resolve classes against the bytecode in the PackageCompilationData, is used to restore the Rules.
     * 
     */
    public void doReadExternal(final ObjectInput stream,
                               final Object[] objects) throws IOException,
                                                      ClassNotFoundException {
        // PackageCompilationData must be restored before Rules as it has the ClassLoader needed to resolve the generated code references in Rules
        this.pkgs = (Map) stream.readObject();

        this.packageClassLoader = new CompositePackageClassLoader( Thread.currentThread().getContextClassLoader() );
        for ( final Iterator it = this.pkgs.values().iterator(); it.hasNext(); ) {
            this.packageClassLoader.addClassLoader( ((Package) it.next()).getPackageCompilationData().getClassLoader() );
        }

        // Return the rules stored as a byte[]
        final byte[] bytes = (byte[]) stream.readObject();

        //  Use a custom ObjectInputStream that can resolve against a given classLoader
        final ObjectInputStreamWithLoader streamWithLoader = new ObjectInputStreamWithLoader( new ByteArrayInputStream( bytes ),
                                                                                              this.packageClassLoader );

        this.id = (String) streamWithLoader.readObject();
        this.factHandleFactory = (FactHandleFactory) streamWithLoader.readObject();
        this.globals = (Map) streamWithLoader.readObject();

        this.config = (RuleBaseConfiguration) streamWithLoader.readObject();

        this.workingMemories = new WeakHashMap();

        for ( int i = 0, length = objects.length; i < length; i++ ) {
            objects[i] = streamWithLoader.readObject();
        }
    }

    /**
     * @return the id
     */
    public String getId() {
        return this.id;
    }

    /**
     * @see RuleBase
     */
    public WorkingMemory newWorkingMemory() {
        return newWorkingMemory( true );
    }

    /**
     * @see RuleBase
     */
    abstract public WorkingMemory newWorkingMemory(boolean keepReference);

    public void disposeWorkingMemory(final WorkingMemory workingMemory) {
        this.workingMemories.remove( workingMemory );
    }

    /**
     * @see RuleBase
     */
    public FactHandleFactory getFactHandleFactory() {
        return this.factHandleFactory;
    }

    public FactHandleFactory newFactHandleFactory() {
        return this.factHandleFactory.newInstance();
    }

    public Package[] getPackages() {
        return (Package[]) this.pkgs.values().toArray( new Package[this.pkgs.size()] );
    }

    public Map getGlobals() {
        return this.globals;
    }

    /**
     * Add a <code>Package</code> to the network. Iterates through the
     * <code>Package</code> adding Each individual <code>Rule</code> to the
     * network. Before update network each referenced <code>WorkingMemory</code>
     * is locked.
     * 
     * @param pkg
     *            The package to add.
     * @throws PackageIntegrationException 
     * 
     * @throws RuleIntegrationException
     *             if an error prevents complete construction of the network for
     *             the <code>Rule</code>.
     * @throws FactException
     * @throws InvalidPatternException
     */
    public void addPackage(final Package newPkg) throws PackageIntegrationException {
        newPkg.checkValidity();
        final Package pkg = (Package) this.pkgs.get( newPkg.getName() );

        // Iterate each workingMemory and lock it
        // This is so we don't update the Rete network during propagation
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();
            workingMemory.getLock().lock();
        }

        if ( pkg != null ) {
            mergePackage( pkg,
                          newPkg );
        } else {
            this.pkgs.put( newPkg.getName(),
                           newPkg );
        }

        final Map newGlobals = newPkg.getGlobals();

        // Check that the global data is valid, we cannot change the type
        // of an already declared global variable
        for ( final Iterator it = newGlobals.keySet().iterator(); it.hasNext(); ) {
            final String identifier = (String) it.next();
            final Class type = (Class) newGlobals.get( identifier );
            boolean f =  this.globals.containsKey( identifier );
            if ( f ) {
                boolean y = !this.globals.get( identifier ).equals( type );
                if ( f &&  y ) {
                    throw new PackageIntegrationException( pkg );
                }
            }
        }
        this.globals.putAll( newGlobals );

        final Rule[] rules = newPkg.getRules();

        for ( int i = 0; i < rules.length; ++i ) {
            addRule( rules[i] );
        }

        this.packageClassLoader.addClassLoader( newPkg.getPackageCompilationData().getClassLoader() );

        // Iterate each workingMemory and attempt to fire any rules, that were activated as a result 
        // of the new rule addition. Unlock after fireAllRules();
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();

            workingMemory.fireAllRules();
            workingMemory.getLock().unlock();
        }
    }

    /**
     * Merge a new package with an existing package.
     * Most of the work is done by the concrete implementations, 
     * but this class does some work (including combining imports, compilation data, globals,
     * and the actual Rule objects into the package).
     */
    private void mergePackage(final Package pkg,
                              final Package newPkg) throws PackageIntegrationException {
        final Map globals = pkg.getGlobals();
        final List imports = pkg.getImports();

        // First update the binary files
        // @todo: this probably has issues if you add classes in the incorrect order - functions, rules, invokers.
        final PackageCompilationData compilationData = pkg.getPackageCompilationData();
        final PackageCompilationData newCompilationData = newPkg.getPackageCompilationData();
        final String[] files = newCompilationData.list();
        for ( int i = 0, length = files.length; i < length; i++ ) {
            compilationData.write( files[i],
                                   newCompilationData.read( files[i] ) );
        }

        // Merge imports
        imports.addAll( newPkg.getImports() );

        // Add invokers
        compilationData.putAllInvokers( newCompilationData.getInvokers() );

        // Add globals
        for ( final Iterator it = newPkg.getGlobals().keySet().iterator(); it.hasNext(); ) {
            final String identifier = (String) it.next();
            final Class type = (Class) globals.get( identifier );
            if ( globals.containsKey( identifier ) && !globals.get( identifier ).equals( type ) ) {
                throw new PackageIntegrationException( "Unable to merge new Package",
                                                       newPkg );
            }
        }
        globals.putAll( newPkg.getGlobals() );

        //Add rules into the RuleBase package
        //as this is needed for individual rule removal later on
        final Rule[] newRules = newPkg.getRules();
        for ( int i = 0; i < newRules.length; i++ ) {
            final Rule newRule = newRules[i];
            if ( pkg.getRule( newRule.getName() ) == null ) {
                pkg.addRule( newRule );
            }
        }
    }

    protected void addRule(final Rule rule) throws InvalidPatternException {
        if ( !rule.isValid() ) {
            throw new IllegalArgumentException( "The rule called " + rule.getName() + " is not valid. Check for compile errors reported." );
        }
    }

    public void removePackage(final String packageName) {
        final Package pkg = (Package) this.pkgs.get( packageName );
        // Iterate each workingMemory and lock it
        // This is so we don't update the Rete network during propagation
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();
            workingMemory.getLock().lock();
        }

        final Rule[] rules = pkg.getRules();

        for ( int i = 0; i < rules.length; ++i ) {
            removeRule( rules[i] );
        }

        this.packageClassLoader.removeClassLoader( pkg.getPackageCompilationData().getClassLoader() );

        pkg.clear();

        // getting the list of referenced globals 
        final Set referencedGlobals = new HashSet();
        for ( final Iterator it = this.pkgs.values().iterator(); it.hasNext(); ) {
            final org.drools.rule.Package pkgref = (org.drools.rule.Package) it.next();
            if ( pkgref != pkg ) {
                referencedGlobals.addAll( pkgref.getGlobals().keySet() );
            }
        }
        // removing globals declared inside the package that are not shared
        for ( final Iterator it = pkg.getGlobals().keySet().iterator(); it.hasNext(); ) {
            final String globalName = (String) it.next();
            if ( !referencedGlobals.contains( globalName ) ) {
                this.globals.remove( globalName );
            }
        }
        // removing the package itself from the list
        this.pkgs.remove( pkg.getName() );

        // Iterate and unlock
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();
            workingMemory.getLock().unlock();
        }
    }

    public void removeRule(final String packageName,
                           final String ruleName) {
        final Package pkg = (Package) this.pkgs.get( packageName );
        final Rule rule = pkg.getRule( ruleName );
        // Iterate each workingMemory and lock it
        // This is so we don't update the Rete network during propagation
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();
            workingMemory.getLock().lock();
        }
        removeRule( rule );
        pkg.removeRule( rule );

        // Iterate and unlock
        for ( final Iterator it = this.workingMemories.keySet().iterator(); it.hasNext(); ) {
            final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) it.next();
            workingMemory.getLock().unlock();
        }
    }

    protected abstract void removeRule(Rule rule);

    protected void addWorkingMemory(final WorkingMemory workingMemory,
                                    final boolean keepReference) {
        if ( keepReference ) {
            this.workingMemories.put( workingMemory,
                                      AbstractRuleBase.PRESENT );
        }
    }

    public Set getWorkingMemories() {
        return this.workingMemories.keySet();
    }

    public RuleBaseConfiguration getConfiguration() {
        return this.config;
    }

    public WorkingMemory newWorkingMemory(final InputStream stream) throws IOException,
                                                             ClassNotFoundException {
        return newWorkingMemory( stream,
                                 true );
    }

    public WorkingMemory newWorkingMemory(final InputStream stream,
                                          final boolean keepReference) throws IOException,
                                                                ClassNotFoundException {

        final ObjectInputStreamWithLoader streamWithLoader = new ObjectInputStreamWithLoader( stream,
                                                                                              this.packageClassLoader );

        final AbstractWorkingMemory workingMemory = (AbstractWorkingMemory) streamWithLoader.readObject();
        workingMemory.setRuleBase( this );

        return workingMemory;
    }
}
