package org.kie.api.event;

import org.kie.api.runtime.KieRuntime;

/**
 * An event that is generated by the KIE runtime.
 */
public interface KieRuntimeEvent {

    /**
     * {@link org.kie.api.runtime.KieRuntime} that generated the event.
     *
     * @return the KIE runtime
     */
    KieRuntime getKieRuntime();

}
