package org.drools.examples.buspass.jtms;

import org.drools.examples.buspass.Person;
import org.drools.examples.buspass.BadBehaviour
import org.drools.examples.buspass.IsChild;
import org.drools.examples.buspass.IsAdult;
import org.drools.examples.buspass.ChildBusPass;
import org.drools.examples.buspass.AdultBusPass;

rule IssueChildBusPass when
    p : Person()
    IsChild( person == p )
then
    System.out.println( "issue : " + p );
    insertLogical( new ChildBusPass( p ) );
end

rule BadBehaviour when
    p : Person()
    IsChild( person == p )
    BadBehaviour( person == p )
then
    System.out.println( "bad : " + p );
    insertLogical( new ChildBusPass( p ), "neg" );
end


rule PrintChildBusPass when
    c : ChildBusPass( )
then
    System.out.println( "Child Bus Pass : " + c);
end

rule PrintNoChildBusPass when
    c : ChildBusPass( _.neg )
then
    System.out.println( "No Child Bus Pass : " + c);
end