/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package foo;

import java.util.HashMap;
import java.util.HashSet;
import java.utilArrayList;

global HashMap m;
global HashSet s;
global org.drools.Person p;

import function org.drools.xml.DumperTest.testStaticMethod1;
import function org.drools.xml.DumperTest.testStaticMethod2;
import function org.drools.xml.DumperTest.testStaticMethod3;

dialect "java"
salience 0
auto-focus false

declare SomeType
   @ann1( "some value" )
   @ann2( key1="value1", key2="value2" )
   field1 : String @key
   field2 : int
end

function int func1( String p1, boolean p2 ) {
   return 10;
}

function func2() {
   String x = "abc";
}

rule "simple_rule"
  @author(name="Some author", version="1")
  salience 10
  no-loop true
  agenda-group "agenda-group"
  activation-group "activation-group"
  ruleflow-group "xxx"
  lock-on-active true
  auto-focus true
  date-effective "01-Jan-2007"
  date-expires "01-Feb-2007"    
  when
    foo2 : Bar( a ( > 60 && < 70 ) || ( > 50 && < 55 ) && a3 == "black" || a == 40 && a3 == "pink" || a == 12 && a3 == "yellow" || a3 == "blue")
    foo3 : Bar( a == 3 || == 4, a3 == "hello", a4 == null )    
    foo4 : Bar( a4 : a != 4 && != 5) from entry-point "abc"
    foo5 : Bar( b == (a4 + 1) || > a4) from $foo3.bla( x, y )
    foo6 : Bar( a4 : a, b == 6)    
    foo7 : Bar( a4 : a, b4 : b)    
    $cheeseList  : ArrayList(size > 2) from collect( Cheese( type == $likes ) );    
    Baz()
  then
  if ( a == b ) {
    assert( foo3 );
  } else {
    retract( foo4 );
  } 
  System.out.println( a4 );
  testStaticMethod1();
  testStaticMethod2();
  testStaticMethod3();
end

rule "simple_rule2"
  salience (10 + a)
  dialect "mvel"    
  when    
    foo4 : Bar( a4 : a != 4 && != 5)
  then
  if ( a == b ) {
    assert( foo3 );
  } else {
    retract( foo4 );
  } 
  System.out.println( a4 );
  testStaticMethod1();  
  testStaticMethod2();
  testStaticMethod3();  
end