/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.test.findPatterns

import org.drools.verifier.components.Pattern;

import org.drools.verifier.report.components.VerifierMessage;
import org.drools.verifier.report.components.Severity;
import org.drools.verifier.report.components.MessageType;

import org.drools.verifier.data.VerifierReport;

import java.util.HashMap;

global VerifierReport result;



rule "Find patterns"
    when
        $p :Pattern( )
    then
        result.add( new VerifierMessage(
                            new HashMap(),
                            Severity.NOTE,
                            MessageType.NOT_SPECIFIED,
                            $p,
                            "This pattern was found." ) );

end
