/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.misc.missingRanges

import com.sample.DroolsTest.Message;

/*
rule "Redundant restrictions"
	when
		RedundancyPattern( a == 1, a == 1 )
	then
		// Something
end

rule "Redundant rule 1, rules"
	when
		RedundancyPattern( a == 1 )
		RedundancyPattern2( a == 1 )
	then
		System.out.println("TEST");
end
*/
rule "Redundant rule 2, rules"
	when
		RedundancyPattern( a == 1 )
		RedundancyPattern2( a >= 1 )
		RedundancyPattern3( a == 1, a == 1 )
	then
		System.out.println("TEST");
end

rule "Equivalent rule"
	when
		BlaaBlaa( a == 1 )
		RedundancyPattern( a == 1 )
		RedundancyPattern2( a == 1 )
	then
		System.out.println("NOT A TEST");
end
