/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Integer gap rule 1"
    when
        IntegerPattern1( value == 10 )
    then
        // gap > 10 <.
end

rule "Integer gap rule 2"
    when
        IntegerPattern2( value >= 15 )
    then
        // gap < 15.
end

rule "Integer gap rule 3"
    when
        IntegerPattern3( value <= 15 )
    then
        // gap > 15.
end

rule "Integer gap rule 4a"
    when
        IntegerPattern4( value > 25 )
    then
        // gap == 25.
end

rule "Integer gap rule 4b"
    when
        IntegerPattern4( value < 25 )
    then
        // gap == 25.
end

rule "Integer gap rule 5a"
    when
        IntegerPattern5( value > 100 )
    then
        // gap 100 > x > 50.
end

rule "Integer gap rule 5b"
    when
        IntegerPattern5( value < 50 )
    then
        // gap 100 > x > 50.
end

rule "Integer gap rule 6a"
    when
        IntegerPattern6( value > 350 )
    then
        // gap < 350.
end

rule "Integer gap rule 6b"
    when
        IntegerPattern6( value == 350 )
    then
        // gap < 350.
end

rule "Integer gap rule 7a"
    when
        IntegerPattern7( value < 55 )
    then
        // gap > 55.
end

rule "Integer gap rule 7b"
    when
        IntegerPattern7( value == 55 )
    then
        // gap > 55.
end

rule "Integer gap rule 8a"
    when
        IntegerPattern8( value < 333 )
    then
        // No gap
end

rule "Integer gap rule 8b"
    when
        IntegerPattern8( value == 333 )
    then
        // No gap
end

rule "Integer gap rule 8c"
    when
        IntegerPattern8( value > 333 )
    then
        // No gap
end

rule "Integer gap rule 9a"
    when
        IntegerPattern9( value <= 122 )
    then
        // No gap
end

rule "Integer gap rule 9b"
    when
        IntegerPattern9( value == 123 )
    then
        // No gap
end

rule "Integer gap rule 9c"
    when
        IntegerPattern9( value >= 124 )
    then
        // No gap
end
