package org.drools.examples.buspass.good;

import org.drools.examples.buspass.Person;
import org.drools.examples.buspass.IsChild;
import org.drools.examples.buspass.IsAdult;
import org.drools.examples.buspass.ChildBusPass;
import org.drools.examples.buspass.AdultBusPass;

rule IssueChildBusPass when
    p : Person()
    IsChild( person == p )
then
    insertLogical( new ChildBusPass( p ) );
end

rule IssueAdultBusPass when
    p : Person()
    IsAdult( person == p )
then
    insertLogical( new AdultBusPass( p ) );
end

rule PrintChildBusPass when
    ChildBusPass()
then
    System.out.println( "Child Bus Pass" );
end

rule PrintNoChildBusPass when
    ChildBusPass()
then
    System.out.println( "No Child Bus Pass" );
end

rule PrintAdultBussPass when
    AdultBusPass()
then
    System.out.println( "Adult Bus Pass" );
end
