package com.sample

import com.sample.DroolsTest.Message;

/*
rule "Overlap 1a"
	when
		    $s :Something(   )
		    Foo1w( value > $s )
	then
		System.out.println( "Test" );
end

rule "Overlap 1b"
	when
		    $s :Something(  )
		    Foo1w( value < $s )
	then
		System.out.println( "Test" );
end
*/
rule "new rule"
	when
		    Something( a == "1" )
	then
		System.out.println( "Test" );
end