/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Redundant consiquence 1a"
	when
		    $f :Foo1()
	then
		insert( new Test( Test.TestType.TESTING, $f, $f ) );
end

rule "Redundant consiquence 1b"
	when
		    $f :Foo1()
	then
		insert( new Test( Test.TestType.TESTING, $f, $f ) );
end

rule "Redundant consiquence 2a"
	when
		    $f :Foo1()
	then
		Collection c = new ArrayList();
		c.add( "a" );
		c.add( "b" );
		c.add( "c" );
		c.add( "d" );
		c.add( "e" );
		insert( new Test( c ) );
end

rule "Redundant consiquence 2b"
	when
		    $f :Foo1()
	then
		Collection c = new ArrayList();
		c.add( "a" );
		c.add( "b" );
		c.add( "c" );
		c.add( "d" );
		c.add( "e" );
		insert( new Test( c ) );
end

rule "Redundant consiquence 3a"
	when
		    $f :Foo1()
	then
		Collection c = new ArrayList();
		c.add( "a" );
		c.add( "b" );
		
		c.add( "c" );
		
		# comment
		
		c.add( "d" );
		c.add( "e" );
		c.add( "f" );
		insert( new Test( c ) );
end

rule "Redundant consiquence 3b"
	when
		    $f :Foo1()
	then
		Collection c = new ArrayList();
		c.add( "a" );
		c.add( "b" );
		
		# comment
		
		c.add( "c" );
		
		c.add( "d" );
		c.add( "e" );
		c.add( "f" );
		insert( new Test( c ) );
end
