/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Redundant 1a"
	when
		    Foo1( bar == "baz" )
	then
		System.out.println( "Test" );
end

rule "Redundant 1b"
	when
		    Foo1( bar == "baz" )
	then
		System.out.println( "Test" );
end

rule "Redundant 2a"
	when
		    Foo2( bar == 123 )
	then
		System.out.println( "Test" );
end

rule "Redundant 2b"
	when
		    Foo2( bar == 123 )
	then
		System.out.println( "Test" );
end

rule "Redundant 3a"
	when
		    Foo3( bar == "27-Oct-2007" )
	then
		System.out.println( "Test" );
end

rule "Redundant 3b"
	when
		    Foo3( bar == "27-Oct-2007" )
	then
		System.out.println( "Test" );
end

rule "Redundant 4a"
	when
		    Foo4( bar != "baz" )
	then
		System.out.println( "Test" );
end

rule "Redundant 4b"
	when
		    Foo4( bar != "baz" )
	then
		System.out.println( "Test" );
end

rule "Redundant 5a"
	when
		    Foo5( bar > 123 )
	then
		System.out.println( "Test" );
end

rule "Redundant 5b"
	when
		    Foo5( bar > 123 )
	then
		System.out.println( "Test" );
end

rule "Redundant 6a"
	when
		    Foo6( bar < "27-Oct-2007" )
	then
		System.out.println( "Test" );
end

rule "Redundant 6b"
	when
		    Foo6( bar < "27-Oct-2007" )
	then
		System.out.println( "Test" );
end
