/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Redundant 1a"
	when
		    $f :Foo1()
		    Bar1( foo == $f )
	then
		System.out.println( "Test" );
end

rule "Redundant 1b"
	when
		    $f :Foo1()
		    Bar1( foo == $f )
	then
		System.out.println( "Test" );
end

rule "Redundant 2a"
	when
		    $f :Foo2()
		    Bar2( foo == $f && xyz == 123 )
		    or 
		    Bar2( foo == $f && xyz == 321 )
	then
		System.out.println( "Test" );
end

rule "Not Redundant 1a"
	when
		    $f :Foo1a()
		    Bar1a( foo == $f && xyz == 123 )
	then
		System.out.println( "Test" );
end
