/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import org.drools.examples.cdss.data.Diagnose;
import org.drools.examples.cdss.data.Patient;
import org.drools.examples.cdss.data.Recommendation;
import org.drools.examples.cdss.service.RecommendationService;

global RecommendationService recommendationService

rule "Examination1"
	ruleflow-group "Examinations"
	when
	then
		recommendationService.createRecommendation(
			new Recommendation("Examination1"));
end

rule "Examination2"
	ruleflow-group "Examinations"
	when
		Patient( age > 18 )
	then
		recommendationService.createRecommendation(
			new Recommendation("Examination2"));
end

rule "Remove old diagnose"
	ruleflow-group "AdditionalExaminations"
	when
		d: Diagnose( )
	then
		retract(d);
end

rule "Examination3"
	ruleflow-group "AdditionalExaminations"
	when
	then
		recommendationService.createRecommendation(
			new Recommendation("Examination3"));
end