#created on: 29.11.2007
package org.drools.verifier.redundancy.consequences

#list any import classes here.
import org.drools.verifier.components.TextConsequence;
import org.drools.verifier.report.components.Redundancy;
import org.drools.verifier.report.components.RedundancyType;

#declare any global variables here



#
# Dependencies: None
#
rule "Find redundant TextConsequences"
	when
		# Check that VerifierRule $left and $right have redundant fields.
		$left :TextConsequence()
		$right :TextConsequence(
			guid not matches $left.guid,
			text == $left.text
		)

		# Check that there is not already a pair with these values.
		not Redundancy(
			left == $left,
			right == $right
		)
	then
		insert( new Redundancy( RedundancyType.STRONG, $left, $right ) );
end
