/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//created on: 16.11.2009
package org.kie.verifier.redundancy

//list any import classes here.
//global VerifierReport result;



//declare any global variables here
//import org.kie.verifier.data.VerifierReport;
import org.kie.verifier.report.components.Redundancy;
import org.kie.verifier.report.components.Subsumption;
import org.kie.verifier.data.VerifierReport;

global VerifierReport result;

//
// If two objects are subsumptant to each others that makes them redundant.
//
// Dependencies:
//
//    Needs at least the following package:
//        package org.kie.verifier.sumbumption
//
rule "Find redundancy"
    when
        $sub :Subsumption( )

        Subsumption(
            left == $sub.right,
            right == $sub.left
        )

        not Redundancy(
            items contains $sub.left,
            items contains $sub.right
        )
    then
        insert( new Redundancy( $sub.getLeft(),
                                $sub.getRight() ) );
end
