package org.optaplanner.examples.tsp.optional.score;
    dialect "java"

import org.optaplanner.core.api.score.buildin.simplelong.SimpleLongScoreHolder;

import org.optaplanner.examples.tsp.domain.location.Location;
import org.optaplanner.examples.tsp.domain.Domicile;
import org.optaplanner.examples.tsp.domain.Visit;
import org.optaplanner.examples.tsp.domain.TspSolution;

global SimpleLongScoreHolder scoreHolder;

// ############################################################################
// Soft constraints
// ############################################################################

rule "distanceToPreviousStandstill"
    when
        $visit : Visit(previousStandstill != null, $distanceFromPreviousStandstill : distanceFromPreviousStandstill)
    then
        scoreHolder.addConstraintMatch(kcontext, - $distanceFromPreviousStandstill);
end

rule "distanceFromLastVisitToDomicile"
    when
        $visit : Visit(previousStandstill != null)
        not Visit(previousStandstill == $visit)
        $domicile : Domicile()
    then
        scoreHolder.addConstraintMatch(kcontext, - $visit.getDistanceTo($domicile));
end
