/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import org.drools.mvel.compiler.Person;
import org.drools.mvel.compiler.Cheese;
import org.drools.mvel.compiler.Cheesery;
import java.util.List

global List list

rule "match Person 1"
    salience 10
    dialect "mvel"
    when
        $person : Person()
    then
        list.add( $person );
        $person.setStatus("match Person ok");
end    


rule "match Person 2"
    agenda-group "xxx"
    salience ($age2 - $age1)
    when
       $person : Person(name=="mark", $age1 : age )
       cheesery : Cheesery( cheeses contains $person )     
       cheeses : List() from cheesery.getCheeses()           
       Person( age < ( $age1 ) )
       Person( $age2 : age, eval( $age1 == $age2 ) )      
       eval( $age1 == $age2 )
    then
        list.add( $person );
        $person.setStatus("match Person ok");
end   

rule "match Person 3"
    agenda-group "xxx"
    dialect "mvel"
    when
       not Person( name == "mark" )
       exists Person( name == "mark" )       
    then
end 

rule "match Integer"
    agenda-group "yyy"
    auto-focus true
    when
        Person( name ==  "bob" )
    then
        insertLogical ( new Person( "help" ) );
        list.add( new Integer( 4 ) );
end 
