/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List list

rule "single index"
    salience 10
    when
        Primitives( $b : bytePrimitive )
        Primitives( bytePrimitive == $b )
    then
        list.add( "1" );
end    

rule "double index"
    salience 8
    when
        Primitives( $b : bytePrimitive, $s : shortPrimitive )
        Primitives( bytePrimitive == $b, shortPrimitive == $s )
    then
        list.add( "2" );
end    

rule "triple index"
    salience 6
    when
        Primitives( $b : bytePrimitive, $s : shortPrimitive, $i : intPrimitive )
        Primitives( bytePrimitive == $b, shortPrimitive == $s, intPrimitive == $i )
    then
        list.add( "3" );
end    

