/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler

import org.drools.mvel.compiler.Sensor;
import org.drools.mvel.compiler.Alarm;

global java.util.List events;

rule "#1: hot"
when
    $s : Sensor( temperature > 100 )
then
    events.add( "It is hot: " + $s );
    insertLogical(new Alarm("FIRE"));
end

rule "#2: print out"
when
    Alarm( message == "FIRE" )
then
    events.add( "Fire alarm is ON" );
end 