/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.optaplanner.examples.rocktour.solver;
    dialect "java"

import org.optaplanner.core.api.score.buildin.hardmediumsoftlong.HardMediumSoftLongScoreHolder;

import org.optaplanner.examples.rocktour.domain.RockBus;
import org.optaplanner.examples.rocktour.domain.RockShow;
import org.optaplanner.examples.rocktour.domain.RockStandstill;

global HardMediumSoftLongScoreHolder scoreHolder;

// ############################################################################
//  Hard constraints usually
// ############################################################################

rule "Required show"
    when
        RockShow(required == true, date == null)
    then
        scoreHolder.penalize(kcontext);
end

rule "Unassigned show"
    when
        RockShow(bus != null, date == null)
    then
        scoreHolder.penalize(kcontext);
end

// ############################################################################
// Medium constraints usually
// ############################################################################

rule "Revenue opportunity"
    when
        RockShow(date != null, $revenueOpportunity : revenueOpportunity)
    then
        scoreHolder.reward(kcontext, $revenueOpportunity);
end

rule "Driving time to show per second"
    when
        RockShow(previousStandstill != null, $drivingTime : drivingTimeFromPreviousStandstill)
    then
        scoreHolder.penalize(kcontext, $drivingTime);
end

rule "Driving time to bus arrival per second"
    when
        RockShow(nextShow == null, bus != null, $drivingTime : drivingTimeToBusArrivalLocation)
    then
        scoreHolder.penalize(kcontext, $drivingTime);
end

rule "Delay show cost per day"
    when
        RockShow(date != null, $daysAfterBusDeparture : daysAfterBusDeparture)
    then
        scoreHolder.penalize(kcontext, $daysAfterBusDeparture);
end

// ############################################################################
// Soft constraints usually
// ############################################################################

rule "Shorten driving time per millisecond squared"
    when
        RockShow(previousStandstill != null, $drivingTime : drivingTimeFromPreviousStandstill)
    then
        scoreHolder.penalize(kcontext, $drivingTime * $drivingTime);
end
