/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.games.wumpus.client

import org.drools.games.wumpus.*

dialect "mvel"


rule "init" when
then
    channels["commands"].send( new MoveCommand( Move.TURN_LEFT ) );
    insert( 0 );
end 

rule "Rotate" timer(int: 500ms) when
    $i : Integer( this < 7 )
    $sa : SensorArray()
then
    delete( $sa );
    delete( $i );
    insert( $i + 1 );
    channels["commands"].send( new MoveCommand( Move.TURN_LEFT ) );    
end

rule "Print Sensor" when
    $sa : SensorArray()
then
    System.out.println( $sa );
end    
