/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.workitemconsequence

import org.drools.examples.workitemconsequence.WorkItemConsequenceExample2.Greeting;

dialect "mvel"

rule "Call Work Item"
    when
        $g : Greeting( $name : name, response == null )
    then
        org.drools.process.instance.WorkItemManager wiManager = (org.drools.process.instance.WorkItemManager) drools.getWorkingMemory().getWorkItemManager();
        org.drools.process.instance.impl.WorkItemImpl wiGreeting = new org.drools.process.instance.impl.WorkItemImpl();
        wiGreeting.setName( "GreetingWorkItemHandler" );
        wiGreeting.getParameters().put( "name", $name );
        wiManager.internalExecuteWorkItem( wiGreeting );
        
        $g.setResponse( (java.lang.String) wiGreeting.getResult( "response" ) );
        update( $g );
        
end

rule "Show response"
    when
        Greeting( $response : response != null )
    then
        System.out.println( $response );
end
