/**
 * Copyright 2020 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.acme.travels
unit TravellerValidationService

import org.acme.travels.Traveller;


rule "Process travellers"

when
    $traveller: /traveller[processed == false, nationality != 'American']
then
	System.out.println("Hello traveller " + $traveller);   
	$traveller.setProcessed( true );
    
end

rule "Don't process travellers from US"

when
    $traveller: /traveller[processed == false, nationality == 'American']
then
	System.out.println("This system can't deal with " + $traveller.getNationality());
 	$traveller.setProcessed( false ); 
    
end
