////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

== 10.1.0 release notes

=== Language Level DRL10
New language level DRL10 has been added. DRL10 is handled by the new parser based on ANTLR4. The default language level is still DRL6.

DRL10 introduces the following changes mainly to reduce ambiguity:

* Require a prefix '##' to custom operators
* Drop half constraint syntax
* Drop double ampersand as infix and
* Drop double pipe as infix or
* Drop annotation inside LHS pattern

Those syntaxes are deprecated and will be removed in the future. Warnings are logged when the deprecated syntax is used in DRL6.

You can refer xref:language-reference/index.adoc#language-level_drl-rules[Language Level] for details.
