////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

== 10.0.0 release notes

=== DMN 1.5 support
The DMN engine now supports DMN 1.5 specification. You can refer to the OMG official documentation to learn about the introduced features, like:

* Import into the Default Namespace
* New list replace() function
* Alternative image for input Data
* New type restriction attribute typeConstraint
* Possibility to negate a duration
* Possibility to iterate time ranges
* Date type to date and time type coercion

=== Drools Quarkus Extension

Quarkus Extension for Drools has been introduced. You can refer link:https://github.com/apache/incubator-kie-drools/blob/main/drools-quarkus-extension/drools-quarkus-quickstart-test/guide.adoc[Drools Quarkus extension Guide] for details.

=== DRL on YAML

As an experimental feature, DRL on YAML has been introduced, where you can write DRL in YAML format. You can refer link:https://github.com/apache/incubator-kie-drools/tree/main/drools-drlonyaml-parent[DRL on YAML] for details.

=== Drools Reliability

As an experimental feature, Drools Reliability has been introduced, which supports stateful KieSession persistence. You can refer link:https://github.com/apache/incubator-kie-drools/tree/main/drools-reliability[Drools Reliability] for details.