:DROOLS:
include::../_artifacts/document-attributes.adoc[]

[[release.notes]]
:context: release-notes

[id='{context}']
= Release Notes

This chapter contains the release notes for the {PRODUCT} 10-series.

For the release notes of the _previous releases_, you can refer to the {PRODUCT} documentation of link:https://docs.drools.org/8.44.0.Final/drools-docs/drools/release-notes/index.html[version 8].

// This is a placeholder for adding the release notes per minor version
// include::_release-notes-10.0.adoc[leveloffset=0]

== Drools 10-series release notes

=== Minimum requirements update

JDK 17 is now the minimum Java version required to compile Drools and make use of Drools.

Maven `3.8.6` is the minimum Maven version required to build Drools from source, or using `kie-ci` APIs.

=== `drools-mvel` and `drools-engine-classic` are deprecated

`drools-mvel` is deprecated since Drools 8 in favor of the executable model. It also means drools-engine` is recommended instead of deprecated `drools-engine-classic` that contains `drools-mvel`. You can still use MVEL syntax in your rules, so it doesn't affect how to write rules.