:DROOLS:
include::../_artifacts/document-attributes.adoc[]

[[release.notes]]
:context: release-notes

[id='{context}']
= Release Notes

This chapter contains the release notes for the {PRODUCT} 8-series.

For the release notes of the _previous releases_, you can refer to the {PRODUCT} documentation of link:https://docs.drools.org/7.73.0.Final/drools-docs/html_single/index.html#droolsreleasenoteschapter[version 7].

include::_release-notes-8.33.adoc[leveloffset=0]

include::_release-notes-8.32.adoc[leveloffset=0]

include::_release-notes-8.31.adoc[leveloffset=0]

== Drools 8-series release notes

Drools 8-series is a natural evolution of the 7.x-stream, incorporating many features and lessons learned integrating with Kogito and many cloud-native use cases.

=== Rule Unit

Rule Unit is a central paradigm in the Drools 8-series.
You can refer the xref:migration-guide/index.adoc[Migration guide chapter] for more information about Rule Unit.

=== Minimum requirements update

JDK 11 is now the minimum Java version required to compile Drools and make use of Drools.

Maven `3.8.6` is now the minimum Maven version required to build Drools from source, or using `kie-ci` APIs.

=== `drools-mvel` and `drools-engine-classic` are deprecated

`drools-mvel` is now deprecated in favor of the executable model. It also means `drools-engine` is recommended instead of deprecated `drools-engine-classic` that contains `drools-mvel`. You can still use MVEL syntax in your rules, so it doesn't affect how to write rules.

=== Spreadsheet decision tables file extensions

To ensure only files containing Drools decision tables are actually processed for rules compilation, file extension must end in either `.drl.xls`, `.drl.xlsx`, or `.drl.csv`. For example: `rules.drl.xls` is a valid extension and will be included for rule compilation when found in a KJAR based project.

=== Security Manager deprecation

The {PRODUCT} features related to the JDK Security Manager will not be further developed, as starting with JDK17, the Java Platform has deprecated the Security Manager for removal.
You can refer the xref:KIE/index.adoc#_securitymanager[Security Manager chapter] for more information.

=== KIE Marshallers notice

The `KieMarshallers` are still present and working as expected on the release of the Drools 8-series, however we are currently exploring alternative solutions more idiomatic to cloud-native use cases.

=== {KIE_SERVER} is retired
{KIE_SERVER} is no longer a component of {PRODUCT} 8.  For migration, see xref:migration-guide/index.adoc#kie-server_migration-guide[Migration guide chapter].

=== {BUSINESS_CENTRAL} is retired
{BUSINESS_CENTRAL} is no longer a component of {PRODUCT} 8.  For migration, see xref:migration-guide/index.adoc#business-central_migration-guide[Migration guide chapter].

=== OSGi support is retired
{PRODUCT} 8 no longer provides out of the box OSGi support in its modules.

== Previous release notes

For the release notes of the previous releases, you can refer the {PRODUCT} documentation of link:https://docs.drools.org/7.73.0.Final/drools-docs/html_single/index.html#droolsreleasenoteschapter[version 7]. 