/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

 package org.drools.testcoverage.regression;

 import org.drools.testcoverage.common.model.Person;
 import org.drools.testcoverage.common.model.Message;

rule "or1"
	when
		Person( name == "multi" || == "restriction" )
	then
		insert(new Message("or1 fired"));
end

rule "or2"
	when
		Person (name matches "[a-z]*" || matches "[A-Z]*")
	then
		insert(new Message("or2 fired"));
end

rule "and"
	when
		Person (id >= 0 && <= 5)
	then
		insert(new Message("and fired"));
end