/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package test;

import org.drools.compiler.integrationtests.eventgenerator.*;

query "all inserted events"
    Event()
end

query "all inserted events with generation time < 1 min"
    Event(eval(endTime<PseudoSessionClock.timeInMinutes(1)))
end

query "all inserted events with 2 min < generation time < 3 min"
    Event(eval (endTime>PseudoSessionClock.timeInMinutes(2)), eval(endTime<PseudoSessionClock.timeInMinutes(3)))
end

query "all inserted events with parent resource A"
    Event(parentId=="resA")
end

query "all inserted events with parent resource B"
    Event(parentId=="resB")
end
