/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.defeasible;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare C
    id  : int   @key
end

declare D
    id  : int   @key
end

declare X
    id  : int   @key
end

declare Y
    id  : int   @key
end

rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
    insert( new A( 3 ) );   // A(3) is a Fact
    insert( new B( 2 ) );   // same for B(2)
end

rule "Defeater Rule"
@Defeater
when
    A( 1; )
    B( 2; )
then
    insertLogical( new X( -1 ), "neg" );
end

rule "Strict Rule 2"
@Strict
when
    A( 3; )
then
    insertLogical( new X( -1 ) );
    insertLogical( new C( 99 ) );
end

rule "Strict Rule 3"
@Defeasible
@Defeats( { "Defeater Rule", "Another rule" } )
when
    C( 99; )
then
    insertLogical( new X( -1 ) );
end


