/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

rule using_from
  when
    Foo() from bar.baz
    Foo() from bar.baz["key"]    
    Foo() from bar.baz[$key]    
    Foo() from bar.baz[1]        
    Whee(bar=="baz") from whee("y")
    f: Foo(la==2) from bar.la(x)   
    Bam() from wa()
    Kah() from la.wa(42, 42.42, false, null)
    Bam(a=="c") 
  then
      whee();
end
