/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

declare NetworkNode
            locElevation: java.math.BigDecimal
            name: String @key
            nodeClass: String
            locLongitude: java.math.BigDecimal
            nodeType: String
            locLatitude: java.math.BigDecimal
end

declare NetworkConnection
            id: String @key
            node1: NetworkNode
            node2: NetworkNode
            hops: Integer
end

declare NetworkEvent
            @role( event )
            @timestamp( creationTime )

            id: String @key
            locElevation: java.math.BigDecimal
            description: String
            sourceComponent: NetworkNode
            locLongitude: java.math.BigDecimal
            severity: Integer
            creationTime: java.util.Date
            locLatitude: java.math.BigDecimal
end
