= OptaPlanner Operator (experimental)

The OptaPlanner solver operator enables running OptaPlanner workloads on Kubernetes.

*Please note that the OptaPlanner Operator is experimental. As such, it provides no guarantees
in terms of maturity and backward compatibility.*

== Prerequisites

=== Get your environment running

Use an existing OpenShift cluster or download and start either https://developers.redhat.com/products/codeready-containers/overview[RedHat CodeReady Containers] or https://minikube.sigs.k8s.io/docs/start/[Minikube] for a local development.

=== Install ArtemisCloud

The OptaPlanner solver operator depends on ArtemisCloud for creating ActiveMQ queues. To install ArtemisCloud to Minikube or OpenShift and to create a new broker, follow the https://artemiscloud.io/docs/help/operator/[documentation].

NOTE: The ArtemisCloud operator by default watches for ActiveMQ broker and queue resources in the namespace it has been installed to.

== Local development with Minikube

. Run `mvn quarkus:dev` to start the solver operator locally. The operator will connect to the Kubernetes cluster you are logged in.

[#deployToOpenShift]
== Deployment to OpenShift

Login as a user with the `cluster-admin` role.

[#deployOperator]
=== Deploy the OptaPlanner Operator

. Create the `optaplanner-operator` project by running `oc new-project optaplanner-operator`.
. Run `mvn clean package -Dopenshift`.
. Apply the generated CRD by running `oc create -f target/kubernetes/solvers.org.optaplanner.solver-v1.yml`.
. Apply the prepared template by running `oc apply -f src/k8s/openshift.yml`.

TIP: If you encounter the `Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed` exception due to self-signed certificate during the build, add the `-Dquarkus.kubernetes-client.trust-certs=true` property.

== Try the OptaPlanner Operator

=== Create a solver custom resource

The Solver custom resource describes the problem to be solved on Kubernetes and the infrastructure it requires.

There is an example you can use by running either `kubectl apply -f src/k8s/school-timetabling-solver.yml -n <namespace>` (Minikube) or `oc apply -f src/k8s/school-timetabling-solver.yml` (OpenShift).

To check the created resource, run `kubectl get solver -n <namespace>` (Minikube) or `oc get solver` (OpenShift).
