= OptaPlanner Operator (experimental)

*Please note that the OptaPlanner Operator is experimental. As such, it provides no guarantees
in terms of maturity and backward compatibility.*

The OptaPlanner solver operator enables running OptaPlanner workloads on Kubernetes.


== Prerequisites

=== Get your environment running

Log in to an existing OpenShift cluster or use either https://developers.redhat.com/products/codeready-containers/overview[RedHat CodeReady Containers] or https://minikube.sigs.k8s.io/docs/start/[Minikube] for a local development.

=== Install Strimzi

The OptaPlanner solver operator depends on Strimzi for creating Kafka topics. To install Strimzi to Minikube or OpenShift,
see the following sections.

== Local development with Minikube

. Install Strimzi by following their https://strimzi.io/quickstarts/[quickstart].
. Run `mvn quarkus:dev` to start the solver operator locally. The operator will connect to the Kubernetes cluster you are logged in.

== Deployment to OpenShift

=== Install Strimzi

In the OpenShift console, navigate to the menu Operators -> Operator Hub. Find the "Strimzi" operator and install it.

=== Deploy the OptaPlanner Operator

. Create the `optaplanner-operator` project by running `oc new-project optaplanner-operator`
. Run `mvn clean package -Dopenshift`.
. Apply the generated CRD by running `oc create -f target/kubernetes/solvers.org.optaplanner.solver-v1.yml.
. Apply the generated template by running `oc apply -f src/k8s/openshift.yml.

== Try the OptaPlanner Operator

=== Create a solver custom resource

. Create a solver resource that follows the generated CRD. There is an example you can use by running either `kubectl apply -f src/k8s/example-resource.yml -n <namespace>` (Minikube) or `oc apply -f src/k8s/example-resource.yml` (OpenShift).
. Check the created resource: `kubectl get solver -n <namespace>` (Minikube) or `oc get solver` (OpenShift).
