/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

template header
age[]
priorClaims
policyType
discount

package org.acme.insurance;

template "discounts"
age
priorClaims
policyType
discount

rule "Discounts_@{row.rowNumber}"

    when
        Driver(age >= @{age0}, age <= @{age1}, priorClaims == "@{priorClaims}")
        policy: Policy(type == "@{policyType}")
    then
        policy.applyDiscount(@{discount});
end
end template
