/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

template header
age[]
profile
priorClaims
policyType
base
reason

package org.acme.insurance;

template "Pricing bracket"
age
policyType
base

rule "Pricing bracket_@{row.rowNumber}"

    when
        Driver(age >= @{age0}, age <= @{age1}
            , priorClaims == "@{priorClaims}"
            , locationRiskProfile == "@{profile}"
        )
        policy: Policy(type == "@{policyType}")
    then
        policy.setBasePrice(@{base});
        System.out.println("@{reason}");
end
end template
