#!/bin/sh
APPDIR=`dirname $0`;
java -cp "$APPDIR/src:/home/michael/apps/gwt/gwt-user.jar:/home/michael/apps/gwt/gwt-dev-linux.jar" com.google.gwt.dev.GWTCompiler -out "$APPDIR/www" "$@" org.drools.brms.JBRMS;
