package org.drools.defeasible;

global java.util.List list;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare C
    id  : int   @key
end

declare D
    id  : int   @key
end

declare X
    id  : int   @key
end

declare Y
    id  : int   @key
end



rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
    insert( new A( 3 ) );   // A(1) is a Fact
    insert( new B( 2 ) );   // same for B(2)
end

rule "Defeater Rule"
@Defeater
@Defeats( "Rule 3" )
when
    B( 2; )
then
    insertLogical( new X( -1 ), "neg" );
end


rule "Rule 3"
@Defeasible
salience 2
when
    A( )
then
    insertLogical( new X( -1 ) );
end


rule "Fire X"
salience 100
when
    X( -1; )
then
    list.add( "Stage1" );
end


rule "Fires after go is inserted"
salience -100
when
    X( -1; )
then
    list.add( "Stage2" );
end



rule "Defeater Defeater Rule"
@Defeats( "Defeater Rule" )
@Defeasible
when
    $s : String( this == "go" )
    B( 2; )
then
    insertLogical( new X( -1 ) );
end