package org.drools.defeasible;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare X
    id  : int   @key
end

declare Y
    id  : int   @key
end

declare entry-point "neg" end

rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
    insert( new B( 2 ) );   // same for B(2)
end

rule "Defeater Rule 1"
@Defeater
@Defeats( "Victim" )
when
    B( 2; )
then
    insertLogical( new X( -1 ), "neg" );
end

rule "Defeater Rule 2"
@Defeater
@Defeats( "Victim" )
when
    B( 2; )
then
    insertLogical( new X( -1 ), "neg" );
end


rule "Victim"
@Defeasible
when
    A( )
then
    insertLogical( new X( -1 ) );
end


