package org.kie.beliefsystem.defeasible;

global java.util.List list;

declare Matter
    id      : int       @key
    name    : String
end


rule "Positive"
salience 100
when
    Matter( $n : name )
then
    list.add( "+" + $n );
end

rule "Negative"
salience 100
when
    Matter( $n : name ) from entry-point "neg"
then
    list.add( "-" + $n );
end

rule "Pos2"
salience -100
when
    Matter( $n : name )
then
    list.add( "++" + $n );
end

rule "Neg2"
salience -100
when
    Matter( $n : name ) from entry-point "neg"
then
    list.add( "--" + $n );
end



rule "Init +"
when
then
    insertLogical( new Matter( 0, "plus" ) );
end

rule "Init -"
salience -1
when
then
    insertLogical( new Matter( 0, "minus" ), "neg" );
end