/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.games.wumpus;

import org.drools.games.Run;
import org.drools.games.wumpus.view.GameUI;

dialect  "mvel"

rule "main1" when
then
    insert( new Run() );
    setFocus( "Init" );
end

rule "main2" when
    $r : Run()
then
    setFocus( "PaintSensor" );
    setFocus( "PaintCave" );
    setFocus( "UpdateScore" );
    setFocus( "Score" );
    setFocus( "Sensor" );
    setFocus( "Commands" );
    setFocus( "Score" );
    setFocus( "Sensor" );
end

rule "Redraw Cave" when
   $gui : GameUI()
   $r : Run()
then
   $gui.repaint();
   modify( $r ) {}
end