////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

[id="con-migration-to-kogito-overview_{context}"]
= Overview of migration from {PRODUCT} v7 to {KOGITO} microservices

[role="_abstract"]
You can migrate the decision service artifacts that you developed in {PRODUCT} v7 to {KOGITO} microservices. {KOGITO} currently supports migration for the following types of decision services:

* *Decision Model and Notation (DMN) models*: You migrate DMN-based decision services by moving the DMN resources from KJAR artifacts to the respective {KOGITO} archetype.

* *Predictive Model Markup Language (PMML) models*: You migrate PMML-based prediction and prediction services by moving the PMML resources from KJAR artifacts to the respective {KOGITO} archetype.

* *Drools Rule Language (DRL) rules*: You migrate the DRL-based decision services by enclosing them in a {QUARKUS} REST endpoint. This approach of migration enables you to use major Quarkus features, such as hot reload and native compilation. The Quarkus features and the programming model of {KOGITO} enable the automatic generation of the Quarkus REST endpoints for implementation in your applications and services.
