////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

[id="proc-kogito-migrate-external-application-REST_{context}"]
= Migrating external applications to REST endpoints specific to DMN models

[role="_abstract"]
To migrate a DMN project to a {KOGITO} deployment, first you can migrate external applications that use specific DMN REST endpoints to interact with decision services on the {KIE_SERVER}.

.Procedure
. If you are using the REST endpoints in your external application, retrieve the Swagger or OAS specification file of the KJAR using `GET /server/containers/\{containerId}/dmn/openapi.json (|.yaml)` endpoint.
+
For additional information about REST endpoints for specific DMN models, you can reference https://blog.kie.org/2021/03/new-model-specific-dmn-kie-server-endpoints.html[_REST endpoints for specific DMN models_ blog post].

. In your external application, select the Java or JDK library to interact with the decision services. You can interact with the decision services using the REST endpoint for the specific KJAR.

NOTE: The {KIE_SERVER} Client Java API is not supported in the migration to a {KOGITO} deployment.
