[id="con-kogito-modelers_{context}"]
= BPMN and DMN modelers for {KOGITO} microservices

{PRODUCT} provides extensions or applications that you can use to design Business Process Model and Notation (BPMN) process models and Decision Model and Notation (DMN) decision models for your {KOGITO} microservices using graphical modelers.

The following BPMN and DMN modelers are supported:

* *VSCode extension*: Enables you to view and design BPMN and DMN models in Visual Studio Code (VSCode). The VSCode extension requires VSCode 1.46.0 or later.
+
To install the VSCode extension directly in VSCode, select the *Extensions* menu option in VSCode and search for and install the *Red Hat Business Automation Bundle* extension.

* *Business Modeler standalone editors*: Enable you to view and design BPMN and DMN models embedded in your web applications. To download the necessary files, you can either use the NPM artifacts from the https://www.npmjs.com/package/@kogito-tooling/kie-editors-standalone[Kogito tooling repository] or download the JavaScript files directly for the DMN standalone editor library at `https://kiegroup.github.io/kogito-online/standalone/dmn/index.js` and for the BPMN standalone editor library at `https://kiegroup.github.io/kogito-online/standalone/bpmn/index.js`.
