[id="con-kogito-microservices_{context}"]
= {KOGITO} microservices in {PRODUCT}

{KOGITO} is a cloud-native business automation technology for building cloud-ready business applications. The name _Kogito_ derives from the Latin "Cogito", as in "Cogito, ergo sum" ("I think, therefore I am"), and is pronounced `[ˈkoː.d͡ʒi.to]` (_KO-jee-to_). The letter _K_ refers to Kubernetes, the base for {OPENSHIFT} as the target cloud platform for {PRODUCT}, and to the Knowledge Is Everything (KIE) open source business automation project from which {KOGITO} originates.

{KOGITO} in {PRODUCT} is optimized for a hybrid cloud environment and adapts to your domain and tooling needs. The core objective of {KOGITO} microservices is to help you mold a set of decisions into your own domain-specific cloud-native set of services.

IMPORTANT: In {PRODUCT} {ENTERPRISE_VERSION} version, {KOGITO} support is limited to decision services, including Decision Model and Notation (DMN), Drools Rule Language (DRL), and Predictive Model Markup Language (PMML). This support will be improved and extended to Business Process Modeling Notation (BPMN) in a future release.

When you use {KOGITO}, you are building a cloud-native application as a set of independent domain-specific microservices to achieve some business value. The decisions that you use to describe the target behavior are executed as part of the microservices that you create. The resulting microservices are highly distributed and scalable with no centralized orchestration service, and the runtime that your microservice uses is optimized for what is required.

As a business rules developer, you can use {KOGITO} microservices in {PRODUCT} to build cloud-native applications that adapt to your business domain and tooling.
