[id="con-kogito-microservices-quarkus-springboot_{context}"]
= {KOGITO} microservices on {QUARKUS} and Spring Boot

The primary Java frameworks that {KOGITO} microservices support are {QUARKUS} and Spring Boot.

https://access.redhat.com/products/quarkus[{QUARKUS}] is a Kubernetes-native Java framework with a container-first approach to building Java applications, especially for Java virtual machines (JVMs) such as OpenJDK HotSpot. {QUARKUS} optimizes Java specifically for Kubernetes by reducing the size of both the Java application and container image footprint, eliminating some of the Java programming workload from previous generations, and reducing the amount of memory required to run those images.

For {KOGITO} microservices, {QUARKUS} is the preferred framework for optimal Kubernetes compatibility and enhanced developer features, such as live reload in development mode for advanced debugging.

https://access.redhat.com/products/spring-boot[Spring Boot] is a Java-based framework for building standalone production-ready Spring applications. Spring Boot enables you to develop Spring applications with minimal configurations and without an entire Spring configuration setup.

For {KOGITO} microservices, Spring Boot is supported for developers who need to use {PRODUCT} in an existing Spring Framework environment.
