[id="con-migration-to-kogito-overview_{context}"]
= Overview of migration to {KOGITO} microservices

[role="_abstract"]
You can migrate the decision service artifacts that you developed in {CENTRAL} to {KOGITO} microservices. {KOGITO} currently supports migration for the following types of decision services:

* *Decision Model and Notation (DMN) models*: You migrate DMN-based decision services by moving the DMN resources from KJAR artifacts to the respective {KOGITO} archetype.

* *Predictive Model Markup Language (PMML) models*: You migrate PMML-based prediction and prediction services by moving the PMML resources from KJAR artifacts to the respective {KOGITO} archetype.

* *Drools Rule Language (DRL) rules*: You migrate the DRL-based decision services by enclosing them in a {QUARKUS} REST endpoint. This approach of migration enables you to use major Quarkus features, such as hot reload and native compilation. The Quarkus features and the programming model of {KOGITO} enable the automatic generation of the Quarkus REST endpoints for implementation in your applications and services.
