[id="con-kogito-microservices-on-ocp_{context}"]
= {KOGITO} on {OPENSHIFT}

You can deploy {KOGITO} microservices on {OPENSHIFT} for cloud implementation. In this architecture, {KOGITO} microservices are deployed as OpenShift pods that you can scale up and down individually to provide as few or as many containers as required for a particular service.

To help you deploy your {KOGITO} microservices on OpenShift, {PRODUCT} provides *{PRODUCT_PAM} Kogito Operator*. This operator guides you through the deployment process. The operator is based on the https://sdk.operatorframework.io/[Operator SDK] and automates many of the deployment steps for you. For example, when you provide the operator with a link to the Git repository that contains your application, the operator automatically configures the components required to build your project from source and deploys the resulting services.

To install the {PRODUCT_PAM} Kogito Operator in OpenShift web console, go to *Operators* -> *OperatorHub* in the left menu, search for and select *RHPAM Kogito Operator*, and follow the on-screen instructions to install the latest operator version.
