[id="proc-kogito-migrate-dmn-model-kjar_{context}"]
= Migrating a DMN model KJAR to a {KOGITO} microservice

[role="_abstract"]
After migrating your external application, you need to migrate a KJAR that is specific to a DMN model to a {KOGITO} microservice.

.Procedure
. Create a Maven project for your {KOGITO} microservice.
+
For the procedure about creating a Maven project, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#proc-kogito-creating-maven-project_getting-started-kogito-microservices[_Creating a Maven project for a {KOGITO} microservice_].
+
The Maven project creates Kogito artifacts.

. Copy the DMN models from the `src/main/resources` folder of the KJAR to the `src/main/resources` folder of the Kogito artifact.
. Copy the test scenarios from the `src/test/resources` folder of the KJAR to the `src/test/resources` folder of the Kogito artifact.
+
IMPORTANT: You need to import the {KOGITO} dependency of test scenarios in the `pom.xml` file of your project and create a JUnit activator using the {KIE_SERVER} REST API. For more information, see {URL_DEVELOPING_DECISION_SERVICES}#assembly-test-scenarios[_{TESTING_DECISION_SERVICE}_].

. Run the following command and ensure that the test scenario is running for the specified non-regression tests.
+
--
[source]
----
mvn clean install
----

After running the {KOGITO} application, you can retrieve the Swagger or OAS specification file. The Swagger or OAS specifications provide the same information as the REST endpoint along with the following implementation details:

* Base URL of the server where the API is available
* References Schemas names

You can use the provided implementation details when your external application is re-routed to the new URL.
--

After migrating a DMN model KJAR to a {KOGITO} microservice, you need to deploy the microservice using {OPENSHIFT}. For deployment options with Openshift, see {URL_GETTING_STARTED_KOGITO_MICROSERVICES}#con-kogito-operator-deployment-options_deploying-kogito-microservices-on-openshift[_OpenShift deployment options with the RHPAM Kogito Operator_].
