[id="proc-kogito-custom-spring-boot-project-creating_{context}"]
= Creating a custom Spring Boot project for {KOGITO} microservices

You can create custom Maven projects using the Spring Boot archetype for your {KOGITO} microservices. The Spring Boot archetype enables you to add Spring Boot starters or add-ons to your project.

A Spring Boot starter is an all-in-one descriptor for your project and requires business automation engines provided by {KOGITO}. The Spring Boot starters include decisions, rules, and predictions.

When your project contains all the assets and you want a quick way to get started with {KOGITO}, you can use the `kogito-spring-boot-starter` starter. For a more granular approach, you can use a specific starter, such as `kogito-decisions-spring-boot-starter` for decisions, or a combination of starters.

{KOGITO} supports the following Spring Boot starters:

////
Processes Spring Boot starter::
Starter for providing BPMN support to your Spring Boot project. The following is an example of adding a processes Spring boot starter to your project:
+
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-processes-spring-boot-starter</artifactId>
  </dependency>
</dependencies>
----
////

Decisions Spring Boot starter::
Starter for providing DMN support to your Spring Boot project. The following is an example of adding a decisions Spring boot starter to your project:
+
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-decisions-spring-boot-starter</artifactId>
  </dependency>
</dependencies>
----

Predictions Spring Boot starter::
Starter for providing PMML support to your Spring Boot project. The following is an example of adding a predictions Spring boot starter to your project:
+
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-predictions-spring-boot-starter</artifactId>
  </dependency>
</dependencies>
----

Rules Spring Boot starter::
Starter for providing DRL support to your Spring Boot project. The following is an example of adding a rules Spring boot starter to your project:
+
[source,xml]
----
<dependencies>
  <dependency>
    <groupId>org.kie.kogito</groupId>
    <artifactId>kogito-rules-spring-boot-starter</artifactId>
  </dependency>
</dependencies>
----

.Procedure
. In a command terminal, navigate to a local folder where you want to store the new project.
. Enter one of the following commands to generate a project using the `starters` or `addons` property:
* To generate a project using the `starters` property, enter the following command:
+
--
[source,subs="attributes+"]
----
$ mvn archetype:generate \
    -DarchetypeGroupId=org.kie.kogito \
    -DarchetypeArtifactId=kogito-springboot-archetype \
    -DgroupId=org.acme -DartifactId=sample-kogito \
    -DarchetypeVersion={KOGITO_VERSION_LONG} \
    -Dversion=1.0-SNAPSHOT
    -Dstarters=decisions
----
The new project includes the dependencies required to run the decision microservices. You can combine multiple Spring Boot starters using a comma-separated list, such as `starters=decisions,rules`.
--

* To generate a project containing Prometheus monitoring using the `addons` property, enter the following command:
+
--
[source,subs="attributes+"]
----
$ mvn archetype:generate \
    -DarchetypeGroupId=org.kie.kogito \
    -DarchetypeArtifactId=kogito-springboot-archetype \
    -DgroupId=org.acme -DartifactId=sample-kogito \
    -DarchetypeVersion={KOGITO_VERSION_LONG} \
    -Dversion=1.0-SNAPSHOT
    -Dstarters=descisions
    -Daddons=monitoring-prometheus,persistence-infinispan
----

NOTE: When you pass an add-on to the property, the add-on name does not require the `kogito-addons-springboot` prefix. Also, you can combine the `add-ons` and `starters` properties to customize the project.
--

+
. Open or import the project in your IDE to view the contents.
