[id="proc-kogito-creating-maven-project_{context}"]
= Creating a Maven project for a {KOGITO} microservice

Before you can begin developing {KOGITO} microservices, you need to create a Maven project where you can build your assets and any other related resources for your application.

.Procedure
. In a command terminal, navigate to a local folder where you want to store the new project.
. Enter the following command to generate a project within a defined folder:
+
--
.On {QUARKUS}
[source,subs="attributes+"]
----
$ mvn io.quarkus:quarkus-maven-plugin:create \
    -DprojectGroupId=org.acme -DprojectArtifactId=sample-kogito \
    -DprojectVersion=1.0.0-SNAPSHOT -Dextensions=kogito-quarkus
----

.On Spring Boot
[source,subs="attributes+"]
----
$ mvn archetype:generate \
    -DarchetypeGroupId=org.kie.kogito \
    -DarchetypeArtifactId=kogito-spring-boot-archetype \
    -DgroupId=org.acme -DartifactId=sample-kogito \
    -DarchetypeVersion={KOGITO_VERSION_LONG} \
    -Dversion=1.0-SNAPSHOT
----

This command generates a `sample-kogito` Maven project and imports the extension for all required dependencies and configurations to prepare your application for business automation.

If you want to enable PMML execution for your project, add the following dependency to the `pom.xml` file in the Maven project that contains your {KOGITO} microservices:

.Dependency to enable PMML execution
[source,xml]
----
<dependency>
  <groupId>org.kie.kogito</groupId>
  <artifactId>kogito-pmml</artifactId>
</dependency>
<dependency>
  <groupId>org.jpmml</groupId>
  <artifactId>pmml-model</artifactId>
</dependency>
----

On {QUARKUS}, if you plan to run your application on OpenShift, you must also import the `smallrye-health` extension for the https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes[liveness and readiness probes], as shown in the following example:

.SmallRye Health extension for {QUARKUS} applications on OpenShift
[source]
----
$ mvn quarkus:add-extension -Dextensions="smallrye-health"
----

This command generates the following dependency in the `pom.xml` file of your {PRODUCT} project on {QUARKUS}:

.SmallRye Health dependency for {QUARKUS} applications on OpenShift
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-health</artifactId>
</dependency>
----
--
. Open or import the project in your VS Code IDE to view the contents.
