[id="proc-kogito-microservices-deploying-on-ocp-console-file-build_{context}"]
= Deploying {KOGITO} microservices on OpenShift using file build and OpenShift web console

You can build and deploy your {KOGITO} microservices from a single file, such as a Decision Model and Notation (DMN), Drools Rule Language (DRL), or properties file, or from a directory with multiple files. You can specify a single file from your local file system path or specify a file directory from a local file system path only. When you upload the file or directory to an OpenShift cluster, a new Source-to-Image (S2I) build is automatically triggered.

The operator uses the following custom resources to deploy domain-specific microservices (the microservices that you develop):

* `KogitoBuild` generates an application from a file and produces a runtime image.
* `KogitoRuntime` starts the runtime image and configures it as per your requirements.

.Prerequisites
* The RHPAM Kogito Operator is installed.
* The `oc` OpenShift CLI is installed and you are logged in to the relevant OpenShift cluster. For `oc` installation and login instructions, see the https://access.redhat.com/documentation/en-us/openshift_container_platform/{OPENSHIFT_VERSION}/html/cli_tools/openshift-cli-oc[OpenShift documentation].
* You have access to the OpenShift web console with the necessary permissions to create and edit `KogitoBuild` and `KogitoRuntime`.

.Procedure
. Go to *Operators* -> *Installed Operators* and select *RHPAM Kogito Operator*.
. To create the {KOGITO} build definition, on the operator page, select the *Kogito Build* tab and click *Create KogitoBuild*.
. In the application window, use *Form View* or *YAML View* to configure the build definition.
+
--
At a minimum, define the application configurations shown in the following example YAML file:

.Example YAML definition for a {QUARKUS} application with {KOGITO} build
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this service
kind: KogitoBuild  # Application type
metadata:
  name: example-quarkus  # Application name
spec:
  type: LocalSource
----

.Example YAML definition for a Spring Boot application with {KOGITO} build
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this service
kind: KogitoBuild  # Application type
metadata:
  name: example-springboot  # Application name
spec:
  runtime: springboot
  type: LocalSource
----

[NOTE]
====
If you configured an internal Maven repository, you can use it as a Maven mirror service and specify the Maven mirror URL in your {KOGITO} build definition to shorten build time substantially:

[source,yaml]
----
spec:
  mavenMirrorURL: http://nexus3-nexus.apps-crc.testing/repository/maven-public/
----

For more information about internal Maven repositories, see the https://maven.apache.org/guides/introduction/introduction-to-repositories.html[Apache Maven] documentation.
====
--

. After you define your application data, click *Create* to generate the {KOGITO} build.
+
Your application is listed in the *{KOGITO}Builds* page. You can select the application name to view or modify application settings and YAML details.

. Upload the file asset using the following command:
+
--
[source]
----
$ oc start-build example-quarkus-builder --from-file=<file-asset-path> -n namespace
----

* `file-asset-path` is the path of the file asset that you want to upload.
* `namespace` is the namespace where `KogitoBuild` is created.
--

. To create the {KOGITO} microservice definition, on the operator page, select the *Kogito Runtime* tab and click *Create KogitoRuntime*.
. In the application window, use *Form View* or *YAML View* to configure the microservice definition.
+
--
At a minimum, define the application configurations shown in the following example YAML file:

.Example YAML definition for a {QUARKUS} application with {KOGITO} microservices
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this microservice
kind: KogitoRuntime  # Application type
metadata:
  name: example-quarkus  # Application name
----

.Example YAML definition for a Spring Boot application with {KOGITO} microservices
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this microservice
kind: KogitoRuntime  # Application type
metadata:
  name: example-springboot  # Application name
spec:
  runtime: springboot
----

[NOTE]
====
In this case, the application is built from a file and deployed using KogitoRuntime. You must ensure that the application name is same in `KogitoBuild` and `KogitoRuntime`.
====
--

. After you define your application data, click *Create* to generate the {KOGITO} microservice.
+
Your application is listed in the {KOGITO} microservice page. You can select the application name to view or modify application settings and the contents of the YAML file.

. In the left menu of the web console, go to *Builds* -> *Builds* to view the status of your application build.
+
--
You can select a specific build to view build details.

[NOTE]
====
For every {KOGITO} microservice that you create for OpenShift deployment, two builds are generated and listed in the *Builds* page in the web console: a traditional runtime build and a Source-to-Image (S2I) build with the suffix `-builder`. The S2I mechanism builds the application in an OpenShift build and then passes the built application to the next OpenShift build to be packaged into the runtime container image.
====
--

. After the application build is complete, go to *Workloads* -> *Deployments* to view the application deployments, pod status, and other details.

. After your {KOGITO} microservice is deployed, in the left menu of the web console, go to *Networking* -> *Routes* to view the access link to the deployed application.
+
You can select the application name to view or modify route settings.
+
With the application route, you can integrate your {KOGITO} microservices with your business automation solutions as needed.
