[id="proc-kogito-microservices-deploying-on-ocp-console-custom-image-build_{context}"]
= Deploying {KOGITO} microservices on OpenShift using custom image build and OpenShift web console

You can use custom image build as an alternative for building and deploying your {KOGITO} microservices on OpenShift.

The operator uses the following custom resources to deploy domain-specific microservices (the microservices that you develop):

* `KogitoRuntime` starts the runtime image and configures it as per your requirements.

.Prerequisites
* The RHPAM Kogito Operator is installed.
* You have access to the OpenShift web console with the necessary permissions to create and edit `KogitoRuntime`.
* ({QUARKUS} only) The `pom.xml` file of your project contains the following dependency for the `quarkus-smallrye-health` extension. This extension enables the https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes[liveness and readiness probes] that are required for {QUARKUS} projects on OpenShift.
+
.SmallRye Health dependency for {QUARKUS} applications on OpenShift
[source,xml]
----
<dependency>
  <groupId>io.quarkus</groupId>
  <artifactId>quarkus-smallrye-health</artifactId>
</dependency>
----

.Procedure
. Build an application locally.
. Create `Containerfile` in the project root folder with the following content:
+
--
.Example `Containerfile` for a {QUARKUS} application
[source]
----
FROM registry.redhat.io/rhpam-7/rhpam-kogito-runtime-jvm-rhel8:7.11.0

ENV RUNTIME_TYPE quarkus

COPY target/quarkus-app/lib/ $KOGITO_HOME/bin/lib/
COPY target/quarkus-app/*.jar $KOGITO_HOME/bin
COPY target/quarkus-app/app/ $KOGITO_HOME/bin/app/
COPY target/quarkus-app/quarkus/ $KOGITO_HOME/bin/quarkus/
----

.Example `Containerfile` for a Spring Boot application
[source]
----
FROM registry.redhat.io/rhpam-7/rhpam-kogito-runtime-jvm-rhel8:7.11.0

ENV RUNTIME_TYPE springboot

COPY target/<application-jar-file> $KOGITO_HOME/bin
----

* `application-jar-file` is the name of the JAR file of the application.
--

. Build the {KOGITO} image using the following command:
+
--
[source]
----
podman build --tag <final-image-name> -f <Container-file>
----
In the previous command, `final-image-name` is the name of the {KOGITO} image and `Container-file` is name of the `Containerfile` that you created in the previous step.
--

. Optionally, test the built image using the following command:
+
[source]
----
podman run --rm -it -p 8080:8080 <final-image-name>
----

. Push the built {KOGITO} image to an image registry using the following command:
+
[source]
----
podman push <final-image-name>
----

. Go to *Operators* -> *Installed Operators* and select *RHPAM Kogito Operator*.
. To create the {KOGITO} microservice definition, on the operator page, select the *Kogito Runtime* tab and click *Create KogitoRuntime*.
. In the application window, use *Form View* or *YAML View* to configure the microservice definition.
+
--
At a minimum, define the application configurations shown in the following example YAML file:

.Example YAML definition for a {QUARKUS} application with {KOGITO} microservices
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this microservice
kind: KogitoRuntime # Application type
metadata:
  name: example-quarkus # Application name
spec:
  image: <final-image-name> # Kogito image name
  insecureImageRegistry: true # Can be omitted when image is pushed into secured registry with valid certificate
----

.Example YAML definition for a Spring Boot application with {KOGITO} microservices
[source,yaml,subs="attributes+"]
----
apiVersion: rhpam.kiegroup.org/v1 # {KOGITO} API for this microservice
kind: KogitoRuntime # Application type
metadata:
  name: example-springboot # Application name
spec:
  image: <final-image-name> # Kogito image name
  insecureImageRegistry: true # Can be omitted when image is pushed into secured registry with valid certificate
  runtime: springboot
----
--

. After you define your application data, click *Create* to generate the {KOGITO} microservice.
+
Your application is listed in the {KOGITO} microservice page. You can select the application name to view or modify application settings and the contents of the YAML file.

. After the application build is complete, go to *Workloads* -> *Deployments* to view the application deployments, pod status, and other details.

. After your {KOGITO} microservice is deployed, in the left menu of the web console, go to *Networking* -> *Routes* to view the access link to the deployed application.
+
You can select the application name to view or modify route settings.
+
With the application route, you can integrate your {KOGITO} microservices with your business automation solutions as needed.
