[id="proc-kogito-modelers-install_{context}"]
= Installing and using the {KOGITO} Business Modeler Hub

{KOGITO} provides a https://kiegroup.github.io/kogito-online/#/download[Business Modeler Hub] desktop application with all extensions or applications for modeling Decision Model and Notation (DMN) decision models in {KOGITO} microservices.

As you develop {KOGITO} microservices, you can use the {KOGITO} Business Modeler Hub to install, launch, or uninstall the available modeling extensions or applications as needed.

.Procedure
. In a web browser, go to the https://kiegroup.github.io/kogito-online/#/download[Business Modeler Hub] download page, select the relevant *Operating System* option, and click *Download*.
. Extract the downloaded `business_modeler_hub_preview___RELEASE__` binary file to a local directory.
+
--
* On Linux: In a command terminal, navigate to the directory where you downloaded the `business_modeler_hub_preview___RELEASE__` binary file and enter the following command to extract the contents:
+
.Extract the {KOGITO} Business Modeler Hub distribution
[source,subs="attributes+,+quotes"]
----
$ tar -xzpf business_modeler_hub_preview___RELEASE__.tar.gz
----

* On Windows or Mac: In your file browser, navigate to the directory where you downloaded the `business_modeler_hub_preview___RELEASE__` binary file and extract the ZIP file.
--
. In a command terminal, navigate to the extracted `business_modeler_hub_preview___RELEASE__` folder and enter the following command to run the application:
+
--
.Run the {KOGITO} Business Modeler Hub application
[source,subs="attributes+,+quotes"]
----
$ cd __PATH_TO_MODELER_HUB__
$ ./Business\ Modeler\ Hub\ Preview-__RELEASE__/Business\ Modeler\ Hub\ Preview
----

The *Business Modeler Hub* opens in a new window.

NOTE: If the *Business Modeler Hub* window does not appear, review the `README` documentation in the Business Modeler Hub application folder for any details specific to your operating system.

Use the {KOGITO} Business Modeler Hub to install, launch, or uninstall the available extensions or applications as needed.
--
