package org.drools.testcoverage.common.util;

public enum EngineTestConfiguration {
    ALPHA_NETWORK_COMPILER_TRUE,
    ALPHA_NETWORK_COMPILER_FALSE,

    EQUALITY_MODE,
    IDENTITY_MODE,

    CLOUD_MODE,
    STREAM_MODE,

    EXECUTABLE_MODEL_FLOW,
    EXECUTABLE_MODEL_PATTERN,
    EXECUTABLE_MODEL_OFF,

    IMMUTABLE_KIE_BASE
}
