/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples
 
import org.drools.examples.State;
 
rule Bootstrap
	when
		a : State(name == "A", state == State.NOTRUN )
	then
		System.out.println(a.getName() + " finished" );
		a.setState( State.FINISHED );
end

 
rule "A to B"
	when
		State(name == "A", state == State.FINISHED )
		b : State(name == "B", state == State.NOTRUN )		
	then
		System.out.println(b.getName() + " finished" );
		b.setState( State.FINISHED );
end

rule "B to C"
		agenda-group "B to C"
		auto-focus true				
	when
		State(name == "B", state == State.FINISHED )			
		c : State(name == "C", state == State.NOTRUN )
	then
		System.out.println(c.getName() + " finished" );
		c.setState( State.FINISHED );
		drools.getKnowledgeRuntime().getAgenda().getAgendaGroup( "B to D" ).setFocus();
end

rule "B to D"
	agenda-group "B to D"
	when
		State(name == "B", state == State.FINISHED )			
		d : State(name == "D", state == State.NOTRUN )
	then
		System.out.println(d.getName() + " finished" );
		d.setState( State.FINISHED );
end