#created on: Aug 14, 2007
package org.acme.insurance

import org.acme.insurance.base.Rejection;
import org.acme.insurance.base.Policy;
import org.acme.insurance.base.Driver;
import org.acme.insurance.base.AccessoriesCoverage;


// After approved insurance calcule the value
rule "Insurance extra itens percent"
	ruleflow-group "insurancecalcule"
	salience 20
	when
		not Rejection()	
		$driver : Driver ( driverID : id )
		$access : AccessoriesCoverage ( driverId == driverID)
		$policy : Policy( approved == true )
	then
		$policy.setInsurancePrice( $policy.getInsurancePrice() + 
			($access.getAlarmSystemValue() * 0.10) + 
			($access.getArmorValue() * 0.20) +
			($access.getSoundSystemValue() * 0.30 ));
			
		System.out.println("Insurance extra itens percent: " + $policy.getInsurancePrice() );					
end

rule "Insurance Calcule"
	ruleflow-group "insurancecalcule"
	salience 10
	when
		not Rejection()	
		$driver : Driver(ifactor : insuranceFactor)
		$policy : Policy( approved == true, bp : basePrice, ip : insurancePrice )
	then
		$policy.setInsurancePrice((bp * ifactor) + ip);		
		System.out.println("Insurance Calcule: " + ip );		
end
