[id='missing-features-components_{context}']

[id='kie-server_{context}']
== {KIE_SERVER}

{KIE_SERVER} is retired and no longer a component of {PRODUCT} 8. If your system is working on {KIE_SERVER} with {PRODUCT} 7, consider migration to https://kogito.kie.org/[{KOGITO}].

While {KIE_SERVER} hosts multiple kjar containers, One {KOGITO} instance hosts one domain service. Hence, you would create {KOGITO} project per kjar container, which would be microservice style.

You can find the detailed migration steps in the https://blog.kie.org/2021/09/bringing-drools-rules-into-the-cloud-with-kogito-a-step-by-step-path.html[Bringing Drools rules into the cloud with Kogito: a step by step path] article.

[id='business-central_{context}']
== {BUSINESS_CENTRAL}

{BUSINESS_CENTRAL} is retired and no longer a component of {PRODUCT} 8. For asset management, the usual version control system is recommended, for example, git. For editors, https://marketplace.visualstudio.com/items?itemName=kie-group.vscode-extension-kogito-bundle[VS Code Kogito extension] is recommended.

[id='bpmn-integration_{context}']
== BPMN integration / Rule flow

BPMN integration and Rule flow can be achieved by {KOGITO}.
