/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

//created on: 10/11/2006
package org.drools.integrationtests

import org.drools.compiler.Sensor;

global java.util.List sensors;

rule "BindsTest1_returnValue"
    when
        $sensor1 : Sensor( $temp1 : temperature, pressure < $temp1 )
        $sensor2 : Sensor( $temp2 : temperature, pressure < ( $temp1 + $temp2 ) )
    then
        sensors.add( $sensor1 );
end

rule "BindsTest2_predicate"
    when
        $sensor1 : Sensor( $temp1 : temperature, pressure < $temp1 )
        $sensor2 : Sensor( $temp2 : temperature, $p : pressure,  eval ( $p < ($temp1 + $temp2 ) ) )
    then
        sensors.add( $sensor1 );
end

rule "BindsTest3_eval"
    when
        $sensor1 : Sensor( $temp1 : temperature, pressure < $temp1 )
        $sensor2 : Sensor( $temp2 : temperature, $p : pressure )
        eval( $p < $temp1 + $temp2 )
    then
        sensors.add( $sensor1 );
end

