/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#created on: 25-Feb-2010
package org.drools.verifier.overlaps

#list any import classes here.



#declare any global variables here




rule "Overlap I"
	
	when
		Person( 
			age > 10, 
			age > 1 
		)
	then
	 
end

rule "Overlap II"
	when
		Monkey( hasBanana == true )
		Monkey( hasBanana == true )
	then 
		
end
/*
rule "Overlap III A"
	when
		Player( position < 10 )
	then 
		
end

rule "Overlap III B"
	when
		Player( position == 1 )
	then 
		
end
*/
