package org.test;

import org.drools.factmodel.traits.Individual;
import org.drools.factmodel.traits.IThing;

global java.util.List list;

 


declare Student
    @format(trait)
    school  : String
end

declare Worker
    @format(trait)
    wage    : double
end
 
declare Imp
    @traitable
    name    : String
    school  : String
end
 

 
rule "Init"
when 
then 
    Imp core = new Imp( );
    insert( core );
end


rule "Trait1"
when
    $core: Imp()
then
    Student s = don( $core, Student.class );
    list.add("Student");
end



rule "Trait2"
when
    $s : Student( )
    String( this == "hire" )
then
    don( $s, Worker.class );
    list.add("Worker");
end
 

rule "Conflict of interest"
when
    $w : Worker( this isA Student )
    String( this == "check" )
then
    shed( $w, Student.class );
    update( $w );
end


rule "Conflict resolved"
when
    $w : Worker( this not isA Student )
then
    list.add("Conflict");
    shed( $w, Worker.class );
end


rule "Nothing Left"
when
    $t : IThing( this not isA Student && this not isA Worker )
then
    list.add("Nothing");
end



