package org.drools.test;

import java.util.List;

global List list;

declare trait SeniorStudent
@propertyReactive
    grad  : boolean
    year  : int
end

declare Student
@Traitable
@propertyReactive
    grad  : boolean    = false
    year  : int        = 0
end


rule "Init"
when
then
    insert( new Student() );
end

rule "React"
when
    $x : SeniorStudent( $y : year ) @watch( year )
then
    System.out.println( " SeniorStudent Updated " );
    list.add( $y );
end


rule "Don"
salience 1
no-loop
when
    $s : Student( grad == false ) @watch( year )
then
    System.out.println( " Don SeniorStudent " );
    SeniorStudent sen = don( $s, SeniorStudent.class );
end


rule "Age with time"
salience -5
when
    $s : Student( grad == false, $y : year < 4 )
then
    System.out.println( " One year passes " + $y );
	modify( $s ) { setYear( $y + 1 ); }
end


