////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

:DROOLS:
include::../_artifacts/document-attributes.adoc[]

[[pragmatic.ai]]

:context: pragmatic-ai

[id='{context}']
= Pragmatic AI: Integrating Machine Learning with {PRODUCT}

As a business analyst or business rules developer, you can integrate Machine Learning (ML) with {PRODUCT} by using PMML files with Decision Model and Notation (DMN) models.

You can also integrate other {PRODUCT} knowledge assets such as DRL with external Deep Learning (ML/DL) libraries. This section of the documentation is dedicated to highlight one pragmatic example, using DMN and PMML.

include::_ai-con.adoc[leveloffset=+1]

The next section demonstrates how predictive decision automation works with {PRODUCT}.

include::_ai-credit-card-con.adoc[leveloffset=+1]
include::_ai-gsg-proc.adoc[leveloffset=+2]
include::_ai-pmml-ref.adoc[leveloffset=+2]

== Additional resources

* link:https://go.forrester.com/blogs/predictions-2019-ai-artificial-intelligence/[Predictions 2019: Expect A Pragmatic Vision Of AI]
