/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.games.adventures

//import org.drools.games.adventures.Room;
//import org.drools.games.adventures.Thing;
import org.drools.games.adventures.model.*;

dialect "mvel"

rule printEvent salience 10 when
    $ge : GameEvent()
    session : UserSession(  )
then
    session.channels["events"].send( $ge );
end


rule removeGameEvent when
    $ge : GameEvent()
then
    retract ( $ge );
end