/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package evalmodify;

import org.drools.compiler.Cell
import java.lang.Integer

rule "test eval"
    when
        cell1 : Cell(value1:value != 0)
        cell2 : Cell(value2:value < value1)
        eval (true)
    then
        cell2.setValue(value2 + 1);
        update(cell2);
end
