package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list
global java.lang.String string


rule "global rule test"
    when
        Cheese( $type : type, eval  ( $type.equals( string ) ), type == ( string ), type == string )
        eval( string.equals( "stilton" ) )
        eval( $type.equals( string ) )
    then
        list.add( new Integer(5) );
end    
