package org.drools.compiler

dialect "mvel"


import org.drools.compiler.Person
import org.drools.compiler.Address



rule "test something"

    when
        p: Person( name=="Michael",
                                (addresses[1].street == "Low" &&
                                addresses[0].street == "High"  )
                                )
    then
        p.name = "goober";
        System.out.println(p.name);
        insert(new Address("Latona"));
end
