/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list;

rule "not rule test"
    salience 10
    when       
        not Cheese( price == 5 )
    then
        list.add( new Integer( 5 ) );
end    

rule "not rule with bound variable"
    when
        not Cheese( $price:price, eval ( $price == 5 ) )
    then
        list.add( new Integer( 6 ) );
end

rule "not rule with other patterns 1"
    when
        Cheese( $type : type == "cheddar" )
        not Cheese( price == 5 )
    then
        list.add( new Integer( 7 ) );
end

rule "not rule with other patterns 2"
    when
        not Cheese( price == 5 )
        Cheese( $type : type == "cheddar" )
    then
        list.add( new Integer( 8 ) );
end
