/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample

// really long list of imports
import java.util.AbstractCollection
import java.util.AbstractQueue
import java.util.AbstractMap
import java.util.Arrays
import java.util.AbstractList
import java.util.ArrayList
import java.util.AbstractSequentialList
import java.util.AbstractSet
import java.util.BitSet
import java.util.ConcurrentModificationException
import java.util.Collection
import java.util.Calendar
import java.util.Collections
import java.util.Comparator
import java.util.Currency
import java.util.Date
import java.util.DuplicateFormatFlagsException
import java.util.Dictionary
import java.util.EmptyStackException
import java.util.Enumeration
import java.util.EnumMap
import java.util.EventListener
import java.util.EventObject
import java.util.EnumSet
import java.util.EventListenerProxy
import java.util.Formattable
import java.util.FormatterClosedException
import java.util.FormatFlagsConversionMismatchException
import java.util.Formatter
import java.util.FormattableFlags
import java.util.GregorianCalendar
import java.util.Hashtable
import java.util.HashMap
import java.util.HashSet
import java.util.IllegalFormatWidthException
import java.util.IllegalFormatException
import java.util.IllegalFormatPrecisionException
import java.util.InvalidPropertiesFormatException
import java.util.Iterator
import java.util.IllegalFormatCodePointException
import java.util.IdentityHashMap
import java.util.IllegalFormatFlagsException
import java.util.InputMismatchException
import java.util.IllegalFormatConversionException
import java.util.Locale
import java.util.ListResourceBundle
import java.util.LinkedHashMap
import java.util.ListIterator
import java.util.LinkedList
import java.util.List
import java.util.LinkedHashSet
import java.util.MissingResourceException
import java.util.MissingFormatWidthException
import java.util.Map
import java.util.MissingFormatArgumentException
import java.util.NoSuchElementException
import java.util.Observable
import java.util.Observer
import java.util.PriorityQueue
import java.util.PropertyResourceBundle
import java.util.PropertyPermission
import java.util.Properties
import java.util.Queue
import java.util.Random
import java.util.ResourceBundle
import java.util.RandomAccess
import java.util.SimpleTimeZone
import java.util.Stack
import java.util.SortedMap
import java.util.Set
import java.util.SortedSet
import java.util.Scanner
import java.util.StringTokenizer
import java.util.TimeZone
import java.util.TimerTask
import java.util.TooManyListenersException
import java.util.TreeMap
import java.util.Timer
import java.util.TreeSet
import java.util.UUID
import java.util.UnknownFormatFlagsException
import java.util.UnknownFormatConversionException
import java.util.Vector
import java.util.WeakHashMap

rule test
  when
    ArrayList()
  then
    System.out.println("Test");
end