/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;
import org.drools.compiler.Cheesery;

global java.util.List list;

rule "Cheesery contains stilton"
    salience 10
    when
        stilton : Cheese( type == "stilton" )
        Cheesery( cheeses contains stilton )
    then
        list.add( stilton );
end   

rule "Cheesery does not contain brie"
    when
        brie : Cheese( type == "brie" )
        Cheesery( cheeses not contains brie )
    then
        list.add( brie );
end   
