/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List list;

// this is to test eval condition node sharing working properly
rule rule1
    when
        TestParam(val: value1)
        eval(val == null)
    then
        list.add("rule1 fired");
end    


rule rule2
    when
        TestParam(val: value2)
        eval(val == null) // note its the same guts, but different binding
    then
        list.add("rule2 fired");
end  
