/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Person;
import java.util.List
import org.drools.compiler.Person;

global Person a;
global List l;

rule "r"
    no-loop true
    when
        not Person()
    then
           l.add(new org.drools.compiler.Person("0"));
           if (l.size() > 2)
        {
           kcontext.getKieRuntime().halt();
        }
           insertLogical( a );
end
