/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

declare Profile
    pageFreq : java.util.Map
end

rule "Testing out UdayCompare Custom Operator"
    ruleflow-group "udaytesting"
when
    $profile : Profile( $pg : pageFreq )
    Integer( this > 1 ) from $profile.pageFreq["internet"]
then
    System.out.println("Yippie it works!!");
end
