/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package HelloWorld

global java.util.List list;

rule "Hello World 1"
    salience 10
    when
        $m : org.drools.compiler.Message(list contains "hello",
                    text:message == "hola",
                    number in (1, 2, 3, 4, 50, 0),
                    birthday > "10-Jul-1974",
                    message matches ".*ho.*",
                    list excludes "wax",
                    fired == false )
    then
        // putting in a complex consequence, to make sure it picks up the variabels correctly
           list.add( $m );
end
