/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

rule "Rule 1"
        when
                c: Cheese( type == "stilton" )
        then
                c.setPrice( c.getPrice() + 1 );
                c.setType( "brie" );
                update( c );
end
 
rule "Rule 2"
        when
                c: Cheese( type == "brie" )
        then
                c.setPrice( c.getPrice() + 1 );
                c.setType( "stilton" );
                update( c );
end


