/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results
 
rule "Hello World"
when
  $p  : Person( add:addresses )
  $a1 : Address( zipCode == "99999") from add
  and
  ( 
    $a2 : Address( zipCode == "12345") from add
    or 
    $a2 : Address( zipCode == "54321") from add
  )
then
    results.add( $a2 );
end