/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample
 
declare Some
    field : int
end
 
rule "init"
salience 9999
    dialect "mvel"
    when
    then
        with( s0 = new Some() ) {
            field = 0
        }
        insertLogical(s0);
        with( s1 = new Some() ) {
            field = 1
        }
        insertLogical(s1);
end


rule "r1"
salience 100
when
    Some( field == 0 )
    Some( $f : field == 1)
then
    // noop
end


rule "r2"
salience 10
when
     $s : Some( $f : field == 0 )
then
    // noop
end
