/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

global java.util.List results

function boolean test( Object o1, Object o2 ) {
    return o1.equals(o2);
}

declare Person
    name : String @key
    age : int
end    

rule "TestRule"
when
    $p : Person( name == "Bob" );
then
    results.add( $p );
end 

