/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "Accumulate with bound var " salience 100
    when
        Cheese( type == "stilton", $price : price )
        $totalAmount : Number() from accumulate(  $c : Cheese( type == "brie" ),
                                                  init( int total = 0; ),
                                                  action( total += $c.getPrice() + $price; ),
                                                  reverse( total -= $c.getPrice() + $price; ),
                                                  result( new Integer( total ) ) );
    then
        //System.out.println("Total amount = US$ "+$totalAmount );
        results.add($totalAmount);
end  

