/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

import java.util.ArrayList;
import java.util.List;
import java.util.LinkedList;

global java.util.List results;

rule "Collect with memberOf shadow proxy"
    salience 100
    dialect "java"
when
    $order : Order( number == 1 )
    $list : ArrayList( this contains $order ) from collect( Order() )
then
    results.add( $order );
end 

rule "Collect with memberOf no shadow proxy"
    salience 90
    dialect "java"
when
    $item : OrderItem( seq == 1, order.number == 1 )
    $list : ArrayList( this contains $item.order ) from collect( Order() )
then
    results.add( $item );
end 

rule "Accumulate with memberOf shadow proxy"
    salience 80
    dialect "java"
when
    $order : Order( number == 2 )
    $list : List( this contains $order ) from accumulate( $o : Order(),
                                         init( List list = new LinkedList(); ),
                                         action( list.add( $o ); ),
                                         result( list ) )
then
    results.add( $order );
end 

rule "Accumulate with memberOf no shadow proxy"
    salience 70
    dialect "java"
when
    $item : OrderItem( seq == 1, order.number == 2 )
    $list : List( this contains $item.order ) from accumulate( $o : Order(),
                                         init( List list = new LinkedList(); ),
                                         action( list.add( $o ); ),
                                         result( list ) )
then
    results.add( $item );
end 

rule "MVEL Collect with memberOf shadow proxy"
    salience 60
    dialect "mvel"
when
    $order : Order( number == 1 )
    $list : ArrayList( this contains $order ) from collect( Order() )
then
    results.add( $order );
end 

rule "MVEL Collect with memberOf no shadow proxy"
    salience 50
    dialect "mvel"
when
    $item : OrderItem( seq == 1, order.number == 1 )
    $list : ArrayList( this contains $item.order ) from collect( Order() )
then
    results.add( $item );
end 

rule "MVEL Accumulate with memberOf shadow proxy"
    salience 40
    dialect "mvel"
when
    $order : Order( number == 2 )
    $list : List( this contains $order ) from accumulate( $o : Order(),
                                         init( List list = new LinkedList(); ),
                                         action( list.add( $o ); ),
                                         result( list ) )
then
    results.add( $order );
end 

rule "MVEL Accumulate with memberOf no shadow proxy"
    salience 30
    dialect "mvel"
when
    $item : OrderItem( seq == 1, order.number == 2 )
    $list : List( this contains $item.order ) from accumulate( $o : Order(),
                                         init( List list = new LinkedList(); ),
                                         action( list.add( $o ); ),
                                         result( list ) )
then
    results.add( $item );
end 
