/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

import java.util.Date

declare A
    id: String
end

declare B
    a: A
end

// insert one A
rule "insert A"
timer(int: 1)
when
then
    A a = new A();
    a.setId( (new Date()).toString() );
    insert( a );
end

// wrap the single A into a B => 2 facts
rule "wrap A"
timer(int: 100 100)
when
    $a: A( $id: id )
    not B( a == $a )
then
    B b = new B( $a );
    insert( b );
end
