/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list;

function boolean testIllegalChars() {
    return ( 3 < 4 && 4 > 3 );
}

rule "test MAIN 1"
    salience  10
    when
        Cheese( $type : type, eval( 3 < 4 && 4 > 3 ),
                price < ( new Integer( 100 ) ) )
        eval( 3 < 4 && 4 > 3 )
        eval( testIllegalChars() )
    then
        // lets also make sure that special chars are converted
        if ( 3 < 4 && 4 > 3 ) {
            list.add( "MAIN" );
            drools.setFocus( "agenda group 1" );
        }

end 

rule "test group1 1"
    agenda-group "agenda group 1"
    when
        Cheese( $price : price )
    then
        list.add( "1 1" );
end  

rule "test group3 1"
    salience 5
    agenda-group "agenda group 3"
    activation-group "activation group 3"
    auto-focus true
    when
        Cheese( )
    then
        list.add( "3 1" );
end 


rule "test group3 2"
    agenda-group "agenda group 3"
    activation-group "activation group 3"
    when
        Cheese( $type : type, $price : price )
    then
        list.add( "3 2" );
end 
