/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.beliefsystem.defeasible;

global java.util.List list;

declare Matter
    id      : int       @key
    name    : String
end


rule "Positive"
salience 100
when
    Matter( $n : name )
then
    list.add( "+" + $n );
end

rule "Negative"
salience 100
when
    Matter( $n : name ) from entry-point "neg"
then
    list.add( "-" + $n );
end

rule "Pos2"
salience -100
when
    Matter( $n : name )
then
    list.add( "++" + $n );
end

rule "Neg2"
salience -100
when
    Matter( $n : name ) from entry-point "neg"
then
    list.add( "--" + $n );
end



rule "Init plus"
when
then
    insertLogical( new Matter( 0, "plus" ) );
end

rule "Init minus"
salience -1
when
then
    insertLogical( new Matter( 0, "minus" ), "neg" );
end