package org.drools.games.invaders2;

import org.drools.games.KeyPressed
import org.drools.games.Run
import org.drools.games.GameUI

global GameUI ui

dialect "mvel"

rule "init" when
then
    insert( new Run() );
    setFocus( "Init" );
end

rule GameLoop when
    r : Run()
then
    setFocus( "Draw" );
    setFocus( "Keys" );
end


rule Draw when
    r : Run()
then
    modify( r ) {} // force loop
end