/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.reteoo;

import org.drools.compiler.Message
import org.drools.compiler.Cheese
import org.drools.compiler.Person
 
rule "Hello World 1"
    when
        Message(  message1 =="One") &&     Message(  message2 =="Two")
        Message(  message2 =="One") ||  ( Cheese( type == "stilton") && Cheese( type == "brie")  )
        Message(  message3 =="One") ||     Message(  message3 =="Three")
    then
        System.out.println( "done 1" ); 
end

rule "Hello World 2"
    when
        Message(  $message1 : message1 =="One") &&     Message(  message2 =="Two")
        Message(  message2 =="One") ||  ( Cheese( type == "stilton") && Cheese( type == "brie")  )
        Message(  message3 =="One") ||     Message(  message3 =="Three")
        Person( name==annotationk" ) || Person( name == $message1 )
    then
        System.out.println( "done 1" ); 
end