/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler;

import org.drools.compiler.Cheese;
import org.drools.compiler.Person;

rule "three patterns with constraints 1"
  when
    $cheese1 : Cheese( $type : type == "cheddar", $price1 : price )
    $cheese2 : Cheese( type == $type, $price2 : price -> ( $price1 == $price2 ) )    
   annotationson( name == $type )
  then
    System.out.println( "done 1" );
end


rule "three patterns with constraints 2"
  when
    $cheese1 : Cheese( $type : type == "cheddar", $price1 : price )
    $cheese2 : Cheese( type == $type, $price2 : price -> ( $price1 == $price2 ) )   
  then
    System.out.println( "done 2" );

end
