/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.drl

import org.drools.quarkus.test.Person
import org.drools.quarkus.test.Result

rule R1 when
        $r : Result()
        $p : Person( age >= 18 )
    then
        $r.setValue( $p.getName() + " can drink");
end

rule R2 when
        $r : Result()
        $p : Person( age < 18 )
    then
        $r.setValue( $p.getName() + " can NOT drink");
end
