/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.jbpm.examples.request

import org.kie.api.runtime.process.WorkflowProcessInstance

rule "Automatically review large requests" ruleflow-group "Ad-Hoc Sub-Process"
    when
        r: Request( $id: id, amount > 500, canceled == false )
        p: WorkflowProcessInstance()
        Request( id == $id ) from p.getVariable("request")
    then
        System.out.println("Automatically triggering the review process due to large amount");
        kcontext.getKnowledgeRuntime().signalEvent("Review", null, p.getId());
end