package org.jbpm.examples.request

import org.kie.api.runtime.process.WorkflowProcessInstance

rule "Cancellation of request" ruleflow-group "Ad-Hoc Sub-Process"
    when
    	r: Request( canceled == true )
        p: WorkflowProcessInstance()
        Request( id == r.id ) from p.getVariable("request")
    then
        System.out.println("Detected cancelation of request");
        kcontext.getKnowledgeRuntime().signalEvent("Failure", null, p.getId());
end