# We use author-mode for antora build because we generate antora.yml during the maven build
site:
  title: Drools Documentation
  url: https://www.drools.org/docs
  start_page: drools::getting-started/index.adoc
  robots: allow
content:
  edit_url: ~
  sources:
    - url: ..
      branches: [HEAD]
      start_path: drools-docs/src
ui:
  bundle:
    url: ./ui-bundle/ui-bundle.zip
  supplemental_files: ./supplemental-ui
antora:
  extensions:
    - '@antora/lunr-extension'
