= Drools documentation website

https://www.drools.org/docs[www.drools.org/docs]

NOTE: The instructions below are to generate Antora site manually. This drools-docs is already configured to generate Antora site with maven plugins.

== Prerequisite

Running Antora with Lunr extension (required to generate self-hosted search) requires Node.js v16.0.0 or above.

== Installing Antora and Lunr

Install Antora CLI 3.0.0 within the playbook project so you can run the antora command using npx:

`npm i -D -E @antora/cli@3.0.0`

Next, install the site generator package within the playbook project:

`npm i -D -E @antora/site-generator@3.0.0`

Now when you run `npx antora -v`, you should see the version of both the Antora CLI and the site generator printed in the terminal.

```
@antora/cli: 3.0.0
@antora/site-generator: 3.0.0
```

Finally install the Lunr extension with:

`npm i @antora/lunr-extension`

== Building the website locally

This folder contains 2 antora playbooks, `antora-playbook.yml` to generate the documentation from the Drools git repository and `antora-playbook-author.yml` to generate it from the source of your locally installed drools project. To run the latter and generate the documentation locally under the `build` folder use:

`npx antora antora-playbook-author.yml`

== How it works

This module builds a documentation website using https://antora.org/[Antora] that pulls the content from
the latest release branch of the https://github.com/kiegroup/drools[drools repository].

To simplify the maintenance, the documentation website is based on a pre-built default Antora UI bundle
located in `ui-bundle/ui-bundle.zip`. Customizations are located in `supplemental-ui` that Antora uses to replace
parts of the default `ui-bundle.zip`.

== How to upgrade

=== Upgrade UI bundle

Download the latest `ui-bundle.zip` from https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/master/raw/build/ui-bundle.zip?job=bundle-stable[Antora GitLab job]
and replace the existing one in the `ui-bundle` directory.

Be aware that the bundle is not versioned and in the future might not be compatible with the customizations this website uses.

=== Upgrade Lunr search engine

Download the new version of the https://lunrjs.com/[Lunr engine] from the https://www.npmjs.com/package/lunr[NPM registry]
and replace the existing `supplemental-ui/js/vendor/lunr-*.min.js` file.

Make sure the search box in the top-right corner of the documentation website can still provide hints.
