////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

= Drools documentation website

https://www.drools.org/docs[www.drools.org/docs]

== How it works

pom.xml is configured to generate Antora documentation website using adoc contents under `src/modules`.

`mvn clean package` does the steps:

1. Create `antora.yml` file based on `antora-template.yml`
2. install `node`, `npm` and `antora`
3. Execute antora to generate a documentation website

A start page of the generated site would be `target/website/docs/index.html`.

To simplify the maintenance, the documentation website is based on a pre-built default Antora UI bundle
located in `ui-bundle/ui-bundle.zip`. Customizations are located in `supplemental-ui` that Antora uses to replace
parts of the default `ui-bundle.zip`.
