package com.sample

import com.sample.DroolsTest.Message;

rule "Rule redundancy 1a"
	when
		    Foo1()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 1b"
	when
		    Foo1()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 2a"
	salience 100
	when
		    Foo2()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 2b"
	salience 100
	when
		    Foo2()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 3a"
	agenda-group "group 1"
	when
		    Foo3()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 3b"
	agenda-group "group 1"
	when
		    Foo3()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 4a"
	salience 200
	agenda-group "group 2"
	when
		    Foo4()
	then
		System.out.println( "Test" );
end

rule "Rule redundancy 4b"
	salience 200
	agenda-group "group 2"
	when
		    Foo4()
	then
		System.out.println( "Test" );
end