package com.sample

import com.sample.DroolsTest.Message;

rule "Redundant 1a"
	when
		    $f :Foo1()
		    Bar1( foo == $f )
	then
		System.out.println( "Test" );
end

rule "Redundant 1b"
	when
		    $f :Foo1()
		    Bar1( foo == $f )
	then
		System.out.println( "Test" );
end

rule "Redundant 2a"
	when
		    $f :Foo2()
		    Bar2( foo == $f && xyz == 123 )
		    or 
		    Bar2( foo == $f && xyz == 321 )
	then
		System.out.println( "Test" );
end

rule "Not Redundant 1a"
	when
		    $f :Foo1a()
		    Bar1a( foo == $f && xyz == 123 )
	then
		System.out.println( "Test" );
end
