/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.sample
 
import com.sample.DroolsMain.Bar;
import com.sample.DroolsMain.Foo;
import java.util.concurrent.atomic.AtomicInteger;

global AtomicInteger barCount;
global AtomicInteger fooCount;

rule "DuplicateBars"
	dialect "java"
	when
		f1 : Foo( )
		f2 : Foo( this != f1 )
		b1 : Bar( ) from f1.bar
//		b2 : Bar( this == b1 ) from f2.bar
	then
		barCount.incrementAndGet();
end
 
/*
rule "DuplicateFoos"
	dialect "java"
	when
		b1 : Bar( )
		b2 : Bar( this != b1 )
		f1 : Foo( ) from b1.foo
//		f2 : Foo( this == f1 ) from b2.foo
	then
		fooCount.incrementAndGet();
end
*/