/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $bpmn [217x44/16z] {
tPg7bgyi3CIJq0Na_P_sAvuj7lypABVV_PskOn9A1hR8xyF5L6ehARhhYv3orcj9tkGH5b9fhUG0z3OmRVjFx-oHll-dZVusU3wAJ-SFeyexlemJrKz3RIAY
iOyFzYFI6J-cj6ZFzSbDWmSHpTVuxarPnuLgar1H95xq-sKguhWZwNDzyvFW3iwA5n6h0n0ceT0NKSviuvPk2_gYLAnX07OLjm-8fw7YvGimil44Mz1t9kvX
G4eO35siqtClmDGLVJSYNYSjrjcf5p3yYhuoyJgs62fmBy1iI_f0nEk4nJgRl5F7CtH9hrYyJbcjq-IDrJsnj7F7zxDQfySzQNfW5ZeUc8r7vCabPJ0QUgMJ
lBLnk_5WuM4aG_fX1oxqSG4tV7Kg8bRGLDYHDG-Mzq8Fnv1T9NitqGEkmIsHWALSdX_0Xv4UyjsnG8OVRqgQhy77JZxPuKHKK2cAh-1PbdVSE429zJem6Bug
ZGN3g32zWtf7hv3sAcvAgm_yogPyk6_0WHaxjrs3asqWAsm2VHK7Mimk9nAi4pW4xfcAocdnZLp99SdJWk9hFPxEiaxgpA2BSQWt2kgPD31WN42VwGvgh-9w
4XlUqRoB4zvP1nrDKXqFQ4Qo1jgIYPK85q1EA3nlArzXGHjU1uPKnBt3-kKDBP4V6lZ6m4Oxhya60XyOt3lKqhX0IkJRZIyc3aNtYe8ec4IjZvE0UBxT-6BI
K6y4r7xfaNKud9MpAoiHBy2YTsp2NJI3A9JTO5QEbv_g7L7Ex6lU0UtreRw8_7dUWGamAxURt-uTxBXL3vVCBuphztX7Gr72PEOKw37vaFvCxoZ2BrG9NH_T
PEiQq2Ew1tVJx_0E66hrtg5tFQa30Vx4yDkz0reVlqxRcB9vURRVsi_sZe2y0z_zz4tFAC6fmAR-Vk_0eTw8zzuHzHrpyNg_HpriRwZA1I1-w1tj9tZ7Z03q
GH2_rpiyY395OPzoi1YlvQftkDiFt7XAP7tASQlUmRl9hNl7GmhAkWjYtJlSl36_tpiuJMz-t_6NUaTHaT_Z7UudU0SOm1Vm3l3F4z_f7VhTte7p-c_oZfwS
ygn_e7TKESXqG7NBwVL_SZB8IibFlKCdZNcVTqFUyIy
}
@enduml