/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $dmn [175x44/16z] {
rPbdOXqX48Ddw7Mv_sdJ4pP4A0ztw-TZ9OQ1RuijBoqROgujns3N0HzJwJL7P-GX6HzpQpbv0yR6lxfgJi5RbKNGadwK5CTK3zFfyhYfEXfLH4H3lnKIrXhS
sAl5PNt8uaKqhKRxwygwHbP3ee98M3ktB30CgkfKff35mXKx4J4L9NeIXHn1xYeW4NHgRr6FN9UAlN2WsqQ5nG7g7VzNKf6jfNjiodwRfo2AoH7IaAeIECyL
3wCw8OtLYotdCeTHdf06LGYSv_A7KKr-2w085OHOJfL95D-Eimt4bdETHhbZR3B3evVzHg8X9RFN1k34Pzt-b0i5Je7ng5P5n6Hq2pG_gafWgs1KzpzciNNJ
g_ZtnF979kusP1q8smTEjxBn6FnpqSsXRl3dm5ucCavAybjsB9gFGyNbLd2xn5amnibTVh4eiZJTrkJtZthTB68AbclmzRYFYYn-EyKbDqKs--Hfgg5Jwa3A
jhrcMk0AbSoUm4C7H4rbT10ZIjaT8ClX58CknuoWsRlSrS7IKSf-ViSjUAiO8nMKX0-M9ociNTZ2jWepGgBGcCKfl5nguJV5Kyuje1ob48zX5jwi-01fXFAE
K_YTGPa5DukJ1gBmdIIHbDtDfByEQNZswuWqD1m_E6dXKv6c5nX-5z8QIidqv8uahq8QdZsZ1qXZf4NuDjXUY3GSnPzfv1cl6NmAVrJIr8ClIswHzjgaBJLP
zg4M0GBF80r6JGLCsiEwbEF1czLUWJGgA_9-f3cGGkKO0h1Pd3GSnGts_4zQzf0qSahjCMadlJqapGff_AkILkR2FoPf8Fq5IRElI5gQRVhuf0KLOGYy76aA
7e97fDLWPyPxabRdrn3GLL84_x045aAQqWEFewOA8kqh
}
@enduml