/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $drl [134x43/16z] {
hPY7ZlGW30QnwQdl_xH_FRNDc9WLetxB9uWrsEZ23te_kVRUIeuI28wSVoD9trTh8D9jSrITZRJuiZeWvHwo9vcCd6cqUWl8ThzmnDb8Ltjr2SZzJfF9oANc
wkGnZTbbCdBf4Zdv6Fx8lafEaieVALDoxhUFCXiHNEsNaz79I9gIqqkVZBJlvOp_IGLQWd14_n7pUNym8MSrp0vQhH9NGxUAfwxpSfRH7UuOiQqLjvmoSYS_
FWuYqRp1oXjCJ5t-E8g8MJpnoydkS34K8fVTpURbP7VYH_4XqipXkI-GaugV89BDCvS5Sj8fub1EFU6N1NBYALXEURINCooGasgi43792-J4EoAFYCqXg-GC
7MgyUoVg0Zdfvmf_8txMhfApa9pUgRvAJhce5tehyQsSVMZ5tI32P7C3v33SmVqYH8XDxGq0ReC_ICT7kBoU8LeRpCifsNZyga_B6JaplZdvqLaXGkXe0tqW
O9hD9S4OwyB5SAeSmJIRYBfbgwl0QaROD2ODV9RJUCPxDdXCJ4y3Y3JM4v_Oiq57qvXaw7RXJ3o5LZEPtR6x4Cl9JxtrSXQxsMQZr-jgEPjwcgr-XDRAMMJu
0XIhCSHbSkuboakpDHy1kr_ETYFNrghrRzzc3keCjwfvvFmD
}
@enduml