/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $efesto [178x261/16z] {
xD8vTlDA44FX2w2gchIz_-s-IVodo8hqsEVeIv3U7hYhjxUtjxUtjxUtjpeN-r2jpz6dk3SX06NESmISvlwa-Jp2mmmt9qCVpOFm5xSa7h8wJ7FmqrUuAxdA
G3KS_5G7ToLTYS08BlhWbWI-AXrHuUBvudxah-ES50ybT5m_ubpXVcBEdlLvWW2caeNdN6LnFugX9bF7bTVkEjQ8Mt84m9UpFWe4b034BJMNZ_7X0EesDpRY
OTO1SbKdtDc0dFHC01IS5ZVcwiY2Iv1JNCIjwKgEXvq4LzYAD17xK5UFees2tRsgs840XohBI-n1fOpx-4XjSiKHQ2mVpHu26BlIxC4WhAfLx440Ab9X8yjq
DpjTyi9fiuS06gbTxA40CdIQFJG0XpJ37WQ4HkxMDiL0HTtPwLVOT0rR20WfU0vs43rco1nc0mKWij1QnVt9Zz6HjLhSNtXeHsp1Zr6RFKZN9kp1N6oseEsA
BHxai8LmKQAzYYbdi-8aMtrZS9hdY3-8LuhuoH7FzqgHIYzF3hyavdazKwLo5w-ay4jNU9QhA29zkET_AwwgvtjDf-FgIMPucVYF_EOfZbMeMQkPoSo45od1
BowU8BMh1Xhc9ExAEU8r_anqU4AhAqxFX5fql3ohU8t-ip_cMqsofgbIBrPALJvyyXe50l5WYc-et7ypLoVfaIFP5KRFlU-PELcv__Mg8nd1BvCgZUGU1ztq
1s3DVJIxsyuZSzRUllSSJx4-1IR7lvVAxUxiOytTQqzcvjopyGmNA85P_rvdx-EHdKocdUtDTcxUpevdMD3wCBV9dAbFcVrl4w1JUj_kTjEr-pRPqztJHud_
Trb89YMgq-Wqq3QGfgTcqecTvkmn9gupk--xz-4fii1Ey5tQn9Snft0x4yun2zkUkJldRUiPrfJulsnsVLYuFG7RdBFkdZEUOVmiGVnoUjUd9NQ0xERXdBEF
UePHFodVPNl7XvZw5BfpkttlzHGJG_nTC7wP-IoEx1G8oCpUEOypdkFuGGBhbytS0djEurD0t-wPwqcoq_XHuyirNvtdTjQ7-98TpvFw9W72VY_U59oTsI2d
ujDiFD4UtsIc0UjJhjaCk3qp8Ppho_5SVV1TEeFMXrupsT_VU21oRWWf44_pM7yJDC2kqwnYTtOsS3f7uCRJpHt_zBjusx6XEzCpeD4xqnElqFEuP-i7En_5
KzhkPW9aqhojL-dw9SIdCxPjTJAvfpsNuC7vwyo9rqXsufi4dChKm4bdoi8CNJFZPNfE4T-BRsLZeJlTS_Q-7HxITyoMbqQVcGOARfBL1PkztSVPyvXZto_f
Z1ThCyXNSQrfmTbijptx_dx_jIFIZTSQ7nOSuwe5cPrsPdhsd07f_QEAxsVn06rsJZSxZm7IgPTQtvyFuqWQXCnsRE_P-D3idr5yVXLFJTQ7P6RFr2_JymTz
upoCZh7usTxRFsCS1xb6HxK4yNVxsFaZYYVeIhFKYP_rpF5A_LuympYCne_IcUkLneSEkb8RZUjdxVapYhEOONvtVnTVviN5wzE6DaOE8-kxnAUU_JEAJwgD
fXEjAV4bZG_DoekB0oUh3PCEmudVjl4fwvKc1BnHOSqouVhjDF7fUgKMGRhIicQmP7rA6ac0NI-KGS5CKwOpfM7ZGqVyqhTweK42DCKaXnpS2UQKyIMTwuKM
yI4PJ6OmmKa4KRzqJxpEV2_kPt4M1su98m4DERDU9q5zQD4c2nCy0g5WYZF7wxIe3vDWJ8eMpgMNWWawwtKsI85DCSR2GleuZo65W5SMPy40pQ3H2LoGzfQ0
rnSNv00piDQ21UaTn9UkbzduC6TtEeMHRQ15dFV3TuEyT9F-qWmorW7Ju3p-vRl4gop4Bvc5YMD16_BsLttJzI9vW2303XYJYQ1RxcCWFkoD5rdvtp_o2R1d
tvjGdsQE5na9t-s1h1utGFP1PNtAFBn2vXm2qW2T11aP2-IyKnrVxgsdoyoU-fBkJai7J2GQwECXoSQNC-lfDe-_wWS7MBAo-LmfHk9Bp_5ia_jOF-c021kp
-pXUNppfFCHFKj2WsuoY-LwyntEbfkidOO05fZDen9VPzLnZaWE2bEyAbC0EKh_jMS-r9dB5Xvxn9UaES27dVM3yjhUUgcE3Mr-w4qYJkxS2Zutahy3wxTnu
gecKw3dR14ZQIUpClet0d7F_6lyeVW3n91lMXtJsmpGXCzl7l2_G--0VnJkUQygf7wJTzio_7ZsWUtsO-1GtdYihJlnDEfcJj8-xtANdSNp8-DBZsVwplVlG
RHvPWYXyggfxA7l3-x_jZH894RPCMSE5Dtn_DE91OpW2azq8TM3Zn52HKBSDP5pUtnTnrToCy4UB0TJT5KjsH-3g0Eeu0KHg4HyKW_WZMQe21CX9B92l_oeb
Do1GNmIWkuMSy0Up80rYvIIs02Ko1K9GYz3-udo96ulpoG9GjzRQakFjWOl8052vcFsoi05mgf9KTrcSoklCkbDTXbil9KLPf-WUR0e0OkIoMRb6YTFOt7EL
0I051NLh8xqOn7wuCZiURG0ndu8GD-bmLOP0q5eybh3ntR1tLACunz0MNn5NAg425GhhgWW203czUozAtCifpO8kX79_n2JNaXBDbSO805991011QTUhkuVI
PfD9LGGRHTi306fkUXGeCK3CpH8-K_ER0tin404gYBWPoxXrIc4pqdncze9M42i12TmwXs2i2pTRl0YmCH6VSPUPnjoHIu0Y00Taa5ExekAELE5pgX4Gcdm_
3AeCOAzP7kLOx2XWRcGbuQ74p22pKahhQ07YQekF2DkfCW98ZID1ddlS9H80jpcN-OoW1AA26b8jlfOnyHaGhyCi0UjHfaUtqS23QkGsH_WDG2_FMBhrWKfG
nKDb053tm98pn24UlCRQRJuTMFF5XvnRUCUbAfOo1utmaiBLOTMWOHxGkdpKTZAmk1H7kNc5bhw8bGjIV43i7zzr9RQhA2NYA3MlKR6gG28U9A-zernMkhiQ
YyCoG2ylP0Ie1IxnG0A0HaVHM2oUzRxm4kKMd09u7Em0K4kYxlMSJnmtNYtsxj9PyKW3q6bxMSmtr5ltX163MclJvnQ1wDXr2T-WReqPCrQAgz9NfrSfZQKH
JrDA9Cqh0g3o6g0On4VQ05nI5y567E7g4k2CbqUSOcDB3xU9fI_5a-JjFN3LU37OPTZ8s0_sxVvry2nfsrIaORvFfeT0R0eSs4iGqByN88wp1Mpy9hulrGq2
Da4GVtpXQFoYPuAbc7kwy8fu_-sYL0M08kvuW9R14noBlILJp_opbDIVF4cpdf88n5TSPLO21AfVn6lKR3noTzsamaOyGQaFhclvybQyAW8Gf7eK059nbJ9N
UYvNx6dyyXQknBSrg7ePbQrDBcwgUPAhp9xwxRsOmSwb2yH6birgYEESDdlAvQtMG-15lQG0SLySXIiT7xFI-NW3bIAcq4KKEvAA59jzoF4hQwukIJ9pI404
4Xih1ZVRy3tqdTLG7GCePXQ1AWuRomN0C9kA-9GhOg_UBWL8KeoczQBz4H4b0523ZMmzU3Dy9G3Sxui1438J2M80Ry5ghhJauGEmSdNxYvrNI4nLzyLon2hD
dcgCqJMMqHMnftv_RrRoxE3zZ6NhFi30dYG-L9VtOLQoP36NPBRbZ6tkfK28htcvoqMIfOYvWW78BLZVkxBdvUqk5sGXsN3ENHlhymt1bQzoVxaKi14II3AJ
HMZR26pneIKI7rEMjqluYAI8kHnk15XyJ6rRxAZ6vNrT37kI9JEN2yJAyiCzq34tgikllxvr-8o4ga2WCoQC0DTNbuESL5MFiNJ48mBN25EfO1DGyIaDdYBB
AUOgsCX8uNCTn64IjirSOQE0L3pGFCUEpdpPKO1xuWqNsSrS4IiPY8f7sZp1YazSnW8e5O-eECvoWPYf0SJAqk2X8OwIxJ2NsHK7LO09EvmakNLkiGJouA6Z
4NAaPZBlfmBsmaCnHqYsDPXBtezOoEKPnvuiMSrS4e3klugBXyRXLGnzwZ8M0FAKOYH96imLLckudId507QV-VaX0D2yOgCmLs1FSdlIzYRPTNwnDPXIB4bX
S7vnceapZiykZeUOiuubHLfqRh6hcqd5o7BqBkOfTfIwY2yqXrbHVj69nQuglX1pb2Ih_ARJYbNLVAN5OP8ITvzLhBWzzq4rvx_UfXSBGAWkGeY9PzEIqptE
cN5gGNoXYkSeDMevfTXUTCBZbaxLqZgXM5c49nrs-sMHp2zsXX08q8ITRQECEcF6rU9BAa0yHpN62Uiu2V1LJyJp4gSq-nAMNHnGF4k0j8GvykmMK7o7y-xf
FncqYYF2qmIwH4mXSLKBPnKZkYpcSfzOZEqmcQl34UOxOkOGDwggSue5j47CO5OfdJLZjKwuWgKq9_7iO138DiyGHtL0J25zxnqZsK_VtHGJo6mqmd6gS8Ig
Ccz_KBWHZCWS9L371te5Y3aKmQQjy1JLwF0PgIhYX601WjWEprAgU__vYvogX9Lc1OkD8ujlaTCzUXMB4qJ0Hf7vqIJkbCBFPkvKmaycWc7ZjlZPIeRDuATJ
8h6o1E972y5SIVm9I2gkR7uu0NZx16d-52JA02hnvs2NWH7-B5n2bFdpSA3CdqeY_cpq9mp-np_-yOz_0m
}
@enduml