/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $other [232x45/16z] {
nPW7qkmu28G5A3le_gVTwDetnhY5vt-k_IfEObe8MbZ1WcFAjQrhgoK91GnnpBdKlcnBgoKduV1x8Kdbd_Xh_qSG0qL-EDPzd5ZohNB9THjNMexq6NASE4MZ
SIBgDHvgj28XC_Z1jhIQ8ygtz67H96Yq14tzjTGuJfp_4EGWI0FnHGK7tm6hr2mS30cOUlmcZq_wAKuQ9vGQ21_14LiqAXR7JK02NkdvopbyKizryr4kRM2E
VCsKD5s-4LIX4j67cqeXe1PSRtB0wvXmrEIOiPqNMiQKziKwbqSs9E50zZ5XDMm8BzGllLfDXP6lR8YsCICf6m8ikasymSbVjfTAQSY6_5dVIPKX8eEYXT6R
-_jVsL3qI-_30psjms8AmVjljk31PefVtCh3S17lUtbjVRyzjCXjGj_Oa5nd3c4YOfQOsyafUBYeTXMknwJ7QRlMo-adQubALIxRIRVQ-zrXGmcFA9pMmNQ5
yp_8LRQPlaA_4bwjBJhYzqZcVd7g7rdqsz1kkmM52smRIxyz9G-V00TvlIlS9c1wbVQVQItsL6LKKZFVhG6mt7dSSbcd3Fp8i9aV9vrIlLzS4cZ1WztXeItO
uE3viZjLEweY6HQA9ZS53pTY5rtXO04zJgicdTEL9h6oEwL6MMC8_aJNCVQuhBj9z7PTs8s_WPRfdvjjcNZgIoguBQrhzynJSrjqko3BnBzsRbHqL3VsEBaK
uQgS-KetrG0R0cNjtAW4gtlUCxnUFZ6w3nfkWJQKVeCDuUUAJGM_Pe2uN7_3-jJGW4oyP4FukgBwWclDFD4vouJOMh4DuOtY_jY6C2j1kxIJ9c_RaEpZiGrX
8ZuMx5Q1dzQVsr0S67eSl1Xr9xFHghviG-AiRd_m2gQT-y4Ylcn3YrvNhoVoq-3L5BhCDeI-jo7yKBPPqhi4G7boDJJmVdNhSXXhnKC-Rkq6XcqpEARppIFW
s1WjSyWFR0ZV3QNfMVtOuxg08by_5YghKUnGg-BftH23lpk8FJfjgDfPqSzx5DlGi6E_yFKiRcsUT96KROm2Xc2WjeyhI-kxVHAzQqDy4PA4YOYO9PMEhf7g
h1na0809lM53D3p8xT6TKNtLuHyJtxCXzIOYtmQd3MmCxSF3pY4yj25vV4MTN0c_xvc8-blSrV8Z6zfnQpyeN3Q2cwFzHlFf35oAlsD3_WrDztT3WaxWUVIg
rl263Vc7kGwU81ey2Nc1hNb4UTc6_3jATy7nsOBpk6UrcM_Pq84i0rC5zKoPc0RRAztI4U9z6tBT3_L4E3ZjinjCIaq7pKhy8nkgRXjQWu9J6rVM8ZGFdk3i
UC0fbxPilPQSXCB_2B6aKbjVjwNNMf9m-05_0W
}
@enduml