/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
sprite $pmml [232x44/16z] {
xPa7RkKm30KV9QkvyVwdtLujFON03mt4oA37rBXgjWJlHyobRNihELuFf5BNOsjb2JUfE45xZhNLt0cxuGe0iVoxC0j-ipJzXssvIwK18nRbb3WTJe3Kov8z
_fhSzC8Mxb4fXcITiI-JuJXyI0k0iEc0T8jgnP1LvpIXmv9qm2c8fmvPxb1b3D6tE08PFX9vCaaPug_IXMN8VgD1NwJ0IsNF46Sp31i9tYgU8GF9D6mpkQfu
XZQr8FDXEmrmLjapnEkchmEugdY6JDJ9NvsKiOyE2VnKzWo57yHqw8LnExOe04BJdXe085HI3pyLXXIoXyl5EVnXfd_NE28J1RYfx1dAj4yo-5d5Rw9UYFYD
z1Vdfk8Paiv9kX_wuLsOHXF_UwK0NYfxXeHkNEc74wtsoNU60l1JyGnHQUwT2pKA-oiPWDfj7oULFKELVYDxFxpnpo9E2-2bicSeWUMWy0tFdodPFlugUuR2
qHqXf-7Fb6qVPvKzGnAANg2dOS-Klv-xL7mbfz3Ji6VAtyzTAhgISmez3N-cytRug-XApe87POZJWETaYBCA7fOXVflFpr0L01ybGmr3TdsBOo73BxJ3LMNF
4FbLpdCpj2wmVL6xkHt-gX59AIr58SEljCDR5KE7T7lupn51HpTiR4VtVfnKd7XTcK3u21dY2Fb76O4DyzV3s-6WuW3nUkCpehqTV5ExgJZjklB437ixucHJ
kwauQV9_Gwzbw3D3qK55-SmGXm-_tWwvDqFws0pLVYMdMjiXaqtjgU8P-We
}
@enduml