/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//Verification rules for checking DRL type definitions
package org.drools.verifier.definition

import java.util.ArrayList;
import java.util.HashMap;

import org.drools.verifier.data.VerifierReport;
import org.drools.verifier.components.Definition;
import org.drools.verifier.components.ObjectType;
import org.drools.verifier.report.components.Severity;
import org.drools.verifier.report.components.VerifierMessage;
import org.drools.verifier.report.components.MessageType;

rule "Missing Definition for ObjectType"
    @verifying_scopes(["definition-check"])
    when
        $objectType : ObjectType( $typeName : name, $packageName : packageName != null )
        not Definition( typeName == $typeName, packageName == $packageName )
    then
        HashMap<String,String> map = new HashMap<String,String>();
        map.put("typeName", $typeName);
        map.put("packageName", $packageName);
        
        result.add(new VerifierMessage(
                        map,
                        Severity.ERROR,
                        MessageType.MISSING_COMPONENT,
                        $objectType,
                        "Missing type definition for fact type: " + $typeName + " in package: " + $packageName,
                        new ArrayList() ) );
end

