/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.trait.test;

import org.drools.core.factmodel.traits.Traitable;
import org.drools.core.factmodel.traits.Entity;

global java.util.List list;




declare Imp
    @Traitable
    name    : String
    code    : String
end



declare trait Person
    @typesafe(false)
    name    : String
    code    : int
end
  


 

 
 
rule "Init"
when
then
    Imp core = new Imp( "adam", "code123" );
    insert( core );
end

rule "Trait"
no-loop
when
    $core: Imp( "adam", "code123" ;)
then
    Person<Imp> s = drools.<Person,Imp>don( $core, Person.class, true );
    s.setCode( 456 );
    System.out.println(s);
    update(s);
end


rule "Cloak"
when
    $p    : Person( $c1 : code == 456, core.getClass() == Imp, $core : core.code == "code123" )
then
    list.add("OK");
end



