/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
rule "GroupByParserTest"
when
    groupby( $p: Person ( $age : age < 30 );           // SOURCE_PATTERN
             $initial : $p.getName().substring(0, 1);  // GROUPING_FUNCTION
             $sumOfAges : sum($age),                   // 2 ACC_FUNCTIONS, one summing the ages of the persons in the group
             $countOfPersons : count();                // and the other simply counting them
             $sumOfAges > 10 )                         // CONSTRAINT filtering away groups
then
end