package org.drools.compiler.test;
 
import org.drools.compiler.Cheese;
import org.drools.compiler.Cheesery;
import java.util.List;

global List list1;
global List list2;
global List list3;
global Cheesery cheesery;

rule "test from using a global"
    when
        $cheese : Cheese() from cheesery.getCheeses()
    then
        list1.add( $cheese );
end

rule "test from using a global against a map lookup"
    when
        Person( $stilton : type, type == "stilton" )
        $cheese : Cheese( type == $stilton ) from cheesery.getCheeseMap["stilton"]
    then
        list1.add( $cheese );
end
