/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.test;

rule R1 when
  accumulate( $s1: String(), $sum : count( $s1 ) )
then
  System.out.println( $sum );
end

rule R2 when
  $sum : Number() from accumulate( $s2: String(), count( $s2 ) )
then
  System.out.println( $sum );
end