/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package foo;

rule "simple_rule"
  salience 10
  no-loop true
  agenda-group "agenda-group"
  activation-group "activation-group"
  when
    foo2 : Bar( a ( > 60 && < 70 ) || ( > 50 && < 55 ) && a3 == "black" || a == 40 && a3 == "pink" || a == 12 && a3 == "yellow" || a3 == "blue")
    foo3 : Bar( a == 3 || == 4, a3 == "hello", a4 == null )    
    foo4 : Bar( a4 : a != 4 && != 5)
    foo5 : Bar( b == (a4 + 1) || > a4)    
    foo6 : Bar( a4 : a, b == 6)    
    foo7 : Bar( a4 : a, b4 : b)    
    $cheeseList  : ArrayList(size > 2) from collect( Cheese( type == $likes ) );    
    Baz()
  then
  if ( a == b ) {
    assert( foo3 );
  } else {
    retract( foo4 );
  } 
  System.out.println( a4 );
end