/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;
import org.drools.compiler.Cheesery;

global java.util.List list;

rule "Stilton is memberOf Cheesery"
    salience 10
    when
        Cheesery( $cheeses : cheeses )
        cheese : Cheese( type memberOf $cheeses )
    then
        list.add( cheese );
end   

rule "Muzzarela is not memberOf Cheesery"
    when
        Cheesery( $cheeses : cheeses )
        cheese : Cheese( type not memberOf $cheeses )
    then
        list.add( cheese );
end   
