/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;


rule "eval rewrite"
    when
        $o : OrderItem( order.number == 10 )
    then
        results.add( $o );
end

rule "eval rewrite2"
    when
        $o1 : OrderItem( order.number == 11, $seq : seq == 1 )
        $o2 : OrderItem( order.number == $o1.order.number, seq != $seq )
    then
        results.add( $o2 );
end

rule "eval rewrite3"
    when
        $o1 : OrderItem( order.number == 12, seq == 1 )
        $o : Order( items[(Integer) 1] == $o1 )
    then
        results.add( $o );
end

rule "eval rewrite4"
    when
        OrderItem( $nbr : order.number == 13, seq == 1 )
        $o : Order( number == $nbr )
    then
        results.add( $o );
end
