/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler;

global java.util.List results;

rule "Test enabled expression 1"
    @ruleID(1234)
    // arbitrary expression using a rule metadata
    enabled ( rule.metaData["ruleID"] == "1234" )
  when
    Person(name == "Michael")
  then
    results.add( "1" );
end

rule "Test enabled expression 2"
    @ruleID(1234)
    // using bound variables
    enabled ( "Michael".equals( $name ) )
  when
    Person( $name : name )
  then
    results.add( "2" );
end

rule "Test enabled expression 3"
    @ruleID(1234)
    // using simple expressions
    enabled ( 1 + 1 == 2 )
  when
    Person( $name : name )
  then
    results.add( "3" );
end

rule "Test enabled expression 4"
    @ruleID(1234)
    // using a false expression
    enabled ( 1 + 1 == 5 )
  when
    Person( $name : name )
  then
    results.add( "4" );
end

