/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "test chars 1"
    salience 100
when
    Primitives( charPrimitive == 'a' ) 
then
    results.add( "1" );
end

rule "test chars 2"
    salience 90
when
    Primitives( $c1: charPrimitive == 'a' ) 
    Primitives( charPrimitive != $c1 )
then
    results.add( "2" );
end

rule "test chars 3"
    salience 80
when
    Primitives( $c1: stringAttribute == 'a' ) 
    Primitives( charPrimitive == $c1 )
then
    results.add( "3" );
end

