@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Runtime
participant Assembler
participant Compiler

Runtime -> Assembler: search model
Assembler -> Compiler: instantiation
Compiler -> Assembler: instances
Assembler -> Runtime: instances

@enduml
