/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.example.cdi.cdiexample

import org.drools.example.cdi.cdiexample.Message

global java.io.PrintStream out

rule "rule 1" salience 10 when
    m : Message( )
then
    out.println( m.getName() + ": " +  m.getText() );
end

rule "rule 2" when
    Message( text == "Hello, HAL. Do you read me, HAL?" )
then
    insert( new Message("HAL", "Dave. I read you." ) );
end