package com.answers.kie.layoutmode;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class LayoutModeInput implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String site;
   private java.lang.String server_addr;
   private java.lang.String user_agent;
   private java.lang.String controller;
   private boolean is_bot;
   private java.lang.String city;
   private java.lang.Integer asn_group_id;
   private java.lang.Integer cookie_asn_group_id;

   private java.lang.String source;

   public LayoutModeInput()
   {
   }

   public java.lang.String getSite()
   {
      return this.site;
   }

   public void setSite(java.lang.String site)
   {
      this.site = site;
   }

   public java.lang.String getServer_addr()
   {
      return this.server_addr;
   }

   public void setServer_addr(java.lang.String server_addr)
   {
      this.server_addr = server_addr;
   }

   public java.lang.String getUser_agent()
   {
      return this.user_agent;
   }

   public void setUser_agent(java.lang.String user_agent)
   {
      this.user_agent = user_agent;
   }

   public java.lang.String getController()
   {
      return this.controller;
   }

   public void setController(java.lang.String controller)
   {
      this.controller = controller;
   }

   public boolean isIs_bot()
   {
      return this.is_bot;
   }

   public void setIs_bot(boolean is_bot)
   {
      this.is_bot = is_bot;
   }

   public java.lang.String getCity()
   {
      return this.city;
   }

   public void setCity(java.lang.String city)
   {
      this.city = city;
   }

   public java.lang.Integer getAsn_group_id()
   {
      return this.asn_group_id;
   }

   public void setAsn_group_id(java.lang.Integer asn_group_id)
   {
      this.asn_group_id = asn_group_id;
   }

   public java.lang.Integer getCookie_asn_group_id()
   {
      return this.cookie_asn_group_id;
   }

   public void setCookie_asn_group_id(java.lang.Integer cookie_asn_group_id)
   {
      this.cookie_asn_group_id = cookie_asn_group_id;
   }

   public java.lang.String getSource()
   {
      return this.source;
   }

   public void setSource(java.lang.String source)
   {
      this.source = source;
   }

   public LayoutModeInput(java.lang.String site, java.lang.String server_addr,
         java.lang.String user_agent, java.lang.String controller,
         boolean is_bot, java.lang.String city, java.lang.Integer asn_group_id,
         java.lang.Integer cookie_asn_group_id, java.lang.String source)
   {
      this.site = site;
      this.server_addr = server_addr;
      this.user_agent = user_agent;
      this.controller = controller;
      this.is_bot = is_bot;
      this.city = city;
      this.asn_group_id = asn_group_id;
      this.cookie_asn_group_id = cookie_asn_group_id;
      this.source = source;
   }

}