/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.test

import com.sample.DroolsTest.Message;


//
// Something
//
rule "Test 1"
    when
            Foo(
                a > 10
            )
    then
        System.out.println( "Test" );
end

rule "Test 2"
    when
            Foo(
                a > 10,
                b == 2
            )
    then
        System.out.println( "Test" );
end

rule "Test 1 GG"
    ruleflow-group "GG"
    when
            Foo(
                a > 10
            )
    then
        System.out.println( "Test" );
end

rule "Test 2 GG"
    ruleflow-group "GG"
    when
            Foo(
                a > 10,
                b == 2
            )
    then
        System.out.println( "Test" );
end

rule "Test 3"
    when
            Bar(
                a > 10,
                b == 2
            )
    then
        System.out.println( "Test" );
end
