//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.08.06 at 04:40:00 PM CEST 
//


package org.kie.dmn.model.v1x;

public enum FunctionKind {

    FEEL("FEEL"),
    JAVA("Java"),
    PMML("PMML");
    private final String value;

    FunctionKind(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FunctionKind fromValue(String v) {
        for (FunctionKind c: FunctionKind.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
