
package org.drools.informer

import org.apache.commons.beanutils.PropertyUtils;

import org.drools.informer.domain.DomainModelSupport;

rule "derive answerType from the underlying domain model if it isn't specified"
when
	question : Question(questionId : id, answerType == null);
	association : DomainModelAssociation(questionId == questionId);
then
	Class propertyClass = PropertyUtils.getPropertyType(association.getObject(), association.getProperty());
	question.setAnswerType(DomainModelSupport.classToAnswerType(propertyClass));
	update(question);
end

rule "copy answers from the underlying domain model to the questions"
no-loop
when
	question : Question(questionId : id, answerType != null);
	association : DomainModelAssociation(questionId == questionId, lastAnswer == question.answer);
	obj : Object();
	eval(association.getObject() == obj);
then
	Object propertyValue = PropertyUtils.getProperty(association.getObject(), association.getProperty());
	Object answer = DomainModelSupport.objectToAnswer(propertyValue, question.getBasicAnswerType());
	if (answer == null ? question.getAnswer() != null : !answer.equals(question.getAnswer())) {
		question.setAnswer(answer);
		update(question);
		association.setLastAnswer(answer);
		update(association);
	}
end

rule "copy question answers to the underlying domain model"
no-loop
when
	question : Question(questionId : id, answerType != null, answer : answer);
	association : DomainModelAssociation(questionId == questionId, object : object, property : property, lastAnswer != answer);
then
	Class propertyClass = PropertyUtils.getPropertyType(object, property); 
	Object propertyValue = DomainModelSupport.answerToObject(question.getBasicAnswerType(), answer, propertyClass);
	Object oldPropertyValue = PropertyUtils.getProperty(object, property);
	PropertyUtils.setProperty(object, property, propertyValue);
	update(object);
	association.setLastAnswer(answer);
	update(association);
end
