/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample
 
import java.util.List;

global List list

rule "Rule1" ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule1");
end

rule "Rule2" ruleflow-group "flowgroup-2"
	when
		eval(true)
	then
		list.add("Rule2");
end

rule "Rule3" ruleflow-group "flowgroup-3" salience 10
	when
		eval(true)
	then
		list.add("Rule3");
end

rule "Rule4" ruleflow-group "flowgroup-4" salience 20
	when
		eval(true)
	then
		list.add("Rule4");
end