/**
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.sample
 
import java.util.List;

global List list

rule "Rule1" @Propagation(EAGER) ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule1");
end

rule "Rule2" @Propagation(EAGER) ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule2");
end

rule "Rule3" @Propagation(EAGER) ruleflow-group "flowgroup-1" salience 10
	when
		eval(true)
	then
		list.add("Rule3");
end

rule "Rule4" @Propagation(EAGER) ruleflow-group "flowgroup-1" salience 20
	when
		eval(true)
	then
		list.add("Rule4");
end