package com.sample
 
import java.util.List;

global List list

rule "Rule1" @Propagation(EAGER) ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule1");
end

rule "Rule2" @Propagation(EAGER) ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule2");
end

rule "Rule3" @Propagation(EAGER) ruleflow-group "flowgroup-1" salience 10
	when
		eval(true)
	then
		list.add("Rule3");
end

rule "Rule4" @Propagation(EAGER) ruleflow-group "flowgroup-1" salience 20
	when
		eval(true)
	then
		list.add("Rule4");
end