[id='executable-model-con_{context}']

= Executable rule models

Executable rule models are embeddable models that provide a Java-based representation of a rule set for execution at build time. The executable model is a more efficient alternative to the standard asset packaging in {PRODUCT} and enables KIE containers and KIE bases to be created more quickly, especially when you have large lists of DRL (Drools Rule Language) files and other {PRODUCT} assets. The model is low level and enables you to provide all necessary execution information, such as the lambda expressions for the index evaluation.

Executable rule models provide the following specific advantages for your projects:

* *Compile time:* Traditionally, a packaged {PRODUCT} project (KJAR) contains a list of DRL files and other {PRODUCT} artifacts that define the rule base together with some pre-generated classes implementing the constraints and the consequences. Those DRL files must be parsed and compiled when the KJAR is downloaded from the Maven repository and installed in a KIE container. This process can be slow, especially for large rule sets. With an executable model, you can package within the project KJAR the Java classes
that implement the executable model of the project rule base and re-create the KIE container and its KIE bases out of it in a much faster way. In Maven projects, you use the `kie-maven-plugin` to automatically generate the executable model sources from the DRL files during the compilation process.
* *Run time:* In an executable model, all constraints are defined as Java lambda expressions. The same lambda expressions are also used
for constraints evaluation, so you no longer need to use `mvel` expressions for interpreted evaluation nor the just-in-time (JIT) process to transform the `mvel`-based constraints into bytecode. This creates a quicker and more efficient run time.
* *Development time:* An executable model enables you to develop and experiment with new features of the {DECISION_ENGINE} without needing to encode elements directly in the DRL format or modify the DRL parser to support them.

NOTE: For query definitions in executable rule models, you can use up to 10 arguments only.

ifdef::DROOLS[]
== Executable model domain-specific languages (DSLs)

One goal while designing the first iteration of the domain-specific language (DSL) for the executable model was to get rid of the notion of pattern and to consider a rule as a flow of expressions (constraints) and actions (consequences). For this reason we called it Flow DSL. Some examples of this DSL are available here.

However after having implemented the Flow DSL it became clear that the decision of avoiding the explicit use of patterns obliged us to implement some extra logic that had both a complexity and a performance cost, since in order to properly re-create the data structures expected by the Drools compiler it is necessary to put together the patterns out of those apparently unrelated expressions.

For this reason it has been decided to reintroduce the patterns in a second DSL that we called Pattern DSL. This allowed to bypass that algorithm grouping expressions that has to fill an artificial semantic gap and that is also time consuming at run time. We believe that both DSLs are valid for different use cases and so we decided to keep and support both. In particular the Pattern DSL is safer and faster (even if more verbose) so this will be the DSL that will be automatically generated when creating a KJAR through the kie-maven-plugin. Conversely the Flow DSL is more succinct and closer to the way a user may want to programmatically define a rule in Java and we planned to make it even less verbose by generating in an automatic way through a post processor the parts of the model defining the indexing and property reactivity. In other words, we expect that the Pattern DSL will be written by machines and the Flow DSL eventually by humans.
endif::DROOLS[]
