[id='executable-model-java-proc_{context}']

= Embedding an executable rule model in a Java application

You can embed an executable rule model programmatically within your Java application to compile your rule assets more efficiently at build time.

.Prerequisites
* You have a Java application that contains {PRODUCT} business assets.

.Procedure
. Add the following dependencies to the relevant classpath for your Java project:
+
--
* `drools-canonical-model`: Enables an executable canonical representation of a rule set model that is independent from {PRODUCT}
* `drools-model-compiler`: Compiles the executable model into {PRODUCT} internal data structures so that it can be executed by the {DECISION_ENGINE}

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-canonical-model</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>

<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-model-compiler</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----

The `<version>` is the Maven artifact version for {PRODUCT} currently used in your project (for example, {MAVEN_ARTIFACT_VERSION}).

ifdef::DM,PAM[]
[NOTE]
====
Instead of specifying a {PRODUCT} `<version>` for individual dependencies, consider adding the {PRODUCT_BA} bill of materials (BOM) dependency to your project `pom.xml` file. The {PRODUCT_BA} BOM applies to both {PRODUCT_DM} and {PRODUCT_PAM}. When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project.

Example BOM dependency:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>com.redhat.ba</groupId>
  <artifactId>ba-platform-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----

For more information about the {PRODUCT_BA} BOM, see
ifdef::PAM[]
https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?].
endif::[]
ifdef::DM[]
https://access.redhat.com/solutions/3363991[What is the mapping between RHDM product and maven library version?].
endif::[]
====
endif::DM,PAM[]
--
. Add rule assets to the KIE virtual file system `KieFileSystem` and use `KieBuilder` with `buildAll( ExecutableModelProject.class )` specified to build the assets from an executable model:
+
--
[source,java]
----
import org.kie.api.KieServices;
import org.kie.api.builder.KieFileSystem;
import org.kie.api.builder.KieBuilder;

  KieServices ks = KieServices.Factory.get();
  KieFileSystem kfs = ks.newKieFileSystem()
  kfs.write("src/main/resources/KBase1/ruleSet1.drl", stringContainingAValidDRL)
  .write("src/main/resources/dtable.xls",
    kieServices.getResources().newInputStreamResource(dtableFileStream));

  KieBuilder kieBuilder = ks.newKieBuilder( kfs );
  // Build from an executable model
  kieBuilder.buildAll( ExecutableModelProject.class )
  assertEquals(0, kieBuilder.getResults().getMessages(Message.Level.ERROR).size());
----
After `KieFileSystem` is built from the executable model, the resulting `KieSession` uses constraints based on lambda expressions instead of less-efficient `mvel` expressions. If `buildAll()` contains no arguments, the project is built in the standard method without an executable model.

As a more manual alternative to using `KieFileSystem` for creating executable models, you can define a `Model` with a fluent API and create a `KieBase` from it:

[source,java]
----
Model model = new ModelImpl().addRule( rule );
KieBase kieBase = KieBaseBuilder.createKieBaseFromModel( model );
----
--

ifdef::DM,PAM[]
For more information about packaging projects programmatically within a Java application, see {URL_PACKAGING_DEPLOYING_PROJECT}#project-build-deploy-java-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::DM,PAM[]
