[id='executable-model-maven-proc_{context}']

= Embedding an executable rule model in a Maven project

You can embed an executable rule model in your Maven project to compile your rule assets more efficiently at build time.

.Prerequisites
* You have a Mavenized project that contains {PRODUCT} business assets.

.Procedure
. In the `pom.xml` file of your Maven project, ensure that the packaging type is set to `kjar` and add the `kie-maven-plugin` build component:
+
--
[source,xml,subs="attributes+"]
----
<packaging>kjar</packaging>
...
<build>
  <plugins>
    <plugin>
      <groupId>org.kie</groupId>
      <artifactId>kie-maven-plugin</artifactId>
      <version>${{PRODUCT_INIT}.version}</version>
      <extensions>true</extensions>
    </plugin>
  </plugins>
</build>
----

The `kjar` packaging type activates the `kie-maven-plugin` component to validate and pre-compile artifact resources. The `<version>` is the Maven artifact version for {PRODUCT} currently used in your project (for example, {MAVEN_ARTIFACT_VERSION}). These settings are required to properly package the Maven project.

ifdef::DM,PAM[]
[NOTE]
====
Instead of specifying a {PRODUCT} `<version>` for individual dependencies, consider adding the {PRODUCT_BA} bill of materials (BOM) dependency to your project `pom.xml` file. The {PRODUCT_BA} BOM applies to both {PRODUCT_DM} and {PRODUCT_PAM}. When you add the BOM files, the correct versions of transitive dependencies from the provided Maven repositories are included in the project.

Example BOM dependency:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>com.redhat.ba</groupId>
  <artifactId>ba-platform-bom</artifactId>
  <version>{BOM_VERSION}</version>
  <scope>import</scope>
  <type>pom</type>
</dependency>
----

For more information about the {PRODUCT_BA} BOM, see
ifdef::PAM[]
https://access.redhat.com/solutions/3405361[What is the mapping between RHPAM product and maven library version?].
endif::[]
ifdef::DM[]
https://access.redhat.com/solutions/3363991[What is the mapping between RHDM product and maven library version?].
endif::[]
====
endif::DM,PAM[]
--
. Add the following dependencies to the `pom.xml` file to enable rule assets to be built from an executable model:
+
--
* `drools-canonical-model`: Enables an executable canonical representation of a rule set model that is independent from {PRODUCT}
* `drools-model-compiler`: Compiles the executable model into {PRODUCT} internal data structures so that it can be executed by the {DECISION_ENGINE}

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-canonical-model</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>

<dependency>
  <groupId>org.drools</groupId>
  <artifactId>drools-model-compiler</artifactId>
  <version>${{PRODUCT_INIT}.version}</version>
</dependency>
----
--
. In a command terminal, navigate to your Maven project directory and run the following command to build the project from an executable model:
+
--
[source]
----
mvn clean install -DgenerateModel=<VALUE>
----

The `-DgenerateModel=<VALUE>` property enables the project to be built as a model-based KJAR instead of a DRL-based KJAR.

Replace `<VALUE>` with one of three values:

* `YES`: Generates the executable model corresponding to the DRL files in the original project and excludes the DRL files from the generated KJAR.
* `WITHDRL`: Generates the executable model corresponding to the DRL files in the original project and also adds the DRL files to the generated KJAR for documentation purposes (the KIE base is built from the executable model regardless).
* `NO`: Does not generate the executable model.

Example build command:

[source]
----
mvn clean install -DgenerateModel=YES
----
--

ifdef::DM,PAM[]
For more information about packaging Maven projects, see {URL_PACKAGING_DEPLOYING_PROJECT}#project-build-deploy-maven-proc_packaging-deploying[_{PACKAGING_DEPLOYING_PROJECT}_].
endif::DM,PAM[]
