# Example DRL with expansion 
# (ie "domain specific language")
# use expanders for domain specific and natural language extensions
use expander cheese.dsl


rule find_seating
    when
        #Bob is in atlanta
        #Bob likes cheese
	    #There exists a Guest with name of "Michael" and sex of "Male"
        >Guest( name == seatingRightGuestName, rightGuestSex:sex, rightGuestHobby:hobby )
        >Guest( leftGuestName:name , sex != rightGuestSex, hobby == rightGuestHobby )
        >count => Count()
        #bind count to Count
    then
        #Send notification to Mark with message "hello"
        >System.out.println("and this is code")
end