alter table Attachment drop foreign key FK_7ndpfa311i50bq7hy18q05va3;
alter table Attachment drop foreign key FK_hqupx569krp0f0sgu9kh87513;
alter table BooleanExpression drop foreign key FK_394nf2qoc0k9ok6omgd6jtpso;
alter table CorrelationPropertyInfo drop foreign key FK_hrmx1m882cejwj9c04ixh50i4;
alter table Deadline drop foreign key FK_68w742sge00vco2cq3jhbvmgx;
alter table Deadline drop foreign key FK_euoohoelbqvv94d8a8rcg8s5n;
alter table Delegation_delegates drop foreign key FK_gn7ula51sk55wj1o1m57guqxb;
alter table Delegation_delegates drop foreign key FK_fajq6kossbsqwr3opkrctxei3;
alter table ErrorInfo drop foreign key FK_cms0met37ggfw5p5gci3otaq0;
alter table Escalation drop foreign key FK_ay2gd4fvl9yaapviyxudwuvfg;
alter table I18NText drop foreign key FK_k16jpgrh67ti9uedf6konsu1p;
alter table I18NText drop foreign key FK_fd9uk6hemv2dx1ojovo7ms3vp;
alter table I18NText drop foreign key FK_4eyfp69ucrron2hr7qx4np2fp;
alter table I18NText drop foreign key FK_pqarjvvnwfjpeyb87yd7m0bfi;
alter table I18NText drop foreign key FK_o84rkh69r47ti8uv4eyj7bmo2;
alter table I18NText drop foreign key FK_g1trxri8w64enudw2t1qahhk5;
alter table I18NText drop foreign key FK_qoce92c70adem3ccb3i7lec8x;
alter table I18NText drop foreign key FK_bw8vmpekejxt1ei2ge26gdsry;
alter table I18NText drop foreign key FK_21qvifarxsvuxeaw5sxwh473w;
alter table Notification drop foreign key FK_bdbeml3768go5im41cgfpyso9;
alter table Notification_BAs drop foreign key FK_mfbsnbrhth4rjhqc2ud338s4i;
alter table Notification_BAs drop foreign key FK_fc0uuy76t2bvxaxqysoo8xts7;
alter table Notification_email_header drop foreign key FK_ptaka5kost68h7l3wflv7w6y8;
alter table Notification_email_header drop foreign key FK_eth4nvxn21fk1vnju85vkjrai;
alter table Notification_Recipients drop foreign key FK_blf9jsrumtrthdaqnpwxt25eu;
alter table Notification_Recipients drop foreign key FK_3l244pj8sh78vtn9imaymrg47;
alter table PeopleAssignments_BAs drop foreign key FK_t38xbkrq6cppifnxequhvjsl2;
alter table PeopleAssignments_BAs drop foreign key FK_omjg5qh7uv8e9bolbaq7hv6oh;
alter table PeopleAssignments_ExclOwners drop foreign key FK_pth28a73rj6bxtlfc69kmqo0a;
alter table PeopleAssignments_ExclOwners drop foreign key FK_b8owuxfrdng050ugpk0pdowa7;
alter table PeopleAssignments_PotOwners drop foreign key FK_tee3ftir7xs6eo3fdvi3xw026;
alter table PeopleAssignments_PotOwners drop foreign key FK_4dv2oji7pr35ru0w45trix02x;
alter table PeopleAssignments_Recipients drop foreign key FK_4g7y3wx6gnokf6vycgpxs83d6;
alter table PeopleAssignments_Recipients drop foreign key FK_enhk831fghf6akjilfn58okl4;
alter table PeopleAssignments_Stakeholders drop foreign key FK_met63inaep6cq4ofb3nnxi4tm;
alter table PeopleAssignments_Stakeholders drop foreign key FK_4bh3ay74x6ql9usunubttfdf1;
alter table Reassignment drop foreign key FK_pnpeue9hs6kx2ep0sp16b6kfd;
alter table Reassignment_potentialOwners drop foreign key FK_8frl6la7tgparlnukhp8xmody;
alter table Reassignment_potentialOwners drop foreign key FK_qbega5ncu6b9yigwlw55aeijn;
alter table Task drop foreign key FK_dpk0f9ucm14c78bsxthh7h8yh;
alter table Task drop foreign key FK_nh9nnt47f3l61qjlyedqt05rf;
alter table Task drop foreign key FK_k02og0u71obf1uxgcdjx9rcjc;
alter table task_comment drop foreign key FK_aax378yjnsmw9kb9vsu994jjv;
alter table task_comment drop foreign key FK_1ws9jdmhtey6mxu7jb0r0ufvs;
drop table if exists Attachment;
drop table if exists AuditTaskImpl;
drop table if exists BAMTaskSummary;
drop table if exists BooleanExpression;
drop table if exists CaseFileDataLog;
drop table if exists CaseIdInfo;
drop table if exists CaseRoleAssignmentLog;
drop table if exists Content;
drop table if exists ContextMappingInfo;
drop table if exists CorrelationKeyInfo;
drop table if exists CorrelationPropertyInfo;
drop table if exists Deadline;
drop table if exists Delegation_delegates;
drop table if exists DeploymentStore;
drop table if exists email_header;
drop table if exists ErrorInfo;
drop table if exists Escalation;
drop table if exists EventTypes;
drop table if exists ExecutionErrorInfo;
drop table if exists I18NText;
drop table if exists NodeInstanceLog;
drop table if exists Notification;
drop table if exists Notification_BAs;
drop table if exists Notification_email_header;
drop table if exists Notification_Recipients;
drop table if exists OrganizationalEntity;
drop table if exists PeopleAssignments_BAs;
drop table if exists PeopleAssignments_ExclOwners;
drop table if exists PeopleAssignments_PotOwners;
drop table if exists PeopleAssignments_Recipients;
drop table if exists PeopleAssignments_Stakeholders;
drop table if exists ProcessInstanceInfo;
drop table if exists ProcessInstanceLog;
drop table if exists QueryDefinitionStore;
drop table if exists Reassignment;
drop table if exists Reassignment_potentialOwners;
drop table if exists RequestInfo;
drop table if exists SessionInfo;
drop table if exists Task;
drop table if exists task_comment;
drop table if exists TaskDef;
drop table if exists TaskEvent;
drop table if exists TaskVariableImpl;
drop table if exists VariableInstanceLog;
drop table if exists WorkItemInfo;
