/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.functional.parser

query "TestEmptyQuery"
    //conditions
end

query "TestSimpleQuery"
    d : Double()
end

query "TestParametrizedQuery" (double max)
    d : Double ( this < max )
end


// more advanced tests from the Drools 5.2.0 introduction

declare Location
    thing : String 
    location : String 
end

query isContainedIn( String x, String y ) 
    Location( x := thing, y := location)
    or 
    ( Location(z := thing, y := location) and ?isContainedIn( x := x, z := y ) )
end

// the same using positional arguments

query isContainedIn2( String x, String y ) 
    Location(x, y;)
    or 
    ( Location(z, y;) and ?isContainedIn(x, z;) )
end



