////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

[id='dmn-execution-kogito-proc_{context}']
= Executing a DMN service using {KOGITO}

Interacting with the REST endpoints of {KOGITO} cloud-native microservice including DMN models provides the most separation between the calling code and the decision logic definition. The calling code is completely free of direct dependencies, and you can implement it in an entirely different development platform such as `Node.js` or `.NET`. 

For a quick getting started guide for {KOGITO} on Quarkus, see the Quarkus guide for https://quarkus.io/guides/kogito-dmn[using {KOGITO} DMN support to add Decision Automation capabilities to a Quarkus application].

For more information about {KOGITO} or migrating to {KOGITO} microservices, see the https://kogito.kie.org/guides/[Kogito website for documentation].
