////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

[id='dmn-support-con_{context}']
= DMN support in {PRODUCT}

{DMN_ENGINE} provides runtime support for DMN 1.1, 1.2, 1.3, and 1.4 models at conformance level 3.

{DMN_EDITOR} provides design support for DMN 1.2 models at conformance level 3.

You can integrate DMN models with your {PRODUCT} decision services in several ways:

* Design your DMN models using the {DMN_EDITOR} online.
* Design your DMN models using the {DMN_EDITOR} in VSCode.
* Import DMN files into your project by opening them in {DMN_EDITOR}. Any DMN 1.1 and 1.3 models (do not contain DMN 1.3 features) that you import or open into {DMN_EDITOR} and save are converted to DMN 1.2 models.
* Package DMN files as part of your project knowledge JAR (KJAR) file without {DMN_EDITOR}.

The following table summarizes the design and runtime support for each DMN version in {PRODUCT}:

.DMN support in {PRODUCT}
[cols="25%,25%,25%,25%"]
|===
.2+h|DMN version
1+h|DMN engine support
2+h|DMN modeler support

h|Execution
h|Open
h|Save

|DMN 1.1
|✅ yes
|✅ yes
|❌ no

|DMN 1.2
|✅ yes
|✅ yes
|✅ yes

|DMN 1.3
|✅ yes
|✅ yes
|❌ no

|DMN 1.4
|✅ yes
|❌ no
|❌ no
|===

In addition to all DMN conformance level 3 requirements, {DMN_ENGINE} also includes enhancements and fixes to FEEL and DMN model components to optimize the experience of implementing DMN decision services with {PRODUCT}. From a platform perspective, DMN models are like any other business asset in {PRODUCT}, such as DRL files or spreadsheet decision tables, that you can include in your {PRODUCT} project and deploy in order to start your DMN decision services.

For more information about including external DMN files with your {PRODUCT} project packaging and deployment method, see
the xref:KIE/index.adoc[Build, Deploy, Utilize and Run section].

You can design a new DMN decision service using a {KOGITO} microservice as an alternative for the cloud-native capabilities of DMN decision services. You could also migrate your existing DMN service to a {KOGITO} microservice. For more information about {KOGITO} or migrating to {KOGITO} microservices, see the https://kogito.kie.org/guides/[Kogito website for documentation].
