[id='dmn-gs-assigning-custom-datatypes-proc']
= Assigning custom data types to the DRD input and decision nodes

After you create the DMN custom data types, assign them to the appropriate *DMN Input Data* and *DMN Decision* nodes in the traffic violations DRD.

.Prerequisite
* You have created the traffic violations DMN custom data types in {CENTRAL}.

.Procedure
. Click the *Model* tab on the DMN designer and click *Diagram properties* in the top-right corner of the DMN designer to expose the DRD properties.
. In the DRD, select the *Driver* input data node and in the *Diagram properties* panel, set *Output data type* to `tDriver`.
. Select the *Violation* input data node and set the *Output data type* to `tViolation`.
. Select the *Fine* input data node and set the *Output data type* to `tFine`.
. Select the *Should the driver be suspended?* decision node and set the following properties:
+
* *Output data type*: `string`
* *Question*: `Should the driver be suspended due to points on his driver license?`
* *Allowed Answers*: `"Yes","No"`
. Click *Save* to open the *Confirm Save* dialog box and click *Save* again.

You have assigned the custom data types to your DRD's input and decision nodes.
