[#decision_model_and_notation_overview]
= Decision Model and Notation

The http://www.omg.org/spec/DMN/1.1[*Decision Model and Notation*], or *DMN*, is a relatively new standard by the http://www.omg.org/[*Object Management Group*], or *OMG*.
It bridges the gap between business models and executable implementations by defining a high level language with a common notation that is readily understandable
by users across the business, from analysts to developers.

The actual specification builds on the experience acquired defining the *Business Process Model and Notation*, or *BPMN*, it's sibling specification, that is used to model
Business Processes. Interoperability and seamless integration between BPMN and DMN is also a goal of the specification.

[#dmn_conformance_levels]
== Conformance Levels

The DMN specification defines three incremental levels of conformance. For the formal definition of each conformance level, please refer to the
http://www.omg.org/spec/DMN/1.1[*DMN 1.1 specification, page 9*]. Here is an informal way of understanding the compliance levels:

Conformance Level 1::
A conformance level 1 implementation is required to support Decision Requirement Diagrams, Decision Logic, and Decision Tables, but the model does not need to be executable.
Any language can be used to define the expressions, including natural, unstructured languages.

Conformance Level 2::
A conformance level 2 implementation is required to support the same as Conformance Level 1, but expressions should be written using the *S-FEEL* (_Simplified FEEL_) language,
as defined in chapter 9 of the specification and the models should be fully executable.

Conformance Level 3::
A conformance level 3 implementation is required to support the same as Conformance Level 2, but expressions can be written using the full *FEEL* language, as defined in chapter
10 of the specification. The implementation also has to support the full set of boxed expressions and be fully executable.

