/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.regression;

import org.drools.testcoverage.common.model.Person;
import java.util.ArrayList;
import org.drools.testcoverage.common.model.ListHolder;

global org.slf4j.Logger LOGGER;

rule "PERSON_PAUL"
	salience 2
	when
		Person (name == "PAUL")
		$listHolder : ListHolder()
		$coll1:ArrayList()
		from collect(Object() from $listHolder.getList())
		$coll2:ArrayList()
		from collect(Object() from $listHolder.getList())
	then
		LOGGER.info("Executing rule");
end

rule "PERSON_PETER"
	salience 1
	when
		person : Person(name != "PETER" )
	then
		person.setName("PETER");
		update(person);
		LOGGER.info("Person: "+person.getName());
end