/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.regression

import java.util.Map

declare Event
    @role( event )
    id : long
end

declare Absence
    id   : long
end

rule "detect absence"
when
    $event : Event(  )
    not (
        Event(
            this != $event,
            id == $event.id,
            this after[0ms, 3100ms] $event
        )
    )
    not (Absence( 
            id == $event.id
        )
    )
    
then
    delete($event);
    insert(new Absence($event.getId()));
end

rule "clear absence"
when
    $event : Event( )
    $absence : Absence (
        id == $event.id
    )
then
    delete($absence);
end







