package org.drools.testcoverage.regression

import org.drools.testcoverage.common.model.Message

declare TestEvent
   @role( event )
   @expires(10s)
   id : String
end

rule "Is It There"
    when
        TestEvent() from entry-point "test"
    then
        insert(new Message("Found a TestEvent"));
end

rule "Accumulate Count"
    when
        $n : Number() from accumulate($t : TestEvent() from entry-point "test", count($t))
    then
        insert(new Message("Found " + $n + " events"));
end