/*
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.explainability.model;

import java.util.UUID;

/**
 * The prediction generated by a {@link PredictionProvider}.
 */
public class CounterfactualPrediction extends BasePrediction {

    private final DataDistribution dataDistribution;
    private final Long maxRunningTimeSeconds;

    public CounterfactualPrediction(PredictionInput input,
            PredictionOutput output,
            DataDistribution dataDistribution,
            UUID executionId,
            Long maxRunningTimeSeconds) {
        super(input, output, executionId);
        this.dataDistribution = dataDistribution;
        this.maxRunningTimeSeconds = maxRunningTimeSeconds;
    }

    public DataDistribution getDataDistribution() {
        return dataDistribution;
    }

    public Long getMaxRunningTimeSeconds() {
        return maxRunningTimeSeconds;
    }
}
