/*
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.explainability.model;

import org.kie.kogito.explainability.local.shap.ShapConfig;

/**
 * The prediction generated by a {@link PredictionProvider}.
 */
public class ShapPrediction extends BasePrediction {
    private final ShapConfig config;

    /**
     * Creata ShapPrediction object that bundles a ShapConfig object with a Prediction
     *
     * @param input: The PredictionInput that was the input to this prediction
     * @param output: The PredictionOutput that is the output to this prediction
     * @param config: The ShapConfig to be used when explaining this prediction
     *
     * @return the mask hash
     */
    public ShapPrediction(PredictionInput input, PredictionOutput output, ShapConfig config) {
        super(input, output);
        this.config = config;
    }

    public ShapConfig getConfig() {
        return this.config;
    }
}