package org.kie.test;

impot org.kie.Cheese;


rulex "eval rule test"
    when
        // some bad stuff here
        Stilton()
        Cheese()
        Poison()
    hen
        // this is an error
        list.add( ;
end 


rule "eval rule test"
    when
        // some bad stuff here
        Stilton()
        Cheese()
        Poison()
    then
        // this is an error
        list.add( ;
    
end 
