package org.drools.test;

import org.drools.Person;

global java.util.List list;
global java.lang.Integer two;

rule "predicate rule test"
    when
        $person1 : Person( $age1 : age )
        // We have no autoboxing of primtives, so have to do by hand
        person2 : Person( $age2:age -> ( $age2.intValue() == $age1.intValue() + two.intValue()  ) )
    then
		list.add( $person1 );
		list.add( person2 );		
end    