package com.sample
 
import java.util.List;

global List list

rule "Rule1" ruleflow-group "flowgroup-1"
	when
		eval(true)
	then
		list.add("Rule1");
end

rule "Rule2" ruleflow-group "flowgroup-2"
	when
		eval(true)
	then
		list.add("Rule2");
end

rule "Rule3" ruleflow-group "flowgroup-3" salience 10
	when
		eval(true)
	then
		list.add("Rule3");
end

rule "Rule4" ruleflow-group "flowgroup-4" salience 20
	when
		eval(true)
	then
		list.add("Rule4");
end