package org.drools.test

import org.drools.Person

global java.util.List list

# this rule shall never fire, since person will be retracted
# by rule 2 that has a higher salience and will fire before rule 1
rule "Salience rule 1" 
    when
        Person( )
    then
		list.add( "Rule 1" );
end    

# this rule shall fire second, since rule 3 has higher salience
rule "Salience rule 2" 
    salience 10
    when
        person: Person( )
    then
		list.add( "Rule 2" );
		retract(person);
end    

# this rule shall fire first since it has the higher salience
rule "Salience rule 3" 
    salience 20
    when
        Person( )
    then
		list.add( "Rule 3" );
end    

