package x;

global java.util.List list;

declare enum DaysOfWeek
    SUNDAY, MONDAY, TUESDAY, WEDNESDAY, THURSDAY, FRIDAY, SATURDAY;
end

declare enum Planets
    MERCURY ( 3.303e+23, 2.4397e6, new String("Mer") + new String("cury").substring(0) ),
    VENUS   ( 4.869e+24, 6.0518e6, "Venus" ),
    EARTH   ( 5.976e+24, 6.37814e6, "Earth" ),
    MARS    ( 6.421e+23, 3.3972e6, "Mars" ),
    JUPITER ( 1.9e+27,   7.1492e7, "Jupiter" ),
    SATURN  ( 5.688e+26, 6.0268e7, "Saturn" ),
    URANUS  ( 8.686e+25, 2.5559e7, "Uranus" ),
    NEPTUNE ( 1.024e+26, 2.4746e7, "Neptune" );

    mass    : double
    radius  : double
    name    : String

end


declare enum WorkLoad
//    LIGHT( x.DaysOfWeek.TUESDAY, 4 ),
//    MEDIUM( x.DaysOfWeek.MONDAY, 8 ),
//    HEAVY( x.DaysOfWeek.SUNDAY, 12 );

    LIGHT( 4 ),
    MEDIUM( 8 ),
    HEAVY( 12 );

//    day     : DaysOfWeek
    hours   : int
end


declare Person
    name    : String
    age     : int
end

declare Test
    load    : WorkLoad
    planet  : Planets
    day     : DaysOfWeek    //= DaysOfWeek.MONDAY
    num     : int           = 111
    pers    : Person        //= new Person("xyz",18)
end


rule "Test"
when
then
    insert( new Test( WorkLoad.LIGHT, Planets.MARS, DaysOfWeek.MONDAY, 4 , new Person("bob",12) ) );
    insert( Planets.valueOf("EARTH") );
    list.add( Planets.MERCURY.getName() );
end

rule "Test2"
when
    Planets( this == Planets.EARTH, $m : mass )
then
    list.add( $m );
end

rule "Test3"
when
    Test( WorkLoad.LIGHT, Planets.MARS, DaysOfWeek.MONDAY ; $h : load.hours )
then
    list.add( $h );
end