package org.drools;

rule "Accumulate non existing function - Java"
    dialect "java"
    when
        $val : Number() from accumulate( $st : StockTick(),
                                         nonExistingFunction( 1 ) );
    then
        // no-op
end  

rule "Accumulate non existing function - MVEL"
    dialect "mvel"
    when
        $val : Number() from accumulate( $st : StockTick(),
                                         nonExistingFunction( 1 ) );
    then
        // no-op
end  
