package org.kie.test;

import org.kie.Cheese;
import org.kie.Person;

global java.util.List results;

rule "External Function" salience 80
    dialect "mvel"
    when
        $person : Person( $likes : likes )
        $min    : Number( intValue <= 5 )
                               from accumulate( $cheese : Cheese( type == $likes, $price : price ),
                                                min( $price ) );
    then
        results.add( $min );
end  
