package org.drools;

global java.util.List results;

rule "Accumulate with bound var " salience 100
    when
        Cheese( type == "stilton", $price : price )
        $totalAmount : Number() from accumulate(  $c : Cheese( type == "brie" ),
                                                  init( int total = 0; ),
                                                  action( total += $c.getPrice() + $price; ),
                                                  reverse( total -= $c.getPrice() + $price; ),
                                                  result( new Integer( total ) ) );
    then
        //System.out.println("Total amount = US$ "+$totalAmount );
        results.add($totalAmount);
end  

