package org.drools;

global java.util.List results;

rule "Test enabled expression 1"
    @ruleID(1234)
    #arbitrary expression using a rule metadata
    enabled ( rule.metaAttributes["ruleID"] == "1234" )
  when
    Person(name == "Michael")
  then
    results.add( "1" );
end

rule "Test enabled expression 2"
    @ruleID(1234)
    # using bound variables 
    enabled ( "Michael".equals( $name ) )
  when
    Person( $name : name )
  then
    results.add( "2" );
end

rule "Test enabled expression 3"
    @ruleID(1234)
    # using simple expressions 
    enabled ( 1 + 1 == 2 )
  when
    Person( $name : name )
  then
    results.add( "3" );
end

rule "Test enabled expression 4"
    @ruleID(1234)
    # using a false expression 
    enabled ( 1 + 1 == 5 )
  when
    Person( $name : name )
  then
    results.add( "4" );
end

