package org.drools;

global java.util.List results;

rule "Test enabled expression 1"
    #arbitrary expression using a rule metadata
    enabled ( "1234".equals( drools.getRule().getMetaAttribute("ruleID") ) )
	@ruleID(1234)
  when
    Person(name == "Michael")
  then
    results.add( "1" );
end

rule "Test enabled expression 2"
    # using bound variables 
    enabled ( "Michael".equals( $name ) )
	@ruleID(1234)
  when
    Person( $name : name )
  then
    results.add( "2" );
end

rule "Test enabled expression 3"
    # using simple expressions 
    enabled ( 1 + 1 == 2 )
	@ruleID(1234)
  when
    Person( $name : name )
  then
    results.add( "3" );
end

rule "Test enabled expression 4"
    # using a false expression 
    enabled ( 1 + 1 == 5 )
	@ruleID(1234)
  when
    Person( $name : name )
  then
    results.add( "4" );
end

