package org.drools;

global java.lang.String cheeseType;
global java.util.List   matchingList;
global java.util.List   nonMatchingList;


rule "Match type"
    when
        $cheese : Cheese( type == (cheeseType) )
    then
        matchingList.add( $cheese );
end

rule "Non matching type"
    when
        $cheese : Cheese( type != (cheeseType) )
    then
        nonMatchingList.add( $cheese );
end
