package org.drools.test;

import org.drools.Cheese;
import org.drools.Person;

global java.util.List results;

rule "External Function" salience 80
    dialect "mvel"
    when
        $person : Person( $likes : likes )
        $count  : Number( intValue >= 2 )
                               from accumulate( $cheese : Cheese( type == $likes  ),
                                                count( $cheese ) );
    then
        results.add( $count );
end  
