package org.drools.test;

import org.drools.Cheese;
import org.drools.Person;

global java.util.List list;

rule justifier1
    when
        cheese : Cheese( type == "brie" )
    then
	    insertLogical( new  Person( "jane" ) );
		list.add( cheese );
end   

rule justifier2
    when
        cheese : Cheese( type == "provolone" )
    then
		insertLogical( new  Person( "jane" ) );
		list.add( cheese );
end   

rule justified
    when
        person : Person( )
    then
		list.add( person );
end 