package org.drools.generatedbeans;

global java.util.List list;

declare Cheese
    type: String
end

declare Person
	age: int
	likes: Cheese
end

rule "simple rule"
    when
        Cheese( type == "stilton" )
    then
		list.add( new Integer(5) );
end

rule "another"
    when
        $cheese : Cheese( type == "stilton" )
     	$person : Person( age== 7, likes == $cheese )
    then
    	list.add( $person );
end