package org.kie.test;

import org.kie.Cheese;
import org.kie.Person;

global java.util.List results;

rule "Test sum" salience 80
    dialect "mvel"
    when
        $person : Person( $likes : likes )
        $sum    : Number( doubleValue >= 10 )
                               from accumulate( Cheese( type == $likes, $price : price  ),
                                                sum( $price ) );
    then
        results.add( $sum );
end  
