package org.drools;

global java.util.Map results;

rule "Duplicate Variable testing"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   Cheese( $type : type == "stilton", $price : price ) or
   Cheese( $type : type == "brie", $price : price )
 then
   results.put( $type, new Integer( $price ) );
end

rule "Duplicate Variable testing 2"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   $cheese : Cheese( type == "stilton", $price : price ) or
   $cheese : Cheese( type == "brie", $price : price )
 then
   results.put( $cheese, new Integer( $price ) );
end

rule "Duplicate Variable testing 3"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   Cheese( $type : type == "stilton", $price : price ) or
   ( Cheese( $type : type == "brie", $price : price ) and Person( name == "bob", likes == $type ) )
 then
   results.put( "test3"+$type, new Integer( $price ) );
end
