/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

//created on: 27-Jun-2007
package org.drools.compiler.test

//list any import classes here.
import org.drools.compiler.Cheese;
import org.drools.compiler.Person;
import org.drools.compiler.Cheesery;

global java.util.List list;

rule "Your First Rule"
    when
        $c : Cheese( type == "stilton" )
        $p : Person( likes == $c.type )
    then
        list.add( $p );
end

rule "Your Second Rule"
    when
        $c : Cheese( type == "cheddar" )
        $p : Person( likes == $c.type )
    then
        list.add( $p );

end
