//created on: 27-Jun-2007
package org.drools.test

//list any import classes here.
import org.drools.compiler.Cheese;
import org.drools.compiler.Person;
import org.drools.compiler.Cheesery;

global java.util.List list;

rule "Your First Rule"
    when
        $c : Cheese( type == "stilton" )
        $p : Person( likes == $c.type )
    then
        list.add( $p );
end

rule "Your Second Rule"
    when
        $c : Cheese( type == "cheddar" )
        $p : Person( likes == $c.type )
    then
        list.add( $p );

end
