/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package salience_test;

import org.drools.compiler.Person

global java.util.List list;

rule "rule 2"
    salience 2
    when
        Person()
    then
        list.add("rule 2");
end
 
rule "rule 1"
    salience 1
    when
        Person()
    then
        list.add("rule 1");
end
 
rule "rule 3"
    salience 3
    when
        Person()
    then
        list.add("rule 3");
end