/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.games.pong;

import org.drools.games.Run;

dialect  "mvel"

rule InitMain when
then
    insert( new Run() );
    setFocus( "Init" );
end

rule Main when
    $r : Run()
then
    setFocus( "Keys" );
    setFocus( "Move" );
    setFocus( "Collision" );
    setFocus( "Game" );
end

rule Redraw when
   gui : PongUI()
   ball : Ball()
   bat1 : Bat( playerId == PlayerId.PlayerOne )
   bat2 : Bat( playerId == PlayerId.PlayerTwo )
   p1 : Player( id == PlayerId.PlayerOne)
   p2 : Player( id == PlayerId.PlayerTwo)
   $r : Run()
then
   gui.drawGame(ball, bat1, bat2, p1, p2);
   modify( $r ) {}
end