/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.pmml.pmml_4_2.test;

import org.drools.pmml.pmml_4_2.ModelMarker;
import org.drools.pmml.pmml_4_2.PMML4AbstractField;


 declare ColdRisk

 end




rule "Input_ColdRisk"
when
    $in : java.lang.Double()
    not ColdRisk( )
then
end






 // Display Name : Outside Temperature

 declare Temp
 end



rule "Input_Temp"
when
    $in : java.lang.Double() from entry-point "in_Temp"
    not Temp( )
then
end


rule "OverrideInput_Temp"
salience 2
when
    $new: java.lang.Double() from entry-point "in_Temp"
    $old: Temp( )
then
end



rule "Mark_MockCold"
salience 9999
no-loop
when
then
    ModelMarker mark = new ModelMarker( "MockCold", "NeuralNetwork" );
    insertLogical( mark );
end

