/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import org.drools.base.factmodel.traits.*;
import org.drools.traits.core.factmodel.*;

import org.drools.traits.compiler.factmodel.traits.ISomethingWithBehaviour;

global java.util.List list;

declare Foo
@Traitable
end

declare trait ISomethingWithBehaviour

end
 
 

rule "Init"
when 
then 
    Entity core = new Entity();
    insert( new Foo() );
end


rule "Mixin'"
dialect "java"
when
    $core: Foo( )
then
    ISomethingWithBehaviour x = don( $core, ISomethingWithBehaviour.class );
    x.setName( "john" );
    x.setAge( 22 );

    x.doAnotherTask();
    list.add( x.doSomething( 5 ) );
end

 
