/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import org.drools.traits.core.factmodel.Entity;
import org.drools.base.factmodel.traits.Traitable;


global java.util.List list;

 
 
declare trait Student
    name    : String            @key
    code    : int               @key
    dcode   : double            @key
    age     : int
end


declare Imp
    @Traitable 
    name    : String
    code    : int
    dcode   : double
    school  : String
end
 

rule "Init"
when 
then 
    Imp core = new Imp( "alan", 33, 3.47, "zkool" );
    insert( core );

    Imp core2 = new Imp( "alan", 33, 3.44, "squola" );
    insert( core2 );
end


rule "Trait"
when
    $core: Imp( "alan", 33, 3.47, "zkool" ; )
then
    Student s = don( $core, Student.class );

    modify ( s ) {
        setAge( 12 ),
        getFields().put( "school", "zkl" );
    }
end


rule "Trait II"
when
    $core: Imp( "alan", 33, 3.44, "squola" ; )
then
    Student s = don( $core, Student.class, true );
end




rule "Check" 
no-loop 
when
    $z: Student( name == "alan", fields[ "age" ] == 12, fields[ "school" ] == "zkl" )
then
    list.add( "DON" );
end 
 
rule "Check II"
no-loop
when
    $s: Student( name == "alan", fields[ "school" ] == "zkl" )
    $z: Student( name == "alan", fields[ "school" ] == "squola" )
then
    $z.setDcode(3.47);
    if ( $s.equals( $z ) ) {
        list.add( "EQUAL" );
    }
end
