/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import java.util.List;
import org.drools.traits.compiler.factmodel.traits.PojoFact;
import org.drools.base.factmodel.traits.Thing;
import org.drools.base.factmodel.traits.Traitable;

global List trueTraits;
global List untrueTraits;


declare PojoFact
	@Traitable
end

declare trait TrueTrait
	flag : boolean
end


rule "Init"
	when
	then
		insert(new PojoFact(1, true));
		insert(new PojoFact(2, false));
end

rule "Don"
	salience 100
	no-loop
	when
		$d : PojoFact( flag == true )
	then
		don( $d, TrueTrait.class, true );
		update($d);
end

rule "True Traits"
	when
		PojoFact( $id : id, this isA TrueTrait )
	then
		trueTraits.add($id);
end

rule "Untrue Traits"
	when
		PojoFact( $id : id, this not isA TrueTrait )
	then
		untrueTraits.add($id);
end

rule "By thing"
    when
        $d : PojoFact()
        exists Thing( core == $d )
    then
end