/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import java.util.List;

global List list;

declare trait SeniorStudent
@propertyReactive
    grad : boolean
    year : int
end

declare Student
@Traitable
@propertyReactive
    grad : boolean = false
    year : int = 0
end


rule "Init"
when
then
    insert( new Student() );
end

rule "React"
when
    $x : SeniorStudent( $y : year ) @watch( year )
then
    list.add( $y );
end


rule "Don"
salience 1
no-loop
when
    $s : Student( grad == false ) @watch( year )
then
    SeniorStudent sen = don( $s, SeniorStudent.class );
end


rule "Age with time"
salience -5
when
    $s : Student( grad == false, $y : year < 4 )
then
modify( $s ) { setYear( $y + 1 ); }
end