/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Person;

global java.util.List list;
global java.lang.Integer two;

rule "predicate rule test"
    when
        $person1 : Person( $age1 : age )
        // We have no autoboxing of primtives, so have to do by hand
        person2 : Person( $age2:age, eval( $age2 == ( $age1 + two.intValue() ) ) )
    then
        list.add( $person1 );
        list.add( person2 );
end    
