package org.drools.compiler.integrationtests

import org.drools.compiler.integrationtests.QueryCepTest.TestEvent

declare TestEvent
    @role( event )
end

query EventsFromStream
    $event : TestEvent() from entry-point FirstStream
end

query ZeroToNineteenSeconds
    $event : TestEvent() from entry-point FirstStream
    $result : TestEvent ( this after [0s, 19s] $event) from entry-point SecondStream
end
