/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "eval rewrite with 'matches'"
    salience 20
    when
        $oi : OrderItem( order.number == 14, seq == 1, order.customer matches "M\\w*" )
    then
        results.add( $oi );
end

rule "eval rewrite with 'not matches'"
    salience 10
    when
        $oi : OrderItem( order.number == 14, seq == 2, order.customer not matches "B\\w*" )
    then
        results.add( $oi );
end
