package org.drools.compiler

global java.util.List result;

function boolean testNonEmptyArray(int[] elements) {
   return elements != null && elements.length > 0;
}

function boolean isNonEmptyObjectArray(Object[] elements) {
   return elements != null && elements.length > 0;
}

rule "Primitive elements in function" salience 20
  when
    Primitives( $elements : primitiveIntArray )
    eval( testNonEmptyArray($elements) )
  then
     result.add( new Integer( $elements.length ) );
end

rule "Primitive Array with Object in function" salience 10
 when
   Primitives( $sArray : arrayAttribute )
   eval( isNonEmptyObjectArray($sArray) )
 then
     result.add( new Integer( $sArray.length ) );
end

rule "Test Array" salience 0
  when
    Primitives( $elements : primitiveIntArray, eval(($elements != null) && ($elements.length > 0)))
  then
    result.add( new Integer( $elements.length ) );
end