/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler;

declare MyBean
    fieldint  : int = 12
    fieldstr : String = "xyz"
    fielddbl : double = 3.23
    field0 : int
    field1 : float
end

declare MyBean2 extends MyBean
    fieldflt  : float = 1.2f
    fieldsht  : short = 2 @key
    field2 : int
    fieldbyt  : byte = 1
end

declare MyBean3 extends MyBean2
    fieldbln : boolean = true
    fieldchr  : char = x
    fieldlng  : long = 9999
end




declare MyBoxBean
    f0 : String
    fieldint : Integer = 12

    fielddbl  : Double = 3.23
    fieldflt  : Float = 1.2f
    fieldsht : Short = 2
    fieldbyt : Byte = 1
    fieldbln : Boolean = true
    fieldchr : Character = x
    fieldlng : Long = 9999


end




declare MyBoxExpressionBean
    f0 : String = "foo" + "bar"
    fieldint : Integer = 12-44

    fielddbl  : Double = Math.sqrt(16.0)
    fieldflt  : Float = 1.0f/2
    fieldsht : Short = 2*3
    fieldbyt : Byte = 1+1
    fieldbln : Boolean = true || false
    fieldchr : Character = x
    fieldlng : Long = 9999

end


declare MySimpleExpressionBean
    f0 : String = "foo" + "bar"
    fieldint : int = 12-44

    fielddbl  : double = Math.sqrt(16.0)
    fieldflt  : float = 1.0f/2
    fieldsht : short = 2*3
    fieldbyt : byte = 1+1
    fieldbln : boolean = true || false
    fieldchr : char = x
    fieldlng : long = 9999

end


rule "mock"
when
    MyBean2( fieldsht > (short) 10 )
then
end