/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List results;

rule "test A"
    salience 10
when
    $a: Cheese ( type == "stilton" )
then
    results.add( $a.getType() );
end

rule "test B" extends "test A"
when
    $b: Cheese ( type == "cheddar" )
    $c: Cheese ( type == "brie" )
then
    modify( $a ) {
        setType( $c.getType() )
    }
    results.add( $a.getType() );
end
