package org.drools.compiler.test;

import org.drools.compiler.Person
import org.drools.compiler.CheeseEqual;

rule "assert"
    salience 10
    when
       p : Person( name == "person" )
    then
        insertLogical( new CheeseEqual( p.getName(), p.getAge() ) );
end

rule "modify"
    no-loop true
    when
        p : Person( name == "person" )
        c : CheeseEqual(price == 2)
    then
        update( p );
end
