/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

global java.util.List list

rule "no patterns1"
    when
        eval(true);
    then
        list.add("fired1");
end    

rule "no patterns2"
    when
        eval(false);
    then
        list.add("fired2");
end 

rule "no patterns3"
    when
        eval(true);
        eval(1==1);
    then
        list.add("fired3");
end  

 
rule "no patterns4"
    when
        eval(false);
        eval(true);
        eval(1==1);
    then
        list.add("fired4");
end 
