/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.SpecialString
import java.util.List

global List list1;
global List list2;
global List list3;
global List list4;

rule "Strange rule1"
when
    x : SpecialString() and
    forall( y : SpecialString(this != x)
                SpecialString(this == y, text == "World") )
then
    list1.add( x );
end 

rule "Strange rule2"
when
    exists(x : SpecialString() and
                forall( y : SpecialString(this != x)
                            SpecialString(this == y, text == "World") ) )
then
    list2.add( "true" );
end 

rule "Strange rule3"
when
    not( exists(x : SpecialString() and
                forall( y : SpecialString(this != x)
                            SpecialString(this == y, text == "Universe") ) ) )
then
    list3.add( "true" );
end 

rule "Strange rule4"
when
    not( exists(x : SpecialString() and
                forall( y : SpecialString(this != x)
                            SpecialString(this == y ) ) ) )
then
    list4.add( "true" );
end 