/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.integrationtests;

import org.drools.compiler.InsertedObject;
import java.util.ArrayList;

rule rule1
  when
  then
    insert( new InsertedObject( "value1") );
    insert( new InsertedObject( "value2") );
end

query "assertedobjquery"
    assertedobj : InsertedObject( value=="value1" )
end 

query "collect objects"
    $list : ArrayList() from collect( InsertedObject() )
end
