package org.drools.test;

import org.drools.Cheese;
import org.drools.Cheesery;
import org.drools.Person;

global java.util.List results;

rule "Constraints everywhere" salience 80
    dialect "mvel"
    when
        $person      : Person( $likes : likes )
        $total       : Number( intValue > 20 )
                               from accumulate( $cheese : Cheese( type == $likes, $p : price ),
                                                init( int total = 0; ),
                                                action( total += $p; ),
                                                reverse( total -= $p; ),
                                                result( new Integer( total ) ) )
    then
        results.add( $total );
end  
