/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "eat food"
   agenda-group "feeding"
   lock-on-active
when
    $p: Person( age >= 15 )
then
    modify( $p ) { setStatus("not hungry") }
    results.add( $p );
end

rule "happy birthday"
   agenda-group "feeding"
   lock-on-active
when
    $p: Person( name == "Michael" )
then
    modify( $p ) { setAge(15) }
end
