/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler
 
import org.drools.compiler.Message;
import org.drools.compiler.Attribute;

global java.util.List list;
 
rule "rule_1"

when
    Message()
    Attribute(value == 1)
then
    System.err.println("case 1");
end

rule "rule_2"

when
    Message()
    Attribute(value == 2)
then
System.err.println("case 2");
end


rule "rule_3"

when
    Message()
    $a:Attribute(value == null)
then
    list.add( "X" );
end 