/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;
 
import org.drools.compiler.Cheese;
import org.drools.compiler.Person;

global java.util.List list;

global java.lang.String str;
 
rule "simple rule"
    when
        Cheese( type == null )
    then
        list.add( new Integer(5) );
end 

rule "another rule"
    when
        Person( bigDecimal != null )
    then 
        list.add( new Integer(6) );
end   

rule "number not null"
    when
         Person( name== "whee", bigDecimal != 3 )
    then
        list.add( new Integer(7) );
end   

rule "global is null"
    when
        p : Person( name == str )
    then
        // str is null, we are just testing we don't get a null pointer
        list.add( p );
end
