/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

import java.util.ArrayList;

global java.util.List results;

rule "Collect results beta constraint"
    salience 10
when
    Integer( $count : intValue )
    $doubles: ArrayList( size == $count ) from collect(Double())
  then
    results.add( "collect" );
end

rule "Accumulate results beta constraint"
when
    Integer( $count:intValue )
    $doubles: ArrayList( size == $count ) from accumulate( $d : Double(),
                                                           init( ArrayList list = new ArrayList(); ),
                                                           action( list.add( $d ); ),
                                                           result( list ) )
  then
    results.add( "accumulate" );
end