package org.drools;

import org.drools.StockTick;

global java.util.List results;

declare StockTick
    @role( event )
    @timestamp( time )
end

rule "after operator on date"
    salience 10
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", dateTimestamp coincides[1s] $a.dateTimestamp )
then
    results.add( $a );
end

rule "after operator on long"
    salience 5
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", time coincides[1s] $a.time )
then
    results.add( $b );
end


rule "after operator on mixed event and date"
    salience 3
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", this coincides[1s] $a.time )
then
    results.add( $a );
end

rule "after operator on mixed date and event"
    salience 0
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", time coincides[1s] $a )
then
    results.add( $b );
end

