package org.drools.compiler.test;

import org.drools.compiler.Cheese;
import org.drools.compiler.Person;

global java.util.List results;

rule "External Function" salience 80
    dialect "mvel"
    when
        $person : Person( $likes : likes )
        $max    : Number( intValue >= 5 )
                               from accumulate( $cheese : Cheese( type == $likes, $price : price ),
                                                max( $price ) );
    then
        results.add( $max );
end  
