/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.metatest;

global java.util.List results;

import org.drools.compiler.Person

rule "Test Consequence"
    @foo(bar)
    @foo2(bar2)
    @ruleID(1234)
    @parentRuleID(1234)
    @dateActive(12/1/08)
    @price(123.00)
    @errorMSG(Stop)
    @userMSG("Please Stop")
  when
    Person(name == "Michael")
  then
    results.add( drools.getRule().getMetaAttribute("foo"));
    results.add( drools.getRule().getMetaAttribute("foo2"));
end
