/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package mortgages


declare LoanApplication
    amount: Integer
    approved: Boolean
    deposit: Integer
    approvedRate: Integer
    lengthYears: Integer
    explanation: String
    insuranceCost: Integer
end

declare Applicant
    age: Integer
    name: String
    creditRating: String
end

declare IncomeSource
    amount: Integer
    type: String
end

declare Bankruptcy
    amountOwed: Integer
    yearOfOccurrence: Integer
end


rule 'Try it again'
       dialect "mvel"
    when
        ( Applicant( creditRating == "OK" ) or Applicant( creditRating == "Sub prime" ) )
        app : LoanApplication( )
    then
        app.setApproved( false );
        app.setExplanation( "Only AB" );
        delete( app );

end

