package org.drools;

import java.util.List;
import java.util.ArrayList;

global java.util.List results;

rule "Accumulate with From Chaining" salience 80
    when
        $cheesery : Cheesery()
        $person   : Person( $likes : likes )
        $list     : List( size > 2 )
                               from accumulate( $cheese : Cheese( type == $likes  ) from $cheesery.getCheeses(),
                                                init( List l = new ArrayList(); ),
                                                action( l.add( $cheese ); )
                                                result( l ) )
    then
        results.add( $list );
end  
