/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;
import org.drools.compiler.Person;
import java.util.ArrayList;

global java.util.List results;

rule "Collect Test" salience 70
    when
        $person      : Person( name == "Bob", $likes : likes )
        $cheeseList  : ArrayList(size > 2) from collect( Cheese( type == $likes ) );
    then
        //System.out.println($person.getName() +" will buy "+ $cheeseList.size() + " pieces of cheese");
        results.add($cheeseList);
end
