/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "Test LR unlinking with multiple joins on the same object type"
	when
	 $p1 : Person ($name : name != null)
	 $p2 : Person ($likes : likes != null)
	 $p3 : Person ($age : age != null)
	 $p4 : Person ($hair : hair != null)
	 $p5 : Person ($happy : happy != null)
	 $p6 : Person (name != $name,
	               likes == $likes, 
	               age == $age, 
	               hair == $hair, 
	               happy == $happy)
	then
		results.add( $p6 );
end