/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "test final class 1"
    dialect "mvel"
    salience 10
    when
        $p : Person( name == "bob", status == null )
    then
        $p.status = "OK";
        results.add("OK");
        update( $p );
end

rule "test final class 2"
    dialect "mvel"
    when
        $p : Person( name == "bob", status == null )
    then
        // this rule should not fire
        $p.status = "NOT OK";
        results.add("NOT OK");
end
