/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.integrationtests.VarargsTest.MySet;

global MySet set;

rule default when
then
    set = new MySet( "x", "y" );
    kcontext.getKnowledgeRuntime().setGlobal("set", set );
    insert( set );
end

rule r1
when
    $ms: MySet()
then
    modify( $ms ){ add( "three", "four" ) }
end

rule r2 salience 1000
when
    $ms: MySet()
then
      modify( $ms ){ add( "z" ) }
end
