/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */
package org.drools.metric.profiling;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Duration;
import java.time.ZoneId;
import java.time.format.DateTimeFormatter;
import java.util.Collection;
import java.util.Comparator;
import java.util.Locale;

import org.drools.metric.util.RuleMetricStats;
import org.drools.metric.util.SessionMetricCollector;

/**
 * Generates a self-contained HTML profiling dashboard from a
 * {@link SessionMetricCollector} snapshot.
 * <p>
 * The generated HTML includes:
 * <ul>
 *   <li>Summary cards (total rules fired, total time, avg time, fact count)</li>
 *   <li>A sortable rule performance table (name, fire count, total/avg/min/max time)</li>
 *   <li>A top-10 hotspot bar chart (pure CSS, no external JS)</li>
 * </ul>
 * <p>
 * The report is fully self-contained with inline CSS, uses a responsive
 * dark theme, and requires no external assets or libraries.
 */
public final class MetricDashboardReporter {

    private static final DateTimeFormatter TIMESTAMP_FORMAT =
            DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss").withZone(ZoneId.systemDefault());

    private MetricDashboardReporter() {
        // Utility class
    }

    /**
     * Generates a complete HTML profiling report.
     *
     * @param collector the session metric collector to report on
     * @return the full HTML string
     */
    public static String generateReport(SessionMetricCollector collector) {
        StringBuilder html = new StringBuilder(8192);
        html.append("<!DOCTYPE html>\n<html lang=\"en\">\n<head>\n");
        html.append("<meta charset=\"UTF-8\">\n");
        html.append("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n");
        html.append("<title>Drools Performance Dashboard</title>\n");
        appendStyles(html);
        html.append("</head>\n<body>\n");

        appendHeader(html, collector);
        appendSummaryCards(html, collector);
        appendHotspotChart(html, collector);
        appendRuleTable(html, collector);

        html.append("<footer><p>Generated by drools-metric profiling &middot; Apache KIE Drools</p></footer>\n");
        html.append("</body>\n</html>\n");
        return html.toString();
    }

    /**
     * Generates and writes the HTML report to a file.
     *
     * @param collector the session metric collector
     * @param outputPath the file path to write to
     * @throws IOException if writing fails
     */
    public static void writeReport(SessionMetricCollector collector, Path outputPath) throws IOException {
        String html = generateReport(collector);
        Files.writeString(outputPath, html, StandardCharsets.UTF_8);
    }

    // ---- HTML Sections ----

    private static void appendHeader(StringBuilder html, SessionMetricCollector collector) {
        html.append("<div class=\"header\">\n");
        html.append("  <h1>&#9889; Drools Performance Dashboard</h1>\n");
        html.append("  <p class=\"subtitle\">Session started: ")
                .append(TIMESTAMP_FORMAT.format(collector.getSessionStartTime()))
                .append(" &middot; Duration: ")
                .append(formatDuration(collector.getSessionDuration()))
                .append("</p>\n");
        html.append("</div>\n");
    }

    private static void appendSummaryCards(StringBuilder html, SessionMetricCollector collector) {
        html.append("<div class=\"cards\">\n");
        appendCard(html, "&#128293;", "Rules Fired", String.valueOf(collector.getTotalRulesFired()));
        appendCard(html, "&#9202;", "Total Firing Time", formatMillis(collector.getTotalFiringTimeMillis()));
        appendCard(html, "&#9889;", "Avg Firing Time", formatMillis(collector.getAverageFiringTimeMillis()));
        appendCard(html, "&#128202;", "Distinct Rules", String.valueOf(collector.getDistinctRuleCount()));
        appendCard(html, "&#10004;", "Matches Created", String.valueOf(collector.getMatchesCreated()));
        appendCard(html, "&#10060;", "Matches Cancelled", String.valueOf(collector.getMatchesCancelled()));

        long factCount = collector.getCurrentFactCount();
        if (factCount >= 0) {
            appendCard(html, "&#128451;", "Current Facts", String.valueOf(factCount));
        }
        html.append("</div>\n");
    }

    private static void appendCard(StringBuilder html, String icon, String label, String value) {
        html.append("  <div class=\"card\">\n");
        html.append("    <div class=\"card-icon\">").append(icon).append("</div>\n");
        html.append("    <div class=\"card-value\">").append(value).append("</div>\n");
        html.append("    <div class=\"card-label\">").append(label).append("</div>\n");
        html.append("  </div>\n");
    }

    private static void appendHotspotChart(StringBuilder html, SessionMetricCollector collector) {
        Collection<RuleMetricStats> topRules = collector.getTopRulesByTime(10);
        if (topRules.isEmpty()) {
            return;
        }

        long maxTime = topRules.stream()
                .mapToLong(RuleMetricStats::getTotalTimeNanos)
                .max().orElse(1);

        html.append("<div class=\"section\">\n");
        html.append("  <h2>&#128293; Top 10 Hotspot Rules (by total time)</h2>\n");
        html.append("  <div class=\"chart\">\n");

        for (RuleMetricStats rule : topRules) {
            double pct = maxTime > 0 ? (double) rule.getTotalTimeNanos() / maxTime * 100.0 : 0;
            html.append("    <div class=\"chart-row\">\n");
            html.append("      <div class=\"chart-label\" title=\"").append(escapeHtml(rule.getRuleName())).append("\">")
                    .append(escapeHtml(shortenRuleName(rule.getRuleName()))).append("</div>\n");
            html.append("      <div class=\"chart-bar-container\">\n");
            html.append("        <div class=\"chart-bar\" style=\"width:").append(String.format(Locale.US, "%.1f", pct)).append("%\">\n");
            html.append("          <span class=\"chart-bar-text\">").append(formatMillis(rule.getTotalTimeMillis()))
                    .append(" (").append(rule.getFireCount()).append("x)</span>\n");
            html.append("        </div>\n");
            html.append("      </div>\n");
            html.append("    </div>\n");
        }

        html.append("  </div>\n");
        html.append("</div>\n");
    }

    private static void appendRuleTable(StringBuilder html, SessionMetricCollector collector) {
        Collection<RuleMetricStats> allRules = collector.getAllRuleStats().values().stream()
                .sorted(Comparator.comparingLong(RuleMetricStats::getTotalTimeNanos).reversed())
                .toList();

        if (allRules.isEmpty()) {
            html.append("<div class=\"section\"><p class=\"empty\">No rules have been fired yet.</p></div>\n");
            return;
        }

        html.append("<div class=\"section\">\n");
        html.append("  <h2>&#128203; Rule Performance Details</h2>\n");
        html.append("  <div class=\"table-wrap\">\n");
        html.append("  <table>\n");
        html.append("    <thead><tr>\n");
        html.append("      <th>Rule Name</th><th>Fire Count</th><th>Total Time</th><th>Avg Time</th><th>Min Time</th><th>Max Time</th>\n");
        html.append("    </tr></thead>\n");
        html.append("    <tbody>\n");

        for (RuleMetricStats rule : allRules) {
            html.append("    <tr>\n");
            html.append("      <td class=\"rule-name\" title=\"").append(escapeHtml(rule.getRuleName())).append("\">")
                    .append(escapeHtml(shortenRuleName(rule.getRuleName()))).append("</td>\n");
            html.append("      <td class=\"num\">").append(rule.getFireCount()).append("</td>\n");
            html.append("      <td class=\"num\">").append(formatMillis(rule.getTotalTimeMillis())).append("</td>\n");
            html.append("      <td class=\"num\">").append(formatMillis(rule.getAvgTimeMillis())).append("</td>\n");
            html.append("      <td class=\"num\">").append(formatNanos(rule.getMinTimeNanos())).append("</td>\n");
            html.append("      <td class=\"num\">").append(formatNanos(rule.getMaxTimeNanos())).append("</td>\n");
            html.append("    </tr>\n");
        }

        html.append("    </tbody>\n  </table>\n");
        html.append("  </div>\n</div>\n");
    }

    // ---- Styles ----

    private static void appendStyles(StringBuilder html) {
        html.append("<style>\n");
        html.append("""
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
                font-family: 'Segoe UI', system-ui, -apple-system, sans-serif;
                background: #0f1117;
                color: #e1e4e8;
                padding: 24px;
                max-width: 1200px;
                margin: 0 auto;
            }
            .header {
                text-align: center;
                padding: 32px 0 24px;
                border-bottom: 1px solid #21262d;
                margin-bottom: 24px;
            }
            .header h1 {
                font-size: 1.8rem;
                background: linear-gradient(135deg, #58a6ff, #d2a8ff);
                -webkit-background-clip: text;
                -webkit-text-fill-color: transparent;
                background-clip: text;
            }
            .subtitle { color: #8b949e; margin-top: 8px; font-size: 0.9rem; }
            .cards {
                display: grid;
                grid-template-columns: repeat(auto-fit, minmax(160px, 1fr));
                gap: 16px;
                margin-bottom: 32px;
            }
            .card {
                background: #161b22;
                border: 1px solid #21262d;
                border-radius: 12px;
                padding: 20px;
                text-align: center;
                transition: transform 0.2s, border-color 0.2s;
            }
            .card:hover { transform: translateY(-2px); border-color: #58a6ff; }
            .card-icon { font-size: 1.5rem; margin-bottom: 8px; }
            .card-value { font-size: 1.6rem; font-weight: 700; color: #f0f6fc; }
            .card-label { font-size: 0.8rem; color: #8b949e; margin-top: 4px; text-transform: uppercase; letter-spacing: 0.5px; }
            .section {
                background: #161b22;
                border: 1px solid #21262d;
                border-radius: 12px;
                padding: 24px;
                margin-bottom: 24px;
            }
            .section h2 { font-size: 1.2rem; margin-bottom: 16px; color: #c9d1d9; }
            .chart { display: flex; flex-direction: column; gap: 10px; }
            .chart-row { display: flex; align-items: center; gap: 12px; }
            .chart-label {
                width: 200px;
                min-width: 200px;
                font-size: 0.82rem;
                text-align: right;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                color: #c9d1d9;
            }
            .chart-bar-container { flex: 1; background: #21262d; border-radius: 6px; height: 28px; }
            .chart-bar {
                background: linear-gradient(90deg, #238636, #2ea043);
                height: 100%;
                border-radius: 6px;
                min-width: 2px;
                display: flex;
                align-items: center;
                padding-left: 8px;
                transition: width 0.5s ease;
            }
            .chart-bar-text { font-size: 0.75rem; color: #fff; white-space: nowrap; }
            .table-wrap { overflow-x: auto; }
            table {
                width: 100%;
                border-collapse: collapse;
                font-size: 0.88rem;
            }
            th {
                text-align: left;
                padding: 10px 12px;
                border-bottom: 2px solid #30363d;
                color: #8b949e;
                font-weight: 600;
                text-transform: uppercase;
                font-size: 0.75rem;
                letter-spacing: 0.5px;
            }
            td {
                padding: 10px 12px;
                border-bottom: 1px solid #21262d;
            }
            tr:hover td { background: #1c2129; }
            .rule-name {
                max-width: 350px;
                overflow: hidden;
                text-overflow: ellipsis;
                white-space: nowrap;
                color: #58a6ff;
            }
            .num { font-family: 'SF Mono', 'Fira Code', monospace; text-align: right; color: #d2a8ff; }
            .empty { text-align: center; color: #8b949e; padding: 40px; }
            footer {
                text-align: center;
                padding: 24px;
                color: #484f58;
                font-size: 0.8rem;
            }
            @media (max-width: 600px) {
                body { padding: 12px; }
                .chart-label { width: 120px; min-width: 120px; font-size: 0.72rem; }
                .cards { grid-template-columns: repeat(2, 1fr); }
            }
        """);
        html.append("</style>\n");
    }

    // ---- Utilities ----

    private static String formatMillis(double ms) {
        if (ms < 1.0) {
            return String.format(Locale.US, "%.3f ms", ms);
        } else if (ms < 1000.0) {
            return String.format(Locale.US, "%.2f ms", ms);
        } else {
            return String.format(Locale.US, "%.2f s", ms / 1000.0);
        }
    }

    private static String formatNanos(long nanos) {
        if (nanos < 1_000) {
            return nanos + " ns";
        } else if (nanos < 1_000_000) {
            return String.format(Locale.US, "%.1f µs", nanos / 1_000.0);
        } else {
            return String.format(Locale.US, "%.2f ms", nanos / 1_000_000.0);
        }
    }

    private static String formatDuration(Duration d) {
        long totalSeconds = d.getSeconds();
        if (totalSeconds < 1) {
            return d.toMillis() + " ms";
        } else if (totalSeconds < 60) {
            return totalSeconds + "." + (d.toMillisPart() / 100) + " s";
        } else {
            long mins = totalSeconds / 60;
            long secs = totalSeconds % 60;
            return mins + "m " + secs + "s";
        }
    }

    private static String shortenRuleName(String fullName) {
        if (fullName == null) {
            return "unknown";
        }
        int lastDot = fullName.lastIndexOf('.');
        if (lastDot >= 0 && lastDot < fullName.length() - 1) {
            return fullName.substring(lastDot + 1);
        }
        return fullName;
    }

    private static String escapeHtml(String text) {
        if (text == null) {
            return "";
        }
        return text.replace("&", "&amp;")
                .replace("<", "&lt;")
                .replace(">", "&gt;")
                .replace("\"", "&quot;");
    }
}
