package org.kie.kogito.codegen.unit;
unit AdultUnit;

import org.kie.kogito.codegen.data.Person
import org.kie.kogito.codegen.data.Results

rule FilterAdult when
    $p: /persons[ age >= 18 ]
then
    // In theory it should also work something like
    //    $p.setAdult(true);
    //    persons.update($p);
    // but for now we don't want to enable an update of an object directly on the DataStore from a consequence
    // otherwise all the property reactivity information will be lost. The following modify will anyway have the
    // effect to propagate the update to the DataStore and then to all the rule units sharing it.
    modify($p) { setAdult(true) };
end

rule RemoveNonAdult when
    $p: /persons[ !adult ]
then
    // Invoking remove on a DataStore has the same effect of just calling
    //    delete($p);
    // In both cases the object is removed from the DataStore from where it has been inserted
    // and the deletion will be propagated to all rule units sharing this DataStore.
    persons.remove($p);
end

rule IsAdult when
    $p: /persons[ $name : name ]
then
    results.add($name);
end

