package org.kie.kogito.codegen.unit;
unit AdultUnit;

import org.kie.kogito.codegen.data.Person

rule CheckAdult when
    $p: /persons[ age >= 18 ]
then
    modify($p) { setAdult(true) };
end

rule CheckNotAdult when
    $p: /persons[ age < 18 ]
then
    modify($p) { setAdult(false) };
end

query FindAdults
    /persons[ adult, $name : name ]
end

query FindAdultsAge
    /persons[ adult, $age : age ]
end

