/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.games.invaders1;

import org.drools.games.KeyPressed
import org.drools.games.Run

dialect "mvel"

rule "init" when
then
    insert( new Run() );
end

rule Main when
    r : Run()
then
    setFocus( "Keys" );
end

rule DetectInsertedKey when
    kp : KeyPressed()
then
    System.out.println( "KeyPressed inserted" + kp );
end

rule DetectDeletedKey when
    not KeyPressed()
then
    System.out.println( "KeyPressed deleted" );
end

rule Loop when
    r : Run()
then
    modify( r ) {}
end