/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.defeasible;

global java.util.List list;

declare A
    id  : int   @key
end

declare B
    id  : int   @key
end

declare X
    id  : int   @key
end


rule "Init"
when
then
    insert( new A( 1 ) );   // A(1) is a Fact
    insert( new B( 2 ) );   // same for B(2)
end

rule "Stronger"
@Defeasible
@Defeats( "Weaker" )
when
    B( 2; )
then
    insertLogical( new X( 1 ), "neg" );
end

rule "Weaker"
@Defeasible
when
    A( 1; )
then
    insertLogical( new X( 1 ) );
end


rule "Pos"
salience -1
when
    $x : X( $id : id )
then
    System.out.println( "Positive X " + $x );
    list.add( "+" + $id );
end

rule "Neg"
salience -1
when
    $x : X( _.neg, $id : id )
then
    System.out.println( "Negative X " + $x );
    list.add( "-" + $id );
end