package org.drools;

dialect "mvel"


import org.drools.Person
import org.drools.Address



rule "test something"

    when
        p: Person( name=="Michael",
                                (addresses[1].street == "Low" &&
                                addresses[0].street == "High"  )
                                )
    then
        p.name = "goober";
        System.out.println(p.name);
        insert(new Address("Latona"));
end
