package org.drools.test;

import org.drools.Cheese;

global java.util.List list;

rule "not rule test"
    when       
        not Cheese( price == 5 )
    then
		list.add( new Integer( 5 ) );
end    

rule "not rule with bound variable"
    when
        not Cheese( $price:price -> ( $price.intValue() == 5 ) )
    then
        System.out.println("It is working, but please replace this sysout for something that junit can check against");
end