package org.drools.test;

import org.drools.Cheese;

global java.util.List list;

rule "not rule test"
	salience 10
    when       
        not Cheese( price == 5 )
    then
		list.add( new Integer( 5 ) );
end    

rule "not rule with bound variable"
    when
        not Cheese( $price:price -> ( $price == 5 ) )
    then
		list.add( new Integer( 6 ) );
end

rule "not rule with other patterns 1"
    when
        Cheese( $type : type == "cheddar" )
        not Cheese( price == 5 )
    then
		list.add( new Integer( 7 ) );
end

rule "not rule with other patterns 2"
    when
        not Cheese( price == 5 )
        Cheese( $type : type == "cheddar" )
    then
		list.add( new Integer( 8 ) );
end
