package org.drools.test;
 
import org.drools.FromTestClass;
import org.drools.Person

global FromTestClass testObject;
global java.util.List list;
global java.lang.Object globalObject;

rule "test from"
	when
		$person : Person()
		$object : Object() from testObject.toList(globalObject, $person, "literal", 42, { $person => globalObject, "key1" => { "key2" => "value2" } } )		
	then
		list.add( $object );
end
