package org.drools.test;

import org.drools.Cheese;
import org.drools.Cheesery;
import org.drools.Person;

global java.util.List results;

rule "Constraints everywhere" salience 80
    dialect "mvel"
    when
        $person      : Person( $likes : likes )
        $cheesery    : Cheesery( totalAmount > 20 )
                               from accumulate( $cheese : Cheese( type == $likes ),
                                                init( cheesery = new Cheesery(); ),
                                                action( cheesery.addCheese( $cheese ); ),
                                                reverse( cheesery.removeCheese( $cheese ); ),
                                                result( cheesery ) );
    then
        results.add( $cheesery );
end  
