package org.drools;

rule "Test OR with multiple evals - java"
    dialect "java"
when
    $aFact : FactA( $a : field1 == "a" )
    $bFact : FactB( $b : f1 == "b" )
    $cFact : FactC( $c : f1 == "c" )
    ( eval( $aFact.getField1().equals( $a ) ) or 
      eval( $bFact.getF1().equals( $b ) ) or
      eval( $cFact.getF1().equals( $c ) ) )
then
    // do something thrice
end

rule "Test OR with multiple evals - mvel"
    dialect "mvel"
when
    $aFact : FactA( $a : field1 == "a" )
    $bFact : FactB( $b : f1 == "b" )
    $cFact : FactC( $c : f1 == "c" )
    ( eval( $aFact.getField1().equals( $a ) ) or 
      eval( $bFact.getF1().equals( $b ) ) or
      eval( $cFact.getF1().equals( $c ) ) )
then
    // do something thrice
end