package org.kie.test

import org.kie.Person
import org.kie.Cheesery
import org.kie.Cheesery.Maturity

global java.util.List list

rule "status, int based enum"
    salience 10
    when
           p : Cheesery(status == Cheesery.SELLING_CHEESE, maturity == Maturity.OLD)
    then
        list.add( p );

end   

rule "maturity, object based enum"
    when
           p : Cheesery(status == Cheesery.MAKING_CHEESE, maturity == Maturity.YOUNG)
    then
        list.add( p );
end  
