package org.drools;

global java.util.Map results;

rule "Duplicate Variable testing"
 when
   // this must raise an error as the variables are in the same branch
   Cheese( $type : type == "stilton", $price : price )
   Cheese( $type : type == "brie", $price : price )
 then
   results.put( $type, new Integer( $price ) );
end

rule "Duplicate Variable testing 2"
 when
   // this must raise an error as the variables are in the same branch
   $cheese : Cheese( type == "stilton", $price : price )
   $cheese : Cheese( type == "brie", $price : price )
 then
   results.put( $cheese, new Integer( $price ) );
end

rule "Duplicate Variable testing 3"
 when
   // this must raise an error as the variables are in the same branch
   Cheese( $type : type == "stilton", $price : price ) 
   Cheese( $type : type == "brie", $price : price ) and Person( name == "bob", likes == $type )
 then
   results.put( "test3"+$type, new Integer( $price ) );
end
