package org.drools.test;

import org.drools.Cheese;
import org.drools.Cheesery;

global java.util.List list;

rule "Cheesery contains stilton"
	salience 10
    when
        stilton : Cheese( type == "stilton" )
        Cheesery( cheeses contains stilton )
    then
		list.add( stilton );
end   

rule "Cheesery do not contains brie"
    when
        brie : Cheese( type == "brie" )
        Cheesery( cheeses not contains brie )
    then
		list.add( brie );
end   