package org.drools.test;
 
#we don't use the import, as class is fully qualified below 
#import org.drools.integrationtests.helloworld.Message
import org.drools.Cheese;
import org.drools.Cheesery;
import java.util.List;

global List list;
global Cheesery cheesery;

rule "test from"
	when
		$cheese : Cheese() from cheesery.getCheeses()		
	then
	    System.out.println( list );
		list.add( $cheese );
end
