package org.drools.generatedbeans;

global java.util.List list;
global Cheese cg;


declare Cheese
    type: String
end

declare Person
    name : String
    age: int
    likes: Cheese
end

rule "simple rule"
    when
        Cheese( type == "stilton" )
    then
        list.add( new Integer(5) );
        cg.setType("nothing");
end

rule "another"
    dialect "mvel"
    when
        $cheese : Cheese( type == "stilton" )
         $person : Person( age== 7, likes == $cheese )
    then
        list.add( $person );
end
