package HelloWorld

global java.util.List list;

rule "Hello World 1"
    salience 10
    when
        $m : org.drools.Message(list contains "hello",
                    text:message == "hola",
                    number in (1, 2, 3, 4, 50, 0),
                    birthday > "10-Jul-1974",
                    message matches ".*ho.*",
                    list excludes "wax",
                    fired == false )
    then
        // putting in a complex consequence, to make sure it picks up the variabels correctly
           list.add( $m );
end
