package mortgages


declare LoanApplication
    amount: Integer
    approved: Boolean
    deposit: Integer
    approvedRate: Integer
    lengthYears: Integer
    explanation: String
    insuranceCost: Integer
end

declare Applicant
    age: Integer
    name: String
    creditRating: String
end

declare IncomeSource
    amount: Integer
    type: String
end

declare Bankruptcy
    amountOwed: Integer
    yearOfOccurrence: Integer
end






rule 'Try it again'
       dialect "mvel"
    when
        ( Applicant( creditRating == "OK" ) or Applicant( creditRating == "Sub prime" ) )
        app : LoanApplication( )
    then
        app.setApproved( false );
        app.setExplanation( "Only AB" );
        retract( app );

end

