package org.drools.test;

import org.drools.Address;
import org.drools.Person;
import java.util.ArrayList;

dialect "mvel"

global java.util.List results;

rule "After Or Evals Collect from MVEL"
salience 70
	when
		$jill        : Person( name == "jill" )
        $bob         : Person( name == "bob" )
		( eval( $jill != null ) || eval( $bob != null ) )
        $addressList : ArrayList(size > 2) from collect( Address() from $bob.addresses )
    then
        results.add($addressList);
end
