package org.drools;

global java.util.List results;

function int f1(int i) {
    return f2(i+1);
}

function int f2(int i) {
    return f3(i+1);
}

function int f3(int i) {
    return f4(i+1);
}

function int f4(int i) {
    return f5(i+1);
}

function int f5(int i) {
    return f6(i+1);
}

function int f6(int i) {
    return f7(i+1);
}

function int f7(int i) {
    return f8(i+1);
}

function int f8(int i) {
    return f9(i+1);
}

function int f9(int i) {
    return f10(i+1);
}

function int f10(int i) {
    return i+1;
}

rule "X"
when
    eval( f1(0) == 10 )
then
    results.add( new Integer( f1(0) ) );
end