package org.drools;

global java.util.List results;

rule "Accumulate Returning Null" salience 100
    when
        // emulating a null return value for accumulate
        $totalAmount : Number() from accumulate( Cheese( $price : price ),
                                                 init( ),
                                                 action( ),
                                                 result( null ) );
    then
        //System.out.println("Total amount = US$ "+$totalAmount );
        results.add($totalAmount);
end  


