////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
////

:DROOLS:
include::../_artifacts/document-attributes.adoc[]

[[experimental-features]]

:context: experimental-features

[id='{context}']
= Experimental features

This chapter documents experimental features that are part of the Drools projects group. As these features are experimental, they may not be finished or stable enough for common use. All aspects of these features are highly likely to change in the future.

include::_experimental-declarative-agenda.adoc[leveloffset=+1]
include::_experimental-traits.adoc[leveloffset=+1]
include::_experimental-impact-analysis.adoc[leveloffset=+1]

