package org.drools.adventures.commands

import org.drools.adventures.Request
import org.drools.adventures.Character
import org.drools.adventures.Thing
import org.drools.adventures.Room

dialect "mvel"

declare Command
    request : long
end

declare MoveCommand extends Command
   character : long @key
   room : long @key
end

declare DropCommand extends Command
   character : long @key
   thing : long @key
end

declare PickupCommand extends Command
   character : long @key
   thing : long @key
end

declare LookCommand extends Command
   character : long @key
   quick : boolean
end