/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.process.order

import java.util.Date
import java.util.Calendar

function int getHourOfDate(Date date) {
	Calendar calendar = Calendar.getInstance();
	calendar.setTime(date);
	return calendar.get(Calendar.HOUR_OF_DAY);
}

rule "5% discount if order includes laptop and order after 18h" ruleflow-group "discount"
	when
		o: Order( date: date )
		eval( getHourOfDate(date) >= 18 )
		Order.OrderItem( itemId == "I-5432" ) from o.getOrderItems() 
	then
		System.out.println("Applying a 5% discount");
		o.setDiscountPercentage(5);
end
