/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.integrationtests;

import org.drools.compiler.integrationtests.DeleteTest.Person;
import java.util.List;

query countPerson
   $personCount : Long() from accumulate ($person: Person(), count( $person ))
end

query someQuery
   $names : List() from accumulate (Person($name : name), collectList( $name ))
end

query informationAboutPersons
    accumulate (
        Person( $age : age, $name : name );
        $minimalAge : min( $age ),
        $maximalAge : max( $age ),
        $averageAge : average( $age ), 
        $countOfPerson : count( $age ),
        $sumOfAges : sum ( $age ),
        $setOfNames : collectSet ( $name ),
        $listOfNames : collectList( $name ),
        $expr : average( $age * 1000 );
        $minimalAge > 0, $maximalAge < 150
    )
end
