package com.sample
 
import java.util.List
import org.drools.core.common.InternalAgenda;

global List list

rule "Sample Rule" @Propagation(EAGER) ruleflow-group "Group1" salience 20
    when
        s: String()
    then
        System.out.println("Clearing ruleflow-group");
        ((InternalAgenda)drools.getWorkingMemory().getAgenda()).clearAndCancelRuleFlowGroup("Group1");
end

rule "Sample Rule 2"  @Propagation(EAGER) ruleflow-group "Group1"
    when
        s: String()
    then
        System.out.println("Adding string " + s);
        list.add(s);
end
