/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.RoutingMessage;
import java.util.List;

global List list;

rule teststartswith
when
    $m : RoutingMessage( routingValue str[startsWith] "R1" )
then
    list.add("Message starts with R1");
end

rule testsendswith
when
    $m : RoutingMessage( routingValue str[endsWith] "R2" )
then
    list.add("Message ends with R2");
end

rule testlength
when
    $m : RoutingMessage( routingValue str[length] 17 )
then
    list.add("Message length is 17");
end

rule testnotlength
when
    $m : RoutingMessage( routingValue not str[length] 17 )
then
    list.add("Message length is not 17");
end

rule testnotstartswith
when
    $m : RoutingMessage( routingValue not str[startsWith] "R2" )
then
    list.add("Message does not start with R2");
end

rule testnotendswith
when
    $m : RoutingMessage( routingValue not str[endsWith] "R1" )
then
    list.add("Message does not end with R1");
end

rule testmultiple
when
    $m : RoutingMessage( routingValue str[startsWith] "R1" && str[endsWith] "R2" && str[length] 17)
then
    list.add("Message starts with R1, ends with R2 and it's length is 17");
end
