/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list
global java.lang.String string


rule "global rule test"
    salience 10
    when
        eval( "stilton".equals( string ) )
    then
        list.add( new Integer(5) );
end    

rule "global rule test with cheese"
    when
        Cheese( price == 100 );
        eval( "stilton".equals( string ) )
    then
        list.add( new Integer(6) );
end    
