/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

rule "Cheese"
no-loop true
    when
        a: Cheese( $type : type, price == 10 );
        b: Cheese( type == $type, price == 15 );
        c: Cheese( type == $type );
    then
        c.setPrice( 30 );
        delete(a);
        update(c);
end

