/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler
 
global java.util.List results;

function void aaa() { 
   // just a dummy function to force java dialect recompilation
}

declare SomeBean
    prop : String
end
 
rule "setup 1"
    dialect "mvel" 
when
    eval(true)
then
    SomeBean someBean = new SomeBean();
    someBean.setProp("mvel");
    insert(someBean);
end

rule "setup 2"
    dialect "java" 
when
    eval(true)
then
    SomeBean someBean = new SomeBean();
    someBean.setProp("java");
    insert(someBean);
end

rule "match"
    salience -20
when
    $bean : SomeBean()
then
    results.add( $bean.getProp() );
end 