/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.Person

global java.util.List list

// this rule shall never fire, since person will be deleted
// by rule 2 that has a higher salience and will fire before rule 1
rule "Salience rule 1" 
    when
        Person( )
    then
        list.add( "Rule 1" );
end    

// this rule shall fire second, since rule 3 has higher salience
rule "Salience rule 2" 
    salience (p.age * 2)
    when
        p : Person( name == "bob" )
    then
        list.add( "Rule 2" );
        delete( p );
end    

// this rule shall fire first since it has the higher salience
rule "Salience rule 3" 
    salience (p.age * 2)
    when
        p : Person( name == "mic")
    then
        list.add( "Rule 3" );
        delete( p );
end    

