/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;
import org.drools.compiler.Cheesery
import org.drools.compiler.Cheese

global java.util.List list;
global Cheesery cheesery;

global String inString
global Cheese inCheese;
global Cheese outCheese;

// test Fact in Parameter
rule "rule1"
    salience 10
    when
        Cheese( this == inCheese, $type : type )
    then
        list.add( "rule1 " + $type );
end    

// test Global in Parameter
rule "rule2"
    salience 5
    when
        Cheese( $type : type == "stilton" )
    then
        list.add( "rule2 " + $type );
end  

// test Global out Parameter
rule "rule3"
    salience 3
    when
    then
        Cheese brie = new Cheese("brie", 50);
        insert( brie );
        list.add( "rule3 brie" ); 
        drools.getWorkingMemory().setGlobal("outCheese", brie);
end  

// test Global in Parameter
rule "rule4"
    salience 0
    when
    then
        list.add( "rule4 " + inString ); 
end 
