package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list;

rule delayed
    duration 100
    when
        cheese : Cheese( $type:type == "brie" )
    then
        list.add( cheese );
        insert(new Cheese("stilton", 42));
        delete(cheese);
end

rule after_delayed
    when
        cheese : Cheese( $type:type == "stilton" )
    then
        list.add( cheese );
end  
