/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler;

import java.util.LinkedList;

global java.util.LinkedList list


declare A2 extends A
    valA2 : String
end


declare B2 extends B
    valB2 : String
end


declare B11 extends B1
    valB11 : String
end


declare A
    valA : String
end


declare A1 extends A
    valA1 : String
end


declare A11 extends A1
    valA11 : String
end


declare B1 extends B
    valB1 : String
end


declare B
    valB : String
end


declare A12 extends A1
    valA12 : String
end


rule "Start"
when
then
    insert( new A12("a","a1","a12") );
end

rule "Check"
when
    $x : A12( valA == "a", valA1 == "a1", valA12 == "a12" )
then
    System.out.println($x);
    list.add($x);
end