/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.generatedbeans;

global java.util.List list;
global Cheese cg;


declare Cheese
    type: String @key()
end

declare Person
    name : String @key()
    last : String @key()
    age: int
    likes: Cheese
end

rule "simple rule"
    when
        Cheese( type == "stilton" )
    then
        list.add( new Integer(5) );
        cg.setType("nothing");
end

rule "another"
    when
        $cheese : Cheese( type == "stilton" )
         $person : Person( age== 7, likes == $cheese )
    then
        list.add( $person );
end
