/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.integrationtests;

import org.drools.compiler.InsertedObject;

rule rule1
  when
  then
    insert( new InsertedObject( "value1") );
    insert( new InsertedObject( "value2") );
end

query "assertedobjquery" ( String $value )
    assertedobj : InsertedObject( value == $value )
end 


query "assertedobjquery2" ( String $value1, String $value2 )
    assertedobj : InsertedObject( value == $value2 )
end
 