/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

import org.drools.compiler.StockTick;

global java.util.List results;

declare StockTick 
    @role( event )
    @timestamp( dateTimestamp )
    // this will override individual rule requirements
    @expires( 10m )
end

rule "Check event"
when
    $st1 : StockTick( company == "ACME" )
    $st2 : StockTick( company == "RHT", this after[0,15m] $st1 )
then
    results.add( $st1 );
end

rule "Check event2"
when
    $st1 : StockTick( company == "RHT" ) over window:time( 15m )
then
    results.add( $st1 );
end
