package org.drools;

global java.util.List results;

rule "test chars 1"
    salience 100
when
    Primitives( charPrimitive == 'a' ) 
then
    results.add( "1" );
end

rule "test chars 2"
    salience 90
when
    Primitives( $c1: charPrimitive == 'a' ) 
    Primitives( charPrimitive != $c1 )
then
    results.add( "2" );
end

rule "test chars 3"
    salience 80
when
    Primitives( $c1: stringAttribute == 'a' ) 
    Primitives( charPrimitive == $c1 )
then
    results.add( "3" );
end

