package org.drools;

global java.util.List results;

rule "test local variable in mvel consequence - same type"
    dialect "mvel"
    when
        $p : Person( $likes : likes )
    then
        Cheese c = new Cheese( $likes );
        results.add( c );
        // below should raise a duplicate local variable declaration
        Cheese c = new Cheese( "stilton" );
end


rule "test local variable in mvel consequence - different type"
    dialect "mvel"
    when
        $p : Person( $likes : likes )
    then
        Cheese c = new Cheese( $likes );
        results.add( c );
        // below should raise a duplicate local variable declaration
        String c = new String( "stilton" );
end
