/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

import org.drools.compiler.StockTick;

global java.util.List results;

declare StockTick
    @role( event )
    @timestamp( time )
end

rule "after operator on date"
    salience 10
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", dateTimestamp coincides[1s] $a.dateTimestamp )
then
    results.add( $a );
end

rule "after operator on long"
    salience 5
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", time coincides[1s] $a.time )
then
    results.add( $b );
end


rule "after operator on mixed event and date"
    salience 3
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", this coincides[1s] $a.time )
then
    results.add( $a );
end

rule "after operator on mixed date and event"
    salience 0
when
    $a : StockTick( company == "DROO" )
    $b : StockTick( company == "ACME", time coincides[1s] $a )
then
    results.add( $b );
end

