/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;
 
//we don't use the import, as class is fully qualified below
//import org.drools.integrationtests.helloworld.Message
import org.drools.compiler.Cheese;
import org.drools.compiler.Cheesery;
import java.util.List;

global List list1;
global List list2;
global List list3;
global Cheesery cheesery;

rule "test from using a global against a map lookup"
    when
        $cheese : Cheese( type == "stilton" ) from cheesery.getCheeseMap["stilton"]
    then
        list1.add( $cheese );
end
