/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.Person

global java.util.List list

// this rule shall never fire, since person will be deleted
// by rule 2 that has a higher salience and will fire before rule 1
rule "Salience rule 1" 
    when
        Person( )
    then
        list.add( "Rule 1" );
end


// this rule shall fire second, since rule 4 has higher salience but this is first in file
rule "Salience rule 2"
    salience 10
    when
        person: Person( )
    then
        list.add( "Rule 2" );
end




// this rule shall fire third, since rule 4 has higher salience  but this is second in file
rule "Salience rule 3" 
    salience 10
    when
        person: Person( )
    then
        list.add( "Rule 3" );
        delete(person);
end

// this rule shall fire first since it has the higher salience
rule "Salience rule 4"
    salience 20
    when
        Person( )
    then
        list.add( "Rule 4" );
end

