/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

function int f1(int i) {
    return f2(i+1);
}

function int f2(int i) {
    return f3(i+1);
}

function int f3(int i) {
    return f4(i+1);
}

function int f4(int i) {
    return f5(i+1);
}

function int f5(int i) {
    return f6(i+1);
}

function int f6(int i) {
    return f7(i+1);
}

function int f7(int i) {
    return f8(i+1);
}

function int f8(int i) {
    return f9(i+1);
}

function int f9(int i) {
    return f10(i+1);
}

function int f10(int i) {
    return checkHierachy( i+ 1 );
}

function int checkHierachy(int i) {
        return checkHierachyRecursive( i+ 1 );
}

function int checkHierachyRecursive(int i) {
    return i+1;
}

rule "X"
when
    eval( f1(0) == 12 )
then
    results.add( new Integer( f1(0) ) );
end