/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.I18nPerson

global java.util.List list

rule "Use garçon property"
    salience 10
    when
        p : I18nPerson( garçon != null )
    then
        list.add( "garçon" );
end

rule "Use élève property"
    salience 10
    when
        p : I18nPerson( élève != null )
    then
        list.add( "éléve" );
end

rule "Use имя property"
    salience 10
    when
        p : I18nPerson( имя != null )
    then
        list.add( "имя" );
end

rule "Use 名称 property"
    salience 10
    when
        p : I18nPerson( 名称 != null )
    then
        list.add( "名称" );
end
