package org.drools;

import java.awt.Dimension;

rule "A"
    when
      exists(x : Dimension(x_height : height) and
             y : Dimension(this!=x, height!=x_height))
           
    then
      System.out.println("A");
end

rule "B"
    when
      not(exists(x : Dimension(x_height : height) and
                 y : Dimension(this!=x, height!=x_height)))
           
    then
      System.out.println("B");
end
