/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler
 
global java.util.List results

rule "test jira jbrules 2369"
    no-loop
    when
        $a : FactA( )
        $b : FactB( )
    then
        results.add( "FIRED" );
        modify( $b ) {
            setF2( $b.getF2().intValue() + 1 )
        }
end
