/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.integrationtests.VarargsTest.B;
import org.drools.compiler.integrationtests.VarargsTest.Invoker;

global Invoker invoker;

rule invokeVarargs dialect "mvel"
when
then
    invoker.invoke("test", 2, new String("abc"), "xyz");
    invoker.invoke("test", 3, null, new B(), new B(1));
    invoker.invoke(42, new B("39"), new B(3));
end
