@Library('jenkins-pipeline-shared-libraries')_

pr_check_script = null

pipeline {
    agent {
        label 'ubuntu'
    }
    options {
        timestamps()
        timeout(time: 480, unit: 'MINUTES')
        disableConcurrentBuilds(abortPrevious: true)
    }
    environment {
        BUILDCHAIN_PROJECT = 'apache/incubator-kie-drools'
        BUILDCHAIN_CONFIG_REPO = 'incubator-kie-drools'
        BUILDCHAIN_CONFIG_FILE_PATH = '.ci/buildchain-config-pr-cdb.yaml'

        ENABLE_SONARCLOUD = 'false'
        SONAR_PROJECT_KEY = 'apache_incubator-kie-drools'
        DROOLS_BUILD_MVN_OPTS = '-Prun-code-coverage'
    }
    stages {
        stage('Initialize') {
            steps {
                script {
                    // load `pr_check.groovy` file from kogito-pipelines:main
                    dir('kogito-pipelines') {
                        checkout(githubscm.resolveRepository('incubator-kie-kogito-pipelines', 'apache', 'main', false, 'ASF_Cloudbees_Jenkins_ci-builds'))
                        pr_check_script = load 'dsl/scripts/pr_check.groovy'
                    }
                }
            }
        }
        stage('PR check') {
            steps {
                script {
                    dir('kogito-pipelines') {
                        pr_check_script.launch()
                    }
                }
            }
        }
    }
    post {
        cleanup {
            cleanWs()
        }
    }
}
