/**
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.kie.kogito.codegen.rules.singleton;
unit Singleton;

rule start
when
    /input[ value == "start"]
then
    output.set(new Datum("continue"));
end

rule contd
when
    datum: /output[ value == "continue"]
then
    modify(datum){
        setValue("updated")
    }
end

rule done
when
    /output[ value == "updated"]
then
    output.set(new Datum("done"));
end

