/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample
 
import java.util.List
import org.drools.core.common.InternalAgenda;

global List list

rule "Sample Rule" @Propagation(EAGER) ruleflow-group "Group1" salience 20
    when
        s: String()
    then
        System.out.println("Clearing ruleflow-group");
        ((InternalAgenda)drools.getWorkingMemory().getAgenda()).clearAndCancelRuleFlowGroup("Group1");
end

rule "Sample Rule 2"  @Propagation(EAGER) ruleflow-group "Group1"
    when
        s: String()
    then
        System.out.println("Adding string " + s);
        list.add(s);
end
