/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.mvel.compiler

import java.util.ArrayList
import org.drools.mvel.compiler.Cheesery
import org.drools.mvel.compiler.Cheese

global java.util.List results;

rule "shadow proxy on collections"
    when
        $list : ArrayList() from collect( Cheesery() )
    then
        Cheesery $c = (Cheesery) $list.get( 0 );
        Cheese cheese = new Cheese( "stilton", 10 );
        $c.getCheeses().add( cheese );
        results.add( cheese );
end

