/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package HelloWorld
 
//we don't use the import, as class is fully qualified below
//import org.drools.integrationtests.helloworld.Message

global java.util.List list;

rule "Hello World"
    date-effective "9-Jul-1974"
    date-expires "10-Jul-1974"
    when
        $m : org.drools.mvel.compiler.Message()
    then
        $m.setFired(true);
end
