/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.mvel.compiler

rule "Test OR with multiple evals - java"
    dialect "java"
when
    $aFact : FactA( $a : field1 == "a" )
    $bFact : FactB( $b : f1 == "b" )
    $cFact : FactC( $c : f1 == "c" )
    ( eval( $aFact.getField1().equals( $a ) ) or 
      eval( $bFact.getF1().equals( $b ) ) or
      eval( $cFact.getF1().equals( $c ) ) )
then
    // do something thrice
end

rule "Test OR with multiple evals - mvel"
    dialect "mvel"
when
    $aFact : FactA( $a : field1 == "a" )
    $bFact : FactB( $b : f1 == "b" )
    $cFact : FactC( $c : f1 == "c" )
    ( eval( $aFact.getField1().equals( $a ) ) or 
      eval( $bFact.getF1().equals( $b ) ) or
      eval( $cFact.getF1().equals( $c ) ) )
then
    // do something thrice
end