/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import org.drools.mvel.compiler.Cheese;

global java.util.List list;

rule "rule0"
    salience 10
    activation-group "activation-group-0"
    when
        Cheese( )
    then
        list.add( "rule0" );
end  

rule "rule1"
    activation-group "activation-group-0"
    when
        Cheese( )
    then
        list.add( "rule1" );
end  

rule "rule2"
    when
        Cheese( )
    then
        list.add( "rule2" );
end  

rule "rule3"
    agenda-group "agenda-group-3"
    activation-group "activation-group-3"
    when
        Cheese( )
    then
        list.add( "rule3" );
end  
