/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler

import org.drools.mvel.compiler.Order
import org.drools.mvel.compiler.Order.OrderStatus
import org.drools.mvel.compiler.OrderItem

rule "insert OrderStatus"
    ruleflow-group "process"
when
    $o : Order()
then
    insert( $o.getStatus() );
end

rule "test modify with ruleflow and subnetwork"
    ruleflow-group "process"
when
    $os : OrderStatus( active == true )
    $o : Order( status == $os, $items : itemsValues )
    Number( intValue < 10 ) from accumulate(
        OrderItem( ) from $items,
        count( 1 ) )
then
    modify( $os ) {
        setActive( false ) 
    }
end
