/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import java.util.List;
import org.drools.mvel.compiler.Person
import org.drools.mvel.compiler.Cheese

global Cheese cheese;
global Person person;
global java.util.List list;

rule "not person then cheese"
    when
        not Person()
    then
        if (list.size() < 10) {
            list.add(new Integer(0));
               insertLogical( cheese );
           }
end
rule "if cheese then person"
    when
        Cheese()
    then
        if (list.size() < 10) {
               list.add(new Integer(0));
            insertLogical( person );
           }
end
