/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import org.drools.mvel.compiler.Cheese;

global java.util.List list;

rule "test MAIN 1"
    salience  10
    when
        Cheese( )
    then
        list.add( "MAIN" );
        drools.setFocus( "group1" );
end 

rule "test MAIN 2"
    when
        Cheese( )
    then
        list.add( "MAIN" );
end 

rule "test group1 1"
    agenda-group "group1"
    when
        Cheese( )
    then
        list.add( "group1" );
end  

rule "test group1 2"
    agenda-group "group1"
    when
        Cheese( )
    then
        list.add( "group1" );
end  

rule "test group2"
    agenda-group "group2"
    when
        Cheese( )
    then
        list.add( "group2" );
end  

rule "test group3 1"
    salience 5
    agenda-group "group3"
    auto-focus true

    when
        Cheese( )
    then
        list.add( "group3" );
        drools.setFocus( "group4" );
end  

rule "test group3 2"
    agenda-group "group3"
    when
        Cheese( )
    then
        list.add( "group3" );
end  

rule "test group4"
    agenda-group "group4"
    when
        Cheese( )
    then
        list.add( "group4" );
end
