/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

//created on: Jun 2, 2011
package org.drools.mvel.compiler

rule "1. home != null"
    salience 80
    when
        Person( namedAddresses["home"] != null )
    then
        // do something
end

rule "2. not home == null"
    salience 70
    when
    	not (
        	Person( namedAddresses["home"] == null )
       	)
    then
        // do something
end

rule "3. home == null"
    salience 60
    when
        Person( namedAddresses["home"] == null )
    then
        // do something
end

rule "4. not home != null"
    salience 50
    when
    	not (
        	Person( namedAddresses["home"] != null )
       	)
    then
        // do something
end

rule "5. work != null"
    salience 40
    when
        Person( namedAddresses["work"] != null )
    then
        // do something
end

rule "6. not work == null"
    salience 30
    when
        not (
            Person( namedAddresses["work"] == null )
        )
    then
        // do something
end

rule "7. work == null"
    salience 20
    when
        Person( namedAddresses["work"] == null )
    then
        // do something
end

rule "8. not work != null"
    salience 10
    when
        not (
            Person( namedAddresses["work"] != null )
        )
    then
        // do something
end
