/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#created on: 31.10.2007
package org.drools.verifier.missingEquality

#list any import classes here.
import org.drools.base.evaluators.Operator;
import org.drools.base.evaluators.MatchesEvaluatorsDefinition;
import org.drools.base.evaluators.SetEvaluatorsDefinition;

import org.drools.verifier.components.VariableRestriction;
import org.drools.verifier.components.LiteralRestriction;
import org.drools.verifier.components.NumberRestriction;
import org.drools.verifier.report.components.MissingRange;
import org.drools.verifier.report.components.VerifierMessage;
import org.drools.verifier.report.components.Severity;
import org.drools.verifier.report.components.MessageType;
import org.drools.verifier.data.VerifierReport;

import java.util.Map;
import java.util.HashMap;



#declare any global variables here
global VerifierReport result;

#
# Informs that there are inequalities, but not equality being catered for.
#
# Type: Warning
# Dependencies: None
# Example: val != 10 when val == 10 is missing.
#
rule "Missing restriction in LiteralRestrictions"
    @verifying_scopes("knowledge-package", "decision-table")
    when
        #
        # == and !=
        #
        (
                $r :LiteralRestriction(
                    operator == Operator.EQUAL
                )
            and
                not LiteralRestriction(
                    fieldPath == $r.fieldPath,
                    operator == Operator.NOT_EQUAL,
                    patternIsNot == $r.patternIsNot,
                    valueAsString == $r.valueAsString
                )
        ) or (
                $r :LiteralRestriction(
                    operator == Operator.NOT_EQUAL
                )
            and
                not LiteralRestriction(
                    fieldPath == $r.fieldPath,
                    operator == Operator.EQUAL,
                    patternIsNot == $r.patternIsNot,
                    valueAsString == $r.valueAsString
                )
        #
        # matches and not matches
        #
        ) or (
                $r :LiteralRestriction(
                    operator == MatchesEvaluatorsDefinition.MATCHES,
                    valueAsString == $r.valueAsString
                )
            and
                not LiteralRestriction(
                    fieldPath == $r.fieldPath,
                    operator == MatchesEvaluatorsDefinition.NOT_MATCHES,
                    patternIsNot == $r.patternIsNot,
                    valueAsString == $r.valueAsString
                )
        ) or (
                $r :LiteralRestriction(
                    operator == MatchesEvaluatorsDefinition.NOT_MATCHES,
                    valueAsString == $r.valueAsString
                )
            and
                not LiteralRestriction(
                    fieldPath == $r.fieldPath,
                    operator == MatchesEvaluatorsDefinition.MATCHES,
                    patternIsNot == $r.patternIsNot,
                    valueAsString == $r.valueAsString
                )
        )
    then
        result.add( new VerifierMessage(
                                new HashMap(),
                                Severity.WARNING,
                                MessageType.MISSING_EQUALITY,
                                $r,
                                "Rule base covers " +
                                $r.getOperator().getOperatorString() + " " + $r.getValueAsString() +
                                ", but it is missing " + MissingRange.getReversedOperator( $r.getOperator() ).getOperatorString() +
                                " " + $r.getValueAsString()
                                ) );
end

#
# Informs that there are inequalities, but not equality being catered for.
#
# Type: Warning
# Dependencies: None
# Example: val != $var when val == $var is missing.
#
rule "Missing restriction in VariableRestrictions"
    @verifying_scopes("knowledge-package", "decision-table")
    when
        #
        # == and !=
        #
        (
                $r :VariableRestriction(
                    operator == Operator.EQUAL
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == Operator.NOT_EQUAL,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        ) or (
                $r :VariableRestriction(
                    operator == Operator.NOT_EQUAL
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == Operator.EQUAL,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        #
        # matches and not matches
        #
        ) or (
                $r :VariableRestriction(
                    operator == MatchesEvaluatorsDefinition.MATCHES
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == MatchesEvaluatorsDefinition.NOT_MATCHES,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        ) or (
                $r :VariableRestriction(
                    operator == MatchesEvaluatorsDefinition.NOT_MATCHES
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == MatchesEvaluatorsDefinition.MATCHES,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        #
        # memberof and not memberof
        #
        ) or (
                $r :VariableRestriction(
                    operator == SetEvaluatorsDefinition.MEMBEROF
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == SetEvaluatorsDefinition.NOT_MEMBEROF,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        ) or (
                $r :VariableRestriction(
                    operator == SetEvaluatorsDefinition.NOT_MEMBEROF
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == SetEvaluatorsDefinition.MEMBEROF,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        #
        # contains and not contains
        #
        ) or (
                $r :VariableRestriction(
                    operator == SetEvaluatorsDefinition.CONTAINS
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == SetEvaluatorsDefinition.NOT_CONTAINS,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        ) or (
                $r :VariableRestriction(
                    operator == SetEvaluatorsDefinition.NOT_CONTAINS
                )
            and
                not VariableRestriction(
                    fieldPath == $r.fieldPath,
                    operator == SetEvaluatorsDefinition.CONTAINS,
                    patternIsNot == $r.patternIsNot,
                    variable.objectTypePath == $r.variable.objectTypePath,
                    variable.objectTypeType == $r.variable.objectTypeType
                )
        )
    then
        result.add( new VerifierMessage(
                                new HashMap(),
                                Severity.WARNING,
                                MessageType.MISSING_EQUALITY,
                                $r,
                                "Rule base covers " +
                                $r.getOperator().getOperatorString() + " " + $r.getVariable().getName() +
                                ", but it is missing " + MissingRange.getReversedOperator( $r.getOperator() ).getOperatorString() +
                                " " + $r.getVariable().getName()
                                ) );
end
