/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.impact.analysis.example;

import org.drools.impact.analysis.example.domain.Order;
import org.drools.impact.analysis.example.domain.Product;

global java.util.List resultList;

rule "Inventory shortage"
when
    $o : Order(status == "Ordered")
    $p : Product( itemName == $o.itemName, quantity < 10 )
then
    System.out.println("Shortage : itemName = " + $p.getItemName());
    resultList.add($o);
end

rule "Wrong price"
when
    $o : Order()
    $p : Product( itemName == $o.itemName, itemPrice != $o.itemPrice )
then
    System.out.println("Wrong Price Warning : order.id = " + $o.getId());
    resultList.add($o);
end
