/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Person

declare trait Student
    school : String
end

rule "create student" 
    when
        $student : Person( age < 26, this not isA Student )
    then
        Student s = don( $student, Student.class );
        s.setSchool("Masaryk University");
        update( $student );
end

rule "print student"
    salience 10
    when
        student : Person( this isA Student )
    then
        // System.out.println("Person is a student: " + student);
end

rule "print school"
    when
        Student( $school : school )
    then
        // System.out.println("Student is attending " + $school);
end