[id='runtime-commands-con_{context}']
= Runtime commands in {PRODUCT}

{PRODUCT} supports runtime commands that you can send to {KIE_SERVER} for asset-related operations, such as executing all rules or inserting or retracting objects in a KIE session. The full list of supported runtime commands is located in the `org.drools.core.command.runtime` package in your {PRODUCT} instance.

In the {KIE_SERVER} REST API, you use the global `org.drools.core.command.runtime` commands or the rule-specific `org.drools.core.command.runtime.rule` commands as the request body for `POST` requests to `\http://SERVER:PORT/kie-server/services/rest/server/containers/instances/{containerId}`. For more information about using the {KIE_SERVER} REST API, see xref:kie-server-rest-api-con_kie-apis[].

In the {KIE_SERVER} Java client API, you can embed these commands in your Java application along with the relevant Java client. For example, for rule-related commands, you use the `RuleServicesClient` Java client with the embedded commands. For more information about using the {KIE_SERVER} Java client API, see xref:kie-server-java-api-con_kie-apis[].

////
[NOTE]
====
{PRODUCT_DM} commands will work only if your {KIE_SERVER} has {PRODUCT_DM} capability.
The rest of the endpoints will work only if your {KIE_SERVER} has {PRODUCT_PAM} capabilities.
Check the following URI for capabilities of your {KIE_SERVER} : __http://_SERVER:PORT_/kie-server/services/rest/server__.
====
////
