////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[releaseNotes]]
= Release Notes

This chapter lists new and noteworthy updates in OptaPlanner releases. OptaPlanner follows a 3-week release cycle.
Bug fixes and minor improvements are generally not announced, which is why some of the minor releases are not mentioned here.

For a step-by-step migration guide, see our https://www.optaplanner.org/download/upgradeRecipe/upgradeRecipe8.html[upgrade recipe].
We even provide a https://www.optaplanner.org/download/upgradeRecipe/upgradeRecipe8.html#automatic-upgrade[migration tool] to make many of these changes automatically.

For release notes on OptaPlanner 7.x and older, please visit https://www.optaplanner.org/download/releaseNotes/[Release Notes on optaplanner.org].

include::release-notes-8.adoc[]