#created on: 18.10.2007
package org.drools.verifier.consequence

#list any import classes here.
import org.drools.verifier.components.VerifierRule;
import org.drools.verifier.components.TextConsequence;
import org.drools.verifier.report.components.VerifierMessage;
import org.drools.verifier.data.VerifierReport;
import org.drools.verifier.report.components.Severity;
import org.drools.verifier.report.components.MessageType;

import java.util.Map;
import java.util.HashMap;

#declare any global variables here
global VerifierReport result;


rule "No action - possibly commented out"
	when
		$c :TextConsequence( ( text == null || matches "" ) )

		$r :VerifierRule(
			guid matches $c.ruleGuid
		)
	then
		Map<String,String> impactedRules = new HashMap<String,String>();
		impactedRules.put( $r.getGuid(), $r.getRuleName());
		
		result.add( new VerifierMessage(
								impactedRules,
								Severity.WARNING,
								MessageType.MISSING_COMPONENT,
								$r,
								$r + " has no RHS." ) );
end
