/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#created on: 18.10.2007
package org.drools.verifier.consequence

#list any import classes here.
import org.drools.verifier.components.VerifierRule;
import org.drools.verifier.components.TextConsequence;
import org.drools.verifier.report.components.VerifierMessage;
import org.drools.verifier.data.VerifierReport;
import org.drools.verifier.report.components.Severity;
import org.drools.verifier.report.components.MessageType;

import java.util.Map;
import java.util.HashMap;

#declare any global variables here
global VerifierReport result;


rule "No action - possibly commented out"
	when
		$c :TextConsequence( ( text == null || == "" ) )

		$r :VerifierRule(
			path == $c.rulePath
		)
	then
		Map<String,String> impactedRules = new HashMap<String,String>();
		impactedRules.put( $r.getPath(), $r.getName());
		
		result.add( new VerifierMessage(
								impactedRules,
								Severity.WARNING,
								MessageType.MISSING_COMPONENT,
								null,
								$r + " has no RHS." ) );
end
