/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "Or condition followed by fact"
  when
    Cheese( type == "stilton" ) or Cheese( type == "brie" )
    Person( )
  then
    results.add("Or condition followed by fact is ok");
end

rule "Fact followed by or condition"
  when
    Person( )
    Cheese( type == "stilton" ) or Cheese( type == "brie" )
  then
    results.add("Fact followed by or condition is ok");
end

rule "Single fact"
  when
    Person( )
  then
    results.add("Single fact is ok");
end

rule "Single or"
  when
    Cheese( type == "stilton" ) or Cheese( type == "brie" )
  then
    results.add("Single or is ok");
end
