/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.List results;

rule "test equality support"
    salience 10
when
    $p : PersonWithEquals( name == "bob" )
then
    $p.setName( "mark" );
    results.add( $p.getName() );
    update( $p );
end

rule "test 2"
when
    $p : PersonWithEquals( name == "bob" )
then
    results.add( "This rule should NEVER fire" );
end

