/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese;

global java.util.List list;

rule "Cheese matches stilton"
    salience 10
    when
        stilton : Cheese( type matches "[Ss]tilto[^0-9]" )
    then
        list.add( stilton );
end   

rule "Cheese not matches"
    when
        brie : Cheese( type not matches "(stil.*|mu\\w*|brie\\d|aged.*|.*prov.*)" )
    then
        list.add( brie );
end   

rule "Cheese matches with space"
    salience -10
    when
        stilton : Cheese( type matches "aged stilton" )
    then
        list.add( stilton );
end   

rule "Cheese matches with ^ and escaped s"
    salience -20
    when
        prov : Cheese( type matches "^provolone\\s*" )
    then
        list.add( prov );
end   
