//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2010.12.10 at 02:27:43 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.dmg.org/PMML-4_0", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.drools.pmml_4_0.descr;
