/*
 * Copyright 2017 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.jbpm.casemgmt.demo.insurance;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ClaimReport implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String name;
   private java.lang.String address;
   private java.util.Date accidentDate;
   private java.lang.String accidentDescription;

   private java.lang.Boolean calculated;

   private java.lang.Double amount;

   public ClaimReport()
   {
   }

   public java.lang.String getName()
   {
      return this.name;
   }

   public void setName(java.lang.String name)
   {
      this.name = name;
   }

   public java.lang.String getAddress()
   {
      return this.address;
   }

   public void setAddress(java.lang.String address)
   {
      this.address = address;
   }

   public java.util.Date getAccidentDate()
   {
      return this.accidentDate;
   }

   public void setAccidentDate(java.util.Date accidentDate)
   {
      this.accidentDate = accidentDate;
   }

   public java.lang.String getAccidentDescription()
   {
      return this.accidentDescription;
   }

   public void setAccidentDescription(java.lang.String accidentDescription)
   {
      this.accidentDescription = accidentDescription;
   }

   public java.lang.Boolean getCalculated()
   {
      return this.calculated;
   }

   public void setCalculated(java.lang.Boolean calculated)
   {
      this.calculated = calculated;
   }

   public java.lang.Double getAmount()
   {
      return this.amount;
   }

   public void setAmount(java.lang.Double amount)
   {
      this.amount = amount;
   }

   public ClaimReport(java.lang.String name, java.lang.String address,
         java.util.Date accidentDate, java.lang.String accidentDescription,
         java.lang.Boolean calculated, java.lang.Double amount)
   {
      this.name = name;
      this.address = address;
      this.accidentDate = accidentDate;
      this.accidentDescription = accidentDescription;
      this.calculated = calculated;
      this.amount = amount;
   }

}