/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.examples.circularTms;
dialect  "mvel"

rule A when
    String( this == "A" )
then
   insertLogical( "B" );
end

rule D when
    String( this == "A" )
then
   insertLogical( "D" );
end

rule B when
    String( this == "B" )
then
   insertLogical( "C" );
end


rule C when
    String( this == "C" )
then
   insertLogical( "B" );
end

rule PrintString when
    s : String( )
then
   System.out.println( s );
end

rule NotA when
    not String( this == "A" )
then
   System.out.println( "Not A" );
end

rule NotB when
    not String( this == "B" )
then
   System.out.println( "Not B" );
end

rule NotC when
    not String( this == "C" )
then
   System.out.println( "Not C" );
end

rule NotD when
    not String( this == "D" )
then
   System.out.println( "Not D" );
end


