package com.sample

import com.sample.DroolsTest.Message;

rule "Pattern redundancy 1a"
	when
		    Foo1()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 1b"
	when
		    Foo1()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 2a"
	when
		    not Foo2()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 2b"
	when
		    not Foo2()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 3a"
	when
		    exists Foo3()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 3b"
	when
		    exists Foo3()
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 4a"
	when
		    forall( Foo4() )
	then
		System.out.println( "Test" );
end

rule "Pattern redundancy 4b"
	when
		    forall( Foo4() )
	then
		System.out.println( "Test" );
end
