/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.jboss.qa.brms.persistence


rule "TestInserted"
	no-loop
	when
		$person : Person ( )
	then
		#consequences
end

rule "TestInsert"
	no-loop
	when
		Person( name == "insert", $val : id )
	then
		insert( new Message( Integer.toString($val) ) );
end

rule "TestUpdate"
	no-loop
	when
		Person( name == "update", $val : id )
		$msg : Message ( message == "toBeUpdated" )

	then
		$msg.setMessage( Integer.toString($val) );
		update( $msg );
end

rule "TestRetract"
	when
		Person( name == "retract" )
		$msg : Message ( message == "toBeRetracted" )

	then
		retract( $msg );
end