[[conferenceScheduling]]
= Conference Scheduling


[[conferenceSchedulingProblemDescription]]
== Problem Description

Assign each conference talk to a timeslot and a room.
Timeslots can overlap. Read/write to/from an `*.xlsx` file that can be edited with LibreOffice or Excel too.

Hard constraints:

* Talk type of timeslot: The type of a talk must match the timeslot's talk type.
* Room unavailable timeslots: A talk's room must be available during the talk's timeslot.
* Room conflict: Two talks can't use the same room during overlapping timeslots.
* Speaker unavailable timeslots: Every talk's speaker must be available during the talk's timeslot.
* Speaker conflict: Two talks can't share a speaker during overlapping timeslots.
* Speaker required timeslot tag: If a speaker has a required timeslot tag, then all his/her tasks must be assigned to a timeslot with that tag.
* Talk required timeslot tag: If a talk has a required timeslot tag, then it must be assigned to a timeslot with that tag.
* Speaker required room tag: If a speaker has a required room tag, then all his/her tasks must be assigned to a room with that tag.
* Talk required room tag: If a talk has a required room tag, then it must be assigned to a room with that tag.

Soft constraints:

* Theme conflict: Minimize the number of talks that share a same theme tag during overlapping timeslots.
* Sector conflict: Minimize the number of talks that share a same sector tag during overlapping timeslots.
* Language diversity: For every timeslot, maximize the number of talks with different languages.
* Speaker preferred timeslot tag: If a speaker has a preferred timeslot tag, then all his/her tasks should be assigned to a timeslot with that tag.
* Talk preferred timeslot tag: If a talk has a preferred timeslot tag, then it should be assigned to a timeslot with that tag.
* Speaker preferred room tag: If a speaker has a preferred room tag, then all his/her tasks should be assigned to a room with that tag.
* Talk preferred room tag: If a talk has a preferred room tag, then it should be assigned to a room with that tag.


[[conferenceSchedulingProblemSize]]
== Problem Size

[source,options="nowrap"]
----
18talks-6timeslots-5rooms    has  18 talks,  6 timeslots and  5 rooms with a search space of  10^26.
36talks-12timeslots-5rooms   has  36 talks, 12 timeslots and  5 rooms with a search space of  10^64.
72talks-12timeslots-10rooms  has  72 talks, 12 timeslots and 10 rooms with a search space of 10^149.
108talks-18timeslots-10rooms has 108 talks, 18 timeslots and 10 rooms with a search space of 10^243.
216talks-18timeslots-20rooms has 216 talks, 18 timeslots and 20 rooms with a search space of 10^552.
----
