package org.drools.examples
 
import org.drools.examples.HelloWorldExample.Message;
 
rule "Hello World"
    dialect "mvel"
	when
		m : Message( status == Message.HELLO, message : message )
	then
	System.out.println( message ); 
	modify ( m ) { message = "Goodbyte cruel world",
	               status = Message.GOODBYE };
end

rule "Good Bye"
    dialect "java"
	when
		Message( status == Message.GOODBYE, message : message )
	then
		System.out.println( message ); 
end