/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples
 
dialect "mvel"

import org.drools.examples.ShoppingExample.Customer
import org.drools.examples.ShoppingExample.Product
import org.drools.examples.ShoppingExample.Purchase
import org.drools.examples.ShoppingExample.Discount
 
rule "Purchase notification"
    salience 10

	when
		$c : Customer()
		$p : Purchase( customer == $c)	    
	then
	    System.out.println( "Customer " + $c.name + " just purchased " + $p.product.name );
end	 
 
rule "Discount removed notification"
	when
	    $c : Customer()
		not Discount( customer == $c )
	then
		$c.discount = 0;
		System.out.println( "Customer " + $c.name + " now has a discount of " + $c.discount );
end

rule "Discount awarded notification"
	when
	    $c : Customer()
		$d : Discount( customer == $c )
	then
		System.out.println( "Customer " + $c.name + " now has a discount of " + $d.amount );
end

rule "Apply 10% discount if total purcahses is over 100"			
	no-loop true	
	dialect "java"
    when
		$c : Customer()
		$i : Double(doubleValue  > 100) from accumulate ( Purchase( customer == $c, $price : product.price ), 
		                                                            sum( $price ) )
    then
  		$c.setDiscount( 10 );
		insertLogical( new Discount($c, 10) );	
		System.out.println( "Customer " + $c.getName() + " now has a shopping total of " + $i );
end