/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

global java.util.Map results;

rule "Duplicate Variable testing"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   Cheese( $type : type == "stilton", $price : price ) or
   Cheese( $type : type == "brie", $price : price )
 then
   results.put( $type, new Integer( $price ) );
end

rule "Duplicate Variable testing 2"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   $cheese : Cheese( type == "stilton", $price : price ) or
   $cheese : Cheese( type == "brie", $price : price )
 then
   results.put( $cheese, new Integer( $price ) );
end

rule "Duplicate Variable testing 3"
 when
   // there should be no problem since each variable 
   // is in a different logical branch
   Cheese( $type : type == "stilton", $price : price ) or
   ( Cheese( $type : type == "brie", $price : price ) and Person( name == "bob", likes == $type ) )
 then
   results.put( "test3"+$type, new Integer( $price ) );
end
