/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

rule "Accumulate 1"
when
     accumulate( Cheese( $price : price );
                 $a1 : average( $price ),
                 $m1 : min( $price ),
                 $M1 : max( $price ); // binds are optional, but it makes no sense to not have a binding in this case
                 $a1 > 10 && $M1 <= 100,
                 $m1 == 5 // inline evals
        )
then
     // do something
end

