/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package test.dialect.rule.end.package.mine;

global java.lang.String rule;

import com.dialect.something.SomeClass

function boolean test() {
    return true;
}

rule type1
  when
    $id : Something( duration == "foo")
  then
      The.method();
      attributes;
      rule;
      package;
end

