/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.examples.buspass.good;

import org.drools.examples.buspass.Person;
import org.drools.examples.buspass.IsChild;
import org.drools.examples.buspass.IsAdult;

rule IsChildPolicy when
    p : Person( age < 16 )
then
    insertLogical( new IsChild( p ) );
end

rule IsAdultPolicy when
    p : Person( age >= 16 )
then
    insertLogical( new IsAdult( p ) );
end

