/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.functional.parser

declare Event
    @role( event )
    @expires( 1d )
    id : int @key

    eventTimestamp : java.util.Date @timestamp
    eventDuration : long @duration
end

rule "TestEntryPoint"
    when
        Event() from entry-point EventStream
    then
        //consequences
end

rule "TestDuration"
    duration( 1s )
    when
        Event() from entry-point EventStream
    then
        //consequences
end

rule "TestTimeWindow"
    when
        Event() over window:time(1h) from entry-point EventStream
    then
        //consequences
end

rule "TestLengthWindow"
    when
        Event() over window:length(1) from entry-point EventStream
    then
        //consequences
end