/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.functional.parser

declare Person
    id : int @key
    name : String
end

declare Employee extends Person
    salary : double
end

rule "TestStr1"
    when
        String( this str[startsWith] "foo")
    then
        //consequences
end

rule "TestStr2"
    when
        String( this str[endsWith] "bar")
    then
        //consequences
end

rule "TestStr3"
    when
        String( this str[length] 6)
    then
        //consequences
end

rule "TestIn"
    when
        $s : String(this == "foobar")
        String( this in ( "foo", "bar", $s ) )
    then
        //consequences
end

rule "TestEmployee"
    when
        Employee ( name == "employee", salary > 99.96 )
    then
        //consequences
end

rule "TestConstructors"
    when
        Object()
    then
        Person p1 = new Person();
        Person p2 = new Person(9);
        Person p3 = new Person(99, "myname");

        Employee e1 = new Employee();
        Employee e2 = new Employee(9);
        Employee e3 = new Employee(99, "myname", 100.00);

        Person pe = new Employee();
end