/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

template header
name
field
fieldLower
fieldUpper
price
tastes

package org.drools.testcoverage.functional;

import  org.drools.testcoverage.functional.TemplatesTest.Vegetable;
import  org.drools.testcoverage.functional.TemplatesTest.Taste;

global java.util.List list;

template "appropriateToBuy"

rule "is appropriate @{row.rowNumber}"
	when
	    Vegetable( $name : name == "@{name}", $field : @{field} >= @{fieldLower} && <= @{fieldUpper}, $price : price <= @{price}, $taste : taste @{tastes} )
	then
	    list.add( $name );
end

end template

  template "isOfAKind"

rule "is kind @{row.rowNumber}"
    when
        Vegetable( $name : name == "@{name}" )
    then
        list.add( $name );
end

end template

template "goodPrice"

rule "is cheap @{row.rowNumber}"
    when
        Vegetable( $name : name, $price : price <= @{price} )
    then
        list.add( $name );
end

end template


template "kindShouldBeThrownAway"

rule "isn't good @{row.rowNumber}"
    when
        Vegetable( $name : name == "@{name}", $taste : taste @{tastes} )
    then
        list.add( $name );
end

end template

template "isBigEnought"

rule "is big enough @{row.rowNumber}"
    when
        Vegetable( $name : name, $field : @{field} >= @{fieldLower} )
    then
        list.add( $name );
end

end template

template "isSmallEnough"

rule "is small enough @{row.rowNumber}"
    when
        Vegetable( $name : name, $field : @{field} <= @{fieldUpper})
    then
        list.add( $name );
end

  end template

template "generalThrowAway"

rule "is bad @{row.rowNumber}"
    when
        Vegetable( $name : name, $taste : taste @{tastes} )
    then
        list.add( $name );
end

end template

template "goodPriceAndSize"

rule "is of good price and size @{row.rowNumber}"
    when
        Vegetable( $name : name == "@{name}", $field : @{field} >= @{fieldLower} && <= @{fieldUpper}, $price : price <= @{price} )
    then
        list.add( $name );
end

end template

template "tastyKind"

rule "is a tasty kind @{row.rowNumber}"
    when
        Vegetable( $name : name == "@{name}", $taste : taste @{tastes} )
    then
        list.add( $name );
end

end template

        template "rightSizeAndTaste"

rule "is of right size and taste @{row.rowNumber}"
    when
        Vegetable( $name : name == "@{name}", $field : @{field} >= @{fieldLower} && <= @{fieldUpper}, $taste : taste @{tastes} )
    then
        list.add( $name );
end

end template