/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/
@startuml
'https://plantuml.com/component-diagram

node Drools_repo {
  [Rule eng.] <--  [Efesto]
  [Decision eng.] <--  [Efesto]
  [Prediction eng.] <--  [Efesto]
}

note bottom of Drools_repo
    * Having both engines and Efesto code in same
    repository force dependency on snapshots,
    even downward (e.g. Kogito), because the repo
    is built atomically
    * This situation should be transitory
end note

[Workflow eng.] <--  [Efesto]
[? eng.] <--  [Efesto]

node "Kogito repo" {
  component Kogito [
    * REST Endpoints
    * Platform specific infra requirements
    ** Messaging
    ** Audit
    ** Persistence
    ** etc…
  ]
}

[Efesto] <-- [Kogito]

node "Serverless Workflow repo" {
  component Serverless_Workflow [
    * Spec Implementation
    * Specific set of cloud native reqs
    * Java Framework opinionated
    * Kubernetes Deployment Interface
   ]
}

[Workflow eng.] <... [Serverless_Workflow]

[Kogito] <- [Serverless_Workflow]



@enduml