/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class node4 as "CompositeKnowledgeBuilderImpl(KnowledgeBuilderImpl)"
class ResourceBuilder
class ResourceDescr
class ResourceToPkgDescrMapper
class node18 as "add(Resource)"
class node7 as "add(Resource,ResourceType)"
class node11 as "add(Resource,ResourceType,ResourceChangeSet)"
class node21 as "add(Resource,ResourceType,ResourceConfiguration)"
class node0 as "add(Resource,ResourceType,ResourceConfiguration,ResourceChangeSet)"
class node3 as "build()"
class node15 as "build(boolean)"
class node10 as "buildAssemblerResourcesAfterRules()"
class node25 as "buildAssemblerResourcesBeforeRules()"
class buildException
class node20 as "buildPackageDescr()"
class node9 as "buildProcesses()"
class node24 as "buildResource(Map<String, CompositePackageDescr>,ResourceType,ResourceToPkgDescrMapper)"
class node8 as "buildResourceType(ResourceBuilder,ResourceType)"
class node23 as "buildResources()"
class currentType
class node17 as "descrToResourceWithConfiguration(ResourceDescr)"
class node5 as "getResources()"
class kBuilder
class node14 as "makeCompositePackageDescr(Resource,PackageDescr)"
class node1 as "registerPackageDescr(ResourceDescr,Map<String, CompositePackageDescr>,Resource,PackageDescr)"
class resourcesByType
class node26 as "type(ResourceType)"

node4                     <-[#595959,plain]-  kBuilder                 
ResourceBuilder           <-[#595959,plain]-  ResourceDescr            
ResourceToPkgDescrMapper  <-[#595959,plain]-  ResourceDescr            
node18                    <-[#595959,plain]-  node7                    
node18                    <-[#595959,plain]-  currentType              
node7                     <-[#595959,plain]-  node21                   
node11                    <-[#595959,plain]-  node0                    
node21                    <-[#595959,plain]-  node0                    
node0                     <-[#595959,plain]-  ResourceDescr            
node0                     <-[#595959,plain]-  resourcesByType          
node3                     <-[#595959,plain]-  node15                   
node15                    <-[#595959,plain]-  node10                   
node15                    <-[#595959,plain]-  node25                   
node15                    <-[#595959,plain]-  buildException           
node15                    <-[#595959,plain]-  node20                   
node15                    <-[#595959,plain]-  node9                    
node15                    <-[#595959,plain]-  node23                   
node15                    <-[#595959,plain]-  node5                    
node15                    <-[#595959,plain]-  kBuilder                 
node15                    <-[#595959,plain]-  resourcesByType          
node10                    <-[#595959,plain]-  ResourceDescr            
node10                    <-[#595959,plain]-  kBuilder                 
node10                    <-[#595959,plain]-  resourcesByType          
node25                    <-[#595959,plain]-  ResourceDescr            
node25                    <-[#595959,plain]-  buildException           
node25                    <-[#595959,plain]-  kBuilder                 
node25                    <-[#595959,plain]-  resourcesByType          
node20                    <-[#595959,plain]-  ResourceToPkgDescrMapper 
node20                    <-[#595959,plain]-  node24                   
node20                    <-[#595959,plain]-  resourcesByType          
node9                     <-[#595959,plain]-  ResourceBuilder          
node9                     <-[#595959,plain]-  node8                    
node24                    <-[#595959,plain]-  ResourceDescr            
node24                    <-[#595959,plain]-  ResourceToPkgDescrMapper 
node24                    <-[#595959,plain]-  buildException           
node24                    <-[#595959,plain]-  kBuilder                 
node24                    <-[#595959,plain]-  node1                    
node24                    <-[#595959,plain]-  resourcesByType          
node8                     <-[#595959,plain]-  ResourceBuilder          
node8                     <-[#595959,plain]-  ResourceDescr            
node8                     <-[#595959,plain]-  buildException           
node8                     <-[#595959,plain]-  kBuilder                 
node8                     <-[#595959,plain]-  resourcesByType          
node23                    <-[#595959,plain]-  ResourceBuilder          
node23                    <-[#595959,plain]-  node8                    
node17                    <-[#595959,plain]-  ResourceDescr            
node5                     <-[#595959,plain]-  ResourceDescr            
node5                     <-[#595959,plain]-  resourcesByType          
node1                     <-[#595959,plain]-  ResourceDescr            
node1                     <-[#595959,plain]-  node14                   
resourcesByType           <-[#595959,dashed]-  ResourceDescr            
node26                    <-[#595959,plain]-  currentType              
@enduml
