/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AbstractEfestoCompilationOutput
class AbstractEfestoFinalCompilationOutput
interface EfestoClassesContainer << interface >>
interface EfestoCompilationOutput << interface >>
interface EfestoFinalOutput << interface >>
class EfestoFinalOutputClassesContainer
class EfestoIntermediateOutput
class EfestoIntermediateOutputClassesContainer

AbstractEfestoCompilationOutput           -[#008200,dashed]-^  EfestoCompilationOutput
AbstractEfestoFinalCompilationOutput      -[#000082,plain]-^  AbstractEfestoCompilationOutput
AbstractEfestoFinalCompilationOutput      -[#008200,dashed]-^  EfestoFinalOutput
EfestoFinalOutput                         -[#008200,plain]-^  EfestoCompilationOutput
EfestoFinalOutputClassesContainer         -[#000082,plain]-^  AbstractEfestoFinalCompilationOutput
EfestoFinalOutputClassesContainer         -[#008200,dashed]-^  EfestoClassesContainer
EfestoIntermediateOutput                  -[#000082,plain]-^  AbstractEfestoCompilationOutput
EfestoIntermediateOutputClassesContainer  -[#008200,dashed]-^  EfestoClassesContainer
EfestoIntermediateOutputClassesContainer  -[#000082,plain]-^  EfestoIntermediateOutput
@enduml
