/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
'https://plantuml.com/sequence-diagram


title On the fly compilation and execution of Mining model with a drl-related one class


actor Input_provider
note over Input_provider: Any service requiring evaluation with the ability of on-the-fly compilation (e.g. KieService)

Input_provider -> Runtime_manager: evaluate (MiningModel input)
Runtime_manager -> Input_provider: no result

Input_provider -> Compilation_Manager: compile (MiningModel)
Compilation_Manager --> PMML_Compiler: compile (MiningModel)
PMML_Compiler --> MiningModel_compiler: compile (MiningModel )
MiningModel_compiler --> Regression_compiler: compile (RegressionModel)
Regression_compiler --> MiningModel_compiler: generatedClasses
MiningModel_compiler --> Tree_compiler: compile (TreeModel )
Tree_compiler --> Compilation_Manager: compile (PackageDescr)
Compilation_Manager --> DrlCompiler: compile (PackageDescr)
DrlCompiler --> Compilation_Manager: generatedClasses
Compilation_Manager --> Tree_compiler: generatedClasses
Tree_compiler --> MiningModel_compiler: generatedClasses
MiningModel_compiler --> Compilation_Manager: generatedClasses
Compilation_Manager --> Input_provider: done

Input_provider -> Runtime_manager: evaluate (input)
Runtime_manager -> PMML_Runtime: evaluate (input)
PMML_Runtime --> MiningModel_runtime: evaluate (input)
MiningModel_runtime --> Regression_runtime: evaluate (input)
Regression_runtime --> MiningModel_runtime: result
MiningModel_runtime --> Tree_runtime: evaluate (input)
Tree_runtime --> Runtime_manager: evaluate (input)
Runtime_manager --> DrlRuntime: evaluate (input)
DrlRuntime --> Runtime_manager: result
Runtime_manager --> Tree_runtime: result
Tree_runtime --> MiningModel_runtime: wrappedResult
MiningModel_runtime --> Runtime_manager: result
Runtime_manager --> Input_provider: result



@enduml