/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
'https://plantuml.com/sequence-diagram


title Primary Resource directly compiled to class

autonumber 1
actor Resource_provider
note over Resource_provider: Any service requiring codegen/class compilation (e.g. Kie Maven Plugin, Kogito, KieLoaderService)

Resource_provider -> Compilation_Manager: compile (Primary Resource)
Compilation_Manager --> Compilation_Manager: Find specific KieCompilerService (Primary Resource)
Compilation_Manager --> KieCompilerService: process (Primary Resource)
KieCompilerService --> Compilation_Manager: Compiled Class
Compilation_Manager -> Resource_provider: IndexFile
Resource_provider -> Resource_provider: Consume IndexFile

newpage Primary Resource compiled to Intermediate Resource

autonumber 1
note over Resource_provider: Any service requiring codegen/class compilation (e.g. Kie Maven Plugin, Kogito, KieLoaderService)

Resource_provider -> Compilation_Manager: compile (Primary Resource)
Compilation_Manager --> Compilation_Manager: Find specific KieCompilerService (Primary Resource)
Compilation_Manager --> KieCompilerService: process (Primary Resource)
KieCompilerService --> Compilation_Manager: Intermediate Resource
Compilation_Manager --> Compilation_Manager: Find specific KieCompilerService (Intermediate Resource)
Compilation_Manager --> KieCompilerService: process (Intermediate Resource)
KieCompilerService --> Compilation_Manager: Compiled Class
Compilation_Manager -> Resource_provider: IndexFile
Resource_provider -> Resource_provider: Consume IndexFile

@enduml