/'
  Licensed to the Apache Software Foundation (ASF) under one
  or more contributor license agreements.  See the NOTICE file
  distributed with this work for additional information
  regarding copyright ownership.  The ASF licenses this file
  to you under the Apache License, Version 2.0 (the
  "License"); you may not use this file except in compliance
  with the License.  You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

  Unless required by applicable law or agreed to in writing,
  software distributed under the License is distributed on an
  "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
  KIND, either express or implied.  See the License for the
  specific language governing permissions and limitations
  under the License.
'/

@startuml
participant Actor
Actor -> PMMLAssemblerService : addResourceAfterRules
activate PMMLAssemblerService
PMMLAssemblerService -> PMMLImplementationsUtil : isjPMMLAvailableToClassLoader
activate PMMLImplementationsUtil
PMMLImplementationsUtil --> PMMLAssemblerService
deactivate PMMLImplementationsUtil
PMMLAssemblerService -> PMMLCompilerService : getKiePMMLModelsFromResourceWithSources
activate PMMLCompilerService
PMMLCompilerService -> KnowledgeBuilderImpl : getCachedOrCreate
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> PMMLCompilerService
deactivate KnowledgeBuilderImpl
PMMLCompilerService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService --> PMMLCompilerService
deactivate PMMLAssemblerService
PMMLCompilerService -> PMMLCompilerService : getFileName
activate PMMLCompilerService
PMMLCompilerService -> PortablePath : of
activate PortablePath
PortablePath -> PortablePath : of
activate PortablePath
PortablePath -> PortablePath : normalizePath
activate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
create PortablePath
PortablePath -> PortablePath : new
activate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
PortablePath --> PMMLCompilerService
deactivate PortablePath
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
create HasKnowledgeBuilderImpl
PMMLCompilerService -> HasKnowledgeBuilderImpl : new
activate HasKnowledgeBuilderImpl
HasKnowledgeBuilderImpl --> PMMLCompilerService
deactivate HasKnowledgeBuilderImpl
PMMLCompilerService -> PMMLCompiler : getKiePMMLModelsWithSources
activate PMMLCompiler
PMMLCompiler -> PMMLCompilerImpl : getKiePMMLModelsWithSources
activate PMMLCompilerImpl
PMMLCompilerImpl -> KiePMMLUtil : load
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingModelName
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingOutputFieldDataType
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingOutputFieldDataType
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingMiningTargetField
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getMiningTargetFields
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getTargetDataField
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getTargetMiningField
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : correctTargetFields
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingPredictedOutputFieldTarget
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getMiningTargetFields
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectMiningModel
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectSegmentId
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingSegmentModelName
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingTargetFieldInSegment
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingPredictedOutputFieldTarget
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectMiningModel
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> PMMLCompilerImpl
deactivate KiePMMLUtil
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLCompilerImpl
deactivate KiePMMLModelUtils
PMMLCompilerImpl -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLCompilerImpl
deactivate KiePMMLModelUtils
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : getModelsWithSources
activate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl -> CommonCompilationDTO : fromGeneratedPackageNameAndFields
activate CommonCompilationDTO
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> CommonCompilationDTO
deactivate KiePMMLModelUtils
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> ModelUtils : getFieldsFromDataDictionaryTransformationDictionaryAndModel
activate ModelUtils
ModelUtils -> ModelUtils : getFieldsFromDataDictionaryAndTransformationDictionary
activate ModelUtils
ModelUtils --> ModelUtils
deactivate ModelUtils
ModelUtils --> CommonCompilationDTO
deactivate ModelUtils
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> PMML_MODEL : byName
activate PMML_MODEL
PMML_MODEL --> CommonCompilationDTO
deactivate PMML_MODEL
CommonCompilationDTO -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> CommonCompilationDTO
deactivate KiePMMLModelUtils
CommonCompilationDTO -> ModelUtils : getTargetFieldName
activate ModelUtils
ModelUtils --> CommonCompilationDTO
deactivate ModelUtils
CommonCompilationDTO -> CommonCompilationDTO : λ→
activate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> PMMLCompilerImpl
deactivate CommonCompilationDTO
PMMLCompilerImpl -> KiePMMLModelRetriever : getFromCommonDataAndTransformationDictionaryAndModelWithSources
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> KiePMMLModelRetriever : λ→
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> ModelImplementationProvider : getKiePMMLModelWithSources
activate ModelImplementationProvider
ModelImplementationProvider -> ModelImplementationProvider : getSourcesMap
activate ModelImplementationProvider
ModelImplementationProvider --> ModelImplementationProvider
deactivate ModelImplementationProvider
create KiePMMLModelWithSources
ModelImplementationProvider -> KiePMMLModelWithSources : new
activate KiePMMLModelWithSources
create KiePMMLModel
KiePMMLModelWithSources -> KiePMMLModel : new
activate KiePMMLModel
create AbstractKiePMMLComponent
KiePMMLModel -> AbstractKiePMMLComponent : new
activate AbstractKiePMMLComponent
AbstractKiePMMLComponent --> KiePMMLModel
deactivate AbstractKiePMMLComponent
KiePMMLModel --> KiePMMLModelWithSources
deactivate KiePMMLModel
KiePMMLModelWithSources --> ModelImplementationProvider
deactivate KiePMMLModelWithSources
ModelImplementationProvider --> KiePMMLModelRetriever
deactivate ModelImplementationProvider
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever -> KiePMMLModelRetriever : getFromCommonDataAndTransformationDictionaryAndModelWithSourcesCommon
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> PMML_MODEL : byName
activate PMML_MODEL
PMML_MODEL -> PMML_MODEL : λ→
activate PMML_MODEL
PMML_MODEL --> PMML_MODEL
deactivate PMML_MODEL
PMML_MODEL -> PMML_MODEL : λ→
activate PMML_MODEL
create KieEnumException
PMML_MODEL -> KieEnumException : new
activate KieEnumException
create KiePMMLInternalException
KieEnumException -> KiePMMLInternalException : new
activate KiePMMLInternalException
KiePMMLInternalException --> KieEnumException
deactivate KiePMMLInternalException
KieEnumException --> PMML_MODEL
deactivate KieEnumException
PMML_MODEL --> PMML_MODEL
deactivate PMML_MODEL
PMML_MODEL --> KiePMMLModelRetriever
deactivate PMML_MODEL
KiePMMLModelRetriever -> KiePMMLModelRetriever : getModelImplementationProviderStream
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> ModelImplementationProviderFinder : getImplementations
activate ModelImplementationProviderFinder
ModelImplementationProviderFinder -> ModelImplementationProviderFinderImpl : getImplementations
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl -> ModelImplementationProviderFinderImpl : getProviders
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinderImpl
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl -> ModelImplementationProviderFinderImpl : λ→
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinderImpl
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinder
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinder --> KiePMMLModelRetriever
deactivate ModelImplementationProviderFinder
KiePMMLModelRetriever -> KiePMMLModelRetriever : λ→
activate KiePMMLModelRetriever
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever --> PMMLCompilerImpl
deactivate KiePMMLModelRetriever
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : getHasSourceMap
activate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLCompilerImpl
deactivate KiePMMLModelUtils
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
create KiePMMLException
PMMLCompilerImpl -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerImpl
deactivate KiePMMLException
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
create KiePMMLException
PMMLCompilerImpl -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerImpl
deactivate KiePMMLException
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
create KiePMMLException
PMMLCompilerImpl -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerImpl
deactivate KiePMMLException
PMMLCompilerImpl -> KiePMMLFactoryFactory : getFactorySourceCode
activate KiePMMLFactoryFactory
KiePMMLFactoryFactory -> JavaParserUtils : getFromFileName
activate JavaParserUtils
create KiePMMLInternalException
JavaParserUtils -> KiePMMLInternalException : new
activate KiePMMLInternalException
KiePMMLInternalException --> JavaParserUtils
deactivate KiePMMLInternalException
create ExternalException
JavaParserUtils -> ExternalException : new
activate ExternalException
ExternalException --> JavaParserUtils
deactivate ExternalException
JavaParserUtils --> KiePMMLFactoryFactory
deactivate JavaParserUtils
KiePMMLFactoryFactory -> KiePMMLFactoryFactory : λ→
activate KiePMMLFactoryFactory
KiePMMLFactoryFactory --> KiePMMLFactoryFactory
deactivate KiePMMLFactoryFactory
KiePMMLFactoryFactory -> KiePMMLFactoryFactory : λ→
activate KiePMMLFactoryFactory
create KiePMMLException
KiePMMLFactoryFactory -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> KiePMMLFactoryFactory
deactivate KiePMMLException
KiePMMLFactoryFactory --> KiePMMLFactoryFactory
deactivate KiePMMLFactoryFactory
KiePMMLFactoryFactory -> KiePMMLFactoryFactory : populateKiePmmlFields
activate KiePMMLFactoryFactory
KiePMMLFactoryFactory -> KiePMMLFactoryFactory : λ→
activate KiePMMLFactoryFactory
KiePMMLFactoryFactory -> KiePMMLFactoryFactory : getInstantiationExpression
activate KiePMMLFactoryFactory
KiePMMLFactoryFactory --> KiePMMLFactoryFactory
deactivate KiePMMLFactoryFactory
KiePMMLFactoryFactory --> KiePMMLFactoryFactory
deactivate KiePMMLFactoryFactory
KiePMMLFactoryFactory --> KiePMMLFactoryFactory
deactivate KiePMMLFactoryFactory
KiePMMLFactoryFactory --> PMMLCompilerImpl
deactivate KiePMMLFactoryFactory
create KiePMMLFactoryModel
PMMLCompilerImpl -> KiePMMLFactoryModel : new
activate KiePMMLFactoryModel
create KiePMMLModel
KiePMMLFactoryModel -> KiePMMLModel : new
activate KiePMMLModel
create AbstractKiePMMLComponent
KiePMMLModel -> AbstractKiePMMLComponent : new
activate AbstractKiePMMLComponent
AbstractKiePMMLComponent --> KiePMMLModel
deactivate AbstractKiePMMLComponent
KiePMMLModel --> KiePMMLFactoryModel
deactivate KiePMMLModel
KiePMMLFactoryModel --> PMMLCompilerImpl
deactivate KiePMMLFactoryModel
create KiePMMLException
PMMLCompilerImpl -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerImpl
deactivate KiePMMLException
create ExternalException
PMMLCompilerImpl -> ExternalException : new
activate ExternalException
ExternalException --> PMMLCompilerImpl
deactivate ExternalException
PMMLCompilerImpl --> PMMLCompiler
deactivate PMMLCompilerImpl
PMMLCompiler --> PMMLCompilerService
deactivate PMMLCompiler
PMMLCompilerService -> PMMLCompilerService : populateWithPMMLRuleMappers
activate PMMLCompilerService
PMMLCompilerService -> PMMLCompilerService : addPMMLRuleMapper
activate PMMLCompilerService
create KiePMMLException
PMMLCompilerService -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerService
deactivate KiePMMLException
PMMLCompilerService -> PMMLRuleMapperFactory : getPMMLRuleMapperSource
activate PMMLRuleMapperFactory
PMMLRuleMapperFactory -> JavaParserUtils : getKiePMMLModelCompilationUnit
activate JavaParserUtils
JavaParserUtils --> PMMLRuleMapperFactory
deactivate JavaParserUtils
PMMLRuleMapperFactory -> PMMLRuleMapperFactory : λ→
activate PMMLRuleMapperFactory
PMMLRuleMapperFactory --> PMMLRuleMapperFactory
deactivate PMMLRuleMapperFactory
PMMLRuleMapperFactory --> PMMLCompilerService
deactivate PMMLRuleMapperFactory
PMMLCompilerService -> HasSourcesMap : addSourceMap
activate HasSourcesMap
HasSourcesMap --> PMMLCompilerService
deactivate HasSourcesMap
PMMLCompilerService -> PMMLCompilerService : addPMMLRuleMapper
activate PMMLCompilerService
create KiePMMLException
PMMLCompilerService -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerService
deactivate KiePMMLException
PMMLCompilerService -> PMMLRuleMapperFactory : getPMMLRuleMapperSource
activate PMMLRuleMapperFactory
PMMLRuleMapperFactory --> PMMLCompilerService
deactivate PMMLRuleMapperFactory
PMMLCompilerService -> HasSourcesMap : addSourceMap
activate HasSourcesMap
HasSourcesMap --> PMMLCompilerService
deactivate HasSourcesMap
PMMLCompilerService -> PMMLCompilerService : addPMMLRuleMapper
activate PMMLCompilerService
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
PMMLCompilerService -> PMMLCompilerService : addPMMLRuleMappers
activate PMMLCompilerService
create KiePMMLException
PMMLCompilerService -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerService
deactivate KiePMMLException
PMMLCompilerService -> PMMLRuleMappersFactory : getPMMLRuleMappersSource
activate PMMLRuleMappersFactory
PMMLRuleMappersFactory -> JavaParserUtils : getKiePMMLModelCompilationUnit
activate JavaParserUtils
JavaParserUtils --> PMMLRuleMappersFactory
deactivate JavaParserUtils
PMMLRuleMappersFactory -> PMMLRuleMappersFactory : λ→
activate PMMLRuleMappersFactory
PMMLRuleMappersFactory --> PMMLRuleMappersFactory
deactivate PMMLRuleMappersFactory
PMMLRuleMappersFactory -> PMMLRuleMappersFactory : λ→
activate PMMLRuleMappersFactory
PMMLRuleMappersFactory --> PMMLRuleMappersFactory
deactivate PMMLRuleMappersFactory
PMMLRuleMappersFactory --> PMMLCompilerService
deactivate PMMLRuleMappersFactory
PMMLCompilerService -> HasSourcesMap : addSourceMap
activate HasSourcesMap
HasSourcesMap --> PMMLCompilerService
deactivate HasSourcesMap
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
create ExternalException
PMMLCompilerService -> ExternalException : new
activate ExternalException
ExternalException --> PMMLCompilerService
deactivate ExternalException
PMMLCompilerService --> PMMLAssemblerService
deactivate PMMLCompilerService
PMMLAssemblerService -> PMMLAssemblerService : addModels
activate PMMLAssemblerService
create PackageDescr
PMMLAssemblerService -> PackageDescr : new
activate PackageDescr
create PackageDescr
PackageDescr -> PackageDescr : new
activate PackageDescr
PackageDescr --> PackageDescr
deactivate PackageDescr
PackageDescr --> PMMLAssemblerService
deactivate PackageDescr
PMMLAssemblerService -> KnowledgeBuilderImpl : getOrCreatePackageRegistry
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getOrCreatePackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> StringUtils : isEmpty
activate StringUtils
StringUtils --> PackageRegistryManagerImpl
deactivate StringUtils
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : createPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : initPackage
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageDescr : addAllImports
activate PackageDescr
PackageDescr --> PackageRegistryManagerImpl
deactivate PackageDescr
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : get
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : put
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> RuleBase : getPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> CoreComponentFactory : get
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
PackageRegistryManagerImpl -> CoreComponentFactory : createKnowledgePackage
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
create ClassFieldAccessorCache
PackageRegistryManagerImpl -> ClassFieldAccessorCache : new
activate ClassFieldAccessorCache
ClassFieldAccessorCache --> PackageRegistryManagerImpl
deactivate ClassFieldAccessorCache
PackageRegistryManagerImpl -> RuleBase : addPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> DialectRuntimeRegistry : onAdd
activate DialectRuntimeRegistry
DialectRuntimeRegistry -> DialectRuntimeData : onAdd
activate DialectRuntimeData
DialectRuntimeData --> DialectRuntimeRegistry
deactivate DialectRuntimeData
DialectRuntimeRegistry --> PackageRegistryManagerImpl
deactivate DialectRuntimeRegistry
create PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : new
activate PackageRegistry
PackageRegistry -> KnowledgeBuilderConfigurationImpl : buildDialectRegistry
activate KnowledgeBuilderConfigurationImpl
KnowledgeBuilderConfigurationImpl -> DialectConfiguration : newDialect
activate DialectConfiguration
DialectConfiguration --> KnowledgeBuilderConfigurationImpl
deactivate DialectConfiguration
KnowledgeBuilderConfigurationImpl -> DialectCompiletimeRegistry : addDialect
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry --> KnowledgeBuilderConfigurationImpl
deactivate DialectCompiletimeRegistry
KnowledgeBuilderConfigurationImpl --> PackageRegistry
deactivate KnowledgeBuilderConfigurationImpl
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
create ImportDescr
PackageRegistryManagerImpl -> ImportDescr : new
activate ImportDescr
ImportDescr --> PackageRegistryManagerImpl
deactivate ImportDescr
PackageRegistryManagerImpl -> PackageRegistry : addImport
activate PackageRegistry
PackageRegistry -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistry
deactivate PackageRegistry
PackageRegistry -> DialectCompiletimeRegistry : addImport
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry -> Dialect : addImport
activate Dialect
Dialect --> DialectCompiletimeRegistry
deactivate Dialect
DialectCompiletimeRegistry --> PackageRegistry
deactivate DialectCompiletimeRegistry
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : getPackageDialect
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
KnowledgeBuilderImpl --> PMMLAssemblerService
deactivate KnowledgeBuilderImpl
PMMLAssemblerService -> PMMLAssemblerService : λ→
activate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService -> ResourceTypePackageRegistry : computeIfAbsent
activate ResourceTypePackageRegistry
ResourceTypePackageRegistry --> PMMLAssemblerService
deactivate ResourceTypePackageRegistry
PMMLAssemblerService -> PMMLPackage : addAll
activate PMMLPackage
PMMLPackage -> PMMLPackageImpl : addAll
activate PMMLPackageImpl
PMMLPackageImpl -> PMMLPackageImpl : add
activate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackageImpl
deactivate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackage
deactivate PMMLPackageImpl
PMMLPackage --> PMMLAssemblerService
deactivate PMMLPackage
PMMLAssemblerService -> PMMLAssemblerService : addModels
activate PMMLAssemblerService
create PackageDescr
PMMLAssemblerService -> PackageDescr : new
activate PackageDescr
create PackageDescr
PackageDescr -> PackageDescr : new
activate PackageDescr
PackageDescr --> PackageDescr
deactivate PackageDescr
PackageDescr --> PMMLAssemblerService
deactivate PackageDescr
PMMLAssemblerService -> KnowledgeBuilderImpl : getOrCreatePackageRegistry
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getOrCreatePackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> StringUtils : isEmpty
activate StringUtils
StringUtils --> PackageRegistryManagerImpl
deactivate StringUtils
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : createPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : initPackage
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageDescr : addAllImports
activate PackageDescr
PackageDescr --> PackageRegistryManagerImpl
deactivate PackageDescr
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : get
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : put
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> RuleBase : getPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> CoreComponentFactory : get
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
PackageRegistryManagerImpl -> CoreComponentFactory : createKnowledgePackage
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
create ClassFieldAccessorCache
PackageRegistryManagerImpl -> ClassFieldAccessorCache : new
activate ClassFieldAccessorCache
ClassFieldAccessorCache --> PackageRegistryManagerImpl
deactivate ClassFieldAccessorCache
PackageRegistryManagerImpl -> RuleBase : addPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> DialectRuntimeRegistry : onAdd
activate DialectRuntimeRegistry
DialectRuntimeRegistry -> DialectRuntimeData : onAdd
activate DialectRuntimeData
DialectRuntimeData --> DialectRuntimeRegistry
deactivate DialectRuntimeData
DialectRuntimeRegistry --> PackageRegistryManagerImpl
deactivate DialectRuntimeRegistry
create PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : new
activate PackageRegistry
PackageRegistry -> KnowledgeBuilderConfigurationImpl : buildDialectRegistry
activate KnowledgeBuilderConfigurationImpl
KnowledgeBuilderConfigurationImpl -> DialectConfiguration : newDialect
activate DialectConfiguration
DialectConfiguration --> KnowledgeBuilderConfigurationImpl
deactivate DialectConfiguration
KnowledgeBuilderConfigurationImpl -> DialectCompiletimeRegistry : addDialect
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry --> KnowledgeBuilderConfigurationImpl
deactivate DialectCompiletimeRegistry
KnowledgeBuilderConfigurationImpl --> PackageRegistry
deactivate KnowledgeBuilderConfigurationImpl
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
create ImportDescr
PackageRegistryManagerImpl -> ImportDescr : new
activate ImportDescr
ImportDescr --> PackageRegistryManagerImpl
deactivate ImportDescr
PackageRegistryManagerImpl -> PackageRegistry : addImport
activate PackageRegistry
PackageRegistry -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistry
deactivate PackageRegistry
PackageRegistry -> DialectCompiletimeRegistry : addImport
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry -> Dialect : addImport
activate Dialect
Dialect --> DialectCompiletimeRegistry
deactivate Dialect
DialectCompiletimeRegistry --> PackageRegistry
deactivate DialectCompiletimeRegistry
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : getPackageDialect
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
KnowledgeBuilderImpl --> PMMLAssemblerService
deactivate KnowledgeBuilderImpl
PMMLAssemblerService -> PMMLAssemblerService : λ→
activate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService -> ResourceTypePackageRegistry : computeIfAbsent
activate ResourceTypePackageRegistry
ResourceTypePackageRegistry --> PMMLAssemblerService
deactivate ResourceTypePackageRegistry
PMMLAssemblerService -> PMMLPackage : addAll
activate PMMLPackage
PMMLPackage -> PMMLPackageImpl : addAll
activate PMMLPackageImpl
PMMLPackageImpl -> PMMLPackageImpl : add
activate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackageImpl
deactivate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackage
deactivate PMMLPackageImpl
PMMLPackage --> PMMLAssemblerService
deactivate PMMLPackage
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService -> PMMLLoaderService : getKiePMMLModelsLoadedFromResource
activate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : loadKiePMMLModelFactory
activate PMMLLoaderService
PMMLLoaderService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService --> PMMLLoaderService
deactivate PMMLAssemblerService
PMMLLoaderService -> PMMLLoaderService : loadKiePMMLModelFactory
activate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : getKiePMMLModelsLoadedFromFactory
activate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : populatePMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : loadPMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : loadPMMLRuleMappersClass
activate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : populatePMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : loadPMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : populatePMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService -> PMMLLoaderService : loadPMMLRuleMappers
activate PMMLLoaderService
PMMLLoaderService -> KieBaseBuilder : createKieBaseFromModel
activate KieBaseBuilder
KieBaseBuilder -> KieServices : get
activate KieServices
KieServices --> KieBaseBuilder
deactivate KieServices
KieBaseBuilder -> KieServices : newKieBaseConfiguration
activate KieServices
KieServices --> KieBaseBuilder
deactivate KieServices
KieBaseBuilder -> KieBaseBuilder : createKieBaseFromModel
activate KieBaseBuilder
KieBaseBuilder --> KieBaseBuilder
deactivate KieBaseBuilder
KieBaseBuilder --> PMMLLoaderService
deactivate KieBaseBuilder
create KnowledgeBuilderImpl
PMMLLoaderService -> KnowledgeBuilderImpl : new
activate KnowledgeBuilderImpl
create KnowledgeBuilderImpl
KnowledgeBuilderImpl -> KnowledgeBuilderImpl : new
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> KnowledgeBuilderImpl
deactivate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> PMMLLoaderService
deactivate KnowledgeBuilderImpl
PMMLLoaderService -> KnowledgeBuilderImpl : addPackage
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
create PackageDescr
KnowledgeBuilderImpl -> PackageDescr : new
activate PackageDescr
PackageDescr --> KnowledgeBuilderImpl
deactivate PackageDescr
KnowledgeBuilderImpl -> KnowledgeBuilderImpl : getOrCreatePackageRegistry
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> KnowledgeBuilderImpl
deactivate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
create PackageCompilationPhase
KnowledgeBuilderImpl -> PackageCompilationPhase : new
activate PackageCompilationPhase
PackageCompilationPhase --> KnowledgeBuilderImpl
deactivate PackageCompilationPhase
KnowledgeBuilderImpl -> PackageCompilationPhase : process
activate PackageCompilationPhase
PackageCompilationPhase --> KnowledgeBuilderImpl
deactivate PackageCompilationPhase
KnowledgeBuilderImpl -> BuildResultCollectorImpl : addAll
activate BuildResultCollectorImpl
BuildResultCollectorImpl --> KnowledgeBuilderImpl
deactivate BuildResultCollectorImpl
KnowledgeBuilderImpl -> DialectRuntimeRegistry : merge
activate DialectRuntimeRegistry
DialectRuntimeRegistry --> KnowledgeBuilderImpl
deactivate DialectRuntimeRegistry
create DuplicateFunction
KnowledgeBuilderImpl -> DuplicateFunction : new
activate DuplicateFunction
DuplicateFunction --> KnowledgeBuilderImpl
deactivate DuplicateFunction
KnowledgeBuilderImpl -> KnowledgeBuilderImpl : addBuilderResult
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> KnowledgeBuilderImpl
deactivate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> InternalKnowledgePackage : addFunction
activate InternalKnowledgePackage
InternalKnowledgePackage --> KnowledgeBuilderImpl
deactivate InternalKnowledgePackage
KnowledgeBuilderImpl -> InternalKnowledgePackage : mergeStore
activate InternalKnowledgePackage
InternalKnowledgePackage --> KnowledgeBuilderImpl
deactivate InternalKnowledgePackage
KnowledgeBuilderImpl -> DialectRuntimeRegistry : onBeforeExecute
activate DialectRuntimeRegistry
DialectRuntimeRegistry --> KnowledgeBuilderImpl
deactivate DialectRuntimeRegistry
KnowledgeBuilderImpl -> KnowledgeBuilderImpl : mergePackage
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> KnowledgeBuilderImpl
deactivate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> PMMLLoaderService
deactivate KnowledgeBuilderImpl
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
PMMLLoaderService --> PMMLLoaderService
deactivate PMMLLoaderService
create KiePMMLException
PMMLLoaderService -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLLoaderService
deactivate KiePMMLException
PMMLLoaderService --> PMMLAssemblerService
deactivate PMMLLoaderService
PMMLAssemblerService -> PMMLCompilerService : getKiePMMLModelsCompiledFromResource
activate PMMLCompilerService
PMMLCompilerService -> KnowledgeBuilderImpl : getCachedOrCreate
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl --> PMMLCompilerService
deactivate KnowledgeBuilderImpl
PMMLCompilerService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> PMMLAssemblerService : getFactoryClassNamePackageName
activate PMMLAssemblerService
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> PMMLAssemblerService
deactivate KiePMMLModelUtils
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService --> PMMLCompilerService
deactivate PMMLAssemblerService
PMMLCompilerService -> PMMLCompilerService : getFileName
activate PMMLCompilerService
PMMLCompilerService -> PortablePath : of
activate PortablePath
PortablePath -> PortablePath : of
activate PortablePath
PortablePath -> PortablePath : normalizePath
activate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
create PortablePath
PortablePath -> PortablePath : new
activate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
PortablePath --> PortablePath
deactivate PortablePath
PortablePath --> PMMLCompilerService
deactivate PortablePath
PMMLCompilerService --> PMMLCompilerService
deactivate PMMLCompilerService
create HasKnowledgeBuilderImpl
PMMLCompilerService -> HasKnowledgeBuilderImpl : new
activate HasKnowledgeBuilderImpl
HasKnowledgeBuilderImpl --> PMMLCompilerService
deactivate HasKnowledgeBuilderImpl
PMMLCompilerService -> PMMLCompiler : getKiePMMLModels
activate PMMLCompiler
PMMLCompiler -> PMMLCompilerImpl : getKiePMMLModels
activate PMMLCompilerImpl
PMMLCompilerImpl -> KiePMMLUtil : load
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingModelName
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingOutputFieldDataType
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingOutputFieldDataType
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingMiningTargetField
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getMiningTargetFields
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getTargetDataField
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getTargetMiningField
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : correctTargetFields
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingPredictedOutputFieldTarget
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : getMiningTargetFields
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : λ→
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectMiningModel
activate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectSegmentId
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingSegmentModelName
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingTargetFieldInSegment
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateMissingPredictedOutputFieldTarget
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil -> KiePMMLUtil : populateCorrectMiningModel
activate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> KiePMMLUtil
deactivate KiePMMLUtil
KiePMMLUtil --> PMMLCompilerImpl
deactivate KiePMMLUtil
PMMLCompilerImpl -> PMMLCompilerImpl : getModels
activate PMMLCompilerImpl
PMMLCompilerImpl -> PMMLCompilerImpl : λ→
activate PMMLCompilerImpl
PMMLCompilerImpl -> CommonCompilationDTO : fromGeneratedPackageNameAndFields
activate CommonCompilationDTO
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> KiePMMLModelUtils : getSanitizedPackageName
activate KiePMMLModelUtils
KiePMMLModelUtils --> CommonCompilationDTO
deactivate KiePMMLModelUtils
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> ModelUtils : getFieldsFromDataDictionaryTransformationDictionaryAndModel
activate ModelUtils
ModelUtils -> ModelUtils : getFieldsFromDataDictionaryAndTransformationDictionary
activate ModelUtils
ModelUtils --> ModelUtils
deactivate ModelUtils
ModelUtils --> CommonCompilationDTO
deactivate ModelUtils
create CommonCompilationDTO
CommonCompilationDTO -> CommonCompilationDTO : new
activate CommonCompilationDTO
CommonCompilationDTO -> PMML_MODEL : byName
activate PMML_MODEL
PMML_MODEL --> CommonCompilationDTO
deactivate PMML_MODEL
CommonCompilationDTO -> KiePMMLModelUtils : getSanitizedClassName
activate KiePMMLModelUtils
KiePMMLModelUtils --> CommonCompilationDTO
deactivate KiePMMLModelUtils
CommonCompilationDTO -> ModelUtils : getTargetFieldName
activate ModelUtils
ModelUtils --> CommonCompilationDTO
deactivate ModelUtils
CommonCompilationDTO -> CommonCompilationDTO : λ→
activate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> CommonCompilationDTO
deactivate CommonCompilationDTO
CommonCompilationDTO --> PMMLCompilerImpl
deactivate CommonCompilationDTO
PMMLCompilerImpl -> KiePMMLModelRetriever : getFromCommonDataAndTransformationDictionaryAndModel
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> KiePMMLModelRetriever : getModelImplementationProviderStream
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> ModelImplementationProviderFinder : getImplementations
activate ModelImplementationProviderFinder
ModelImplementationProviderFinder -> ModelImplementationProviderFinderImpl : getImplementations
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl -> ModelImplementationProviderFinderImpl : getProviders
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinderImpl
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl -> ModelImplementationProviderFinderImpl : λ→
activate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinderImpl
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinderImpl --> ModelImplementationProviderFinder
deactivate ModelImplementationProviderFinderImpl
ModelImplementationProviderFinder --> KiePMMLModelRetriever
deactivate ModelImplementationProviderFinder
KiePMMLModelRetriever -> KiePMMLModelRetriever : λ→
activate KiePMMLModelRetriever
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever -> KiePMMLModelRetriever : λ→
activate KiePMMLModelRetriever
KiePMMLModelRetriever -> ModelImplementationProvider : getKiePMMLModel
activate ModelImplementationProvider
ModelImplementationProvider --> KiePMMLModelRetriever
deactivate ModelImplementationProvider
KiePMMLModelRetriever --> KiePMMLModelRetriever
deactivate KiePMMLModelRetriever
KiePMMLModelRetriever --> PMMLCompilerImpl
deactivate KiePMMLModelRetriever
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
PMMLCompilerImpl --> PMMLCompilerImpl
deactivate PMMLCompilerImpl
create KiePMMLException
PMMLCompilerImpl -> KiePMMLException : new
activate KiePMMLException
KiePMMLException --> PMMLCompilerImpl
deactivate KiePMMLException
create ExternalException
PMMLCompilerImpl -> ExternalException : new
activate ExternalException
ExternalException --> PMMLCompilerImpl
deactivate ExternalException
PMMLCompilerImpl --> PMMLCompiler
deactivate PMMLCompilerImpl
PMMLCompiler --> PMMLCompilerService
deactivate PMMLCompiler
create ExternalException
PMMLCompilerService -> ExternalException : new
activate ExternalException
ExternalException --> PMMLCompilerService
deactivate ExternalException
PMMLCompilerService --> PMMLAssemblerService
deactivate PMMLCompilerService
PMMLAssemblerService -> PMMLAssemblerService : addModels
activate PMMLAssemblerService
create PackageDescr
PMMLAssemblerService -> PackageDescr : new
activate PackageDescr
create PackageDescr
PackageDescr -> PackageDescr : new
activate PackageDescr
PackageDescr --> PackageDescr
deactivate PackageDescr
PackageDescr --> PMMLAssemblerService
deactivate PackageDescr
PMMLAssemblerService -> KnowledgeBuilderImpl : getOrCreatePackageRegistry
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getOrCreatePackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> StringUtils : isEmpty
activate StringUtils
StringUtils --> PackageRegistryManagerImpl
deactivate StringUtils
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : createPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : initPackage
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageDescr : addAllImports
activate PackageDescr
PackageDescr --> PackageRegistryManagerImpl
deactivate PackageDescr
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : get
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : put
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> RuleBase : getPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> CoreComponentFactory : get
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
PackageRegistryManagerImpl -> CoreComponentFactory : createKnowledgePackage
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
create ClassFieldAccessorCache
PackageRegistryManagerImpl -> ClassFieldAccessorCache : new
activate ClassFieldAccessorCache
ClassFieldAccessorCache --> PackageRegistryManagerImpl
deactivate ClassFieldAccessorCache
PackageRegistryManagerImpl -> RuleBase : addPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> DialectRuntimeRegistry : onAdd
activate DialectRuntimeRegistry
DialectRuntimeRegistry -> DialectRuntimeData : onAdd
activate DialectRuntimeData
DialectRuntimeData --> DialectRuntimeRegistry
deactivate DialectRuntimeData
DialectRuntimeRegistry --> PackageRegistryManagerImpl
deactivate DialectRuntimeRegistry
create PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : new
activate PackageRegistry
PackageRegistry -> KnowledgeBuilderConfigurationImpl : buildDialectRegistry
activate KnowledgeBuilderConfigurationImpl
KnowledgeBuilderConfigurationImpl -> DialectConfiguration : newDialect
activate DialectConfiguration
DialectConfiguration --> KnowledgeBuilderConfigurationImpl
deactivate DialectConfiguration
KnowledgeBuilderConfigurationImpl -> DialectCompiletimeRegistry : addDialect
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry --> KnowledgeBuilderConfigurationImpl
deactivate DialectCompiletimeRegistry
KnowledgeBuilderConfigurationImpl --> PackageRegistry
deactivate KnowledgeBuilderConfigurationImpl
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
create ImportDescr
PackageRegistryManagerImpl -> ImportDescr : new
activate ImportDescr
ImportDescr --> PackageRegistryManagerImpl
deactivate ImportDescr
PackageRegistryManagerImpl -> PackageRegistry : addImport
activate PackageRegistry
PackageRegistry -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistry
deactivate PackageRegistry
PackageRegistry -> DialectCompiletimeRegistry : addImport
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry -> Dialect : addImport
activate Dialect
Dialect --> DialectCompiletimeRegistry
deactivate Dialect
DialectCompiletimeRegistry --> PackageRegistry
deactivate DialectCompiletimeRegistry
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : getPackageDialect
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
KnowledgeBuilderImpl --> PMMLAssemblerService
deactivate KnowledgeBuilderImpl
PMMLAssemblerService -> PMMLAssemblerService : λ→
activate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService -> ResourceTypePackageRegistry : computeIfAbsent
activate ResourceTypePackageRegistry
ResourceTypePackageRegistry --> PMMLAssemblerService
deactivate ResourceTypePackageRegistry
PMMLAssemblerService -> PMMLPackage : addAll
activate PMMLPackage
PMMLPackage -> PMMLPackageImpl : addAll
activate PMMLPackageImpl
PMMLPackageImpl -> PMMLPackageImpl : add
activate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackageImpl
deactivate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackage
deactivate PMMLPackageImpl
PMMLPackage --> PMMLAssemblerService
deactivate PMMLPackage
PMMLAssemblerService -> PMMLAssemblerService : addModels
activate PMMLAssemblerService
create PackageDescr
PMMLAssemblerService -> PackageDescr : new
activate PackageDescr
create PackageDescr
PackageDescr -> PackageDescr : new
activate PackageDescr
PackageDescr --> PackageDescr
deactivate PackageDescr
PackageDescr --> PMMLAssemblerService
deactivate PackageDescr
PMMLAssemblerService -> KnowledgeBuilderImpl : getOrCreatePackageRegistry
activate KnowledgeBuilderImpl
KnowledgeBuilderImpl -> PackageRegistryManagerImpl : getOrCreatePackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> StringUtils : isEmpty
activate StringUtils
StringUtils --> PackageRegistryManagerImpl
deactivate StringUtils
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : createPackageRegistry
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : initPackage
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : λ→
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> PackageDescr : addAllImports
activate PackageDescr
PackageDescr --> PackageRegistryManagerImpl
deactivate PackageDescr
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : get
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl -> PackageAttributeManagerImpl : put
activate PackageAttributeManagerImpl
PackageAttributeManagerImpl --> PackageRegistryManagerImpl
deactivate PackageAttributeManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl -> RuleBase : getPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> CoreComponentFactory : get
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
PackageRegistryManagerImpl -> CoreComponentFactory : createKnowledgePackage
activate CoreComponentFactory
CoreComponentFactory --> PackageRegistryManagerImpl
deactivate CoreComponentFactory
create ClassFieldAccessorCache
PackageRegistryManagerImpl -> ClassFieldAccessorCache : new
activate ClassFieldAccessorCache
ClassFieldAccessorCache --> PackageRegistryManagerImpl
deactivate ClassFieldAccessorCache
PackageRegistryManagerImpl -> RuleBase : addPackage
activate RuleBase
RuleBase --> PackageRegistryManagerImpl
deactivate RuleBase
PackageRegistryManagerImpl -> DialectRuntimeRegistry : onAdd
activate DialectRuntimeRegistry
DialectRuntimeRegistry -> DialectRuntimeData : onAdd
activate DialectRuntimeData
DialectRuntimeData --> DialectRuntimeRegistry
deactivate DialectRuntimeData
DialectRuntimeRegistry --> PackageRegistryManagerImpl
deactivate DialectRuntimeRegistry
create PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : new
activate PackageRegistry
PackageRegistry -> KnowledgeBuilderConfigurationImpl : buildDialectRegistry
activate KnowledgeBuilderConfigurationImpl
KnowledgeBuilderConfigurationImpl -> DialectConfiguration : newDialect
activate DialectConfiguration
DialectConfiguration --> KnowledgeBuilderConfigurationImpl
deactivate DialectConfiguration
KnowledgeBuilderConfigurationImpl -> DialectCompiletimeRegistry : addDialect
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry --> KnowledgeBuilderConfigurationImpl
deactivate DialectCompiletimeRegistry
KnowledgeBuilderConfigurationImpl --> PackageRegistry
deactivate KnowledgeBuilderConfigurationImpl
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
create ImportDescr
PackageRegistryManagerImpl -> ImportDescr : new
activate ImportDescr
ImportDescr --> PackageRegistryManagerImpl
deactivate ImportDescr
PackageRegistryManagerImpl -> PackageRegistry : addImport
activate PackageRegistry
PackageRegistry -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistry
deactivate PackageRegistry
PackageRegistry -> DialectCompiletimeRegistry : addImport
activate DialectCompiletimeRegistry
DialectCompiletimeRegistry -> Dialect : addImport
activate Dialect
Dialect --> DialectCompiletimeRegistry
deactivate Dialect
DialectCompiletimeRegistry --> PackageRegistry
deactivate DialectCompiletimeRegistry
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistry : registerImport
activate PackageRegistry
create ImportDeclaration
PackageRegistry -> ImportDeclaration : new
activate ImportDeclaration
ImportDeclaration --> PackageRegistry
deactivate ImportDeclaration
PackageRegistry -> InternalKnowledgePackage : addImport
activate InternalKnowledgePackage
InternalKnowledgePackage -> KnowledgePackageImpl : addImport
activate KnowledgePackageImpl
KnowledgePackageImpl -> TypeResolver : addImport
activate TypeResolver
TypeResolver --> KnowledgePackageImpl
deactivate TypeResolver
KnowledgePackageImpl --> InternalKnowledgePackage
deactivate KnowledgePackageImpl
InternalKnowledgePackage --> PackageRegistry
deactivate InternalKnowledgePackage
PackageRegistry --> PackageRegistryManagerImpl
deactivate PackageRegistry
PackageRegistryManagerImpl -> PackageRegistryManagerImpl : getPackageDialect
activate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> PackageRegistryManagerImpl
deactivate PackageRegistryManagerImpl
PackageRegistryManagerImpl --> KnowledgeBuilderImpl
deactivate PackageRegistryManagerImpl
KnowledgeBuilderImpl --> PMMLAssemblerService
deactivate KnowledgeBuilderImpl
PMMLAssemblerService -> PMMLAssemblerService : λ→
activate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService -> ResourceTypePackageRegistry : computeIfAbsent
activate ResourceTypePackageRegistry
ResourceTypePackageRegistry --> PMMLAssemblerService
deactivate ResourceTypePackageRegistry
PMMLAssemblerService -> PMMLPackage : addAll
activate PMMLPackage
PMMLPackage -> PMMLPackageImpl : addAll
activate PMMLPackageImpl
PMMLPackageImpl -> PMMLPackageImpl : add
activate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackageImpl
deactivate PMMLPackageImpl
PMMLPackageImpl --> PMMLPackage
deactivate PMMLPackageImpl
PMMLPackage --> PMMLAssemblerService
deactivate PMMLPackage
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
PMMLAssemblerService --> PMMLAssemblerService
deactivate PMMLAssemblerService
return
@enduml