#created on: Aug 14, 2007
package org.acme.insurance

// After approved insurance calcule the value
rule "Insurance extra itens percent"
	agenda-group "insurancecalcule"
	salience 20
	when
		not Rejection()	
		driver : Driver ( driverID : id )
		access : AccessoriesCoverage ( driverId == driverID)
		policy : Policy( approved == true )
	then
		policy.setInsurancePrice( policy.getInsurancePrice() + 
			(access.getAlarmSystemValue() * 0.10) + 
			(access.getArmorValue() * 0.20) +
			(access.getSoundSystemValue() * 0.30 ));
			
		System.out.println("Insurance extra itens percent: " + policy.getInsurancePrice() );					
end

rule "Insurance Calcule"
	agenda-group "insurancecalcule"
	salience 10
	when
		not Rejection()	
		driver : Driver()
		policy : Policy( approved == true )
	then
		policy.setInsurancePrice(policy.getBasePrice() * driver.getInsuranceFactor() + policy.getInsurancePrice());		
		System.out.println("Insurance Calcule: " + policy.getInsurancePrice() );		
end
