package org.drools.samples
import org.drools.benchmark.models.Account;

rule rule0
  when
    $acc : Account(status == "standard", title == "mr", accountId == "acc0")
  then
    System.out.println("rule0 fired");
end

rule rule1
  when
    $acc : Account(status == "standard", title == "mr", accountId == "acc1")
  then
    System.out.println("rule1 fired");
end

rule rule2
  when
    $acc : Account(status == "standard", title == "mr", accountId == "acc2")
  then
    System.out.println("rule2 fired");
end

rule rule3
  when
    $acc : Account(status == "standard", title == "mr", accountId == "acc3")
  then
    System.out.println("rule3 fired");
end

rule rule4
  when
    $acc : Account(status == "standard", title == "mr", accountId == "acc4")
  then
    System.out.println("rule4 fired");
end

