package org.drools.testing.core.rules
import org.drools.testing.core.rules.model.Account;
import org.drools.testing.core.rules.model.Person;

rule rule1
	when 
		$acc : Account (status == "active", balance == 0)
	then
		$acc.setBalance(new Integer(10));
		modify($acc);
end

rule rule2
	when
		$acc : Account (status == "active", balance < 0)
	then
		$acc.setStatus("overdrawn");
		modify($acc);
end

rule rule3
	when
		$acc : Account (balance > 0)
	then
		System.out.println("The banks likes you.. so we're increasing our fees!");
end							 