package org.kie.dmn.core.impl;


public enum DMNMessageTypeId {
    ELEMENT_WITH_ID_NOT_SUPPORTED,
    REQ_NOT_FOUND,
    NO_TYPE_REF_FOUND,
    NO_TYPE_DEF_FOUND,
    INVALID_NAME,
    INVALID_SYNTAX,
    DECISION_NOT_FOUND,
    MISSING_EXPRESSION,
    MISSING_DEP,
    ERROR_EVAL_NODE,
    EXPR_TYPE_NOT_SUPPORTED_IN_NODE,
    NO_EXPR_DEF_FOR_NODE,
    ERR_COMPILING_FEEL,
    ERR_EVAL_CTX,
    FEEL_PROBLEM,
    ERR_EVAL,
    ERR_INVOKE;
}
