#created on: 2.6.2008
package org.drools.verifier.incompatibility

#list any import classes here.
import org.drools.verifier.components.Restriction;
import org.drools.verifier.components.PatternPossibility;

import org.drools.verifier.report.components.Incompatibility;

import org.drools.verifier.dao.VerifierResult;

#declare any global variables here
global VerifierResult result;

#
# Pattern possibilities are incompatible if any of the restrictions are incompatible.
#
# Depandencies: None
# Example: 
#		Pattern( a < b )
#		Pattern( a > b )
#
rule "Incompatible Patterns"
	when
		$incompatibility :Incompatibility()
		
		$pp1 :PatternPossibility(
			items contains $incompatibility.left
		)
		
		$pp2 :PatternPossibility(
			items contains $incompatibility.right
		)
		
		# Check that these facts do not already exist
		not Incompatibility( left == $pp1, right == $pp2)
		not Incompatibility( left == $pp2, right == $pp1)	
	then 
		insert( new Incompatibility( $pp1, $pp2 ));
end