/**
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.process.order

global CustomerService customerService
global ItemCatalog itemCatalog

rule "Invalid customer id" ruleflow-group "validate" lock-on-active true
	when
		o: Order( )
		not (Customer( ) from customerService.getCustomer(o.getCustomerId()))
	then 
	    System.err.println("Invalid customer id found!");
		o.addError("Invalid customer id");
end

rule "Invalid item id" ruleflow-group "validate" lock-on-active true
	when
		o: Order( )
		i: Order.OrderItem( ) from o.getOrderItems()
		not (Item( ) from itemCatalog.getItem(i.getItemId()))
	then 
	    System.err.println("Invalid item id found!");
		o.addError("Invalid item id " + i.getItemId());
end
 
rule "Minimal age" ruleflow-group "validate" lock-on-active true
	when
		o: Order( )
		c: Customer( ) from customerService.getCustomer(o.getCustomerId())
		oi: Order.OrderItem( ) from o.getOrderItems()
		i: Item( minimalAge > (c.getAge()) ) from itemCatalog.getItem(oi.getItemId())
	then 
	    System.err.println("Minimal age violated!");
	    o.addError("Minimal age not met for item " + i.getItemId());
end

rule "Update order " ruleflow-group "validate"
		 lock-on-active true salience -1
	when
		o: Order( )
	then 
	    update(o);
end