package org.drools.examples.process.order

import org.drools.process.instance.impl.WorkItemImpl
import org.drools.workflow.instance.node.WorkItemNodeInstance

rule "Execute Pending Work Item" salience 20
	when
	    workItemNodeInstance: WorkItemNodeInstance( workItemId <= 0 )
	    workItem: WorkItemImpl( state == WorkItemImpl.PENDING ) from workItemNodeInstance.getWorkItem()
	then 
		workItemNodeInstance.getProcessInstance().getWorkingMemory()
			.getWorkItemManager().internalExecuteWorkItem(workItem);
		workItemNodeInstance.internalSetWorkItemId(workItem.getId());
		update(workItemNodeInstance);
end

rule "Complete WorkItemNodeInstance" salience 20
	when
	    workItemNodeInstance: WorkItemNodeInstance( )
		WorkItemImpl( state == WorkItemImpl.COMPLETED ) from workItemNodeInstance.getWorkItem()
	then 
		workItemNodeInstance.triggerCompleted();
end
