#created on: 1.12.2009
package org.drools.verifier.subsumption.patterns


import org.drools.verifier.components.TextConsequence;
import org.drools.verifier.report.components.Subsumption;
import org.drools.verifier.data.VerifierReport;

global VerifierReport result;

#
#
rule "Subsumptant consequences"
	when
		$left :TextConsequence()
		
		$right :TextConsequence(
			path != $left.path,
			text == $left.text
		)	
		
	then 
		insert( new Subsumption( $left, $right ) );
end