#created on: 1.12.2009
package org.drools.verifier.subsumption.patterns


import org.drools.verifier.components.TextConsequence;
import org.drools.verifier.report.components.Subsumption;



#
#
rule "Subsumptant consequences"
	when
		$left :TextConsequence()
		
		$right :TextConsequence(
			guid != $left.guid,
			text == $left.text
		)	
		
	then 
		insert( new Subsumption( $left, $right ) );
end