package org.drools.probe

import org.drools.quarkus.test.ProbeEvent;
import org.drools.quarkus.test.ProbeCounter;

declare ProbeCounter
    @role (event)
end
declare ProbeEvent
    @role (event)
end

rule "Probe rule" when
    $pc : ProbeCounter()
    $pe : ProbeEvent( this not before $pc )
then
   $pc.addValue();
end

rule "Halt rule" when
    ProbeCounter (total == 10)
then
   drools.halt();
end