/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

#set( $symbol_pound = '#' )
#set( $symbol_dollar = '$' )
#set( $symbol_escape = '\' )
package ${package};

global java.util.Set controlSet;

#if( $exampleWithCEP=="true" || $exampleWithCEP == "y" ||  $exampleWithCEP == "yes")
declare Measurement
	@role(event)
end

rule "colors seen in the last 2 minutes"
no-loop
when
	accumulate ( Measurement( id == "color", $colorVal : val) over window:time(2m);
				 $mySet : collectSet( $colorVal )
				 )  
then
	controlSet.clear();
	controlSet.addAll($mySet);
end
#else
rule "will execute per each Measurement having ID color"
no-loop
when
	Measurement( id == "color", $colorVal : val )
then
	controlSet.add($colorVal);
end
#end