= FEEL built-in functions

To promote interoperability, FEEL includes a library of built-in functions, described below.
The built-in functions are implemented and available to be used in the Drools DMN engine; this document provides and overall description and helpful examples.
The formal specification of these functions can be referenced in the original DMN Specification document from OMG.

== Conversion functions

These functions support conversion between values of different types.
Some specific string formats are used, such as:

* `date string` as specified by XML Schema Part 2 Datatypes, for example `2020-06-01`
* `time string` either 
** as specified by XML Schema Part 2 Datatypes, for example `23:59:00z`
** a local time as specified by ISO 8601 followed by `@` and a IANA Timezone, for example `00:01:00@Etc/UTC`
* `date time string` a composite of a `date string` followed by `T` and a `time string`, for example `2012-12-25T11:00:00Z`
* `duration string` as a date time duration or year month duration as specified by the XQuery 1.0 and XPath 2.0 Data Model, for example `P1Y2M`

=== date(from)

Convert `from` to a `date`.

.Parameters
* `from` of type `string` of `date string` format

.Examples
[source,FEEL]
----
date("2012-12-25") - date("2012-12-24") = duration("P1D")
----

// ----------------------------------------------------------------------------

=== date(from)

Convert `from` to a `date`, setting time components to null.

.Parameters
* `from` of type `date and time`

.Examples
[source,FEEL]
----
date(date and time("2012-12-25T11:00:00Z")) = date("2012-12-25")
----

// ----------------------------------------------------------------------------

=== date(year, month, day)

Produce a `date` from year, month and day values.

.Parameters
* `year` of type `number`
* `month` of type `number`
* `day` of type `number`

.Examples
[source,FEEL]
----
date(2012, 12, 25) = date("2012-12-25")
----

// ----------------------------------------------------------------------------

=== date and time(date, time)

Produce a `date and time` from the given date ignoring any time components and the given time. 

.Parameters
* `date` of type `date` or `date and time`
* `time` of type `time`

.Examples
[source,FEEL]
----
date and time ("2012-12-24T23:59:00") = date and time(date("2012-12-24"), time("23:59:00"))
----

// ----------------------------------------------------------------------------

=== date and time(from)

Produce a `date and time` from the given string. 

.Parameters
* `from` of type `string` of `date time string` format

.Examples
[source,FEEL]
----
date and time("2012-12-24T23:59:00") + duration("PT1M") = date and time("2012-12-25T00:00:00")
----

// ----------------------------------------------------------------------------

=== time(from)

Produce a `time` from the given string. 

.Parameters
* `from` of type `string` of `time string` format

.Examples
[source,FEEL]
----
time("23:59:00z") + duration("PT2M") = time("00:01:00@Etc/UTC")
----

// ----------------------------------------------------------------------------

=== time(from)

Produce a `time` from the given parameter, ignoring any date components 

.Parameters
* `from` of type `time` or `date and time`

.Examples
[source,FEEL]
----
time(date and time("2012-12-25T11:00:00Z")) = time("11:00:00Z")
----

// ----------------------------------------------------------------------------

=== time(hour, minute, second, offset?)

Produce a `time` from the given hour, minute and second component values 

.Parameters
* `hour` of type `number`
* `minute` of type `number`
* `second` of type `number`
* `offset` and optional parameter of type `days and time duration` or null

.Examples
[source,FEEL]
----
time("23:59:00z") = time(23, 59, 0, duration("PT0H"))
----

// ----------------------------------------------------------------------------

=== number(from, grouping separator, decimal separator)

Converts `from` into a `number` using the specified separators.

.Parameters
* `from` of type `string` representing a valid number
* `grouping separator` one of space (` `) or comma (`,`) or period (`.`) or null
* `decimal separator` as above, but different from the group separator, or also null

.Examples
[source,FEEL]
----
number("1 000,0", " ", ",") = number("1,000.0", ",", ".")
----

// ----------------------------------------------------------------------------

=== string(from)

Provide a string representation of the supplied parameter.

.Parameters
* `from` a non-null value

.Examples
[source,FEEL]
----
string(1.1) = "1.1"
string(null) = null
----

// ----------------------------------------------------------------------------

=== duration(from)

Convert `from` to a `days and time` or `years and months duration`.

.Parameters
* `from` of type `string` of `duration string` format

.Examples
[source,FEEL]
----
date and time("2012-12-24T23:59:00") - date and time("2012-12-22T03:45:00") = duration("P2DT20H14M")
duration("P2Y2M") = duration("P26M")
----

// ----------------------------------------------------------------------------

=== years and months duration(from, to)

Calculate the years and months duration between the two supplied parameters

.Parameters
* `from` of type `date` or `date and time` 
* `to` same type as above

.Examples
[source,FEEL]
----
years and months duration( date("2011-12-22"), date("2013-08-24") ) = duration("P1Y8M")
----

// ----------------------------------------------------------------------------

== Boolean functions

Function for Boolean operations.

=== not(negand)

Perform the logical negation of the `negand` operand.

.Parameters
* `negand` of type `boolean`

.Examples
[source,FEEL]
----
not(true) = false
not(null) = null
----

// ----------------------------------------------------------------------------

== String functions

Functions for string operations.

NOTE: in FEEL, Unicode characters are counted using their codepoints.

=== substring(string, start position, length?)

Returns the substring from start position for the given length; the first character is at position value `1`.

.Parameters
* `string` of type `string`
* `start position` of type `number`
* `length` optional parameter of type `number`

.Examples
[source,FEEL]
----
substring("foobar",3) = "obar"
substring("foobar",3,3) = "oba"
substring("foobar", -2, 1) = "a"
substring("\U01F40Eab", 2) = "ab"
----

NOTE: in FEEL the string literal ``"\U01F40Eab"`` is the `🐎ab` string

// ----------------------------------------------------------------------------

=== string length(string)

Calculates the length of the string

.Parameters
* `string` of type `string`

.Examples
[source,FEEL]
----
string length("foo") = 3
string length("\U01F40Eab") = 3
----

// ----------------------------------------------------------------------------

=== upper case(string)

Produce an upper case version of the string

.Parameters
* `string` of type `string`

.Examples
[source,FEEL]
----
upper case("aBc4") = "ABC4"
----

// ----------------------------------------------------------------------------

=== lower case(string)

Produce an lower case version of the string

.Parameters
* `string` of type `string`

.Examples
[source,FEEL]
----
lower case("aBc4") = "abc4"
----

// ----------------------------------------------------------------------------

=== substring before(string, match)

Calculates the substring before the match

.Parameters
* `string` of type `string`
* `match` of type `string`

.Examples
[source,FEEL]
----
substring before("foobar", "bar") = "foo"
substring before("foobar", "xyz") = ""
----

// ----------------------------------------------------------------------------

=== substring after(string, match)

Calculates the substring after the match

.Parameters
* `string` of type `string`
* `match` of type `string`

.Examples
[source,FEEL]
----
substring after("foobar", "ob") = "ar"
substring after("", "a") = ""
----

// ----------------------------------------------------------------------------

=== replace(input, pattern, replacement, flags?)

Calculates the regular expression replacement

.Parameters
* `input` of type `string`
* `pattern` of type `string`
* `replacement` of type `string`
* `flags` optional parameter of type `string`

NOTE: uses regular expression parameters as defined in XQuery 1.0 and XPath 2.0

.Examples
[source,FEEL]
----
replace("abcd", "(ab)|(a)", "[1=$1][2=$2]") = "[1=ab][2=]cd"
----

// ----------------------------------------------------------------------------

=== contains(string, match)

Returns true if the string contains the match

.Parameters
* `string` of type `string`
* `match` of type `string`

.Examples
[source,FEEL]
----
contains("foobar", "of") = false
----

// ----------------------------------------------------------------------------

=== starts with(string, match)

Returns true if the string starts with the match

.Parameters
* `string` of type `string`
* `match` of type `string`

.Examples
[source,FEEL]
----
starts with("foobar", "fo") = true
----

// ----------------------------------------------------------------------------

=== ends with(string, match)

Returns true if the string ends with the match

.Parameters
* `string` of type `string`
* `match` of type `string`

.Examples
[source,FEEL]
----
ends with("foobar", "r") = true
----

// ----------------------------------------------------------------------------

=== matches(input, pattern, flags?)

Returns true if the input matches the regular expression

.Parameters
* `input` of type `string`
* `pattern` of type `string`
* `flags` optional parameter of type `string`

NOTE: uses regular expression parameters as defined in XQuery 1.0 and XPath 2.0

.Examples
[source,FEEL]
----
matches("foobar", "^fo*b") = true
----

// ----------------------------------------------------------------------------

=== split(string, delimiter)

Returns a list of the original string, splitted at the delimiter regexp pattern.

.Parameters
* `string` of type `string`
* `delimiter` of type `string` for a regular expression pattern

NOTE: uses regular expression parameters as defined in XQuery 1.0 and XPath 2.0

.Examples
[source,FEEL]
----
split( "John Doe", "\\s" ) = ["John", "Doe"]
split( "a;b;c;;", ";" ) = ["a","b","c","",""]
----

// ----------------------------------------------------------------------------

== List functions

Functions for list operations.

NOTE: in FEEL, the index of the first elements in a list is `1`, the index of the last element in a list cab also be identified as `-1`.

=== list contains(list, element)

Returns true if the list contains the element

.Parameters
* `list` of type `list`
* `element` of any type, including null

.Examples
[source,FEEL]
----
list contains([1,2,3], 2) = true
----

// ----------------------------------------------------------------------------

=== count(list)

Counts the element in the list

.Parameters
* `list` of type `list`

.Examples
[source,FEEL]
----
count([1,2,3]) = 3
count([]) = 0
count([1,[2,3]]) = 2
----

// ----------------------------------------------------------------------------

=== min(list)

Returns the minimum comparable element in the list

.Parameters
* `list` of type `list`

.Alternative signature
----
min(e1, e2, ..., eN)
----

.Examples
[source,FEEL]
----
min([1,2,3]) = 1
min(1) = 1
min([1]) = 1
----

// ----------------------------------------------------------------------------

=== max(list)

Returns the maximum comparable element in the list

.Parameters
* `list` of type `list`

.Alternative signature
----
max(e1, e2, ..., eN)
----

.Examples
[source,FEEL]
----
max(1,2,3) = 3
max([]) = null
----

// ----------------------------------------------------------------------------

=== sum(list)

Returns the sum of the numbers in the list

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
sum(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
sum([1,2,3]) = 6
sum(1,2,3) = 6
sum(1) = 1
----

----
sum([]) = null
----

// ----------------------------------------------------------------------------

=== mean(list)

Calculates the average (arithmetic mean) of the element in the list

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
mean(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
mean([1,2,3]) = 2
mean(1,2,3) = 2
mean(1) = 1
mean([]) = null
----

// ----------------------------------------------------------------------------

=== all(list)

Returns true if and only if all elements in the list are true

.Parameters
* `list` of type `list` of `boolean` elements

.Alternative signature
----
all(b1, b2, ..., bN)
----

.Examples
[source,FEEL]
----
all([false,null,true]) = false
all(true) = true
all([true]) = true
all([]) = true
all(0) = null
----

// ----------------------------------------------------------------------------

=== any(list)

Returns true if any of the elements in the list is true

.Parameters
* `list` of type `list` of `boolean` elements

.Alternative signature
----
any(b1, b2, ..., bN)
----

.Examples
[source,FEEL]
----
any([false,null,true]) = true
any(false) = false
any([]) = false
any(0) = null
----

// ----------------------------------------------------------------------------

=== sublist(list, start position, length?)

Returns the sublist from start position, limited to length elements

.Parameters
* `list` of type `list`
* `start position` of type `number`
* `length` an optional parameter of type `number`

.Examples
[source,FEEL]
----
sublist([4,5,6], 1, 2) = [4,5]
----

// ----------------------------------------------------------------------------

=== append(list, item...)

Creates a list appended with the item(s)

.Parameters
* `list` of type `list`
* `item` parameters of any type

.Examples
[source,FEEL]
----
append([1], 2, 3) = [1,2,3]
----

// ----------------------------------------------------------------------------

=== concatenate(list...)

Creates a list which is the result of the concatenated lists

.Parameters
* `list` parameters of type `list`

.Examples
[source,FEEL]
----
concatenate([1,2],[3]) = [1,2,3]
----

// ----------------------------------------------------------------------------

=== insert before(list, position, newItem)

Creates a list with the newItem inserted at the specified position

.Parameters
* `list` of type `list`
* `position` of type `number`
* `newItem` of any type

.Examples
[source,FEEL]
----
insert before([1,3],1,2) = [2,1,3]
----

// ----------------------------------------------------------------------------

=== remove(list, position)

Creates a list which the removed element from the specified position

.Parameters
* `list` of type `list`
* `position` of type `number`

.Examples
[source,FEEL]
----
remove([1,2,3], 2) = [1,3]
----

// ----------------------------------------------------------------------------

=== reverse(list)

Returns a reversed list

.Parameters
* `list` of type `list`

.Examples
[source,FEEL]
----
reverse([1,2,3]) = [3,2,1]
----

// ----------------------------------------------------------------------------

=== index of(list, match)

Returns indexes matching the element

.Parameters
* `list` of type `list`
* `match` of any type

.Examples
[source,FEEL]
----
index of([1,2,3,2],2) = [2,4]
----

// ----------------------------------------------------------------------------

=== union(list...)

Returns a list of all the elements from the lists without duplicates

.Parameters
* `list` parameters of type `list`

.Examples
[source,FEEL]
----
union([1,2],[2,3]) = [1,2,3]
----

// ----------------------------------------------------------------------------

=== distinct values(list)

Returns a list without duplicates

.Parameters
* `list` of type `list`

.Examples
[source,FEEL]
----
distinct values([1,2,3,2,1]) = [1,2,3]
----

// ----------------------------------------------------------------------------

=== flatten(list)

Returns a flattened list

.Parameters
* `list` of type `list`

.Examples
[source,FEEL]
----
flatten([[1,2],[[3]], 4]) = [1,2,3,4]
----

// ----------------------------------------------------------------------------

=== product(list)

Returns the product of the numbers in the list

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
product(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
product([2, 3, 4]) = 24
product(2, 3, 4) = 24
----

// ----------------------------------------------------------------------------

=== median( list )

Returns the median of the numbers in the list.
After sorting the elements, in the case of an odd number of elements, the result is the middle element;
in the case of even number of elements, the result is the average of the two middle elements.

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
median(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
median( 8, 2, 5, 3, 4 ) = 4
median( [6, 1, 2, 3] ) = 2.5
median( [ ] ) = null
----

// ----------------------------------------------------------------------------

=== stddev( list )

Returns the sample standard deviation of the numbers in the list.

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
stddev(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
stddev( 2, 4, 7, 5 ) = 2.081665999466132735282297706979931
stddev( [ 47 ] ) = null
stddev( 47 ) = null
stddev( [ ] ) = null
----

// ----------------------------------------------------------------------------

=== mode( list )

Returns the mode of the numbers in the list; in case of multiple elements, these are returned in their ascending order.

.Parameters
* `list` of type `list` of `number` elements

.Alternative signature
----
mode(n1, n2, ..., nN)
----

.Examples
[source,FEEL]
----
mode( 6, 3, 9, 6, 6 ) = [ 6 ]
mode( [6, 1, 9, 6, 1] ) = [ 1, 6 ]
mode( [ ] ) = [ ]
----

// ----------------------------------------------------------------------------

== Numeric functions

Functions for number operations.

=== decimal(n, scale)

Returns number with the given scale

.Parameters
* `n` of type `number`
* `scale` of any `number` in the range ` [−6111..6176]`

.Examples
[source,FEEL]
----
decimal(1/3, 2) = .33
decimal(1.5, 0) = 2
decimal(2.5, 0) = 2
----

// ----------------------------------------------------------------------------

=== floor(n)

Returns the greatest integer less or equal to the number

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
floor(1.5) = 1
floor(-1.5) = -2
----

// ----------------------------------------------------------------------------

=== ceiling(n)

Returns the smallest integer greater or equal to the number

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
ceiling(1.5) = 2
ceiling(-1.5) = -1
----

// ----------------------------------------------------------------------------

=== abs(n)

Returns the absolute value

.Parameters
* `n` of type `number`, `days and time duration` or `year and month duration`

.Examples
[source,FEEL]
----
abs( 10 ) = 10
abs( -10 ) = 10
abs(@"PT5H") = @"PT5H"
abs(@"-PT5H") = @"PT5H"
----

// ----------------------------------------------------------------------------

=== modulo( dividend, divisor )

Returns the remainder of the division of the dividend by divisor.
In the case either dividend or divisor is negative, the result will be of the same sign as the divisor.

NOTE: this can be equivalently be exprssed as: `modulo(dividend, divisor) = dividend - divisor*floor(dividen d/divisor)`.

.Parameters
* `dividend` of type `number`
* `divisor` of type `number`

.Examples
[source,FEEL]
----
modulo( 12, 5 ) = 2
modulo(-12,5)= 3
modulo(12,-5)= -3
modulo(-12,-5)= -2
modulo(10.1, 4.5)= 1.1
modulo(-10.1, 4.5)= 3.4
modulo(10.1, -4.5)= -3.4
modulo(-10.1, -4.5)= -1.1
----

// ----------------------------------------------------------------------------

=== sqrt( number )

Returns the square root of the number

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
sqrt( 16 ) = 4
----

// ----------------------------------------------------------------------------

=== log( number )

Returns the natural logarithm of the number

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
decimal( log( 10 ), 2 ) = 2.30
----

// ----------------------------------------------------------------------------

=== exp( number )

Returns the Euler’s number e raised to the power of the number

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
decimal( exp( 5 ), 2 ) = 148.41
----

// ----------------------------------------------------------------------------

=== odd( number )

Returns true if the number is odd

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
odd( 5 ) = true
odd( 2 ) = false
----

// ----------------------------------------------------------------------------

=== odd( number )

Returns true if the number is even

.Parameters
* `n` of type `number`

.Examples
[source,FEEL]
----
even( 5 ) = false
even ( 2 ) = true
----

// ----------------------------------------------------------------------------