/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.testcoverage.kjar

import org.drools.testcoverage.domain.Customer;
import org.drools.testcoverage.domain.Drink;
import org.drools.testcoverage.domain.Order;

rule "approve non-alcoholic drink"
when
  order: Order(isApproved() == null, drink.containsAlcohol == false)
then
  order.approve();
end

rule "approve alcoholic drink"
when
  order: Order(isApproved() == null, drink.containsAlcohol, customer.ageInYears >= 18)
then
  order.approve();
end

rule "disapprove alcoholic drink for too young customer"
when
  order: Order(isApproved() == null, drink.containsAlcohol, customer.ageInYears < 18)
then
  order.disapprove();
end
