package org.drools.compiler.test;

import com.answers.kie.layoutmode.LayoutModeInput;
import com.answers.kie.layoutmode.VisitorClass;

global java.util.List list;

rule "Global_VisitorClassification_type_crawler"
        ruleflow-group "ruleflow-group-visitor-classification"
        activation-group "activation-group-visitor-classification-root"
        salience 2
        dialect "mvel"
        when
                LayoutModeInput( user_agent matches ".*Googlebot.*" )
                not (VisitorClass( classLevel == "type_crawler" )) 
        then
                list.add( "Global_VisitorClassification_type_crawler" );
                VisitorClass fact0 = new VisitorClass();
                fact0.setClassLevel( "type_crawler" );
                insert( fact0 );
end

rule "LMI_default_null"
        salience -1
        activation-group "visitor_classification"
        ruleflow-group "ruleflow-group-visitor-classification"
        dialect "mvel"
        when
                exists (LayoutModeInput( )) 
        then
                list.add( "LMI_default_null" );        
end

rule "VisitorClassification_lowperf_10004"
        salience 10004
        activation-group "visitor_classification"
        ruleflow-group "ruleflow-group-visitor-classification"
        dialect "mvel"
        when
                LayoutModeInput( city == "mountain view" )
        then
                list.add( "VisitorClassification_lowperf_10004" );
                VisitorClass fact0 = new VisitorClass();
                fact0.setClassLevel( "low_perf" );
                insert( fact0 );
end

rule "VisitorClassification_type_4_7000"
        salience 7000
        activation-group "visitor_classification"
        ruleflow-group "ruleflow-group-visitor-classification"
        dialect "mvel"
        when
                lmi : LayoutModeInput( user_agent matches ".*Safari.*" )
                LayoutModeInput(source == null)
        then
                list.add( "VisitorClassification_type_4_7000" );
                VisitorClass fact0 = new VisitorClass();
                fact0.setClassLevel( "type_4" );
                insert( fact0 );
end
