#created on: 29.11.2007
package org.drools.analytics.redundancy.consequences

#list any import classes here.
import org.drools.analytics.components.TextConsequence;
import org.drools.analytics.report.components.Redundancy;

#declare any global variables here



rule "Find redundant TextConsequences"
	when
		# Check that AnalyticsRule $left and $right have redundant fields.
		$left :TextConsequence()
		$right :TextConsequence( 
			id != $left.id, 
			text == $left.text
		)
		
		# Check that there is not already a pair with these values.
		not Redundancy( 
			left == $left, 
			right == $right 
		)
		not Redundancy( 
			left == $right, 
			right == $left 
		)
	then
		insert( new Redundancy( Redundancy.RedundancyType.STRONG, $left, $right ) );
end
