#created on: 12.10.2007
package org.drools.analytics.redundancy

#list any import classes here.
global AnalyticsResult result;



#declare any global variables here
import java.util.Collection;
import java.util.ArrayList;

import org.drools.analytics.components.PatternPossibility;
import org.drools.analytics.components.RulePossibility;
import org.drools.analytics.dao.AnalyticsResult;
import org.drools.analytics.report.components.Redundancy;
import org.drools.analytics.report.components.AnalyticsMessage;
import org.drools.analytics.report.components.Cause;
import org.drools.analytics.report.components.CauseType;
import org.drools.analytics.report.components.Severity;
import org.drools.analytics.report.components.MessageType;


#
# Dependencies:
#
#	Needs at least one rule from following rules:
#		package org.drools.analytics.redundancy.restrictions
#			rule "Find redundant VariableRestriction"
#			rule "Find redundant LiteralRestriction"
#
rule "Find redundant restrictions from pattern possibilities"
	salience -100
	when
		$r :Redundancy(
			left.causeType == CauseType.RESTRICTION
		)

		$pp :PatternPossibility(
			items contains $r.left,
			items contains $r.right
		)
	then
		Collection causes = new ArrayList();
		causes.add( $r.getLeft() );
		causes.add( $r.getRight() );

		result.add(new AnalyticsMessage(
						Severity.NOTE, MessageType.REDUNDANCY,
						$r, "Same restriction exists twice.", causes ) );
end

#
# Dependencies:
#
#		package org.drools.analytics.redundancy.possibilities
#			rule "Find pattern possibility redundancy"
#
rule "Find redundant pattern possibilities from rule possibilities"
	salience -100
	when
		$r :Redundancy(
			left.causeType == CauseType.PATTERN_POSSIBILITY
		)

		RulePossibility(
			items contains $r.left,
			items contains $r.right
		)
	then
		Collection causes = new ArrayList();
		causes.add( $r.getLeft() );
		causes.add( $r.getRight() );

		result.add(new AnalyticsMessage(
						Severity.NOTE, MessageType.REDUNDANCY,
						$r, "Two pattern possibilities with redundant restrictions exists twice in the same rule.", causes ) );
end

