#created on: 7.9.2007
package org.drools.analytics.equivalency.rules

import org.drools.analytics.components.AnalyticsRule;
import org.drools.analytics.report.components.Redundancy;

#
# Only checks for redundant rule specifications where consequences are not redundant, 
# does not include actual pattern and restriction checks.
#
# Depandencies: None
#
rule "Find equivalent Rules"
	when
		# Check that AnalyticsRule $left and $right have redundant fields.
		$left :AnalyticsRule()
		$right :AnalyticsRule( 
			id != $left.id, 
			ruleAgendaGroup == $left.ruleAgendaGroup
		)
		
		not Redundancy(
			left == $left.consequence,
			right == $right.consequence
		)
		
		# Check that there is not already a pair with these values.
		not Redundancy( 
			left == $left, 
			right == $right 
		)
	then
		insert( new Redundancy( Redundancy.RedundancyType.WEAK, $left, $right ) );
end

