////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

  http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

[[evolutionaryAlgorithms]]
= Evolutionary algorithms
:doctype: book
:sectnums:
:icons: font


[[evolutionaryAlgorithmsOverview]]
== Overview

Evolutionary Algorithms work on a population of solutions and evolve that population.


[[evolutionaryStrategies]]
== Evolutionary strategies

This algorithm has not been implemented yet.


[[geneticAlgorithms]]
== Genetic algorithms

This algorithm has not been implemented yet.

[NOTE]
====
A good Genetic Algorithms prototype in OptaPlanner was written some time ago, but it wasn't practical to merge and support it at the time.
The results of Genetic Algorithms were consistently and seriously inferior to all the xref:local-search/local-search.adoc#localSearch[Local Search] variants (except Hill Climbing) on all use cases tried.
Nevertheless, a future version of OptaPlanner will add support for Genetic Algorithms, so you can easily benchmark Genetic Algorithms on your use case too.
====
