/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.process.order.logging

import org.drools.process.instance.impl.WorkItemImpl
import org.jbpm.workflow.instance.node.WorkItemNodeInstance
import org.jbpm.process.core.context.variable.VariableScope
import org.jbpm.process.instance.context.variable.VariableScopeInstance

rule "Log the execution of 'Correct Order'" salience 25
    when
        workItemNodeInstance: WorkItemNodeInstance( workItemId <= 0, node.name == "Correct Order" )
        workItem: WorkItemImpl( state == WorkItemImpl.PENDING ) from workItemNodeInstance.getWorkItem()
    then
        VariableScopeInstance variableScopeInstance =
            (VariableScopeInstance) workItemNodeInstance.getProcessInstance().getContextInstance(VariableScope.VARIABLE_SCOPE);
        System.out.println("LOGGING: Requesting the correction of " + variableScopeInstance.getVariable("order"));
end
