package org.jbpm.test.functional

import org.jbpm.test.domain.Person;

rule "person detector"
    when
        Person( )
    then
        // System.out.println("There is a person.");
end

rule "initial actions"
	ruleflow-group "Initial Actions"
	when
	then
		// System.out.println("Rule in initial actions ruleflow-group fired.");
end

rule "closing actions"
    ruleflow-group "Closing Actions"
    when
    then
        // System.out.println("Rule in closing actions ruleflow-group fired.");
end

rule "wanted person detector"
    ruleflow-group "Wanted Person"
    when
        Person( name == "wanted person" )
    then
        // System.out.println("Wanted person");
end

rule "change unwanted person to wanted"
    ruleflow-group "Unwanted Person Change"
    when
        $person : Person( name == "unwanted person" )
    then
        modify ($person){
            setName("wanted person")
        };
        // System.out.println("Unwanted person changed to wanted one");
end

rule "add new person"
    ruleflow-group "Maternity Hospital"
    when
    then
        insert( new Person() );
        // System.out.println("new person was inserted");
end



