drop table Attachment cascade constraints;
drop table AuditTaskImpl cascade constraints;
drop table BAMTaskSummary cascade constraints;
drop table BooleanExpression cascade constraints;
drop table CaseFileDataLog cascade constraints;
drop table CaseIdInfo cascade constraints;
drop table CaseRoleAssignmentLog cascade constraints;
drop table Content cascade constraints;
drop table ContextMappingInfo cascade constraints;
drop table CorrelationKeyInfo cascade constraints;
drop table CorrelationPropertyInfo cascade constraints;
drop table Deadline cascade constraints;
drop table Delegation_delegates cascade constraints;
drop table DeploymentStore cascade constraints;
drop table email_header cascade constraints;
drop table ErrorInfo cascade constraints;
drop table Escalation cascade constraints;
drop table EventTypes cascade constraints;
drop table ExecutionErrorInfo cascade constraints;
drop table I18NText cascade constraints;
drop table NodeInstanceLog cascade constraints;
drop table Notification cascade constraints;
drop table Notification_BAs cascade constraints;
drop table Notification_email_header cascade constraints;
drop table Notification_Recipients cascade constraints;
drop table OrganizationalEntity cascade constraints;
drop table PeopleAssignments_BAs cascade constraints;
drop table PeopleAssignments_ExclOwners cascade constraints;
drop table PeopleAssignments_PotOwners cascade constraints;
drop table PeopleAssignments_Recipients cascade constraints;
drop table PeopleAssignments_Stakeholders cascade constraints;
drop table ProcessInstanceInfo cascade constraints;
drop table ProcessInstanceLog cascade constraints;
drop table QueryDefinitionStore cascade constraints;
drop table Reassignment cascade constraints;
drop table Reassignment_potentialOwners cascade constraints;
drop table RequestInfo cascade constraints;
drop table SessionInfo cascade constraints;
drop table Task cascade constraints;
drop table task_comment cascade constraints;
drop table TaskDef cascade constraints;
drop table TaskEvent cascade constraints;
drop table TaskVariableImpl cascade constraints;
drop table VariableInstanceLog cascade constraints;
drop table WorkItemInfo cascade constraints;
drop sequence ATTACHMENT_ID_SEQ;
drop sequence AUDIT_ID_SEQ;
drop sequence BAM_TASK_ID_SEQ;
drop sequence BOOLEANEXPR_ID_SEQ;
drop sequence CASE_FILE_DATA_LOG_ID_SEQ;
drop sequence CASE_ID_INFO_ID_SEQ;
drop sequence CASE_ROLE_ASSIGN_LOG_ID_SEQ;
drop sequence COMMENT_ID_SEQ;
drop sequence CONTENT_ID_SEQ;
drop sequence CONTEXT_MAPPING_INFO_ID_SEQ;
drop sequence CORRELATION_KEY_ID_SEQ;
drop sequence CORRELATION_PROP_ID_SEQ;
drop sequence DEADLINE_ID_SEQ;
drop sequence DEPLOY_STORE_ID_SEQ;
drop sequence EMAILNOTIFHEAD_ID_SEQ;
drop sequence ERROR_INFO_ID_SEQ;
drop sequence ESCALATION_ID_SEQ;
drop sequence EXEC_ERROR_INFO_ID_SEQ;
drop sequence I18NTEXT_ID_SEQ;
drop sequence NODE_INST_LOG_ID_SEQ;
drop sequence NOTIFICATION_ID_SEQ;
drop sequence PROC_INST_LOG_ID_SEQ;
drop sequence PROCESS_INSTANCE_INFO_ID_SEQ;
drop sequence QUERY_DEF_ID_SEQ;
drop sequence REASSIGNMENT_ID_SEQ;
drop sequence REQUEST_INFO_ID_SEQ;
drop sequence SESSIONINFO_ID_SEQ;
drop sequence TASK_DEF_ID_SEQ;
drop sequence TASK_EVENT_ID_SEQ;
drop sequence TASK_ID_SEQ;
drop sequence TASK_VAR_ID_SEQ;
drop sequence VAR_INST_LOG_ID_SEQ;
drop sequence WORKITEMINFO_ID_SEQ;
