/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample;

import org.jbpm.bpmn2.objects.Address;
import org.jbpm.bpmn2.objects.Person;

global java.util.List listPerson;
global java.util.List listAddress;

rule PersonRule ruleflow-group "person-rules"
  when
    $p : Person()
  then
    System.out.println("Found person " + $p.getName());
    listPerson.add($p.getName());
end


rule AddressRule ruleflow-group "address-rules"
  when
    $a : Address()
  then
    System.out.println("Found address " + $a.getStreet());
    listAddress.add($a.getStreet());
end