/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//created on: Oct 26, 2011
//jsvitak
package org.drools.testcoverage.functional

import org.kie.api.runtime.rule.Match


rule startAgenda
salience 100
when
    String(this == 'startAgenda')
then
    drools.getKieRuntime().getAgenda().getAgendaGroup("agenda").setFocus();
end

rule catering1
agenda-group "agenda"
when
    $s : String( this == 'fireRules' )
then
end

rule catering2
salience 5
when
    $s : String( this == 'fireRules' )
then
end

rule sales1 @department('sales')
agenda-group "agenda"
when
    $s : String( this == 'fireRules' )
then
end

rule sales2 @department('sales')
when
    $s : String( this == 'fireRules' )
then
end

rule salesBlocker @activationListener('direct')
when
    $s : String( this == 'fireBlockerRule' )
    $i : Match( department == 'sales' )
then
    kcontext.blockMatch( $i );
end

