#created on: 24.9.2007
package org.drools.analytics.rangeChecks.cleanUp

import org.drools.analytics.components.*;  
import org.drools.analytics.result.Gap;  
import org.drools.analytics.result.MissingNumberPattern;

import org.drools.analytics.dao.AnalyticsData;

#declare any global variables here
global AnalyticsData data;

#
# Example: missing ( x >= 10 ) and ( x <= 10 ). This is the same as ( x == 10 )
#
rule "Merge gaps"
	when
		$g1 :Gap(
			evaluator == ">="
		)
		$g2 :Gap( 
			id != $g1.id,
			field == $g1.field,
			evaluator == "<=",
			valueAsString == $g1.valueAsString
		)		
	then	
		data.remove( $g1 );
		data.remove( $g2 );
		retract( $g1 );
		retract( $g2 );
		
		MissingNumberPattern mnp = new MissingNumberPattern( 
											$g1.getField(), 
											"==", 
											$g1.getField().getFieldType(), 
											$g1.getValueAsString() );
		mnp.setFiredRuleName( drools.getRule().getName() );
		data.save( mnp );
		insert( mnp );
end

#
# Example: covered ( x > 10 ), ( x > 70 ) ( x < 100 )and ( x == 50 )
# reports that ( x < 50 ), ( x > 50 ) and ( x <= 70 ) is missing.
#
rule "Remove useless integer gaps lesser or lesser and equal"
	when
		# Covered x > 10
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.INT,
			( evaluator == ">" || == ">=")
		)

		# Covered x < 100
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			intValue > $lower.intValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == "<=" || == "<" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			intValue > $lower.intValue,
			intValue < $higher.intValue
		)

		# gap ( x < 50 ) or ( x > 50 ) or ( x <= 70 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.intValue > $lower.intValue,
			restriction.intValue < $higher.intValue
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > 10 ), ( x < 70 ) ( x < 100 )and ( x == 50 )
# reports that ( x < 50 ), ( x > 50 ) and ( x >= 70 ) is missing.
#
rule "Remove useless integer gaps greater or greater and equal"
	when
		# Covered x > 10
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.INT,
			( evaluator == ">" || == ">=")
		)

		# Covered x < 100
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			intValue > $lower.intValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == ">=" || == ">" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			intValue > $lower.intValue,
			intValue < $higher.intValue
		)

		# gap ( x < 50 ) or ( x > 50 ) or ( x >= 70 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.intValue > $lower.intValue,
			restriction.intValue < $higher.intValue
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > 10.0 ), ( x > 70.0 ) ( x < 100.0 )and ( x == 50.0 )
# reports that ( x < 50.0 ), ( x > 50.0 ) and ( x <= 70.0 ) is missing.
#
rule "Remove useless double gaps lesser or lesser and equal"
	when
		# Covered x > 10.0
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DOUBLE,
			( evaluator == ">" || == ">=")
		)

		# Covered x < 100.0
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			doubleValue > $lower.doubleValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == "<=" || == "<" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			doubleValue > $lower.doubleValue,
			doubleValue < $higher.doubleValue
		)

		# gap ( x < 50.0 ) or ( x > 50.0 ) or ( x <= 70.0 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.doubleValue > $lower.doubleValue,
			restriction.doubleValue < $higher.doubleValue
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > 10.0 ), ( x < 70.0 ) ( x < 100.0 )and ( x == 50.0 )
# reports that ( x < 50.0 ), ( x > 50.0 ) and ( x >= 70.0 ) is missing.
#
rule "Remove useless double gaps greater or greater and equal"
	when
		# Covered x > 10.0
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DOUBLE,
			( evaluator == ">" || == ">=")
		)

		# Covered x < 100.0
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			doubleValue > $lower.doubleValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == ">=" || == ">" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			doubleValue > $lower.doubleValue,
			doubleValue < $higher.doubleValue
		)

		# gap ( x < 50.0 ) or ( x > 50.0 ) or ( x >= 70.0 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.doubleValue > $lower.doubleValue,
			restriction.doubleValue < $higher.doubleValue
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > "01-Oct-2007" ), ( x > "15-Oct-2007" ) ( x < "20-Oct-2007" )and ( x == "10-Oct-2007" )
# reports that ( x < "10-Oct-2007" ), ( x > "10-Oct-2007" ) and ( x <= "15-Oct-2007" ) is missing.
#
rule "Remove useless date gaps lesser or lesser and equal"
	when
		# Covered x > "01-Oct-2007"
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DATE,
			( evaluator == ">" || == ">=")
		)

		# Covered x < "20-Oct-2007"
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<="),
			eval( dateValue.after( $lower.getDateValue() ) )
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == "<=" || == "<" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			eval( dateValue.after( $lower.getDateValue() ) ),
			eval( dateValue.before( $higher.getDateValue() ) )
		)

		# gap ( x < "10-Oct-2007" ) or ( x > "10-Oct-2007" ) or ( x <= "15-Oct-2007" )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			eval( restriction.getDateValue().after( $lower.getDateValue() ) ),
			eval( restriction.getDateValue().before( $higher.getDateValue() ) )
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > "01-Oct-2007" ), ( x < "15-Oct-2007" ) ( x < "20-Oct-2007" )and ( x == "10-Oct-2007" )
# reports that ( x < "10-Oct-2007" ), ( x > "10-Oct-2007" ) and ( x >= "15-Oct-2007" ) is missing.
#
rule "Remove useless date gaps greater or greater and equal"
	when
		# Covered x > "01-Oct-2007"
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DATE,
			( evaluator == ">" || == ">=")
		)

		# Covered x < "20-Oct-2007"
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<="),
			eval( dateValue.after( $lower.getDateValue() ) )
		)
		
		# No "<" or "<=" restrictions between these two
		not LiteralRestriction( 
			( evaluator == ">=" || == ">" ),
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot,
			eval( dateValue.after( $lower.getDateValue() ) ),
			eval( dateValue.before( $higher.getDateValue() ) )
		)

		# gap ( x < "10-Oct-2007" ) or ( x > "10-Oct-2007" ) or ( x >= "15-Oct-2007" )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			eval( restriction.getDateValue().after( $lower.getDateValue() ) ),
			eval( restriction.getDateValue().before( $higher.getDateValue() ) )
		)
	then
		#System.out.println( $lower + " | " + $higher );
		retract( $gap );
		data.remove( $gap );
end

/*
#
# Example: covered ( x > 10 ),  ( x < 100 )and ( x == 50 )
# reports that ( x < 50 ) ( x > 50 ) is missing.
#
rule "Remove useless integer gaps"
	when
		# Covered x > 10
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.INT,
			( evaluator == ">" || == ">=")
		)
		
		# Covered x < 100
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			intValue > $lower.intValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
	
		# Nothing in between except "==" restrictions
		not LiteralRestriction( 
			evaluator != "==",
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			intValue > $lower.intValue,
			intValue < $higher.intValue
		)
		
		# gap ( x < 50.0 ) or ( x > 50.0 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.evaluator == "==",
			restriction.intValue > $lower.intValue,
			restriction.intValue < $higher.intValue
		)

	then
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > 10.0 ),  ( x < 100.0 )and ( x == 50.0 )
# reports that ( x < 50.0 ) ( x > 50.0 ) is missing.
#
rule "Remove useless double gaps"
	when
		# Covered x > 10.0
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DOUBLE,
			( evaluator == ">" || == ">=")
		)
		
		# Covered x < 100.0
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			doubleValue > $lower.doubleValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
	
		# Nothing in between except "==" restrictions
		not LiteralRestriction( 
			evaluator != "==",
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			doubleValue > $lower.doubleValue,
			doubleValue < $higher.doubleValue
		)
		
		# gap ( x < 50.0 ) or ( x > 50.0 )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.evaluator == "==",
			restriction.doubleValue > $lower.doubleValue,
			restriction.doubleValue < $higher.doubleValue
		)

	then
		retract( $gap );
		data.remove( $gap );
end

#
# Example: covered ( x > "01-Oct-2007" ),  ( x < "20-Oct-2007" )and ( x == "10-Oct-2007" )
# reports that ( x < "10-Oct-2007" ) ( x > "10-Oct-2007" ) is missing.
#
rule "Remove useless date gaps"
	when
		# Covered x > "01-Oct-2007"
		$lower :LiteralRestriction( 
			valueType == Field.FieldType.DATE,
			( evaluator == ">" || == ">=")
		)
		
		# Covered x < "20-Oct-2007"
		$higher :LiteralRestriction( 
			fieldId == $lower.fieldId,
			dateValue > $lower.dateValue,
			patternIsNot == $lower.patternIsNot,
			( evaluator == "<" || == "<=")
		)
	
		# Nothing in between except "==" restrictions
		not LiteralRestriction( 
			evaluator != "==",
			fieldId == $lower.fieldId,
			patternIsNot == $lower.patternIsNot, 
			dateValue > $lower.dateValue,
			dateValue < $higher.dateValue
		)
		
		# gap ( x < "10-Oct-2007" ) or ( x > "10-Oct-2007" )
		$gap :Gap(
			restriction.fieldId == $lower.fieldId,
			restriction.patternIsNot == $lower.patternIsNot,
			restriction.evaluator == "==",
			restriction.dateValue > $lower.dateValue,
			restriction.dateValue < $higher.dateValue
		)

	then
		retract( $gap );
		data.remove( $gap );
end
*/
