
package org.drools.informer

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;

rule "build list of available items"
no-loop
when
	questionnaire : Questionnaire();
	items : ArrayList() from collect (Item(id != questionnaire.id, questionnaire.itemList contains id));
then
	List availableItemIds = new ArrayList();
	for (Iterator iterator = items.iterator(); iterator.hasNext();) {
		availableItemIds.add(((Item)iterator.next()).getId());
	}
	List itemIds = new ArrayList(questionnaire.getItemList());
	for (Iterator iterator = itemIds.iterator(); iterator.hasNext();) {
		String id = (String)iterator.next();
		if (!availableItemIds.contains(id)) {
			iterator.remove();
		}
	}
	String [] oldAvailableItems = questionnaire.getAvailableItems();
	if (oldAvailableItems ==  null) {
		oldAvailableItems = new String[]{};
	}
	String[] newAvailableItems = (String[])itemIds.toArray(new String[]{});
	if (!Arrays.equals(newAvailableItems, oldAvailableItems)) {
		questionnaire.setAvailableItems(newAvailableItems);
		update(questionnaire);
	}
end

rule "return from navigation branch"
salience 5 # before : activate top-level item (if Questionnaire.activeItem is used)
when
	questionnaire : Questionnaire(activeItem == "#return");
then
	questionnaire.navigationReturn();
	update(questionnaire);
end

rule "activate top-level item (if Questionnaire.activeItem is used)"
no-loop
salience 4 # before: "activate/deactivate lower-level items (if Questionnaire.activeItem is used)"
when
	questionnaire : Questionnaire(activeItem != null);
	item : Item(id memberOf questionnaire.itemList, id == questionnaire.activeItem, active == false);
then
	item.setActive(true);
	update(item);
end

rule "deactivate top-level items (if Questionnaire.activeItem is used)"
no-loop
salience 4 # before: "activate/deactivate lower-level items (if Questionnaire.activeItem is used)"
when
	questionnaire : Questionnaire(activeItem != null);
	item : Item(id memberOf questionnaire.itemList, id != questionnaire.activeItem, active == true);
then
	item.setActive(false);
	update(item);
end

rule "activate/deactivate lower-level items (if Questionnaire.activeItem is used)"
no-loop
salience 3 # before: "activate/deactivate InvalidAnswers"
when
	questionnaire : Questionnaire(activeItem != null);
	item : Item(id != questionnaire.id, id not memberOf questionnaire.itemList);
	groups : ArrayList() from collect (Group(id != questionnaire.id, itemList contains item.id));
then
	boolean groupActive = false;
	for (Iterator iterator = groups.iterator(); iterator.hasNext();) {
		Group group = (Group)iterator.next();
		if (group.isActive()) {
			groupActive = true;
			break;
		}
	}
	// an item is active if and only if it is in a group that is active
	if (item.isActive() != groupActive) {
		item.setActive(groupActive);
		update(item);
	}
end

rule "activate everything (if Questionnaire.activeItem is not used)"
salience 3 # before: "activate/deactivate InvalidAnswers"
when
	questionnaire : Questionnaire(activeItem == null);
	item : Item(id != questionnaire.id, active == false);
then
	item.setActive(true);
	update(item);
end

rule "activate/deactivate InvalidAnswers"
salience 2 # before: "propagate readonly from group to questions or subgroups"
when
	question : Question();
	invalidAnswer : InvalidAnswer(questionId == question.id, active != question.active);
then
	invalidAnswer.setActive(question.isActive());
	update(invalidAnswer);
end

rule "retract invalid answers for inactive questions"
salience -1000 # ensure this is the last rule in the Agenda Group to fire
when
    invalidAnswer : InvalidAnswer();
    question : Question($id : id == invalidAnswer.questionId, active == false);
    questionnaire : Questionnaire(enableActionValidation == true, itemList contains $id);
then
    retract(invalidAnswer);
end

rule "deactivate orphan InvalidAnswers"
salience 2 # before: "propagate readonly from group to questions or subgroups"
when
	invalidAnswer : InvalidAnswer(active == true);
	not(exists(Question(id == invalidAnswer.questionId)));
then
	invalidAnswer.setActive(false);
	update(invalidAnswer);
end
