@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant Runtime
participant Assembler
participant Compiler

Runtime -> Assembler: search model
Assembler -> Compiler: codegen
Compiler -> Assembler: sources
Assembler -> Runtime: factory instantiation

@enduml
