/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package com.myteam.proj1;

rule R0
    when
        $s : String()
    then
        System.out.println($s);
end

rule R1
    when
        $s : String()
    then
        System.out.println($s);
end

rule R2
    when
        $s : String()
    then
        System.out.println($s);
end

rule R3
    when
        $s : String()
    then
        System.out.println($s);
end

rule R4
    when
        $s : String()
    then
        System.out.println($s);
end

rule R5
    when
        $s : String()
    then
        System.out.println($s);
end

rule R6
    when
        $s : String()
    then
        System.out.println($s);
end

rule R7
    when
        $s : String()
    then
        System.out.println($s);
end

rule R8
    when
        $s : String()
    then
        System.out.println($s);
end

rule R9
    when
        $s : String()
    then
        System.out.println($s);
end

rule R10
    when
        $s : String()
    then
        System.out.println($s);
end

