/**
 * Copyright 2021 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *       http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ruletask;
unit Generated;

import org.kie.kogito.codegen.data.Person;

rule singlePerson when
    p: /singlePerson[ age >= 18 ]
then
    p.setAdult(true);

end


rule singlePerson_add_note when
    p: /singlePerson[ age == 50 ]
    s: /singleString[ this == "hello" ]
then
    p.setAdult(true);
	singleString.set("Now the life starts again");
end

rule singlePerson_clear_note when
    p: /singlePerson[ age == 60 ]
    s: /singleString
then
    p.setAdult(true);
	singleString.clear();
end