package com.sample

import com.sample.DroolsTest.Message;

#
# These rules have gaps
#
rule "Missing int range 1a, warning"
	when
		    Foo1warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 1b, warning"
	when
		    Foo1warning( value < 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 2a, warning"
	when
		    Foo2warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 2b, warning"
	when
		    Foo2warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 3a, warning"
	when
		    Foo3warning( value >= 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 3b, warning"
	when
		    Foo3warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 4a, warning"
	when
		    Foo4warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 4b, warning"
	when
		    Foo4warning( value <= 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5a, warning"
	when
		    Foo5warning( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5b, warning"
	when
		    Foo5warning( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 6a, warning"
	when
		    Foo6warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 6b, warning"
	when
		    Foo6warning( value == 40 )
	then
		System.out.println( "Test" );
end

#
# These rules have gaps
#
rule "Missing not int range 7a, warning"
	when
		    not Foo7warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 7b, warning"
	when
		    not Foo7warning( value < 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 8a, warning"
	when
		    not Foo8warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 8b, warning"
	when
		    not Foo8warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 9a, warning"
	when
		    not Foo9warning( value >= 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 9b, warning"
	when
		    not Foo9warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10a, warning"
	when
		    not Foo10warning( value > 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10b, warning"
	when
		    not Foo10warning( value <= 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 11a, warning"
	when
		    not Foo11warning( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 11b, warning"
	when
		    not Foo11warning( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 12a, warning"
	when
		    not Foo12warning( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 12b, warning"
	when
		    not Foo12warning( value == 40 )
	then
		System.out.println( "Test" );
end

#
# These rules do not have gaps
#
rule "Missing int range 1a, ok"
	when
		    Foo1ok( value >= 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 1b, ok"
	when
		    Foo1ok( value < 42 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 2a, ok"
	when
		    Foo2ok( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 2b, ok"
	when
		    Foo2ok( value <= 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 3a, ok"
	when
		    Foo3ok( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 3b, ok"
	when
		    Foo3ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 3c, ok"
	when
		    Foo3ok( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 4a, ok"
	when
		    Foo4ok( value == 40 )
	then
		System.out.println( "Test" );
end
rule "Missing int range 4b, ok"
	when
		    Foo4ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5a, ok"
	when
		    Foo5ok( value > 41 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5b, ok"
	when
		    Foo5ok( value == 41 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5c, ok"
	when
		    Foo5ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing int range 5d, ok"
	when
		    Foo5ok( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 6a, ok"
	when
		    not Foo6ok( value >= 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 6b, ok"
	when
		    not Foo6ok( value < 42 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 7a, ok"
	when
		    not Foo7ok( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 7b, ok"
	when
		    not Foo7ok( value <= 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 8a, ok"
	when
		    not Foo8ok( value > 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 8b, ok"
	when
		    not Foo8ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 8c, ok"
	when
		    not Foo8ok( value < 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 9a, ok"
	when
		    not Foo4ok( value == 40 )
	then
		System.out.println( "Test" );
end
rule "Missing not int range 9b, ok"
	when
		    not Foo4ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10a, ok"
	when
		    not Foo10ok( value > 41 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10b, ok"
	when
		    not Foo10ok( value == 41 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10c, ok"
	when
		    not Foo10ok( value == 40 )
	then
		System.out.println( "Test" );
end

rule "Missing not int range 10d, ok"
	when
		    not Foo10ok( value < 40 )
	then
		System.out.println( "Test" );
end