#created on: 7.6.2007
package org.drools.analytics.rangeChecks.reports;

#list any import classes here.
import org.drools.analytics.components.Field;
import org.drools.analytics.report.components.AnalyticsRangeCheckMessage;
import org.drools.analytics.dao.AnalyticsResult;
import org.drools.analytics.report.components.MissingRange;

import java.util.ArrayList;

#declare any global variables here
global AnalyticsResult result

rule "Collect gaps"
	salience -100
	when
		$f :Field()
		$list :ArrayList( size > 0)
			from collect(
				MissingRange( field == $f )
			)
	then
		result.save( new AnalyticsRangeCheckMessage( 
								AnalyticsRangeCheckMessage.Severity.WARNING, $f, 
								$f + " has one or more gaps.", $list ) );
end