/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.example.api.kiebaseinclusion

import org.drools.example.api.namedkiesession.Message

rule "rule 3" when
    Message( text == "Open the pod bay doors, HAL." )
then
    insert( new Message("HAL", "I'm sorry, Dave. I'm afraid I can't do that." ) );
end