/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package foo.bar

import org.drools.compiler.Cheese

global java.util.List list

rule "rule1"
    when
        c: Cheese()
    then
        System.out.println("rule1---");
        c.setType("rule1");
end

rule "rule2"
    when
        c: Cheese()
    then
        c.setType("rule2");
        System.out.println("rule2---");
end

rule "rule3"
    when
        c: Cheese()
    then
        //we are not using a list, but thats cool, we won't fire this rule...
        list.add("rule3");
        c.setType("rule3");
        System.out.println("rule3---");
end

rule "rule4"
    when
        not Cheese()
    then
        System.err.println("whee");
end

