/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.integrationtests;

import org.drools.compiler.integrationtests.model.CalcFact;
import org.drools.compiler.integrationtests.model.Item;
import org.drools.compiler.integrationtests.model.RecordFact;

dialect "mvel"

rule R1
	when
        String()
        CalcFact( $lineNumber : lineNumber, $itemList : itemList )
        Integer()
	then
end

rule R2
	when
        String()
        $fact : CalcFact( $itemList : itemList )
        $item : Item( decomposedPointFlag == null ) from $itemList
        $record : RecordFact( decomposedPoint == null )
        not RecordFact( lineNumber == $fact.lineNumber )
	then
        modify($record){
          decomposedPoint = null
        }
        modify($item){
          decomposedPointFlag = "1"
        }
        modify($fact){
          itemList = $itemList
        }
        System.out.println("[DEBUG] after  $item=" + $item);
end
