/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler

import org.drools.testcoverage.common.model.Cheese;
import org.drools.testcoverage.common.model.Person;
import org.drools.testcoverage.common.model.Cheesery;

global java.util.List results;

rule "MultiPatternAccumulate" salience 80
    dialect "mvel"
    when
        $cheesery    : Cheesery( totalAmount > 30 )
                               from accumulate( $person : Person( $likes: likes) and $cheese : Cheese( type == $likes ),
                                                init( Cheesery cheesery = new Cheesery(); ),
                                                action( cheesery.addCheese( $cheese ); ),
                                                reverse( cheesery.removeCheese( $cheese ); ),
                                                result( cheesery ) );
    then
        results.add( $cheesery );
end  
