/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler

import org.drools.testcoverage.common.model.StockTick;

global java.util.List results;

declare StockTick
    @role( event )
end

rule "Test entry point 1"
when
    $st : StockTick( company == "ACME", price > 10 ) from entry-point "stream1"
then
    drools.getEntryPoint("stream2").insert( $st );
end

rule "Test entry point 2"
    dialect "mvel"
when
    $st : StockTick( company == "ACME", price > 20 ) from entry-point "stream2"
then
    drools.getEntryPoint("stream3").insert( $st );
end

rule "Test entry point 3"
when
    $st : StockTick( ) from entry-point "stream3"
then
    results.add( $st );
end

