/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler

import org.drools.testcoverage.common.model.Person;

global java.util.List results;

rule "1. && operator"
    salience 10
    when
        $person : Person( age > 30 && < 40 && hair == "red" )
    then
        results.add( $person );
end    

rule "2. || operator"
    salience 8
    when
        $person : Person( age > 70 && < 90 || hair == "green" )
    then
        results.add( $person );
end    

rule "3. Complex expression"
    salience 7
    when
        $person : Person( ( age == 70 && hair == "black" ) ||
                          ( age == 40 && hair == "pink" ) ||
                          ( age == 12 && ( hair == "yellow" || hair == "blue" ) ) )
    then
        results.add( $person );
end    

rule "4. Constraint connectors"
    salience 5
    when
        // forcing a variable restriction so we can trigger the issue reported in JBRULES-909
        Person( $age : age == 48, hair == "blue" )
        $person : Person( age > $age || hair == "gray" )
    then
        results.add( $person );
end
