package iristreemodel

import org.kie.pmml.models.drools.executor.KiePMMLStatusHolder
import org.dmg.pmml.SimplePredicate
import org.kie.api.pmml.PMML4Result

global PMML4Result $pmml4Result

declare  SPECIES

    value : String
end

declare  SEPAL_LENGTH

    value : double
end

declare  SEPAL_WIDTH

    value : double
end

declare  PETAL_LENGTH

    value : double
end

declare  PETAL_WIDTH

    value : double
end


rule "_setosa"
when
    $statusHolder : KiePMMLStatusHolder( status == null )
then
// System.out.println("_setosa match");
$statusHolder.setStatus("_setosa");
update($statusHolder);

end

rule "_setosa_setosa"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa" )
then
// System.out.println("_setosa_setosa match");
$statusHolder.setStatus("_setosa_setosa_surrogate");
update($statusHolder);

end


rule "_setosa_setosa_surrogate_PETAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_setosa_surrogate" )
    $inputField : PETAL_LENGTH(  )
    if ( $inputField.getValue() < 2.45 )  break[match]
then
// System.out.println("_setosa_setosa_surrogate_PETAL_LENGTH match");
//$statusHolder.setStatus("_setosa_setosa");
//update($statusHolder);
then[match]
// System.out.println("_setosa_setosa_surrogate_PETAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "setosa");
end

rule "_setosa_setosa_surrogate_PETAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_setosa_surrogate" )
    $inputField : PETAL_WIDTH(  )
    if ( $inputField.getValue() < 0.8 )  break[match]
then
// System.out.println("_setosa_setosa_surrogate_PETAL_WIDTH match");
//$statusHolder.setStatus("_setosa_setosa");
//update($statusHolder);
then[match]
// System.out.println("_setosa_setosa_surrogate_PETAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "setosa");
end

rule "_setosa_setosa_surrogate_SEPAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_setosa_surrogate" )
    $inputField : SEPAL_LENGTH(  )
    if ( $inputField.getValue() < 5.45 )  break[match]
then
// System.out.println("_setosa_setosa_surrogate_SEPAL_LENGTH match");
//$statusHolder.setStatus("_setosa_setosa");
//update($statusHolder);
then[match]
// System.out.println("_setosa_setosa_surrogate_SEPAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "setosa");
end

rule "_setosa_setosa_surrogate_SEPAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_setosa_surrogate" )
    $inputField : SEPAL_WIDTH(  )
    if ( $inputField.getValue() >= 3.35 )  break[match]
then
// System.out.println("_setosa_setosa_surrogate_SEPAL_WIDTH match");
$statusHolder.setStatus("_setosa");
update($statusHolder);
then[match]
// System.out.println("_setosa_setosa_surrogate_SEPAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "setosa");
end

rule "_setosa_versicolor"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa" )
then
// System.out.println("_setosa_versicolor_surrogate_PETAL_LENGTH match");
$statusHolder.setStatus("_setosa_versicolor_surrogate");
update($statusHolder);
end

rule "_setosa_versicolor_surrogate_PETAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor_surrogate" )
    $inputField : PETAL_LENGTH(  )
    if ( $inputField.getValue() >= 2.45 )  break[match]
then
// System.out.println("_setosa_versicolor_surrogate_PETAL_LENGTH match");
//$statusHolder.setStatus("_setosa_versicolor");
//update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_surrogate_PETAL_LENGTH break");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_surrogate_PETAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor_surrogate" )
    $inputField : PETAL_WIDTH(  )
    if ( $inputField.getValue() >= 0.8 )  break[match]
then
// System.out.println("_setosa_versicolor_surrogate_PETAL_WIDTH match");
//$statusHolder.setStatus("_setosa_versicolor");
//update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_surrogate_PETAL_WIDTH break");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_surrogate_SEPAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor_surrogate" )
    $inputField : SEPAL_LENGTH(  )
    if ( $inputField.getValue() >= 5.45 )  break[match]
then
// System.out.println("_setosa_versicolor_surrogate_SEPAL_LENGTH match");
//$statusHolder.setStatus("_setosa_versicolor");
//update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_surrogate_SEPAL_LENGTH break");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_surrogate_SEPAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor_surrogate" )
    $inputField : SEPAL_WIDTH(  )
    if ( $inputField.getValue() < 3.35 )  break[match]
then
// System.out.println("_setosa_versicolor_surrogate_SEPAL_WIDTH match");
$statusHolder.setStatus("_setosa");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_surrogate_SEPAL_WIDTH break");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_versicolor"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor_versicolor" )
then
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_WIDTH match");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_versicolor_surrogate_PETAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : PETAL_WIDTH(  )
    if ( $inputField.getValue() < 1.75 )  break[match]
then
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_WIDTH match");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_versicolor_surrogate_PETAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : PETAL_LENGTH(  )
    if ( $inputField.getValue() < 4.75 )  break[match]
then
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_LENGTH match");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_versicolor_surrogate_PETAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_versicolor_surrogate_SEPAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : SEPAL_LENGTH(  )
    if ( $inputField.getValue() < 6.15 )  break[match]
then
// System.out.println("_setosa_versicolor_versicolor_surrogate_SEPAL_LENGTH match");
$statusHolder.setStatus("_setosa_versicolor_versicolor");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_versicolor_surrogate_SEPAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_versicolor_surrogate_SEPAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : SEPAL_WIDTH(  )
    if ( $inputField.getValue() < 2.95 )  break[match]
then
// System.out.println("_setosa_versicolor_versicolor_surrogate_SEPAL_WIDTH match");
$statusHolder.setStatus("DONE");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_versicolor_surrogate_SEPAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");
end

rule "_setosa_versicolor_virginica_surrogate_PETAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : PETAL_WIDTH(  )
    if ( $inputField.getValue() >= 1.75 )  break[match]
then
// System.out.println("_setosa_versicolor_virginica_surrogate_PETAL_WIDTH match");
$statusHolder.setStatus("_setosa_versicolor_virginica");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_virginica_surrogate_PETAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "virginica");
end

rule "_setosa_versicolor_virginica_surrogate_PETAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : PETAL_LENGTH(  )
    if ( $inputField.getValue() >= 4.75 )  break[match]
then
// System.out.println("_setosa_versicolor_virginica_surrogate_PETAL_LENGTH match");
$statusHolder.setStatus("_setosa_versicolor_virginica");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_virginica_surrogate_PETAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "virginica");
end

rule "_setosa_versicolor_virginica_surrogate_SEPAL_LENGTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : SEPAL_LENGTH(  )
    if ( $inputField.getValue() >= 6.15 )  break[match]
then
// System.out.println("_setosa_versicolor_virginica_surrogate_SEPAL_LENGTH match");
$statusHolder.setStatus("_setosa_versicolor_virginica");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_virginica_surrogate_SEPAL_LENGTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "virginica");
end

rule "_setosa_versicolor_virginica_surrogate_SEPAL_WIDTH"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
    $inputField : SEPAL_WIDTH(  )
    if ( $inputField.getValue() >= 2.95 )  break[match]
then
// System.out.println("_setosa_versicolor_virginica_surrogate_SEPAL_WIDTH match");
$statusHolder.setStatus("DONE");
update($statusHolder);
then[match]
// System.out.println("_setosa_versicolor_virginica_surrogate_SEPAL_WIDTH break");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "virginica");
end

rule "default__setosa_versicolor"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa_versicolor" )
then
// System.out.println("default__setosa_versicolor match");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "versicolor");

end

rule "default__setosa"
when
    $statusHolder : KiePMMLStatusHolder( status == "_setosa" )
then
// System.out.println("default__setosa match");
$statusHolder.setStatus("DONE");
update($statusHolder);
$pmml4Result.setResultCode("OK");
$pmml4Result.addResultVariable($pmml4Result.getResultObjectName(), "setosa");

end
