/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/



rule myrule 
  when
  then
      int i = 0;
    i = 1;
    i / 1;
    i == 1;
    i(i);
    i = 'i';
    i.i.i;
    i\i;
    i<i;
    i>i;
    i="i";
    ++i;
    i++;
    --i;
    i--;
    i += i;
    i -= i;
    i *= i;
    i /= i;
    int i = 5;
    for(int j; j<i; ++j) {
      System.out.println(j);
    }
    Object o = new String("Hello");
    String s = (String) o;

end
