/*
 * Copyright 2011 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.examples.traits

import org.drools.examples.traits.Scholar;


declare Person
    @Traitable

    name    : String       = "john"     @key

    age     : int          = 18

    weight  : Double       = 75.4

end


declare Student extends Scholar
    @format( trait )

    name    : String

    age     : int

    weight  : Double

    school  : String
end


rule "Zero"
when
then
    insert( new Person() );
end


rule "Student"
no-loop
when
    $p : Person( $name : name, $age : age < 25, $weight : weight )
then
    Student s = don( $p, Student.class );
        s.setSchool( "SomeSchool" );
        s.learn( " AI " );
end










