package org.drools.examples.traits

import java.util.List

declare Person
    @Traitable 
    name : String
    gender : String
end


declare Parent
    @format ( trait )
    children : List    
end    

declare Father
end

declare Mother
end

/*
rule xxx when
    $person : Person()
    exists ( Person() from $person.fields[ "children" ] )
then
    don( $person, Parent.class, true );
end 

rule xxx when
    $parent : Parent( gender == "male" )
then
     don( $per, Father.class, true );
end      

rule xxx when
    $parent : Parent( gender == "female" )
then
     don( $per, Mother.class, true );
end    

rule xxx when
    $father : Father()
    Today( this == Sunday )
then
    System.out.println( $father + ": It's your day off" );
end
*/