{
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "$handlerName$ endpoint request count per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"$handlerName$\"}[1d]))"
    }
   ]
  },
  {
   "title": "Average requests per minute to $handlerName$ endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(api_http_response_code{endpoint=\"$handlerName$\"}[1m]))"
    }
   ]
  },
  {
   "title": "Execution time quantiles for endpoint $handlerName$",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "ns" }
   ],
   "targets": [
    {
     "expr": "api_execution_elapsed_nanosecond{endpoint=\"$handlerName$\"}"
    }
   ]
  },
  {
   "title": "$handlerName$ endpoint status code responses per minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(api_http_response_code{endpoint=\"$handlerName$\"}[1m])"
    }
   ]
  },
  {
   "title": "Exceptions details",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "increase(api_http_stacktrace_exceptions{endpoint=\"$handlerName$\"}[1d])"
    }
   ]
  },
  {
   "title": "Exception count per day",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(increase(api_http_stacktrace_exceptions{endpoint=\"$handlerName$\"}[1d]))"
    }
   ]
  }
 ]
}