package org.acme.insurance;

import org.acme.insurance.base.Rejection;
import org.acme.insurance.base.Policy;

rule "approve"
	agenda-group "risk assessment"
	salience -1
	when
		not Rejection()
		$policy : Policy( approved == false )
	then
		System.out.println("approve: " + $policy.getInsurancePrice() );	
		$policy.setApproved(true);
		update($policy);
		drools.setFocus("insurancecalcule");
		System.out.println("Policy aproved focusing insurance calcule agenda-group");
end

rule "rejection"
	agenda-group "rejection"
	auto-focus 
	when
		Rejection()
	then
		drools.halt();
		System.out.println("There's some rejection: halting drools ");
end
