/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.testcoverage.functional

// internalMatch group test

rule "basic1"
    activation-group "basic"
    salience 0
    when
        String(this == "basicActivationGroup")
    then
end

rule "basic2"
    activation-group "basic"
    salience 10
    when
	 String(this == "basicActivationGroup")
    then
end

rule "basic3"
    activation-group "basic"
    salience 5
    when
        String(this == "basicActivationGroup")
    then
end

//----------------------------------------------------------------------

rule "simplyRecursive1"
    activation-group "simplyRecursive"
    salience 0
    when
        String(this == "recursiveActivationGroup") or String(this == "simplyRecursiveCall")
    then
end

rule "simplyRecursive2"
    activation-group "simplyRecursive"
    salience 5
    when
        String(this == "recursiveActivationGroup") or String(this == "simplyRecursiveCall")
    then
end

rule "simplyRecursive3"
    no-loop true
    activation-group "simplyRecursive"
    salience 10
    when
        String(this == "recursiveActivationGroup") or String(this == "simplyRecursiveCall")
    then
        insert("simplyRecursiveCall");
end

//----------------------------------------------------------------------

rule "defaultSalience1"
    activation-group "defaultSalience"
    when
        String(this == "defaultSalienceActivationGroup")
    then
end

rule "defaultSalience2"
    activation-group "defaultSalience"
    when
        String(this == "defaultSalienceActivationGroup")
    then
end

rule "defaultSalience3"
    activation-group "defaultSalience"
    when
        String(this == "defaultSalienceActivationGroup")
    then
end

//----------------------------------------------------------------------

rule "defaultSalienceWithRecursion1"
    no-loop
    activation-group "defaultSalienceRecursion"
    when
	String(this == "defaultSalienceWithRecursion") or String(this == "defaultSalienceWithRecursionCall")
    then
	insert("defaultSalienceWithRecursionCall");	
end

rule "defaultSalienceWithRecursion2"
    activation-group "defaultSalienceRecursion"
    when
	String(this == "defaultSalienceWithRecursion") or String(this == "defaultSalienceWithRecursionCall")
    then
    insert("defaultSalienceWithRecursionCall");
end

rule "defaultSalienceWithRecursion3"
    no-loop
    activation-group "defaultSalienceRecursion"
    when
	String(this == "defaultSalienceWithRecursion") or String(this == "defaultSalienceWithRecursionCall")
    then
        insert("defaultSalienceWithRecursionCall");
end

//--------------------------------------------------------------------



