/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

//created on: Nov 8, 2011
//jsvitak
package org.drools.testcoverage.functional

import org.kie.api.runtime.rule.Match

rule sales1 @department('sales') @cathegory('special')
salience 10
when
    String( this == 'fireRules' )
then
end

rule sales2 @department('sales') 
when
    String( this == 'fireRules' )
then
end

rule salesCancel @activationListener('direct')
when
    String(this == 'fireCancelRule')
    $i : Match( department == 'sales', cathegory == 'special' )
then
    kcontext.cancelMatch($i);
end
