package org.drools.testcoverage.common.model;

public class E extends AbstractBean {

    /**
     * In this case id is autogenerated.
     *
     * @param value
     */
    public E(final int value) {
        super(value);
    }

    public E(final long id, final int value) {
        super(id, value);
    }
}
