package org.drools.testcoverage.common.model;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Food implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "cost")
	private double cost;

	public Food() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public double getCost() {
		return this.cost;
	}

	public void setCost(double cost) {
		this.cost = cost;
	}

	public Food( java.lang.String name, double cost) {
		this.name = name;
		this.cost = cost;
	}

}