#created on: 18.10.2007
package org.drools.analytics.consequence

#list any import classes here.
import org.drools.analytics.components.AnalyticsRule;  
import org.drools.analytics.components.TextConsequence;  
import org.drools.analytics.report.components.AnalyticsMessage;  
import org.drools.analytics.dao.AnalyticsResult;

#declare any global variables here
global AnalyticsResult result;


rule "No action - possibly commented out"
	when
		$c :TextConsequence(
			( text == null || text matches "" )
		)
	
		$r :AnalyticsRule(
			id == $c.ruleId
		)
	then 
		result.save( new AnalyticsMessage( 
								AnalyticsMessage.Severity.WARNING,
								AnalyticsMessage.MessageType.MISSING_COMPONENT,
								$r, 
								$r + " has no RHS." ) );
end
