package SistersRules;
 
import org.drools.jsr94.rules.Person;

global java.util.Vector vector

rule FindSisters
    when
    	$person1 : Person ( $name1:name )
    	$person2 : Person ( $name2:name )
        eval( $person1.hasSister($person2) )
    then
    	vector.add($person1.getName() + " and " + $person2.getName() +" are sisters");
    	assert( $person1.getName() + " and " + $person2.getName() +" are sisters");
end