/*
 * Copyright 2010 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package foo.bar

import org.drools.workbench.models.testscenarios.backend.Cheese


rule "rule1"
    when
        c1: Cheese(price == 1)
    then
        c1.setType("rule1");
end

rule "rule2"
    when
        c1: Cheese(price == 1)
        c2: Cheese(price == 2)
    then
        c1.setType("rule2");
        c2.setType("rule2");
end

rule "rule3"
    when
        c1: Cheese(price == 42)
    then
        c1.setType("rule3");
end

rule "rule4"
    when
        c1 : Cheese(price == 46)
        not Cheese(price == 42)
    then
        c1.setType("rule4");
end


