package nesting;

dialect "mvel"

import org.drools.Person
import org.drools.Address

fdsfdsfds


rule "test something"

    when
        p: Person( name=="Michael",
                                (addresses[1].street == "Low" &&
                                addresses[0].street == "High"  )
                                )
    then
        p.name = "goober"
        System.out.println(p.name)
end
