/*
 * Copyright 2016 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.drools.testcoverage.functional.parser

declare Something
    someAttribute : String
end

declare SomethingElse
    someAttribute : String
end

rule "1" when then end

rule "2" when str:String() then end

rule "3" when str: String() then end

rule "4" when str : String() then end

rule "5" when str :String() then end

rule"6" when then end rule"7" when then end

// according to Wolgang Laune's ideas on drools-dev mailing list
rule "8"
    when
        Something ( a1: someAttribute )
        Something ( a2 :someAttribute )
        Something ( a3:someAttribute )
    then
end