#created on: 16.11.2009
package org.drools.verifier.redundancy

#list any import classes here.
#global VerifierReport result;



#declare any global variables here
#import org.drools.verifier.data.VerifierReport;
import org.drools.verifier.report.components.Redundancy;
import org.drools.verifier.report.components.Subsumption;


#
# If two objects are subsumptant to each others that makes them redundant.
#
# Dependencies:
#
#	Needs at least the following package:
#		package org.drools.verifier.sumbumption
#
rule "Find redundancy"
	when
		$sub :Subsumption( )
		
		Subsumption(
			guid != $sub.guid,
			left == $sub.right,
			right == $sub.left
		)
		
		not Redundancy(
			items contains $sub.left, 
			items contains $sub.right 
		)
	then
		insert( new Redundancy( $sub.getLeft(), 
								$sub.getRight() ) );
end
