/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package com.sample 

import import java.util.List
import org.drools.compiler.Cheese
import org.drools.compiler.Cheesery

global Cheesery cheesery
global List list

rule "simple_rule"
    salience 10
    no-loop true
    agenda-group agenda-group
    activation-group activation-group
when
    cheese : Cheese( type == 1 ) from collect( Person( hair == "pink" )  ) 
then
 list.add( $cheese ); end
