/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Test 1"
    when
            list :List()
            Foo()  from list.items
    then
        System.out.println( "Test" );
end

rule "Test 2"
    when
            list :List()
            Foo(
                a > 10
            )  from list.items
            Foo(
                a > 100
            )  from list.items
    then
        System.out.println( "Test" );
end
/*
rule "Test 3"
    when
            list2 :List2()
            Foo(
                a > 10
            )  from list2.items
    then
        System.out.println( "Test" );
end
*/

rule "Test x"
    when
            Bar()
    then
        System.out.println( "Test" );
end
