/*
 * Copyright 2010 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.sample

import com.sample.DroolsTest.Message;

rule "Test 1"
    when
            Foo(
                a == 10,
                a == 100,
                b == 1
            )
    then
        System.out.println( "Test 1" );
end

rule "Test 2"
    when
            Foo(
                a == 10,
                a == 10,
                b == 2
            )
    then
        System.out.println( "Test 2" );
end
