/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

package org.drools.compiler.test;

import function org.drools.mvel.compiler.StaticMethods.*;
import function org.drools.mvel.compiler.StaticMethods2.getString3;

import org.drools.mvel.compiler.Cheese;

global java.util.List list;

function String getString4( String string ) {
    return string;
}

rule "test rule1"
    salience 30
    when
        Cheese()
    then
        list.add( getString1( "rule1" ) );
end

rule "test rule2"
    salience 20
    when
        Cheese( type == ( getString2("stilton") ) );
    then
        list.add( getString3( "rule", new Integer( 2 ) ) );
end

rule "test rule3"
    salience 10
    when
        Cheese( $type : type);
        eval( $type.equals( getString1( "stilton" ) ) );
    then
        list.add( getString2( "rule3" ) );
end

rule "test rule4"
    salience 0
    when
        Cheese();
    then
        list.add( getString4( "rule4" ) );
end
