[id='cep-event-streams-con_{context}']

= Event streams and entry points

The {RULE_ENGINE} can process high volumes of events in the form of event streams. In DRL rule declarations, a stream is also known as an _entry point_. When you declare an entry point in a DRL rule or Java application, the {RULE_ENGINE}, at compile time, identifies and creates the proper internal structures to use data from only that entry point to evaluate that rule.

Facts from one entry point, or stream, can join facts from any other entry point in addition to facts already in the working memory of the {RULE_ENGINE}. Facts always remain associated with the entry point through which they entered the {RULE_ENGINE}. Facts of the same type can enter the {RULE_ENGINE} through several entry points, but facts that enter the {RULE_ENGINE} through entry point A can never match a pattern from entry point B.

Event streams have the following characteristics:

* Events in the stream are ordered by time stamp. The time stamps may have different semantics for different streams, but they are always ordered internally.
* Event streams usually have a high volume of events.
* Atomic events in streams are usually not useful individually, only collectively in a stream.
* Event streams can be homogeneous and contain a single type of event, or heterogeneous and contain events of different types.
