/**
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

template header
first_name
last_name
age
city
phone

package This_is_a_ruleset;

template "template1"
first_name
rule "How cool is @{first_name} @{row.rowNumber}"
    when
        user.getName().equals("@{first_name}")
    then
end
end template

template "template2"
first_name
last_name
rule "How uncool is @{first_name} @{row.rowNumber}"
    when
        user.getFirstName().equals("@{first_name}")
    then
end
end template
