template header
first_name
last_name
age
city
phone

package This_is_a_ruleset;

template "template1"
first_name
rule "How cool is @{first_name} @{row.rowNumber}"
	when
		user.getName().equals("@{first_name}")
	then
end
end template

template "template2"
first_name
last_name
rule "How uncool is @{first_name} @{row.rowNumber}"
	when
		user.getFirstName().equals("@{first_name}")
	then
end
end template
