/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

// Example DRL with expansion
// (ie "domain specific language")

// declare expanders for domain specific and natural language extensions
use expander cheese.dsl.properties
//this one is just a simple properties file


rule cheese_rules
    when
        Bob is in atlanta
        Bob likes cheese
        #There exists a Guest with name of "Michael" and sex of "Male"
        >Guest( name == seatingRightGuestName, rightGuestSex:sex, rightGuestHobby:hobby )
        >Guest( leftGuestName:name , sex != rightGuestSex, hobby == rightGuestHobby )

        #count => Count() can be replaced by
        bind count to Count
    then
        Send notification to Mark with message "hello"
        >System.out.println("and this is code")
end
