name: Kogito Examples

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths-ignore:
      - 'LICENSE'
      - '**/.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

jobs:
  kogito_examples-build:
    concurrency:
      group: ${{ matrix.examples-subfolder }}-pr-${{ github.head_ref }}
      cancel-in-progress: true
    timeout-minutes: 180
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        maven-version: ['3.8.6']
        examples-subfolder:
          - kogito-quarkus-examples
          - kogito-springboot-examples
          - serverless-workflow-examples
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - ${{ matrix.examples-subfolder }}
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kogito-pipelines/.ci/actions/ubuntu-disk-space@main
        if: ${{ matrix.os == 'ubuntu-latest' }}
      - name: Support long paths
        if: ${{ matrix.os == 'windows-latest' }}
        uses: kiegroup/kogito-pipelines/.ci/actions/long-paths@main
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Build Chain
        uses: kiegroup/kogito-pipelines/.ci/actions/build-chain@main
        env:
          KOGITO_EXAMPLES_SUBFOLDER_POM: ${{ matrix.examples-subfolder }}/
        with:
          definition-file: https://raw.githubusercontent.com/kiegroup/kogito-pipelines/%{process.env.GITHUB_BASE_REF.replace(/(\d*)\.(.*)\.(.*)/g, (m, n1, n2, n3) => `${+n1-7}.${n2}.${n3}`)}/.ci/pull-request-config.yaml
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          starting-project: kiegroup/kogito-examples
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Surefire Report
        uses: kiegroup/kogito-pipelines/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'
