# Tests RHBOP productized profile builds on PRs
name: Optaplanner

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches:
      - main
      - 8.*
    paths-ignore:
      - 'LICENSE*'
      - '.gitignore'
      - '**.md'
      - '**.adoc'
      - '*.txt'
      - 'docsimg/**'
      - '.ci/jenkins/**'

defaults:
  run:
    shell: bash

jobs:
  productized-build-chain:
    concurrency:
      group: rhbop_pull_request-${{ github.event_name }}-${{ github.head_ref }}-${{ matrix.os }}-${{ matrix.java-version }}
      cancel-in-progress: true
    timeout-minutes: 120
    strategy:
      matrix:
        os: [ubuntu-latest]
        java-version: [11]
        maven-version: ['3.8.6']
      fail-fast: false
    runs-on: ${{ matrix.os }}
    name: ${{ matrix.os }} - Java ${{ matrix.java-version }} - Maven
    steps:
      - name: Clean Disk Space
        uses: kiegroup/kogito-pipelines/.ci/actions/ubuntu-disk-space@main
      - name: Java and Maven Setup
        uses: kiegroup/kogito-pipelines/.ci/actions/maven@main
        with:
          java-version: ${{ matrix.java-version }}
          maven-version: ${{ matrix.maven-version }}
          cache-key-prefix: ${{ runner.os }}-${{ matrix.java-version }}-maven${{ matrix.maven-version }}
      - name: Productized Build Chain
        uses: kiegroup/kogito-pipelines/.ci/actions/build-chain@main
        with:
          definition-file: https://raw.githubusercontent.com/${GROUP:kiegroup}/optaplanner/${BRANCH:main}/.ci/pull-request-config-rhbop.yaml
          annotations-prefix: ${{ runner.os }}-${{ matrix.java-version }}/${{ matrix.maven-version }}
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          starting-project: kiegroup/optaplanner
      - name: Surefire Report
        uses: kiegroup/kogito-pipelines/.ci/actions/surefire-report@main
        if: ${{ always() }}
        with:
          report_paths: '**/*-reports/TEST-*.xml'

