/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.Person
import org.drools.compiler.Cheese

global java.util.List list

rule "first"
    when
           p : Person(status=="start")
    then
        list.add("first");
        p.setStatus("next");
           update(p);
end    

rule "second"
    when
        p : Person(status == "next")
    then
        list.add("second");
        p.setStatus("final");
        update(p);
end

rule "third"
    when
        p : Person(status == "final")
    then
        list.add("third");
        retract(p);
end

rule "fourth"
    when
        not Person()
    then
        list.add("fourth");
        insert(new Cheese("stilton", 42));
end

rule "fifth"
    when
        Cheese(type == "stilton")
    then
        list.add("fifth");
end
