/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test

import org.drools.compiler.Person;
import java.math.BigDecimal;

global java.util.List list;

rule "BigDec"

    when
        p: Person(bigDecimal < 100.01)
    then
        System.err.println("rule1");
        list.add( p );
end

rule "BigInt"
    when
        p: Person(bigInteger < 100.1)
    then
    System.err.println("rule2");
        list.add( p );
end

rule "BigDec2"

    when
        p: Person(bigDecimal == 42)
    then
    System.err.println("rule3");
        list.add( p );
end

rule "BigInt2"
    when
        p: Person(bigInteger == 42)
    then
    System.err.println("rule4");
        list.add( p );
end

rule "BigDec3"

    when
        p: Person(bigDecimal != 100)
    then
    System.err.println("rule5");
        list.add( p );
end

rule "BigInt3"
    when
        p: Person(bigInteger != 100)
    then
    System.err.println("rule6");
        list.add( p );
end


