/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.integrationtests

import org.drools.compiler.integrationtests.ParallelCompilationTest.User;


rule "When a user is young, print his name."
    when
        $user : User(age < 20)
    then
        System.out.println("Young: "+$user.getName() );
end


rule "When a user is old, print his name."
    when
        $user : User(age > 30)
    then
        System.out.println("Old: "+$user.getName() );
end


rule "Girls get a special parking lot."
    when
        $user : User(age < 20, gender == User.Gender.FEMALE)
    then
        System.out.println("Park: "+$user.getName() );
end

rule "When there is god, the light always shines."
    when
        $user : User(name matches "God")
    then
        System.out.println("Light is on" );
end
