/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

import org.drools.compiler.Person;

global java.util.List list1;
global java.util.List list2;
global java.util.List list3;
global java.util.List list4;


rule "1. && operator with number range"
    when
        $person : Person( age > 30 && < 40, hair == "red" )
    then
        list1.add( $person );
end    

rule "2. && operator with != and strings"
    when
        $person : Person( hair != "blue" && != "purple", age > 30 && < 40  )
    then
        list2.add( $person );
end   

rule "3. || operator with == and strings"
    when
        $person : Person( hair == "blue" ||  == "purple",   age < 30 )
    then
        list3.add( $person );
end   


rule "4. ||  and && operator with ==  and != and strings"
    when
        $person : Person( age > 30 && < 40 || > 10 && < 20, hair == "red" || == "blue" )
    then
        list4.add( $person );
end  
