/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

declare A
    id : int
end

declare B
    id : int
end

declare C
    id : int
end

rule "Setup"
    salience 100
then
    insert( new A(1) );
    insert( new A(1) );
    insert( new B(1) );
    insert( new C(1) );
    insert( new B(2) );
    insert( new C(4) );
end

rule "Trigger"
    salience 50
    no-loop
when
    $a : A()
    $c1 : C( id == 1 )
    $c4 : C( id == 4 )
then
    modify( $a ) {}
    modify( $c1 ) { }
    modify( $c4 ) { setId( 5 ) }
end

rule "Offending"
when
  A( $id : id )
  B( )
  C( id == $id )
  exists( B(  ) and
          C( id == 4 ) )
then
  // do something
end


