/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler

rule "setupFactC"
no-loop true
    when
        a: FactA(s:field1, i:field2, f:field3)
        not FactC(f1==s)
    then
        insert(s != null ? new FactC(s, i, f) :
                                  new FactC());
end

rule "factBWithRetract"
    when
        b : FactB(s:f1, i:f2, f:f3)
        a : FactA(field1==s)
        c : FactC(f1==s)
    then
        c.setF3(f);
        retract(b);
        update(c);
end