/*
 * Copyright 2015 JBoss Inc
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler.test;

import org.drools.compiler.Cheese
import org.drools.compiler.Cheese;

global java.util.List list;
global java.util.List list2;

function String someFunction() {
    return "hello world";
}

rule "mvel1"
    dialect "mvel"
    when
        $c : Cheese(type == "stilton", price == (new Integer( 5 ) + 5 ), eval(price == (new Integer( 5 ) + 5 ) ) )
        eval( $c.price == 10 && list == empty)
    then
        Cheese cheese = new Cheese("cheddar", 35);

        a = new java.math.BigInteger( "10" );
        b = new java.math.BigInteger( "10" );
        c = a + b;
        list.add( c + $c.price);

        modify ( $c ) { price = c }
end


rule "mvel2"
    dialect "mvel"
    when
        $c : Cheese(type == "stilton", price == 20 )
    then
        list.add( $c.price + 2);
        list2.add( someFunction() );
        $c.usedBy = "10-Jul-1974"
end
