/*
 * Copyright 2015 Red Hat, Inc. and/or its affiliates.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * 
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
*/

package org.drools.compiler
import org.drools.compiler.Cheese

global java.util.List results;

rule "test local variable in mvel consequence - same type"
    dialect "mvel"
    when
        $p : Person( $likes : likes )
    then
        Cheese c = new Cheese( $likes );
        results.add( c );
        // below should raise a duplicate local variable declaration
        Cheese c = new Cheese( "stilton" );
end


rule "test local variable in mvel consequence - different type"
    dialect "mvel"
    when
        $p : Person( $likes : likes )
    then
        Cheese c = new Cheese( $likes );
        results.add( c );
        // below should raise a duplicate local variable declaration
        String c = new String( "stilton" );
end
